### ISSUE TITLE
onnx离线版本报错

### ISSUE THREAD

**Issue by haha010508** [alibaba-damo-academy/FunASR#1004]
https://github.com/alibaba-damo-academy/FunASR/blob/d9c808a8df49a747b484993f7b69dc9c4936992b/funasr/runtime/python/onnxruntime/funasr_onnx/paraformer_bin.py#L120
报错如下：
    timestamp, timestamp_raw = time_stamp_lfr6_onnx(us_peaks_, copy.copy(raw_tokens))
ValueError: not enough values to unpack (expected 2, got 0)
发生情况，音频中没有明显的文字出现，仅仅是一些噪音（似乎是vad的锅），这时raw_tokens为空列表，则会报错，有音频，如需请联系我

**Comment by LauraGPT** [comment]
If it is convenient to you, please upload the test audio and we could verify it.

**Comment by haha010508** [comment]
how to upload?

**Comment by haha010508** [comment]
> If it is convenient to you, please upload the test audio and we could verify it.

add me wechat:15815571301

**Comment by LauraGPT** [comment]
> how to upload?

CTR C and CTR V

**Comment by haha010508** [comment]
你是认真的吗？那可是音频文件！

**Comment by ww451575464** [comment]
raw_tokens这个为空的话，time_stamp_lfr6_onnx会返回一个[]，但是这里需要返回两个值，所以报错。
修改一下time_stamp_lfr6_onnx函数就可以了

**Comment by R1ckShi** [comment]
fixed
