### ISSUE TITLE
Running python client for 5.5 hours long audio recognition fails

### ISSUE THREAD

**Issue by JacksonPan123** [alibaba-damo-academy/FunASR#1005]
OS: linux（CentOS Linux release 7.8.2003 (Core)）

Python/C++ Version：Python-3.8.18

Package Version：pytorch-wpe（0.0.1）、torchaudio（2.1.0）、modelscope（1.9.2）、funasr（0.8.0）

Model：
speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-onnx
punc_ct-transformer_zh-cn-common-vocab272727-onnx
speech_fsmn_vad_zh-cn-16k-common-onnx

Command：
python3 funasr_wss_client.py --host 127.0.0.1 --port 10095 --mode offline --audio_in /data/asr/temp/replay.1693548503.57554748.wav --send_without_sleep --output_dir /data/asr/funasr-runtime-resources/samples/python

Details：
The java and python clients in the use case cannot recognize long audio, but audio within 30 minutes can be recognized normally.
![image](https://github.com/alibaba-damo-academy/FunASR/assets/87793735/42b185ed-a1d2-4dde-9505-397ebc10e8dc)
![image](https://github.com/alibaba-damo-academy/FunASR/assets/87793735/a7903896-c01d-4bf7-9f7e-bebeb14143f3)

Error log：
Running python client for 5.5 hours long audio recognition fails

**Comment by LauraGPT** [comment]
If it is convenient  to you, please upload the test audio and we could verify it.

**Comment by lyblsgo** [comment]
if the issue still persists, you can reopen the issue and provide steps to reproduce.
