### ISSUE TITLE
run.sh: 行 81: utils/text2token.py: 不是目录

### ISSUE THREAD

**Issue by CreepJoye** [alibaba-damo-academy/FunASR#1011]
OS: linux 18.04.6

Python/C++ Version：Python 3.8.18 

Package Version：pytorch 2.0.0、torchaudio2.0.1+cu118、modelscope 1.9.2、funasr version 0.7.8

Model：

Command：bash run.sh --CUDA_VISIBLE_DEVICES "0,1" --gpu_num 2

Details：

Error log：
local/aishell_data_prep.sh: 行 51: utils/filter_scp.pl: 不是目录
local/aishell_data_prep.sh: 行 53: utils/filter_scp.pl: 不是目录
local/aishell_data_prep.sh: AISHELL data preparation succeeded
run.sh: 行 81: utils/text2token.py: 不是目录

**Comment by LauraGPT** [comment]
This is because the installation is wrong. Please install by source code, as [docs](https://alibaba-damo-academy.github.io/FunASR/en/installation/installation.html#or-install-from-source-code)
