### ISSUE TITLE
paraformer-en模型支持finetune

### ISSUE THREAD

**Issue by andyweiqiu** [alibaba-damo-academy/FunASR#1012]
希望大佬们能够支持paraformer-en模型的finetune，让我们在自己的场景数据下体验下效果

**Comment by zw76859420** [comment]
同时希望，目前en 还不支持 finetune

**Comment by LauraGPT** [comment]
We have already supported fine-tuning of the English model. Please refer to the [documentation](https://github.com/alibaba-damo-academy/FunASR/tree/main/egs_modelscope/asr_vad_punc/speech_paraformer-large-vad-punc_asr_nat-en-16k-common-vocab10020). To upgrade the modelscope, you will need to use the [source code](https://github.com/modelscope/modelscope). Additionally, please ensure that funasr is also upgraded.
