### ISSUE TITLE
ValueError: AutomaticSpeechRecognitionPipeline: unknown input_layer: pe_online 

### ISSUE THREAD

**Issue by aixuedegege** [alibaba-damo-academy/FunASR#1020]
您好，我的环境如下：
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:15:13_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0

modelscope                    1.4.3
tensorboard                   1.15.0
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
tensorboardX                  2.6
tensorflow                    1.15.5+cu113
tensorflow-estimator          1.15.1
open-clip-torch               2.16.0
pytorch-lightning             1.7.7
pytorch-metric-learning       2.0.1
pytorch-wavelets              1.3.0
pytorch-wpe                   0.0.1
pytorch3d                     0.7.2
rotary-embedding-torch        0.2.1
torch                         1.11.0+cu113
torch-complex                 0.4.3
torchaudio                    0.11.0+cu113
torchmetrics                  0.11.4
torchsummary                  1.5.1
torchvision                   0.12.0+cu113

运行[这里面的代码](https://www.modelscope.cn/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/summary)时，
```python
os.environ["MODELSCOPE_CACHE"] = "./"
inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model='damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online',
    model_revision='v1.0.6',
    mode="paraformer_streaming"
)
```
**会报错：**
**ValueError:** _AutomaticSpeechRecognitionPipeline:_ unknown input_layer: pe_online

网上完全没有相关问题，所以请教一下如何破解？
Pipeline related: @Firmament-cyou @wenmengzhou

Contribute your model: @zzclynn

**Comment by hnluo** [comment]
Please update modelscope package (pip install -U modelscope -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html)

**Comment by aixuedegege** [comment]
已更新为modelscope                    1.9.2，
仍然会报上面错误

**Comment by hnluo** [comment]
Please refer to https://alibaba-damo-academy.github.io/FunASR/en/installation/installation.html

**Comment by aixuedegege** [comment]
好的 我参考一下，谢谢
