### ISSUE TITLE
多个mp3音频合并成一个mp3识别只识别第一个音频

### ISSUE THREAD

**Issue by huwenkai26** [alibaba-damo-academy/FunASR#1022]
我将多个mp3文件合并成一个mp3文件去给funasr识别时，funasr只能识别出第一个mp3的内容，然后就不识别了
MP3urL https://tuiwen-prod-oss.startupfun.vip/ysleague-wallpaper-tts-audio/5f32815798d3e187e079910aa9426b36.mp3

**Comment by lyblsgo** [comment]
check the process for merging MP3s
