### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by ww451575464** [alibaba-damo-academy/FunASR#1023]
https://github.com/alibaba-damo-academy/FunASR/blob/e950a921736eff5a547e7f53eb534c6ab5ecf86e/funasr/runtime/python/libtorch/funasr_torch/utils/timestamp_utils.py#L4

这个函数中，会判断传入的第二个参数的长度，如果为空则返回一个空结果。
但问题是在正确返回的时候会返回两个变量。所以当函数返回空结果的时候会报错。

**Comment by R1ckShi** [comment]
感谢反馈，已更正，可以拉取最新代码尝试一下。
