### ISSUE TITLE
流式模型latency配置`[5,10,5]`是什么意思？

### ISSUE THREAD

**Issue by aixuedegege** [alibaba-damo-academy/FunASR#1026]
请教一下[这里面](https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/runtime/docs/SDK_tutorial_online_zh.md#python-client)的这句话：
```bash
chunk_size：表示流式模型latency配置`[5,10,5]`，表示当前音频解码片段为600ms，并且回看300ms，右看300ms。
```
是什么意思？5,10,5如何计算维600 300 300的？

小白求指教，多谢。

**Comment by hnluo** [comment]
One frame of speech is 60ms, so 10 * 60ms = 600ms

**Comment by LauraGPT** [comment]
![image](https://github.com/alibaba-damo-academy/FunASR/assets/18321252/19abb5d1-87a0-4390-9dff-6e57a1a9810d)

**Comment by aixuedegege** [comment]
感谢大家的回答，我有个新的问题，“Paraformer语音识别-中文-通用-16k-实时-large”这里的实时、离线有什么区别么？我的理解是实时是一些小的音频frame组成的训练数据比较多，离线是长音频训练数据多？是这个意思么？

**Comment by LauraGPT** [comment]
> 感谢大家的回答，我有个新的问题，“Paraformer语音识别-中文-通用-16k-实时-large”这里的实时、离线有什么区别么？我的理解是实时是一些小的音频frame组成的训练数据比较多，离线是长音频训练数据多？是这个意思么？

Maybe you could test them by:

中文离线文件转写：
https://101.37.77.25:1335/static/index.html
中文实时语音听写：

https://101.37.77.25:1336/static/index.html

**Comment by aixuedegege** [comment]
好的 谢谢！

**Comment by aixuedegege** [comment]
中文离线文件转写：
https://101.37.77.25:1335/static/index.html
中文实时语音听写：
https://101.37.77.25:1336/static/index.html

功能上离线指的是说完了把整个音频A1丢进模型Model1识别，实时是做的语音流截取部分得到音频A2丢给模型Model2识别。

我想问的是Model2和Model1有什么区别么？是不是都是Paraformer模型，他们在训练时对输入是不是有什么区别么？
或者离线模型通过流式服务部署就能变成实时的了吗？

**Comment by AliceShen122** [comment]
+1

**Comment by sanwei111** [comment]
没看明白。
“chunk_size：表示流式模型latency配置`[5,10,5]`，表示当前音频解码片段为600ms，并且回看300ms，右看300ms。”
是不是要求回看+又看等于片段长度？但是我发现1可以不等于

**Comment by busishengui** [comment]
> 没看明白。 “chunk_size：表示流式模型latency配置`[5,10,5]`，表示当前音频解码片段为600ms，并且回看300ms，右看300ms。” 是不是要求回看+又看等于片段长度？但是我发现1可以不等于

我有类似的问题
