### ISSUE TITLE
funasr离线服务识别结果不准

### ISSUE THREAD

**Issue by qdu123** [alibaba-damo-academy/FunASR#1028]
我使用官方例子（funasr-runtime-deploy-offline-cpu-zh.sh）部署了一个离线服务，模型选用信息如下：
- ASR:speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-onnx
- VAD:speech_fsmn_vad_zh-cn-16k-common-onnx
- PUNC:punc_ct-transformer_zh-cn-common-vocab272727-onnx
客户端测试：
```
python funasr_wss_client.py --host 127.0.0.1 --port 10095 --audio_in "./wangbing_new_0.wav"
输出结果：
Namespace(audio_in='./wangbing_new_0.wav', chunk_interval=10, chunk_size=[5, 10, 5], host='127.0.0.1', mode='2pass', output_dir=None, port=10095, send_without_sleep=True, ssl=1, thread_num=1, words_max_print=10000)
connect to wss://127.0.0.1:10095
pid0_0: demo: 包邮岳父,你就出剩,这缘是否我不唱歌听嗯。
Exception: sent 1000 (OK); then received 1000 (OK)
end
```

可是我在魔搭[Paraformer语音识别-中文-通用-16k-离线-large-长音频版](https://modelscope.cn/models/damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/summary)中的demo测试同样的音频，结果如下：
”大家好，我是索菲亚家居总裁王斌市场有不确定性供应链。“ （<font color=red>这个是语音正确的内容</font>）

恳请大佬们解惑，是否是安装时候存在姿势错误。

**Comment by lyblsgo** [comment]
If convenient, please provide The audio

**Comment by qdu123** [comment]
> If convenient, please provide The audio

thanks a lot for your replay, the audio file's url is https://mj-server-gz.oss-cn-guangzhou.aliyuncs.com/wangbing_new_0.wav?Expires=1697799449&OSSAccessKeyId=TMP.3KdbCiA9C8KZqzxuKKgiquMKed6DLUC1PfoSzLR1nhC4CzrWUgt8p1EbzPT1KzVdxPdPiy1M3oqTHvt4uBN5VsGHs67YDb&Signature=v2qKCNTg8EOe%2BegsscxheXYo1Q0%3D
.it will expire in 30000 seconds.

**Comment by seayuw** [comment]
设置音频采样率参数 "audio_fs", 32000 识别的结果是对的，当  "audio_fs", 16000 时候就是你反馈的错误的结果

**Comment by qdu123** [comment]
> 设置音频采样率参数 "audio_fs", 32000 识别的结果是对的，当 "audio_fs", 16000 时候就是你反馈的错误的结果
谢谢，我用代码把音频文件的采样率改为32k，同时修改了funasr_wss_client.py中
```
# send first time
        message = json.dumps({"mode": args.mode, "chunk_size": args.chunk_size, "chunk_interval": args.chunk_interval,
            "audio_fs": 32000, "wav_name": wav_name, "is_speaking": True})
```
还是没有得到正确的结果，我继续研究一下

**Comment by lyblsgo** [comment]
> https://mj-server-gz.oss-cn-guangzhou.aliyuncs.com/wangbing_new_0.wav?Expires=1697799449&OSSAccessKeyId=TMP.3KdbCiA9C8KZqzxuKKgiquMKed6DLUC1PfoSzLR1nhC4CzrWUgt8p1EbzPT1KzVdxPdPiy1M3oqTHvt4uBN5VsGHs67YDb&Signature=v2qKCNTg8EOe%2BegsscxheXYo1Q0%3D

I'm sorry, but I just noticed the message. The audio file has expired.

**Comment by qdu123** [comment]
> > https://mj-server-gz.oss-cn-guangzhou.aliyuncs.com/wangbing_new_0.wav?Expires=1697799449&OSSAccessKeyId=TMP.3KdbCiA9C8KZqzxuKKgiquMKed6DLUC1PfoSzLR1nhC4CzrWUgt8p1EbzPT1KzVdxPdPiy1M3oqTHvt4uBN5VsGHs67YDb&Signature=v2qKCNTg8EOe%2BegsscxheXYo1Q0%3D
> 
> I'm sorry, but I just noticed the message. The audio file has expired.

Thanks a lot,i've tried resample the audio to 16k,16bit,1(sample rate,bit,channel),then the result is ok
