### ISSUE TITLE
如何检测说完话了

### ISSUE THREAD

**Issue by monkeycc** [alibaba-damo-academy/FunASR#1029]
ChatGPT的语音对话

说完话之后 自动切换到GPT

funasr要如何完成这个效果

**Comment by LauraGPT** [comment]
We think it is a nlp task, not speech. The VAD of funasr could detect the end of a sentence, maybe you could try it. [doc](https://mp.weixin.qq.com/s/8He081-FM-9IEI4D-lxZ9w)
