### ISSUE TITLE
不使用docker，编译安装websocket-cpp出错，求成功编译的软件系统环境版本。

### ISSUE THREAD

**Issue by mdys** [alibaba-damo-academy/FunASR#1034]
不习惯使用docker部署，想自己编译websocket-cpp，各种报错。之前未加入 ffmpeg的时候是可以的。求可成功编译的系统版本、软件版本。请问需要安装什么ffmpeg 版本呢？ 感谢！下载的  ffmpeg-N-111383-g20b8688092-linux64-gpl-shared 看不出版本
oS: centos7.9 X64
GCC :4.8.5  11.1 都换过无效
cmake ：3.26.3
make ：3.82
![图片](https://github.com/alibaba-damo-academy/FunASR/assets/1708120/6ce8206b-26f9-4735-b998-393ffc963bda)

**Comment by lyblsgo** [comment]
try gcc 8.3.1

**Comment by csukuangfj** [comment]
> GCC :4.8.5 11.1 都换过无效

GCC 11.1 都出现这个错误，就不可理解了。

**Comment by mdys** [comment]
感谢各位大佬，试了下在 centos下依然是失败的。
ldd   2.31
gcc  8.3.1
cmake  3.26.3
make 4.4
ffmpeg 6.0

最终在docker下的 Ubuntu 环境才成功编译。然后把所有bin拷到centos下运行的..

**Comment by nyfll** [comment]
请问在ubuntu环境进行编译，再将程序拷贝到其他linux主机上运行，需要注意哪些内容？比如要用编译成静态库吗？我使用静态库编译，ldd funasr-wss-client看到还是有许多要依赖的文件，应该如何处理这些依赖使得能够在另一台服务器上运行呢？
