### ISSUE TITLE
使用Termius连接远程服务器运行run.sh服务器连接被关闭

### ISSUE THREAD

**Issue by Boomprogrammar** [alibaba-damo-academy/FunASR#1038]
您好，我试过好多次了，gpu也都没问题，且处于空闲状态，但每次执行run.sh都会被强行关闭连接，请问这是为什么呢？gpu数目1和2都试过了

**Comment by LauraGPT** [comment]
Please detail the logfiles

**Comment by Boomprogrammar** [comment]
没有任何报错信息，就是直接关闭连接，偶然一次使用nohup sh run.sh --CUDA_VISIBLE_DEVICES="0,1" --gpu_num=2 > run.log 2>&1 &这个命令 在后台成功运行了   改用gpu2,3再用这个命令也不能正常运行

**Comment by Boomprogrammar** [comment]
我刚又试了下./run.sh > log.txt 2>&1 &这个命令   log文件第一次是显示permission denied   然后我第二次执行了这个命令 . ./run.sh --CUDA_VISIBLE_DEVICES="0,1" --gpu_num=2  > log.txt 2>&1   log文件则显示-bash: utils/parse_options.sh: Not a directory   感谢解答

**Comment by hnluo** [comment]
try `bash run.sh --CUDA_VISIBLE_DEVICES "0,1" --gpu_num 2`

**Comment by LauraGPT** [comment]
> 我刚又试了下./run.sh > log.txt 2>&1 &这个命令 log文件第一次是显示permission denied 然后我第二次执行了这个命令 . ./run.sh --CUDA_VISIBLE_DEVICES="0,1" --gpu_num=2 > log.txt 2>&1 log文件则显示-bash: utils/parse_options.sh: Not a directory 感谢解答

Ref to this issue, you should install funasr from source code.  
https://github.com/alibaba-damo-academy/FunASR/issues/1011#issuecomment-1763967538

**Comment by Boomprogrammar** [comment]
stage 0: Data preparation
run.sh: line 76: local/aishell_data_prep.sh: Permission denied 现在又出现这个问题了  用的命令时 bash run.sh

**Comment by Boomprogrammar** [comment]
朋友们已经解决了，解决方式是把paraformer下的原utils删除，将transformer下的utils全部复制过来，另外还有大量文件的默认权限是不可执行，需要手动加一下。最后就是run.sh的数据集目录有点问题得手动改一些，感谢大佬们的帮助！
