### ISSUE TITLE
微调报错

### ISSUE THREAD

**Issue by Tomsawyerhu** [alibaba-damo-academy/FunASR#1041]
<img width="830" alt="image" src="https://github.com/alibaba-damo-academy/FunASR/assets/46986832/438970d5-1ea0-47b2-842b-86aede4656bf">
微调的时候抱这个错，有人遇到吗

**Comment by hnluo** [comment]
OS: [e.g. linux]
Python/C++ Version：
Package Version：pytorch、torchaudio、modelscope、funasr version（pip list）
Model：
Command：
Details：
Error log：
