### ISSUE TITLE
中文数字 ITN 预测不正常

### ISSUE THREAD

**Issue by chenfuckthesky** [alibaba-damo-academy/FunASR#1045]
使用pipeline进行asr的时候，发现输出的数字都汉字，在钉群里反馈之后，得到的答复是pipeline不支持itn。然后翻了一通issue，在194#这个issue里面也提到了类似的问题，于是我按照issue里提问者的问题做了一遍，发现确实是没加空格的时候无法转换，比如我输入
`python` -m fun_text_processing.inverse_text_normalization.inverse_normalize --text "我的电话号码是一三八零零五五五五零三" --overwrite_cache --language zh --verbose`，得到的结果仍然是我的电话号码是一三八零零五五五五零三，除非我加个空格在数字前面。在这个issue里面，有个人回复说要把内容写到一个txt文件里，然后通过input_file的参数去转，我也按照这个做了，但是实际上并没有他说的那个效果，依然是汉字。由于这个issue已被关闭，这里只能重新提一个。

**Comment by LauraGPT** [comment]
Sorry, we `fun_text_processing ` does not support ITN in zh.
