### ISSUE TITLE
VAD online mode produces {'text':[-1,xxx]} or {'text':[xxx,-1]}

### ISSUE THREAD

**Issue by dancingonmoon** [alibaba-damo-academy/FunASR#1046]
the github discussion [How to use VAD decoding in FunASR](https://github.com/alibaba-damo-academy/FunASR/discussions/236#top)
, explains the usage of VAD on the mode of both online and offline ,

while, upon applying it on mode='online', it often produces start point or end point with "-1", for example: {'text':[-1,xxx]} or {'text':[xxx,-1]}

could anyone explain to me what "-1" stands for here ?  an obvious understanding on vad segments is the list of tuple which marks the start point and end point.  how to explain when start point = -1 or end point = -1 ?

**Comment by LauraGPT** [comment]
The format of vad output: `[[beg1, end1], ..., [begN, endN]]`.
For the `beg` and `end`, it could be the real value, or `-1`. When the value is `-1`, it means the vad model does not detect a begin or end.
