### ISSUE TITLE
Real-time transcription service ONLY SUPPORT wav_format pcm.

### ISSUE THREAD

**Issue by 440981** [alibaba-damo-academy/FunASR#1055]
我是用脚本安装的 使用h5网页上传mp3格式文件就会报这个错误 但是我看文档是支持mp3格式的 难道是我的版本不对吗
```
安装脚本
curl -O https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/shell/funasr-runtime-deploy-online-cpu-zh.sh;
```
config文件如下
<img width="895" alt="image" src="https://github.com/alibaba-damo-academy/FunASR/assets/51017558/b9c1adc4-47d5-4aba-988e-29ea4753b005">

**Comment by lyblsgo** [comment]
Real-time transcription service ONLY SUPPORT wav_format pcm
