### ISSUE TITLE
离线推理ASR识别语音文件长度限制

### ISSUE THREAD

**Issue by sunjinguo** [alibaba-damo-academy/FunASR#1066]
想请教下离线推理语音ASR，语音识别的结果末尾处会有缺失，是否限定语音文件的长度，感谢

**Comment by lyblsgo** [comment]
Transcribing without specifying the length. If possible, please provide reproducible steps and corresponding audio for us . You can experience our deployed offline file transcription service：[https://101.37.77.25:1335/static/index.html](https://101.37.77.25:1332/static/index.html)
