### ISSUE TITLE
热词好像不起效果

### ISSUE THREAD

**Issue by yibo-liang** [alibaba-damo-academy/FunASR#1068]
阿里的各位你们好。打扰了。

我按照说明，改成contextual的模型以后，用websocket连接，加上了hotwords发现没有识别热词的能力。

以下是docker的命令行
```
root@0ca449b3551e:/workspace/FunASR/funasr/runtime# ps aux > log.txt
root@0ca449b3551e:/workspace/FunASR/funasr/runtime# cat log.txt
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   4248  3328 pts/0    Ss   Nov06   0:00 /bin/bash
root          28  0.4  0.0  93148  7488 ?        Ssl  Nov06   6:46 /etc/docker/daemon
root          41  0.1  0.0  11432  9072 ?        S    Nov06   1:58 python /workspace/FunASR/funasr/utils/funasr_progress.py
root          53  4.6  7.5 6178904 1820648 ?     Sl   Nov06  66:21 /workspace/FunASR/funasr/runtime/websocket/build/bin/funasr-wss-server-2pass --certfile  --decoder-thread-num 32 --download-model-dir /workspace/models --io-thread-num 8 --keyfile  --model-dir damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404-onnx --port 10095 --punc-dir damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727-onnx --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx
root       23114  0.0  0.0   5900  2816 pts/0    R+   22:58   0:00 ps aux
```
连接的代码
```
let request = {
            "chunk_size": chunk_size,
            "wav_name": "NodeJS",
            "is_speaking": true,
            "chunk_interval": 10,
            "mode": mode,
            "hotwords": hotwords.join(" "),
            "itn": use_itn
        }

this.client = new WebSocket(url);

this.client.on("open", () => {
    
         this.client.send(JSON.stringify(request));
    }
```
            
是我用法不对吗？

**Comment by yibo-liang** [comment]
> 阿里的各位你们好。打扰了。
> 
> 我按照说明，改成contextual的模型以后，用websocket连接，加上了hotwords发现没有识别热词的能力。
> 
> 以下是docker的命令行
> 
> ```
> root@0ca449b3551e:/workspace/FunASR/funasr/runtime# ps aux > log.txt
> root@0ca449b3551e:/workspace/FunASR/funasr/runtime# cat log.txt
> USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
> root           1  0.0  0.0   4248  3328 pts/0    Ss   Nov06   0:00 /bin/bash
> root          28  0.4  0.0  93148  7488 ?        Ssl  Nov06   6:46 /etc/docker/daemon
> root          41  0.1  0.0  11432  9072 ?        S    Nov06   1:58 python /workspace/FunASR/funasr/utils/funasr_progress.py
> root          53  4.6  7.5 6178904 1820648 ?     Sl   Nov06  66:21 /workspace/FunASR/funasr/runtime/websocket/build/bin/funasr-wss-server-2pass --certfile  --decoder-thread-num 32 --download-model-dir /workspace/models --io-thread-num 8 --keyfile  --model-dir damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404-onnx --port 10095 --punc-dir damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727-onnx --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx
> root       23114  0.0  0.0   5900  2816 pts/0    R+   22:58   0:00 ps aux
> ```
> 
> 连接的代码
> 
> ```
> let request = {
>             "chunk_size": chunk_size,
>             "wav_name": "NodeJS",
>             "is_speaking": true,
>             "chunk_interval": 10,
>             "mode": mode,
>             "hotwords": hotwords.join(" "),
>             "itn": use_itn
>         }
> 
> this.client = new WebSocket(url);
> 
> this.client.on("open", () => {
>     
>          this.client.send(JSON.stringify(request));
>     }
> ```
> 
> 是我用法不对吗？

我发现了问题，就是如果热词是稀有词就基本无效，比如我用“袤袤“作为热词，那么识别不了，如果用”帽帽“作为热词就能识别。所以为了识别”袤袤“，必须把同音词”帽帽“作为热词，然后之后用工程方法替换掉。

**Comment by lyblsgo** [comment]
Model speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404-onnx can increase the probability of corresponding words appearing, but they do not guarantee a 100% effectiveness.
