### ISSUE TITLE
离线大模型speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch识别结果异常

### ISSUE THREAD

**Issue by xiaodiandian1234** [alibaba-damo-academy/FunASR#1072]
用离线大模型speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch  v1.2.1 识别附件声音时，识别结果中多出一堆不相关的字
[wav.zip](https://github.com/alibaba-damo-academy/FunASR/files/13303473/wav.zip)

**Comment by xiaodiandian1234** [comment]
补充下相关信息：
操作系统：Linux。Torch：1.12.1。Funasr：0.8.0。Modelscope：1.9.2。
问题描述：基于以上环境，用模型speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch v1.2.1 识别上面附件中的声音，识别结果中多很多字。如201510251552017这一句，识别结果为：我 们 二 二 零 二 二 二 零 零 零 零 二 一 一  一 一 一 二 二 二 零 零 二 二 二 二 零 二 零 的 一 的。
问题分析：通过调试代码，发现calc_predictor的返回值alphas，大部分都是1.0。

**Comment by LauraGPT** [comment]
You could use the asr model with vad. I have tested them, the results is right. You could try is again, by:
https://www.modelscope.cn/models/damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/summary
