### ISSUE TITLE
离线文件识别安装包3.0 客户端代码执行出现段错误

### ISSUE THREAD

**Issue by HalFTeen** [alibaba-damo-academy/FunASR#1076]
1、提供一个清晰而简明的问题描述，并附上您所遵循的文档链接。
服务端docker启动服务后，下载客户端，按照cpp文件夹中的readme.md 编译websocket client。编译通过，但是测试出现段错误，信息如下：
![d030e00dd033634ca82f3aa09ca70307](https://github.com/alibaba-damo-academy/FunASR/assets/38465161/4646c857-fd92-421e-983a-d936afcf7f3d)

文档链接：  https://mp.weixin.qq.com/s/jSbnKw_m31BUUbTukPSOIw

    2、指明问题出现的环境，包括操作系统（如Windows、Linux、macOS）和相关软件版本（如Python、Torch、Funasr、Modelscope）。
linux centos7，
gcc=11.1.0 ,
openssl=1.1.0,

**Comment by lyblsgo** [comment]
![image](https://github.com/alibaba-damo-academy/FunASR/assets/9068933/0a26018c-0074-4837-8e90-58e62ee745c1)
I am unable to reproduce the issue you mentioned as I tested it successfully on my end.

**Comment by lyblsgo** [comment]
try funasr-runtime-sdk-cpu-0.4.0

**Comment by lyblsgo** [comment]
If the issue persists, please reopen the issue and provide detailed steps to reproduce, as well as server and client logs.
