### ISSUE TITLE
onnxruntime 编译funasr-onnx-offline时链接静态库和链接动态库生成的测试用例加载TLG.fst时出现报错

### ISSUE THREAD

**Issue by LFTF** [alibaba-damo-academy/FunASR#1077]
[error.pdf](https://github.com/alibaba-damo-academy/FunASR/files/13315295/error.pdf)

**Comment by LFTF** [comment]
链接静态库编译funasr-onnx-offline测试结果如下：


链接动态库编译funasr-onnx-offline测试结果如下：

**Comment by lyblsgo** [comment]
The static library of OpenFst requires additional dependencies, which can be cumbersome. Currently, only dynamic library support is available.
