### ISSUE TITLE
建立websocket连接时，为什么需要先转换成https连接进行一下手工授权，而且有时候多台机器同时手工授权，模型的websocket就再也连不上了，需要重启

### ISSUE THREAD

**Issue by yellowfish621** [alibaba-damo-academy/FunASR#1083]

**Comment by LauraGPT** [comment]
Please raise a issue as the docs https://github.com/alibaba-damo-academy/FunASR/issues/1074

**Comment by lyblsgo** [comment]
If the issue persists, please reopen the issue and provide detailed steps to reproduce, as well as server and client logs.
