### ISSUE TITLE
上传一段长音频时，报错

### ISSUE THREAD

**Issue by 385628424** [alibaba-damo-academy/FunASR#1089]
运行的命令如下：
python funasr_wss_client.py --host "xxx" --port 10095 --mode offline --audio_in "..\..\musics\38ecb379-4544-43ba-b62f-a3510fe65a2c.mp3"

运行的log如下：
Namespace(host='xxx', port=10095, chunk_size=[5, 10, 5], chunk_interval=10, hotword='', audio_in='..\\..\\musics\\38ecb379-4544-43ba-b62f-a3510fe65a2c.mp3', send_without_sleep=True, thread_num=1, words_max_print=10000, output_dir=None, ssl=1, use_itn=1, mode='offline')
Namespace(host='xxx', port=10095, chunk_size=[5, 10, 5], chunk_interval=10, hotword='', audio_in='..\\..\\musics\\38ecb379-4544-43ba-b62f-a3510fe65a2c.mp3', send_without_sleep=True, thread_num=1, words_max_print=10000, output_dir=None, ssl=1, use_itn=1, mode='offline')
connect to wss://xxx:10095
pid0_0: demo: 这中层管理啊，职业经理人啊，他们的利益跟公司的利益从来都不是一个利益。真到了要做选择的时候，他们选择的肯定是个人利益。大家好，我是半佛老师。今天继续看魔幻的世界，最近刷到一个非常经典又魔幻的问题啊，关于职场升职的，
什么很多公司宁愿从外面花大价钱高薪招聘新的管理者，也不愿意从内部的老员工里面找一个升职呢？这个问题很常见，也很有趣啊，大家可以看一下这个现象虽然看起来特别矛盾，特别令人想不通，但是其实是一个非常经典又很简单的脑筋急转弯。你看不不白，不是因为你不聪明，也不是因为这个问题复杂，而是这个问题太简单了，刚好卡住了你脑袋里的一个弯。
Exception: sent 1000 (OK); then received 1000 (OK)

总结：前面的识别是准确的，但是识别到一般就报错Exception: sent 1000 (OK); then received 1000 (OK)，然后后面的结果没有了

**Comment by luhairong11** [comment]
我也出现了这个问题，不知道如何解决
