### ISSUE TITLE
实时转写语音服务直接崩溃退出了

### ISSUE THREAD

**Issue by bltcn** [alibaba-damo-academy/FunASR#1090]
HOST OS:Rocky Linux release 8.8 (Green Obsidian)
mem:64g
docker : registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-online-cpu-0.1.5 
command line:nohup bash run_server_2pass.sh \
  --model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx \
  --online-model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx \
  --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx \
  --punc-dir damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727-onnx \
  --itn-dir thuduj12/fst_itn_zh \
  --decoder-thread-num 32 \
  --io-thread-num  8 \
  --port 10095 \
  --certfile 0 \
  --hotword ../../hotwords.txt > log.out 2>&1 &

log.out:
[log.zip](https://github.com/alibaba-damo-academy/FunASR/files/13349124/log.zip)
请问是什么原因造成的，需要怎么处理

**Comment by LauraGPT** [comment]
Ref to https://github.com/alibaba-damo-academy/FunASR/issues/1081

**Comment by bltcn** [comment]
nlohmann::json jReq = {
            { "is_speaking", false }
        };
        std::string strReq = jReq.dump().c_str();
        sendMessage(strReq.c_str(), strReq.length());

客户端执行了这个指令之后，才出现的异常情况。

**Comment by lyblsgo** [comment]
Thank you for the feedback. The issue has been fixed and will be included in the next release.
