### ISSUE TITLE
实时转写标点问题

### ISSUE THREAD

**Issue by shenyw0103** [alibaba-damo-academy/FunASR#1095]
感谢达摩院开源这么棒的引擎，有个问题请教下，在实时转写模式下，一句话的标点需要下一句话结束的时候才会出现前一句话的标点，请问这个怎么将标点实时显示出来，即一句话结束时就带上标点。

**Comment by lyblsgo** [comment]
The punctuation model requires context, specifically, it needs to look ahead. Therefore, the punctuation from the previous sentence appears at the beginning of the next sentence.

**Comment by shenyw0103** [comment]
感谢解答，在实际使用中，如果长时间没人说话，最后一句话要结束时才有标点， 是否有一句话结束时或者一段时间静音后可以解析出标点的模型？

**Comment by lyblsgo** [comment]
It needs to look ahead

**Comment by shenyw0103** [comment]
如果我需要在一句话结束时就获取到标点（获取在第二句话开始时就获取到前一句的标点），而不是在**第二句话完全结束时**才能获取到第一句话的标点，您这边是否有啥好的建议？

**Comment by lyblsgo** [comment]
The current 2-pass structure cannot meet your requirements. Punctuation prediction is only performed after the voice activity detection (VAD) detects a boundary point, and punctuation prediction requires contextual information.
<img width="512" alt="online_structure" src="https://github.com/alibaba-damo-academy/FunASR/assets/9068933/19b18eac-21ed-4f0b-8740-329562c35193">

**Comment by shenyw0103** [comment]
明白，后续有计划支持我这个需求吗？

**Comment by lyblsgo** [comment]
I am useless #
