### ISSUE TITLE
在离线环境下无法加载asr模型？

### ISSUE THREAD

**Issue by xuhongtian** [alibaba-damo-academy/FunASR#1098]
os:python3.9的 modelscope=1.9.4 funasr=0.8.4，torch=2.0.1.
inference_pipline = pipeline(task=Tasks.auto_speech_recognition,model="/data/asr_model/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch")
本地configuration.json配置
{
  "framework": "pytorch",
  "task" : "auto-speech-recognition",
  "model" : {
    "type" : "generic-asr",
    "am_model_name" : "model.pb",
    "model_config" : {
      "type": "pytorch",
      "code_base": "funasr",
      "mode": "paraformer",
      "lang": "zh-cn",
      "batch_size": 1,
      "am_model_config": "config.yaml",
      "asr_model_config": "decoding.yaml",
      "mvn_file": "am.mvn",
      "model":"/data/asr_model/peech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch",
      "lm_model": "/data/asr_model/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch"
    }
  },
  "pipeline": {
    "type":"asr-inference"
  }
}
![333](https://github.com/alibaba-damo-academy/FunASR/assets/53422160/d5d7ea8c-c8f4-41a5-8b2b-8154afd6c9be)
我的配置文件应该均已下载到本地，列表如下
![222](https://github.com/alibaba-damo-academy/FunASR/assets/53422160/2bfa0100-0ec7-4683-b533-e2f8f77d070e)
请问下这是什么问题？

**Comment by LauraGPT** [comment]
Firstly, you should not change the model names in the `configuration.json`. 

Secondly, you just set the model name to the local path. [docs](https://alibaba-damo-academy.github.io/FunASR/en/modelscope_pipeline/quick_start_zh.html#id9)

Lastly, the paraformer-long model contains `asr`, `vad`, `punc` models. You should set them all to local path. [demo](https://github.com/alibaba-damo-academy/FunASR/blob/main/egs_modelscope/asr_vad_punc/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/demo.py)

**Comment by xuhongtian** [comment]
按照你提供的https://alibaba-damo-academy.github.io/FunASR/en/modelscope_pipeline/quick_start_zh.html#id9，我在本地服务器进行模型下载和适配，还是依然存在服务器无法加载离线模型。
code:
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

modelpath = "/data/modelscope_bak/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch"
asr_pipeline = pipeline(task=Tasks.auto_speech_recognition,model=modelpath)
wav_name = "2023110200000949.wav"
asr_result = asr_pipeline(audio_in=wav_name)
print(asr_result)
 模型存放本地地址如下：
<img width="797" alt="模型地址" src="https://github.com/alibaba-damo-academy/FunASR/assets/53422160/57580383-966f-49f4-a297-7baafe1542a9">
config配置如下
<img width="672" alt="configuration配置" src="https://github.com/alibaba-damo-academy/FunASR/assets/53422160/c04dd9f4-54ee-435f-967d-8c1acd001b8f">
发现依然存在模型启动后还是会默认去读取cache,从而无法首先读取本地模型。
