### ISSUE TITLE
测试了一批数据，准确率非常低

### ISSUE THREAD

**Issue by better-one** [alibaba-damo-academy/FunASR#1099]
我们通过附件的测试集，在https://modelscope.cn/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/summary

上传数据进行测试，得到的准确率为0%，请问是哪里的问题呢
![image](https://github.com/alibaba-damo-academy/FunASR/assets/25762955/0992c1fa-e7e7-4723-8020-cc4bb8811d3f)

[测试音频.zip](https://github.com/alibaba-damo-academy/FunASR/files/13389277/default.zip)

**Comment by LauraGPT** [comment]
I have test your wav with soxi, the info is :

```text
(base) ➜  zh-cn soxi common_voice_zh-CN_34926412.wav

Input File     : 'common_voice_zh-CN_34926412.wav'
Channels       : 1
Sample Rate    : 32000
Precision      : 16-bit
Duration       : 00:00:08.14 = 260352 samples ~ 610.2 CDDA sectors
File Size      : 521k
Bit Rate       : 512k
Sample Encoding: 16-bit Signed Integer PCM
```

The demo service in the web-pages only supports the wav with 16000 sampling-rate, and your rate is 32000. Maybe you could resample the wav and try it again. I suggest you use it by pipeline in you computers install or web-pages.
