### ISSUE TITLE
docker deploy memory will not be released after continuous recognition

### ISSUE THREAD

**Issue by JacksonPan123** [alibaba-damo-academy/FunASR#1101]
OS: linux（CentOS Linux release 7.8.2003 (Core)）

Python/C++ Version：Python-3.8.18

Package Version：pytorch-wpe（0.0.1）、torchaudio（2.1.0）、modelscope（1.9.2）、funasr（0.8.0）

16-core vCPU, 32G memory

Model：
speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-onnx
punc_ct-transformer_zh-cn-common-vocab272727-onnx
speech_fsmn_vad_zh-cn-16k-common-onnx

Command：
nohup bash run_server.sh \
  --download-model-dir /workspace/models \
  --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx \
  --model-dir damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-onnx  \
  --punc-dir damo/punc_ct-transformer_zh-cn-common-vocab272727-onnx \
  --certfile 0 \
  --decoder-thread-num 16 \
  --io-thread-num  2 \
  --port 10095 \
  --itn-dir thuduj12/fst_itn_zh > log.out 2>&1 &

Details：
Docker deployment, using Java client for continuous offline speech recognition, incomplete memory release, resulting in memory overflow and service restart.

Video duration is: 15 minutes, 30 minutes, 1.5 hours, 4 hours, The sampling rate is 16000.

Using any audio, continuous recognition will cause memory overflow.

Memory is initially 12.2%：
![image](https://github.com/alibaba-damo-academy/FunASR/assets/87793735/5fddc67f-f899-4652-ade8-0ef15457da8f)

After the above four audio recognitions are completed, the memory reaches 40%：
![image](https://github.com/alibaba-damo-academy/FunASR/assets/87793735/17a25b7c-e08e-4650-b0d1-ece916d7b2cb)

Continue speech recognition, memory overflow：
![image](https://github.com/alibaba-damo-academy/FunASR/assets/87793735/a376917f-0fab-4f2e-abe9-7d2879d2ef44)

**Comment by JacksonPan123** [comment]
docker：registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-cpu-0.3.0

**Comment by Echo-Wxl** [comment]
I also encountered the same problem, did you solve it?

**Comment by LauraGPT** [comment]
Would you please test it with cpp-client? We do not good at java.

**Comment by Echo-Wxl** [comment]
> Would you please test it with cpp-client? We do not good at java.

Thanks for the answer. 
According to my test, It is not a client request problem. When I use cpp、html or python client requests, the problem is also that the memory continues to grow and is not released. Please test whether this bug exists.

**Comment by lyblsgo** [comment]
Try the newest version funasr-runtime-sdk-cpu-0.4.3. If the issue persists, please reopen the issue and provide detailed steps to reproduce, as well as server and client logs.
