### ISSUE TITLE
请问如何部署在安卓设备上？

### ISSUE THREAD

**Issue by birnfly** [alibaba-damo-academy/FunASR#1103]
请问如何部署在安卓设备上？
后面会支持通过mnn部署吗？

**Comment by yeyupiaoling** [comment]
目前runtime中有Android调用WebSocket服务的

**Comment by csukuangfj** [comment]
可以看看https://github.com/k2-fsa/sherpa-onnx/releases/tag/v1.8.10

流式和非流式的 Paraformer, 支持在 android 和 ios 等设备上跑。
<img width="971" alt="Screenshot 2023-11-23 at 13 25 49" src="https://github.com/alibaba-damo-academy/FunASR/assets/5284924/c131362b-c79a-4974-945d-8930bbe36cb6">

**Comment by LauraGPT** [comment]
The `apk` could be found in https://www.modelscope.cn/models/manyeyes/aliparaformerasr-large-model-offline/summary
The source is in https://github.com/alibaba-damo-academy/FunASR/blob/main/runtime/csharp/AliParaformerAsr/README.md

**Comment by birnfly** [comment]
非常感谢大家，我研究一下，离成功又近一步了

**Comment by brekov** [comment]
> 非常感谢大家，我研究一下，离成功又近一步了

Hello 请问在 Android 上跑通了么？请大佬给点资料供参考下吧

**Comment by csukuangfj** [comment]
> > 非常感谢大家，我研究一下，离成功又近一步了
> 
> Hello 请问在 Android 上跑通了么？请大佬给点资料供参考下吧

上面的链接，你看了没？@brekov

**Comment by brekov** [comment]
> > > 非常感谢大家，我研究一下，离成功又近一步了
> > 
> > 
> > Hello 请问在 Android 上跑通了么？请大佬给点资料供参考下吧
> 
> 上面的链接，你看了没？@brekov

看过 sherpa-onnx，项目可以说挺棒的。 但请问 sherpa-onnx 跟 FUNASR 的关系是啥呢？我希望调研更多的方案来对比下效果。

**Comment by csukuangfj** [comment]
funasr的paraformer可以在sherpa-onnx里面跑

可以用sherpa-onnx支持的所有语言，所有操作系统，所有芯片架构
