### ISSUE TITLE
docker onnx err

### ISSUE THREAD

**Issue by hzfei** [alibaba-damo-academy/FunASR#1105]
----------------只用model名字---------
I20231121 09:17:33.607086    56 funasr-wss-server.cpp:27] model-dir : damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404-onnx
I20231121 09:17:33.607156    56 funasr-wss-server.cpp:27] quantize : true
I20231121 09:17:33.607164    56 funasr-wss-server.cpp:27] vad-dir : 
I20231121 09:17:33.607170    56 funasr-wss-server.cpp:27] vad-quant : true
I20231121 09:17:33.607177    56 funasr-wss-server.cpp:27] punc-dir : 
I20231121 09:17:33.607182    56 funasr-wss-server.cpp:27] punc-quant : true
I20231121 09:17:33.607188    56 funasr-wss-server.cpp:27] itn-dir : 
I20231121 09:17:33.607194    56 funasr-wss-server.cpp:27] lm-dir : damo/speech_ngram_lm_zh-cn-ai-wesp-fst
I20231121 09:17:33.607200    56 funasr-wss-server.cpp:27] hotword : ./hotwords.txt
I20231121 09:17:33.607205    56 funasr-wss-server.cpp:27] model-revision : v1.2.1
I20231121 09:17:33.607211    56 funasr-wss-server.cpp:27] vad-revision : v1.2.0
I20231121 09:17:33.607218    56 funasr-wss-server.cpp:27] punc-revision : v1.1.7
I20231121 09:17:33.607223    56 funasr-wss-server.cpp:27] itn-revision : v1.0.1
I20231121 09:17:33.607229    56 funasr-wss-server.cpp:27] lm-revision : v1.0.1
I20231121 09:17:33.607237    56 funasr-wss-server.cpp:220] VAD model is not set, use default.
I20231121 09:17:33.607251    56 funasr-wss-server.cpp:251] Download model: damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404-onnx from modelscope: 
2023-11-21 09:17:34,710 - modelscope - INFO - PyTorch version 1.13.1+cpu Found.
2023-11-21 09:17:34,710 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-11-21 09:17:34,771 - modelscope - INFO - Loading done! Current index file version is 1.9.4, with md5 60bd3d6f6d99e2c5669b65991572d2dd and a total number of 945 components indexed
Traceback (most recent call last):
  File "/workspace/FunASR/funasr/utils/runtime_sdk_download_tool.py", line 23, in <module>
    model_dir = snapshot_download(args.model_name, cache_dir=args.export_dir, revision=args.model_revision)
  File "/usr/local/lib/python3.7/site-packages/modelscope/hub/snapshot_download.py", line 76, in snapshot_download
    cache = ModelFileSystemCache(cache_dir, group_or_owner, name)
  File "/usr/local/lib/python3.7/site-packages/modelscope/hub/utils/caching.py", line 135, in __init__
    super().__init__(os.path.join(cache_root, owner, name))
  File "/usr/local/lib/python3.7/site-packages/modelscope/hub/utils/caching.py", line 35, in __init__
    self.load_cache()
  File "/usr/local/lib/python3.7/site-packages/modelscope/hub/utils/caching.py", line 46, in load_cache
    self.cached_files = pickle.load(f)
EOFError: Ran out of input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/FunASR/funasr/utils/runtime_sdk_download_tool.py", line 26, in <module>
    (model_dir)
TypeError: exceptions must derive from BaseException
I20231121 09:17:34.939603    56 funasr-wss-server.cpp:258] Failed to download model from modelscope. If you set local asr model path, you can ignore the errors.
I20231121 09:17:34.939723    56 funasr-wss-server.cpp:270] Set model-dir : /workspace/models/damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404-onnx
I20231121 09:17:34.939746    56 funasr-wss-server.cpp:315] ITN model is not set, not executed.
I20231121 09:17:34.939771    56 funasr-wss-server.cpp:331] Download model: damo/speech_ngram_lm_zh-cn-ai-wesp-fst from modelscope : 
2023-11-21 09:17:35,986 - modelscope - INFO - PyTorch version 1.13.1+cpu Found.
2023-11-21 09:17:35,986 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-11-21 09:17:36,043 - modelscope - INFO - Loading done! Current index file version is 1.9.4, with md5 60bd3d6f6d99e2c5669b65991572d2dd and a total number of 945 components indexed
Traceback (most recent call last):
  File "/workspace/FunASR/funasr/utils/runtime_sdk_download_tool.py", line 23, in <module>
    model_dir = snapshot_download(args.model_name, cache_dir=args.export_dir, revision=args.model_revision)
  File "/usr/local/lib/python3.7/site-packages/modelscope/hub/snapshot_download.py", line 76, in snapshot_download
    cache = ModelFileSystemCache(cache_dir, group_or_owner, name)
  File "/usr/local/lib/python3.7/site-packages/modelscope/hub/utils/caching.py", line 135, in __init__
    super().__init__(os.path.join(cache_root, owner, name))
  File "/usr/local/lib/python3.7/site-packages/modelscope/hub/utils/caching.py", line 35, in __init__
    self.load_cache()
  File "/usr/local/lib/python3.7/site-packages/modelscope/hub/utils/caching.py", line 46, in load_cache
    self.cached_files = pickle.load(f)
EOFError: Ran out of input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/FunASR/funasr/utils/runtime_sdk_download_tool.py", line 26, in <module>
    (model_dir)
TypeError: exceptions must derive from BaseException
I20231121 09:17:36.207378    56 funasr-wss-server.cpp:345] Failed to download model from modelscope. If you set local lm model path, you can ignore the errors.
I20231121 09:17:36.207473    56 funasr-wss-server.cpp:354] Set lm-dir : /workspace/models/damo/speech_ngram_lm_zh-cn-ai-wesp-fst
I20231121 09:17:36.207497    56 funasr-wss-server.cpp:394] PUNC model is not set, use default.
I20231121 09:17:36.207525    56 funasr-wss-server.cpp:420] hotword path: ./hotwords.txt
E20231121 09:17:36.207628    56 util.cpp:585] Unable to open hotwords file: ./hotwords.txt. If you have not set hotwords, please ignore this message.
I20231121 09:17:36.210507    56 funasr-wss-server.cpp:453] SSL is closed!
I20231121 09:17:36.210793    56 offline-stream.cpp:22] VAD model file is not exist, skip load vad model.
I20231121 09:17:36.289235    56 paraformer.cpp:270] Successfully load model from /workspace/models/damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404-onnx/model_eb.onnx
I20231121 09:17:36.289315    56 seg_dict.cpp:37] load seg dict successfully
E20231121 09:17:36.289477    56 paraformer.cpp:43] Error when load am onnx model: Load model from /workspace/models/damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404-onnx/model_quant.onnx failed:/onnxruntime_src/onnxruntime/core/graph/model.cc:130 onnxruntime::Model::Model(onnx::ModelProto&&, const PathString&, const IOnnxRuntimeOpSchemaRegistryList*, const onnxruntime::logging::Logger&, const onnxruntime::ModelOptions&) ModelProto does not have a graph.

-----------用了model绝对路径------------------
I20231121 09:20:33.529752   294 funasr-wss-server.cpp:27] model-dir : /workspace/models/damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404-onnx
I20231121 09:20:33.529811   294 funasr-wss-server.cpp:27] quantize : true
I20231121 09:20:33.529819   294 funasr-wss-server.cpp:27] vad-dir : 
I20231121 09:20:33.529824   294 funasr-wss-server.cpp:27] vad-quant : true
I20231121 09:20:33.529829   294 funasr-wss-server.cpp:27] punc-dir : 
I20231121 09:20:33.529834   294 funasr-wss-server.cpp:27] punc-quant : true
I20231121 09:20:33.529839   294 funasr-wss-server.cpp:27] itn-dir : 
I20231121 09:20:33.529845   294 funasr-wss-server.cpp:27] lm-dir : /workspace/models/damo/speech_ngram_lm_zh-cn-ai-wesp-fst
I20231121 09:20:33.529850   294 funasr-wss-server.cpp:27] hotword : ./hotwords.txt
I20231121 09:20:33.529855   294 funasr-wss-server.cpp:27] model-revision : v1.2.1
I20231121 09:20:33.529860   294 funasr-wss-server.cpp:27] vad-revision : v1.2.0
I20231121 09:20:33.529865   294 funasr-wss-server.cpp:27] punc-revision : v1.1.7
I20231121 09:20:33.529870   294 funasr-wss-server.cpp:27] itn-revision : v1.0.1
I20231121 09:20:33.529876   294 funasr-wss-server.cpp:27] lm-revision : v1.0.1
I20231121 09:20:33.529883   294 funasr-wss-server.cpp:220] VAD model is not set, use default.
I20231121 09:20:34.435026   294 funasr-wss-server.cpp:270] Set model-dir : /workspace/models/damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404-onnx
I20231121 09:20:34.435086   294 funasr-wss-server.cpp:315] ITN model is not set, not executed.
I20231121 09:20:35.307076   294 funasr-wss-server.cpp:354] Set lm-dir : /workspace/models/damo/speech_ngram_lm_zh-cn-ai-wesp-fst
I20231121 09:20:35.307134   294 funasr-wss-server.cpp:394] PUNC model is not set, use default.
I20231121 09:20:35.307160   294 funasr-wss-server.cpp:420] hotword path: ./hotwords.txt
E20231121 09:20:35.307232   294 util.cpp:585] Unable to open hotwords file: ./hotwords.txt. If you have not set hotwords, please ignore this message.
I20231121 09:20:35.309887   294 funasr-wss-server.cpp:453] SSL is closed!
I20231121 09:20:35.310106   294 offline-stream.cpp:22] VAD model file is not exist, skip load vad model.
I20231121 09:20:35.391731   294 paraformer.cpp:270] Successfully load model from /workspace/models/damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404-onnx/model_eb.onnx
I20231121 09:20:35.391809   294 seg_dict.cpp:37] load seg dict successfully
E20231121 09:20:35.391985   294 paraformer.cpp:43] Error when load am onnx model: Load model from /workspace/models/damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404-onnx/model_quant.onnx failed:/onnxruntime_src/onnxruntime/core/graph/model.cc:130 onnxruntime::Model::Model(onnx::ModelProto&&, const PathString&, const IOnnxRuntimeOpSchemaRegistryList*, const onnxruntime::logging::Logger&, const onnxruntime::ModelOptions&) ModelProto does not have a graph.

**Comment by lyblsgo** [comment]
来自@hzfei 反馈：
我用docker root权限导出的onnx等文件，在构建新的镜像的时候，docker copy没有权限复制。
现在把文件权限改了，可以了
