### ISSUE TITLE
请问这里可以加入左右声道区分的功能么？

### ISSUE THREAD

**Issue by aixuedegege** [alibaba-damo-academy/FunASR#1107]
https://github.com/alibaba-damo-academy/FunASR/blob/b57b98364ff60ae0119b2e8d92471316bb4e504f/runtime/html5/static/main.js#L544C100-L544C100

**Comment by yeyupiaoling** [comment]
这个要手动分离再输入

**Comment by yeyupiaoling** [comment]
因为WebSocket服务端是不会自动分割多通道的。

**Comment by aixuedegege** [comment]
好的 谢谢
