### ISSUE TITLE
基于FunASR/egs自己训练的paraformer模型如何进行inference呢？

### ISSUE THREAD

**Issue by h310558606** [alibaba-damo-academy/FunASR#1108]
我想基于FunASR/egs的代码训练一个小语种的ASR模型，训练完成以后在exp文件夹中生成了一些模型文件和配置文件： checkpoint.pb，valid.acc.best.pb，config.yaml；
但是我不知道如何利用这些生成的文件进行模型的inference操作，貌似readme里边也没有讲解，请问我应该如何操作呢？

请大神赐教操作步骤，非常感谢！！！

![屏幕截图2023 11 22_10 53 29](https://github.com/alibaba-damo-academy/FunASR/assets/38098690/3f400cfb-d674-4daa-9fac-4c103764b1eb)

**Comment by MiningIrving** [comment]
我直接把生成的pb文件替换掉之前官方的pb文件，之后就可以使用官方的推理程序进行推理

**Comment by LauraGPT** [comment]
duplicated to https://github.com/alibaba-damo-academy/FunASR/issues/1109
