### ISSUE TITLE
Export onnx model: Error: No module named 'funasr.export.models.language_models'

### ISSUE THREAD

**Issue by Philshuo** [alibaba-damo-academy/FunASR#1112]
OS: ubuntu 20.04 LTS
Python/C++ Version：python3.8 gcc8.2
Package Version：funasr-onnx==0.2.4 torch==2.1.0、modelscope==1.9.5、funasr==0.8.5、torchaudio==2.1.0、onnx==1.15.0、onnxruntime==1.16.3
CMD:(funasr) ssr@ssr:~/funasr/funasr11/FunASR/egs_modelscope/asr/paraformer/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/checkpoint/11_17/1$ python -m funasr.export.export_model --model-name ./damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online --export-dir ./export --type onnx --quantize true

Details: 
Traceback (most recent call last):
  File "/home/ssr/miniconda3/envs/funasr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ssr/miniconda3/envs/funasr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ssr/funasr/funasr11/FunASR/funasr/export/export_model.py", line 8, in <module>
    from funasr.export.models import get_model
  File "/home/ssr/funasr/funasr11/FunASR/funasr/export/models/__init__.py", line 4, in <module>
    from funasr.export.models.e2e_asr_conformer import Conformer as Conformer_export
  File "/home/ssr/funasr/funasr11/FunASR/funasr/export/models/e2e_asr_conformer.py", line 11, in <module>
    from funasr.export.models.decoder.xformer_decoder import XformerDecoder as TransformerDecoder_export
  File "/home/ssr/funasr/funasr11/FunASR/funasr/export/models/decoder/xformer_decoder.py", line 9, in <module>
    from funasr.export.models.language_models.embed import Embedding
ModuleNotFoundError: No module named 'funasr.export.models.language_models'

there is a model.pb under "~/funasr/funasr11/FunASR/egs_modelscope/asr/paraformer/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/checkpoint/11_17/1/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/"

drwxrwxr-x  6 ssr ssr      4096 11月 23 11:09 ./
drwxrwxr-x 11 ssr ssr      4096 11月 23 11:00 ../
-rw-------  1 ssr ssr     11203 11月 22 16:13 am.mvn
-rw-------  1 ssr ssr       562 11月 22 16:13 configuration.json
-rw-rw-r--  1 ssr ssr     56744 11月 22 15:59 config.yaml
-rw-------  1 ssr ssr        91 11月 22 16:13 decoding.yaml
drwxrwxr-x  2 ssr ssr      4096 11月 22 16:13 example/
drwxrwxr-x  2 ssr ssr      4096 11月 22 17:05 fig/
-rw-------  1 ssr ssr       725 11月 22 16:13 finetune.yaml
-rw-rw-r--  1 ssr ssr        93 11月 22 16:49 .mdl
-rw-rw-r--  1 ssr ssr 880716538 11月 22 16:11 model.pb
-rw-------  1 ssr ssr       771 11月 22 17:05 .msc
-rw-------  1 ssr ssr      8403 11月 22 17:04 README.md
-rw-------  1 ssr ssr   8287834 11月 22 17:04 seg_dict
drwxrwxr-x  2 ssr ssr      4096 11月 22 21:53 temp/
-rw-------  1 ssr ssr     34846 11月 22 17:05 tokens.txt

reference:https://alibaba-damo-academy.github.io/FunASR/en/funasr/export/README.html?highlight=onnx

follow the doc to export onnx model of local finetune model(model.pb)

**Comment by LauraGPT** [comment]
Bug has been fixed, please update funasr-0.8.6

**Comment by Philshuo** [comment]
Yes, after update funasr-0.8.6, everything looks good! Got the exported .onnx file using python -m funasr.export.export_model --model-name damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch --export-dir ./export --type onnx --quantize false under relative dir.

Thanks! Very nice work!
