### ISSUE TITLE
小视频可以分析，大视频报错

### ISSUE THREAD

**Issue by yanliuyiran** [alibaba-damo-academy/FunASR#1116]
![1700721685560](https://github.com/alibaba-damo-academy/FunASR/assets/19900081/7d9979a6-d7ed-4c40-98c3-a5982a228ca3)
官方提供的文件较小的可以进行分析，然后传递一个几百MB的视频一直报错，想知道怎么解决

**Comment by LauraGPT** [comment]
Please raise a issue as https://github.com/alibaba-damo-academy/FunASR/issues/1074

**Comment by lyblsgo** [comment]
try the newest docker images:  [https://github.com/alibaba-damo-academy/FunASR/blob/main/runtime/readme_cn.md](url)
