### ISSUE TITLE
训练paraformer时出现梯度为NaN的值

### ISSUE THREAD

**Issue by sister-tong** [alibaba-damo-academy/FunASR#1124]
linux:Ubuntu 20.04.4
python=3.8.18
torch=2.0.1
funasr=0.8.2
modelscope=1.9.3

在训练egs/aishell/paraformer模型的时候，出现梯度为Nan的警告[autodl-container-4d6411b93c-8a044365] 2023-11-24 08:26:08,148 (ctc:67) WARNING: 1/140 samples got nan grad. These were ignored for CTC loss.
具体的日志：
train.log.0里面显示
[autodl-container-4d6411b93c-8a044365] 2023-11-24 08:24:49,269 (sequence_iter_factory:77) INFO: [valid] Batch sampler: LengthBatchSampler(N-batch=52, batch_bins=25000, sort_in_batch=descending, sort_batch=descending)
[autodl-container-4d6411b93c-8a044365] 2023-11-24 08:24:49,269 (sequence_iter_factory:78) INFO: [valid] mini-batch sizes summary: N-batch=52, mean=57.7, min=4, max=97
[autodl-container-4d6411b93c-8a044365] 2023-11-24 08:24:49,355 (build_trainer:260) INFO: 1/150epoch started
[autodl-container-4d6411b93c-8a044365] 2023-11-24 08:24:55,103 (e2e_asr_paraformer:488) INFO: enable sampler in paraformer, sampling_ratio: 0.4
[autodl-container-4d6411b93c-8a044365] 2023-11-24 08:25:19,871 (build_trainer:733) INFO: 1epoch:train:1-50batch:50num_updates: iter_time=0.069, forward_time=0.248, loss_ctc=256.253, loss_att=76.810, pre_loss_att=74.184, acc=0.045, loss_pre=15.994, loss=198.566, backward_time=0.165, optim_step_time=0.022, optim0_lr0=4.417e-06, train_time=0.610
[autodl-container-4d6411b93c-8a044365] 2023-11-24 08:25:44,581 (build_trainer:733) INFO: 1epoch:train:51-100batch:100num_updates: iter_time=1.530e-04, forward_time=0.211, loss_ctc=89.220, loss_att=65.906, pre_loss_att=61.067, acc=0.087, loss_pre=6.916, loss=122.564, backward_time=0.164, optim_step_time=0.020, optim0_lr0=1.275e-05, train_time=0.494
[autodl-container-4d6411b93c-8a044365] 2023-11-24 08:26:07,913 (build_trainer:733) INFO: 1epoch:train:101-150batch:150num_updates: iter_time=1.244e-04, forward_time=0.195, loss_ctc=87.374, loss_att=67.221, pre_loss_att=64.451, acc=0.089, loss_pre=6.898, loss=125.281, backward_time=0.155, optim_step_time=0.019, optim0_lr0=2.108e-05, train_time=0.467
[autodl-container-4d6411b93c-8a044365] 2023-11-24 08:26:08,148 (ctc:67) WARNING: 1/140 samples got nan grad. These were ignored for CTC loss.
[autodl-container-4d6411b93c-8a044365] 2023-11-24 08:26:31,019 (build_trainer:733) INFO: 1epoch:train:151-200batch:200num_updates: iter_time=1.146e-04, forward_time=0.196, loss_ctc=80.427, loss_att=59.902, pre_loss_att=60.842, acc=0.093, loss_pre=5.982, loss=114.631, backward_time=0.146, optim_step_time=0.019, optim0_lr0=2.942e-05, train_time=0.462
[autodl-container-4d6411b93c-8a044365] 2023-11-24 08:26:54,208 (build_trainer:733) INFO: 1epoch:train:201-250batch:250num_updates: iter_time=1.355e-04, forward_time=0.200, loss_ctc=81.137, loss_att=56.568, pre_loss_att=62.780, acc=0.097, loss_pre=6.104, loss=113.989, backward_time=0.143, optim_step_time=0.019, optim0_lr0=3.775e-05, train_time=0.464
[autodl-container-4d6411b93c-8a044365] 2023-11-24 08:27:18,115 (build_trainer:733) INFO: 1epoch:train:251-300batch:300num_updates: iter_time=1.127e-04, forward_time=0.197, loss_ctc=80.881, loss_att=51.466, pre_loss_att=63.410, acc=0.098, loss_pre=6.149, loss=110.827, backward_time=0.162, optim_step_time=0.019, optim0_lr0=4.608e-05, train_time=0.478
[autodl-container-4d6411b93c-8a044365] 2023-11-24 08:27:41,173 (build_trainer:733) INFO: 1epoch:train:301-350batch:350num_updates: iter_time=1.062e-04, forward_time=0.188, loss_ctc=78.571, loss_att=46.789, pre_loss_att=61.837, acc=0.098, loss_pre=5.874, loss=105.484, backward_time=0.156, optim_step_time=0.018, optim0_lr0=5.442e-05, train_time=0.461
[autodl-container-4d6411b93c-8a044365] 2023-11-24 08:28:06,382 (build_trainer:733) INFO: 1epoch:train:351-400batch:400num_updates: iter_time=1.222e-04, forward_time=0.202, loss_ctc=79.238, loss_att=45.230, pre_loss_att=62.730, acc=0.100, loss_pre=5.638, loss=104.982, backward_time=0.182, optim_step_time=0.019, optim0_lr0=6.275e-05, train_time=0.504

请问这种问题，该怎么去排查

**Comment by LauraGPT** [comment]
We have also encounter the case, and do not know what happen. According to our experiments, the warning does not affect the results. 
And also, we are rebuild the structure of funasr to avoid the case.

**Comment by sister-tong** [comment]
Ok, thanks for the answer
