### ISSUE TITLE
运行离线语音转写服务报错

### ISSUE THREAD

**Issue by INSIinc** [alibaba-damo-academy/FunASR#1126]
运行
```
cd FunASR/runtime
nohup bash run_server.sh \
  --download-model-dir /workspace/models \
  --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx \
  --model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx  \
  --punc-dir damo/punc_ct-transformer_cn-en-common-vocab471067-large-onnx \
  --lm-dir damo/speech_ngram_lm_zh-cn-ai-wesp-fst \
  --itn-dir thuduj12/fst_itn_zh \
  --hotword /workspace/models/hotwords.txt > log.out 2>&1 &
```
log.ouit报错如下
```
I20231124 11:48:53.589133 15268 funasr-wss-server.cpp:198] Download model: damo/speech_fsmn_vad_zh-cn-16k-common-onnx from modelscope: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/workspace/FunASR/funasr/__init__.py", line 5, in <module>
    import torch
  File "/usr/local/lib/python3.7/site-packages/torch/__init__.py", line 218, in <module>
    from torch._C import *  # noqa: F403
ImportError: /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so: cannot read file data
I20231124 11:48:53.627151 15268 funasr-wss-server.cpp:205] Failed to download model from modelscope. If you set local vad model path, you can ignore the errors.
E20231124 11:48:53.627213 15268 funasr-wss-server.cpp:213] /workspace/models/damo/speech_fsmn_vad_zh-cn-16k-common-onnx/model_quant.onnx do not exists.
```

**Comment by LauraGPT** [comment]
> 运行
> 
> ```
> cd FunASR/runtime
> nohup bash run_server.sh \
>   --download-model-dir /workspace/models \
>   --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx \
>   --model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx  \
>   --punc-dir damo/punc_ct-transformer_cn-en-common-vocab471067-large-onnx \
>   --lm-dir damo/speech_ngram_lm_zh-cn-ai-wesp-fst \
>   --itn-dir thuduj12/fst_itn_zh \
>   --hotword /workspace/models/hotwords.txt > log.out 2>&1 &
> ```
> 
> log.ouit报错如下
> 
> ```
> I20231124 11:48:53.589133 15268 funasr-wss-server.cpp:198] Download model: damo/speech_fsmn_vad_zh-cn-16k-common-onnx from modelscope: 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
>     __import__(pkg_name)
>   File "/workspace/FunASR/funasr/__init__.py", line 5, in <module>
>     import torch
>   File "/usr/local/lib/python3.7/site-packages/torch/__init__.py", line 218, in <module>
>     from torch._C import *  # noqa: F403
> ImportError: /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so: cannot read file data
> I20231124 11:48:53.627151 15268 funasr-wss-server.cpp:205] Failed to download model from modelscope. If you set local vad model path, you can ignore the errors.
> E20231124 11:48:53.627213 15268 funasr-wss-server.cpp:213] /workspace/models/damo/speech_fsmn_vad_zh-cn-16k-common-onnx/model_quant.onnx do not exists.
> ```


please use the docker image which we offered.

**Comment by INSIinc** [comment]
> > 运行
> > ```
> > cd FunASR/runtime
> > nohup bash run_server.sh \
> >   --download-model-dir /workspace/models \
> >   --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx \
> >   --model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx  \
> >   --punc-dir damo/punc_ct-transformer_cn-en-common-vocab471067-large-onnx \
> >   --lm-dir damo/speech_ngram_lm_zh-cn-ai-wesp-fst \
> >   --itn-dir thuduj12/fst_itn_zh \
> >   --hotword /workspace/models/hotwords.txt > log.out 2>&1 &
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > log.ouit报错如下
> > ```
> > I20231124 11:48:53.589133 15268 funasr-wss-server.cpp:198] Download model: damo/speech_fsmn_vad_zh-cn-16k-common-onnx from modelscope: 
> > Traceback (most recent call last):
> >   File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
> >     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
> >   File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
> >     __import__(pkg_name)
> >   File "/workspace/FunASR/funasr/__init__.py", line 5, in <module>
> >     import torch
> >   File "/usr/local/lib/python3.7/site-packages/torch/__init__.py", line 218, in <module>
> >     from torch._C import *  # noqa: F403
> > ImportError: /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so: cannot read file data
> > I20231124 11:48:53.627151 15268 funasr-wss-server.cpp:205] Failed to download model from modelscope. If you set local vad model path, you can ignore the errors.
> > E20231124 11:48:53.627213 15268 funasr-wss-server.cpp:213] /workspace/models/damo/speech_fsmn_vad_zh-cn-16k-common-onnx/model_quant.onnx do not exists.
> > ```
> 
> please use the docker image which we offered.请使用我们提供的Docker镜像。

你好，我用的是sudo bash funasr-runtime-deploy-offline-cpu-zh.sh install --workspace ./funasr-runtime-resources命令

**Comment by INSIinc** [comment]
> > 运行
> > ```
> > cd FunASR/runtime
> > nohup bash run_server.sh \
> >   --download-model-dir /workspace/models \
> >   --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx \
> >   --model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx  \
> >   --punc-dir damo/punc_ct-transformer_cn-en-common-vocab471067-large-onnx \
> >   --lm-dir damo/speech_ngram_lm_zh-cn-ai-wesp-fst \
> >   --itn-dir thuduj12/fst_itn_zh \
> >   --hotword /workspace/models/hotwords.txt > log.out 2>&1 &
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > log.ouit报错如下
> > ```
> > I20231124 11:48:53.589133 15268 funasr-wss-server.cpp:198] Download model: damo/speech_fsmn_vad_zh-cn-16k-common-onnx from modelscope: 
> > Traceback (most recent call last):
> >   File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
> >     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
> >   File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
> >     __import__(pkg_name)
> >   File "/workspace/FunASR/funasr/__init__.py", line 5, in <module>
> >     import torch
> >   File "/usr/local/lib/python3.7/site-packages/torch/__init__.py", line 218, in <module>
> >     from torch._C import *  # noqa: F403
> > ImportError: /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so: cannot read file data
> > I20231124 11:48:53.627151 15268 funasr-wss-server.cpp:205] Failed to download model from modelscope. If you set local vad model path, you can ignore the errors.
> > E20231124 11:48:53.627213 15268 funasr-wss-server.cpp:213] /workspace/models/damo/speech_fsmn_vad_zh-cn-16k-common-onnx/model_quant.onnx do not exists.
> > ```
> 
> please use the docker image which we offered.请使用我们提供的Docker镜像。
```

I20231127 17:53:15.671620  2528 funasr-wss-server.cpp:27] model-dir : damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx
I20231127 17:53:15.671730  2528 funasr-wss-server.cpp:27] quantize : true
I20231127 17:53:15.671741  2528 funasr-wss-server.cpp:27] vad-dir : damo/speech_fsmn_vad_zh-cn-16k-common-onnx
I20231127 17:53:15.671747  2528 funasr-wss-server.cpp:27] vad-quant : true
I20231127 17:53:15.671753  2528 funasr-wss-server.cpp:27] punc-dir : damo/punc_ct-transformer_cn-en-common-vocab471067-large-onnx
I20231127 17:53:15.671758  2528 funasr-wss-server.cpp:27] punc-quant : true
I20231127 17:53:15.671764  2528 funasr-wss-server.cpp:27] itn-dir : thuduj12/fst_itn_zh
I20231127 17:53:15.671769  2528 funasr-wss-server.cpp:27] lm-dir : damo/speech_ngram_lm_zh-cn-ai-wesp-fst
I20231127 17:53:15.671775  2528 funasr-wss-server.cpp:27] hotword : /workspace/resources/hotwords.txt
I20231127 17:53:15.671780  2528 funasr-wss-server.cpp:27] model-revision : v1.2.1
I20231127 17:53:15.671787  2528 funasr-wss-server.cpp:27] vad-revision : v1.2.0
I20231127 17:53:15.671792  2528 funasr-wss-server.cpp:27] punc-revision : v1.1.7
I20231127 17:53:15.671798  2528 funasr-wss-server.cpp:27] itn-revision : v1.0.1
I20231127 17:53:15.671803  2528 funasr-wss-server.cpp:27] lm-revision : v1.0.1
I20231127 17:53:15.671811  2528 funasr-wss-server.cpp:198] Download model: damo/speech_fsmn_vad_zh-cn-16k-common-onnx from modelscope: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/workspace/FunASR/funasr/__init__.py", line 5, in <module>
    import torch
  File "/usr/local/lib/python3.7/site-packages/torch/__init__.py", line 28, in <module>
    from .torch_version import __version__ as __version__
ImportError: cannot import name '__version__' from 'torch.torch_version' (/usr/local/lib/python3.7/site-packages/torch/torch_version.py)
I20231127 17:53:15.711788  2528 funasr-wss-server.cpp:205] Failed to download model from modelscope. If you set local vad model path, you can ignore the errors.
E20231127 17:53:15.711880  2528 funasr-wss-server.cpp:213] /workspace/models/damo/speech_fsmn_vad_zh-cn-16k-common-onnx/model_quant.onnx do not exists.

```
容器内部报错如上

**Comment by LauraGPT** [comment]
> > > 运行
> > > ```
> > > cd FunASR/runtime
> > > nohup bash run_server.sh \
> > >   --download-model-dir /workspace/models \
> > >   --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx \
> > >   --model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx  \
> > >   --punc-dir damo/punc_ct-transformer_cn-en-common-vocab471067-large-onnx \
> > >   --lm-dir damo/speech_ngram_lm_zh-cn-ai-wesp-fst \
> > >   --itn-dir thuduj12/fst_itn_zh \
> > >   --hotword /workspace/models/hotwords.txt > log.out 2>&1 &
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > log.ouit报错如下
> > > ```
> > > I20231124 11:48:53.589133 15268 funasr-wss-server.cpp:198] Download model: damo/speech_fsmn_vad_zh-cn-16k-common-onnx from modelscope: 
> > > Traceback (most recent call last):
> > >   File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
> > >     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
> > >   File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
> > >     __import__(pkg_name)
> > >   File "/workspace/FunASR/funasr/__init__.py", line 5, in <module>
> > >     import torch
> > >   File "/usr/local/lib/python3.7/site-packages/torch/__init__.py", line 218, in <module>
> > >     from torch._C import *  # noqa: F403
> > > ImportError: /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so: cannot read file data
> > > I20231124 11:48:53.627151 15268 funasr-wss-server.cpp:205] Failed to download model from modelscope. If you set local vad model path, you can ignore the errors.
> > > E20231124 11:48:53.627213 15268 funasr-wss-server.cpp:213] /workspace/models/damo/speech_fsmn_vad_zh-cn-16k-common-onnx/model_quant.onnx do not exists.
> > > ```
> > 
> > 
> > please use the docker image which we offered.请使用我们提供的Docker镜像。
> 
> 你好，我用的是sudo bash funasr-runtime-deploy-offline-cpu-zh.sh install --workspace ./funasr-runtime-resources命令


Sorry, we do not maintain the tool `funasr-runtime-deploy-offline-cpu-zh.sh`. Please use the [docs](https://github.com/alibaba-damo-academy/FunASR/blob/main/runtime/docs/SDK_advanced_guide_offline_zh.md)

**Comment by INSIinc** [comment]
> > > > 运行
> > > > ```
> > > > cd FunASR/runtime
> > > > nohup bash run_server.sh \
> > > >   --download-model-dir /workspace/models \
> > > >   --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx \
> > > >   --model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx  \
> > > >   --punc-dir damo/punc_ct-transformer_cn-en-common-vocab471067-large-onnx \
> > > >   --lm-dir damo/speech_ngram_lm_zh-cn-ai-wesp-fst \
> > > >   --itn-dir thuduj12/fst_itn_zh \
> > > >   --hotword /workspace/models/hotwords.txt > log.out 2>&1 &
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > log.ouit报错如下
> > > > ```
> > > > I20231124 11:48:53.589133 15268 funasr-wss-server.cpp:198] Download model: damo/speech_fsmn_vad_zh-cn-16k-common-onnx from modelscope: 
> > > > Traceback (most recent call last):
> > > >   File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
> > > >     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
> > > >   File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
> > > >     __import__(pkg_name)
> > > >   File "/workspace/FunASR/funasr/__init__.py", line 5, in <module>
> > > >     import torch
> > > >   File "/usr/local/lib/python3.7/site-packages/torch/__init__.py", line 218, in <module>
> > > >     from torch._C import *  # noqa: F403
> > > > ImportError: /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so: cannot read file data
> > > > I20231124 11:48:53.627151 15268 funasr-wss-server.cpp:205] Failed to download model from modelscope. If you set local vad model path, you can ignore the errors.
> > > > E20231124 11:48:53.627213 15268 funasr-wss-server.cpp:213] /workspace/models/damo/speech_fsmn_vad_zh-cn-16k-common-onnx/model_quant.onnx do not exists.
> > > > ```
> > > 
> > > 
> > > please use the docker image which we offered.请使用我们提供的Docker镜像。请使用我们提供的Docker镜像。
> > 
> > 
> > 你好，我用的是sudo bash funasr-runtime-deploy-offline-cpu-zh.sh install --workspace ./funasr-runtime-resources命令
> 
> Sorry, we do not maintain the tool `funasr-runtime-deploy-offline-cpu-zh.sh`. Please use the [docs](https://github.com/alibaba-damo-academy/FunASR/blob/main/runtime/docs/SDK_advanced_guide_offline_zh.md)对不起，我们不维护该工具 `funasr-runtime-deploy-offline-cpu-zh.sh` 。请使用文档

您好，第一个报错是根据您发的文档配置的
