### ISSUE TITLE
speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404量化导出ONNX权重文件大小不对

### ISSUE THREAD

**Issue by Liam-Ji** [alibaba-damo-academy/FunASR#1130]
版本信息：
Python 3.8.18，funasr  0.8.6，modelscope 1.9.3，onnx 1.15.0，onnxruntime 1.16.3，torch 2.1.0，torch-quant 0.4.0，torchaudio 2.1.0，

问题描述：
使用https://alibaba-damo-academy.github.io/FunASR/en/funasr/export/README.html?highlight=onnx文档描述的导出方法对modelscope下载的speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404模型进行量化导出操作，
1、得到的model_quant.onnx（大小234M）文件与modelscope下载的对应onnx版本模型权重大小（850M）相差太大，请问是生成文件什么原因？
2、导出的文件不是在--export-dir ./export目录，而是跑到了输入目录
导出命令：
python -m funasr.export.export_model --model-name ./speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404 --export-dir ./export --type onnx --quantize true

生成文件
(funasr) linux-635d:/home/workspace/finetuned_model # ll speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404/ -h
total 2.0G
-rw-r--r-- 1 root root   97 Nov 27 10:48 .mdl
-rw------- 1 root root  970 Nov 27 10:48 .msc
-rw------- 1 root root  36K Nov 27 10:49 README.md
-rw------- 1 root root  11K Nov 27 10:48 am.mvn
-rw------- 1 root root  56K Nov 27 10:48 config.yaml
-rw------- 1 root root  631 Nov 27 10:48 configuration.json
-rw------- 1 root root   91 Nov 27 10:48 decoding.yaml
drwxr-xr-x 2 root root 4.0K Nov 27 10:48 example
drwxr-xr-x 2 root root 4.0K Nov 27 10:49 fig
-rw------- 1 root root  733 Nov 27 10:48 finetune.yaml
drwxr-xr-x 2 root root 4.0K Nov 27 10:48 lm
-rw-r--r-- 1 root root 831M Nov 27 11:06 model.onnx
-rw------- 1 root root 871M Nov 27 10:49 model.pb
-rw-r--r-- 1 root root  25M Nov 27 11:05 model_eb.onnx
-rw-r--r-- 1 root root  25M Nov 27 11:05 model_eb_quant.onnx
-rw-r--r-- 1 root root 234M Nov 27 11:07 model_quant.onnx
-rw------- 1 root root 8.0M Nov 27 10:49 seg_dict
-rw------- 1 root root  35K Nov 27 10:49 tokens.txt

运行log：

`(funasr) linux-635d:/home/workspace/finetuned_model # python -m funasr.export.export_model --model-name ./speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404 --export-dir ./export --type onnx --quantize true
export model: ./speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404
WARNING:root:enable bias encoder sampling and contextual training
/root/miniconda3/envs/funasr/lib/python3.8/site-packages/torch/onnx/symbolic_opset9.py:4661: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with LSTM can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model.
  warnings.warn(
WARNING:root:Please consider to run pre-processing before quantization. Refer to example: https://github.com/microsoft/onnxruntime-inference-examples/blob/main/quantization/image_classification/cpu/ReadMe.md
output dir: ./speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404
/home/workspace/FunASR/funasr/modules/embedding.py:398: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  log_timescale_increment = torch.log(torch.tensor([10000], dtype=dtype, device=device)) / (depth / 2 - 1)
/home/workspace/FunASR/funasr/export/models/decoder/contextual_decoder.py:110: TracerWarning: torch.Tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  contextual_length = torch.Tensor([bias_embed.shape[1]]).int().repeat(hs_pad.shape[0])
/home/workspace/FunASR/funasr/export/models/decoder/contextual_decoder.py:110: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  contextual_length = torch.Tensor([bias_embed.shape[1]]).int().repeat(hs_pad.shape[0])
/root/miniconda3/envs/funasr/lib/python3.8/site-packages/torch/onnx/utils.py:631: UserWarning: ONNX Preprocess - Removing mutation from node aten::add_ on block input: 'frame.17'. This changes graph semantics. (Triggered internally at ../torch/csrc/jit/passes/onnx/remove_inplace_ops_for_onnx.cpp:350.)
  _C._jit_pass_onnx_remove_inplace_ops_for_onnx(graph, module)
/root/miniconda3/envs/funasr/lib/python3.8/site-packages/torch/onnx/utils.py:631: UserWarning: ONNX Preprocess - Removing mutation from node aten::add_ on block input: 'integrate.23'. This changes graph semantics. (Triggered internally at ../torch/csrc/jit/passes/onnx/remove_inplace_ops_for_onnx.cpp:350.)
  _C._jit_pass_onnx_remove_inplace_ops_for_onnx(graph, module)
/root/miniconda3/envs/funasr/lib/python3.8/site-packages/torch/onnx/_internal/jit_utils.py:307: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ../torch/csrc/jit/passes/onnx/constant_fold.cpp:179.)
  _C._jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version)
/root/miniconda3/envs/funasr/lib/python3.8/site-packages/torch/onnx/utils.py:702: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ../torch/csrc/jit/passes/onnx/constant_fold.cpp:179.)
  _C._jit_pass_onnx_graph_shape_type_inference(
/root/miniconda3/envs/funasr/lib/python3.8/site-packages/torch/onnx/utils.py:1209: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ../torch/csrc/jit/passes/onnx/constant_fold.cpp:179.)
  _C._jit_pass_onnx_graph_shape_type_inference(
WARNING:root:Please consider to run pre-processing before quantization. Refer to example: https://github.com/microsoft/onnxruntime-inference-examples/blob/main/quantization/image_classification/cpu/ReadMe.md
Ignore MatMul due to non constant B: /[/encoder/encoders0/encoders0.0/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders0/encoders0.0/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.0/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.0/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.1/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.1/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.2/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.2/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.3/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.3/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.4/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.4/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.5/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.5/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.6/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.6/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.7/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.7/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.8/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.8/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.9/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.9/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.10/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.10/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.11/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.11/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.12/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.12/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.13/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.13/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.14/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.14/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.15/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.15/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.16/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.16/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.17/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.17/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.18/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.18/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.19/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.19/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.20/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.20/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.21/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.21/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.22/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.22/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.23/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.23/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.24/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.24/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.25/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.25/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.26/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.26/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.27/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.27/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.28/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.28/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.29/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.29/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.30/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.30/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.31/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.31/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.32/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.32/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.33/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.33/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.34/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.34/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.35/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.35/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.36/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.36/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.37/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.37/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.38/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.38/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.39/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.39/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.40/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.40/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.41/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.41/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.42/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.42/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.43/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.43/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.44/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.44/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.45/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.45/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.46/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.46/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.47/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.47/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.48/self_attn/MatMul]
Ignore MatMul due to non constant B: /[/encoder/encoders/encoders.48/self_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.0/src_attn/MatMul]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.0/src_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.1/src_attn/MatMul]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.1/src_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.2/src_attn/MatMul]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.2/src_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.3/src_attn/MatMul]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.3/src_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.4/src_attn/MatMul]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.4/src_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.5/src_attn/MatMul]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.5/src_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.6/src_attn/MatMul]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.6/src_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.7/src_attn/MatMul]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.7/src_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.8/src_attn/MatMul]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.8/src_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.9/src_attn/MatMul]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.9/src_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.10/src_attn/MatMul]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.10/src_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.11/src_attn/MatMul]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.11/src_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.12/src_attn/MatMul]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.12/src_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.13/src_attn/MatMul]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.13/src_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.14/src_attn/MatMul]
Ignore MatMul due to non constant B: /[/decoder/decoders/decoders.14/src_attn/MatMul_1]
Ignore MatMul due to non constant B: /[/decoder/last_decoder/src_attn/MatMul]
Ignore MatMul due to non constant B: /[/decoder/last_decoder/src_attn/MatMul_1]
output dir: ./speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404`

**Comment by R1ckShi** [comment]
modelscope上开源的Paraformer语音识别-中文-通用-16k-离线-large-热词版-onnx中的model_quant.onnx实际上导出时并没有使用量化，因为观察到在热词模型上的量化会导致热词激励能力有一定的损失。但是为了保证sdk调用模型时文件名一致，onnx文件名命名为了model_quant.onnx。
在导出时可以通过--quantize控制是否使用量化功能。

**Comment by Liam-Ji** [comment]
了解了，谢谢解答

**Comment by yourengod** [comment]
> 了解了，谢谢解答

请问你训练后导出的模型用funasr中的c++能调用吗？

**Comment by Liam-Ji** [comment]
能用的，训练后的参数文件替换pytorch版本的参数，导出为onnx就能用
