### ISSUE TITLE
demo_paraformer_online.py 这个文件的最后一个字要很久才出现，是概率出现，好像和声音大小有关

### ISSUE THREAD

**Issue by haha010508** [alibaba-damo-academy/FunASR#1134]
代码如下：
`import soundfile
import librosa
from funasr_onnx.paraformer_online_bin import Paraformer
from pathlib import Path

model_dir = "damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online"
wav_path = r'./save_audio/record_all_152347.wav'

chunk_size = [5, 10, 5]
model = Paraformer(model_dir, batch_size=1, quantize=True, chunk_size=chunk_size, intra_op_num_threads=4) # only support batch_size = 1

##online asr
speech, sample_rate = librosa.load(wav_path, sr=None)

speech_length = speech.shape[0]
sample_offset = 0
step = chunk_size[1] * 960
param_dict = {'cache': dict()}
final_result = ""
for sample_offset in range(0, speech_length, min(step, speech_length - sample_offset)):
    if sample_offset + step >= speech_length - 1:
        step = speech_length - sample_offset
        is_final = True
    else:
        is_final = False
    param_dict['is_final'] = is_final
    rec_result = model(audio_in=speech[sample_offset: sample_offset + step],
                            param_dict=param_dict)
    if len(rec_result) > 0:
       final_result += rec_result[0]["preds"][0]
    print(rec_result)
print(final_result)`

输出结果如下：
`[]
[]
[]
[]
[{'preds': ('你好', ['你', '好'])}]
[{'preds': ('仰', ['仰'])}]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[{'preds': ('望', ['望'])}]
[{'preds': ('今天', ['今', '天'])}]
[{'preds': ('星期', ['星', '期'])}]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[{'preds': ('几', ['几'])}]
[]
[]
[]
[{'preds': ('啊', ['啊'])}]
[{'preds': ('今天星', ['今', '天', '星'])}]
[{'preds': ('期几', ['期', '几'])}]
[]
[]
[{'preds': ['啊', ['啊']]}]
你好仰望今天星期几啊今天星期几啊`

解释：今天星期几，几是很多帧后才输出，不知道为啥，

音频文件如下：
[Uploading record_all_152347.zip…]()

**Comment by LauraGPT** [comment]
This is a normal phenomenon, which depends on the volume, speech rate, etc. To put it simply, streaming transcription is about accumulating energy; when the energy builds up to a certain level for a character, that character is then output. For the last character, if the volume is low, it may happen that the speech has finished, but the accumulated energy is not enough for a character. In this case, the system will keep accumulating energy until it reaches the level needed for a character, or until it receives an `is_final=true` signal, at which point it will forcibly output the character, even though the energy is insufficient.
