### ISSUE TITLE
pip更新funasr之后，训练日志报错 ModuleNotFoundError: No module named 'funasr.text'

### ISSUE THREAD

**Issue by sister-tong** [alibaba-damo-academy/FunASR#1135]
linux：Ubuntu 20.04.4
python=3.8.18
torch=2.0.1
funasr=0.8.7
modelscope=1.9.5

之前funasr版本为0.8.5,modelscope版本1.9.3在使用pip3 install -U funasr命令升级funasr之后，运行egs/aishell/e_branchformer目录下的run.sh，训练日志中报错：
Traceback (most recent call last):
  File "/root/autodl-tmp/FunASR/egs/aishell/e_branchformer/../../../funasr/bin/train.py", line 20, in <module>
    from funasr.text.phoneme_tokenizer import g2p_choices
ModuleNotFoundError: No module named 'funasr.text'

这是什么原因？

**Comment by LauraGPT** [comment]
Please update funasr-0.8.7

**Comment by sister-tong** [comment]
我把我的modelscope更新到了1.9.3,funasr更新到了0.8.7,还是会出现这个错误
![image](https://github.com/alibaba-damo-academy/FunASR/assets/103936070/7edf2945-b707-4f1f-b646-cf6b19777c1c)

**Comment by LauraGPT** [comment]
The new code is:https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/bin/train.py#L20C16-L20C16

please update funasr by: 
```
git pull 
pip install -e ./
```

**Comment by yitingss** [comment]
> linux：Ubuntu 20.04.4 python=3.8.18 torch=2.0.1 funasr=0.8.7 modelscope=1.9.5
> 
> 之前funasr版本为0.8.5,modelscope版本1.9.3在使用pip3 install -U funasr命令升级funasr之后，运行egs/aishell/e_branchformer目录下的run.sh，训练日志中报错： Traceback (most recent call last): File "/root/autodl-tmp/FunASR/egs/aishell/e_branchformer/../../../funasr/bin/train.py", line 20, in from funasr.text.phoneme_tokenizer import g2p_choices ModuleNotFoundError: No module named 'funasr.text'
> 
> 这是什么原因？

text现在被修改成名称tokenizer了
