### ISSUE TITLE
FSMN-VAD model

### ISSUE THREAD

**Issue by wwfcnu** [alibaba-damo-academy/FunASR#1136]
[FSMN-VAD model](https://modelscope.cn/models/damo/speech_fsmn_vad_zh-cn-16k-common-pytorch/summary)
这个模型在进行语音端点检测，有时候切分一段语音，start，end全是相差60s的，感觉像是没检测，直接按照60s切的

**Comment by wwfcnu** [comment]
如何设置额外的参数，控制切分的长度以及相邻端点之间的静音时间

**Comment by LauraGPT** [comment]
You could change the value of `max_single_segment_time ` in the `vad.yaml` to split shorter slice.
