### ISSUE TITLE
double free or corruption (!prev)

### ISSUE THREAD

**Issue by jimmyshenjianjun** [alibaba-damo-academy/FunASR#1154]
1、按照官网部署步骤部署
2、使用java客户端代码连接ws服务，之后进行推理
3、遇到特定音频文件ws服务必报错“double free or corruption (!prev)”，服务停止

![粘贴图片](https://github.com/alibaba-damo-academy/FunASR/assets/12603427/4fc2ded6-d792-4ce3-9f4a-39ec6c0f613d)

特定音频文件：
[052e5311b83f50c7b652ea2836dba487.zip](https://github.com/alibaba-damo-academy/FunASR/files/13595391/052e5311b83f50c7b652ea2836dba487.zip)

**Comment by lyblsgo** [comment]
The issue has been fixed and will be released in the next version.
