### ISSUE TITLE
FunAsr通过参数更改模型为paraformer-zh-spk，无法正确下载

### ISSUE THREAD

**Issue by NuyoahCx330** [alibaba-damo-academy/FunASR#1168]
###再Linux环境中

1、再容器内启动时通过 --model-dir damo/speech_paraformer-large-vad-punc-spk_asr_nat-zh-cn  指定
2、使用脚本方式更新  bash funasr-runtime-deploy-offline-cpu-zh.sh update  --asr_model  damo/speech_paraformer-large-vad-punc-spk_asr_nat-zh-cn
（--vad_model 的参数也试过了）

###错误信息1：
Traceback (most recent call last):
  File "/workspace/FunASR/funasr/utils/runtime_sdk_download_tool.py", line 23, in <module>
    model_dir = snapshot_download(args.model_name, cache_dir=args.export_dir, revision=args.model_revision)
  File "/usr/local/lib/python3.7/site-packages/modelscope/hub/snapshot_download.py", line 97, in snapshot_download
    model_id, revision=revision, cookies=cookies)
  File "/usr/local/lib/python3.7/site-packages/modelscope/hub/api.py", line 507, in get_valid_revision
    (model_id, revision, vl))
modelscope.hub.errors.NotExistError: The model: damo/speech_paraformer-large-vad-punc-spk_asr_nat-zh-cn has no revision: v1.2.1 valid are: [v0.0.2,v0.0.1]!

###错误信息2：
E20231211 14:31:52.425563   975 funasr-wss-server.cpp:266] /workspace/models/damo/speech_paraformer-large-vad-punc-spk_asr_nat-zh-cn/model_quant.onnx do not exists

这个需要额外的配置吗

**Comment by NuyoahCx330** [comment]
有计划去支持这个模型吗，或者modelscope.cn中更多的模型

**Comment by lyblsgo** [comment]
There are no plans to support this model.
