### ISSUE TITLE
funasr_wss_client 长音频转写连接提前被关闭

### ISSUE THREAD

**Issue by yijinsheng** [alibaba-damo-academy/FunASR#1180]
系统环境：mac
操作步骤：
1.  参考 [docker 部署文档](https://github.com/alibaba-damo-academy/FunASR/blob/main/runtime/docs/SDK_advanced_guide_online_zh.md )部署了 2pass模型
2. 使用 [funasr_wss_client.py](https://github.com/alibaba-damo-academy/FunASR/blob/main/runtime/python/websocket/funasr_wss_client.py) 访问 server
`python3 funasr_wss_client.py --host "127.0.0.1" --port 10096 --mode offline --ssl 0 --audio_in  /Users/yijinsheng/Downloads/足球中国VS印度.wav --output_dir ./result_yindu`
问题：
130分钟的音频，转写结果只有30min不到，websocket连接被提前关闭
服务端日志：
![image](https://github.com/alibaba-damo-academy/FunASR/assets/4934944/cd39e51b-43d4-406c-a8c9-e7b87784e6e3)
客户端日志：
![image](https://github.com/alibaba-damo-academy/FunASR/assets/4934944/4def717a-7534-4fa7-ae8e-d5981e4e239c)
转写结果： 
![image](https://github.com/alibaba-damo-academy/FunASR/assets/4934944/e11a5c8c-41d3-4caa-9e14-607c9ca74682)

**Comment by lyblsgo** [comment]
Thanks for the feedback and the PR; the issue has been resolved by https://github.com/alibaba-damo-academy/FunASR/commit/3c2d793370d11c32fede02148478899be1a5a501
