### ISSUE TITLE
server got "core dumped" if client disconnect to network and then connect again

### ISSUE THREAD

**Issue by wbz5087** [alibaba-damo-academy/FunASR#1185]
Our server is running on Ubuntu with docker (funasr:funasr-runtime-sdk-online-cpu-0.1.5) provided using command:
`nohup bash run_server_2pass.sh \
  --model-dir damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404-onnx \
  --online-model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx \
  --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx \
  --punc-dir damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727-onnx \
  --itn-dir thuduj12/fst_itn_zh \
  --decoder-thread-num 32 \
  --io-thread-num  8 \
  --port 10095 \
  --certfile 0 \
  --hotword /workspace/models/hotwords.txt > log.out 2>&1 &`

Our client is c# demo from FunASR.
The first connect is correct.
![image](https://github.com/alibaba-damo-academy/FunASR/assets/12483092/19733cc6-ad12-4928-b828-435df90922ab)

Then if we disconnect the Internet and connect again. Some error occured. 
Shown as:
![image](https://github.com/alibaba-damo-academy/FunASR/assets/12483092/00d8c275-cf8f-4c50-8c0e-745a19d4a69f)
And the Server:
![image](https://github.com/alibaba-damo-academy/FunASR/assets/12483092/bec9be3f-a199-438c-bef9-d8727a0cdc57)

Now, if I restart the server with "nohup ...", the error still exists:
![image](https://github.com/alibaba-damo-academy/FunASR/assets/12483092/20549ccb-ae97-4130-acb6-4ad5be1fd7b9)

**Comment by wbz5087** [comment]
I tried python and html demo just now. When I disconnect the Internet for like 30 seconds, the client crushed (python). Html has no response. I think these demos have no reconnect mechanism, so the server is safe. 
But in c# demo, there exists reconnect mechanism, so it will cause server to be down.

**Comment by lyblsgo** [comment]
The client in C# is contributed by the community and might not be sending data according to the communication protocol, which could lead to server crashes. Similar issues have been fixed before and will be released in the next version.

**Comment by lyblsgo** [comment]
try funasr:funasr-runtime-sdk-online-cpu-0.1.6

**Comment by wbz5087** [comment]
I will have a try! Many thanks!
