### ISSUE TITLE
音频切的比较碎，有没有办法一句一句的生成？

### ISSUE THREAD

**Issue by lucasjinreal** [alibaba-damo-academy/FunASR#1187]
<img width="331" alt="image" src="https://github.com/alibaba-damo-academy/FunASR/assets/21303438/2f0c3dfa-6590-486b-a68b-03207c68512f">

转来的峰哥音频，很多额，嗯的连词实际上是一整句话，被切成了好几个碎段。

有啥办法可以连在一起啊。

**Comment by R1ckShi** [comment]
可以考虑调整vad模型的max silence参数
