### ISSUE TITLE
标点预测中，上一句话的标点会出现在下一句话的开头问题是否可以优化？

### ISSUE THREAD

**Issue by Dzhlong** [alibaba-damo-academy/FunASR#1191]
1.请列出你的环境？
   linux环境，docker镜像版本为registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-online-cpu-0.1.5

2. 贴出你遵循的文档链接？
   https://alibaba-damo-academy.github.io/FunASR/en/funasr/quick_start_zh.html
3. 执行到哪一个步骤？
  服务已经启动并运行。
4. 错误信息是什么？
  标点预测中，上一句话的标点会出现在下一句话的开头，详情如图所示
 
![e30639802da4268be523ad63f558818](https://github.com/alibaba-damo-academy/FunASR/assets/43267184/9df4da29-7aa2-41bd-99d2-5e433fd25784)
5. 你 Google 这个错误信息收集到的结论是什么？
   群里大佬给出的原因是到了下一句才会知道上一句应该是什么标点，但是我看代码里面进行标点预测的时候输入是当前这一句的文本，并没有上一句话的文本，所以不太明白这个标点预测的原理。
  如果要结合上下文信息进行标点预测，那开头和结尾的标点如何进行预测
  
![image](https://github.com/alibaba-damo-academy/FunASR/assets/43267184/455a9610-977c-49cc-affb-6f691a24d461)

6. 请教该往哪个方向排查？
   有没有什么参数可以设置，强制标点预测只针对当前句子进行预测。

**Comment by lyblsgo** [comment]
punctuation prediction requires contextual information and needs to look to the right.
