### ISSUE TITLE
通过离线转写docker镜像启动服务端，指定参数"--model-thread-num 2"时报错。

### ISSUE THREAD

**Issue by 184653090** [alibaba-damo-academy/FunASR#1194]
1.环境：离线文件转写docker镜像registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-cpu-0.3.0
2.遵循的文档：服务端用法详解 https://github.com/alibaba-damo-academy/FunASR/blob/main/runtime/docs/SDK_advanced_guide_offline_zh.md#%E5%A6%82%E4%BD%95%E5%AE%9A%E5%88%B6%E6%9C%8D%E5%8A%A1%E9%83%A8%E7%BD%B2
3.执行的步骤：启动FunASR服务
4：指定“--model-thread-num 2”时，日志中报错“invalid option --model-thread-num”
<img width="332" alt="2a9bbffe4cbd7938802922117fe12ff" src="https://github.com/alibaba-damo-academy/FunASR/assets/86349126/91f4f83a-7fc0-40db-8695-662113364f3b">

**Comment by lyblsgo** [comment]
funasr-runtime-sdk-cpu-0.3.0，setting of the model-thread-num parameter is not supported, but it will be supported in the next version.

**Comment by 184653090** [comment]
感谢回答，还有一个关于并发数的问题，请问怎么从图中这几个参数计算服务所支持的最大并发数？
<img width="160" alt="455c58b7f5e964727f97041d2588b1a" src="https://github.com/alibaba-damo-academy/FunASR/assets/86349126/eaccf202-f66a-4139-a69d-0c512efe8d92">

**Comment by lyblsgo** [comment]
https://github.com/alibaba-damo-academy/FunASR/blob/main/runtime/docs/SDK_advanced_guide_offline_zh.md#%E6%9C%8D%E5%8A%A1%E7%AB%AF%E7%94%A8%E6%B3%95%E8%AF%A6%E8%A7%A3
