### ISSUE TITLE
funasr在线服务

### ISSUE THREAD

**Issue by wwfcnu** [alibaba-damo-academy/FunASR#1196]
funasr在线服务，
```
 python funasr_wss_client.py \
        --host "127.0.0.1" \
        --port 10096 \
        --audio_in wav.scp \
        --output_dir "./result_online\
        --mode 2pass \
        --thread_num 10 
```
输出结果如下
```
TEST_MEETING_T0000008258_S00000	对外成
TEST_MEETING_T0000008258_S00000	样什么样的
TEST_MEETING_T0000008258_S00000	规划划
TEST_MEETING_T0000008258_S00000	得有一个什么样什么样的规划
TEST_MEETING_T0000008258_S00000	大家
TEST_MEETING_T0000008258_S00000	都各自
TEST_MEETING_T0000008258_S00000	详细来
TEST_MEETING_T0000008258_S00000	谈一下
TEST_MEETING_T0000008258_S00000	，大家都各自详细的谈一下
TEST_MEETING_T0000008258_S00000	还
TEST_MEETING_T0000008258_S00000	有一些学
TEST_MEETING_T0000008258_S00000	生的状
TEST_MEETING_T0000008258_S00000	况今天还
TEST_MEETING_T0000008258_S00000	有两个
TEST_MEETING_T0000008258_S00000	家长代表
TEST_MEETING_T0000008258_S00000	来过来参
TEST_MEETING_T0000008258_S00000	加咱们这个
TEST_MEETING_T0000008258_S00000	会
TEST_MEETING_T0000008258_S00000	议给咱们
TEST_MEETING_T0000008258_S00000	提供一
TEST_MEETING_T0000008258_S00000	些好
TEST_MEETING_T0000008258_S00000	的意
TEST_MEETING_T0000008258_S00000	。还有一些学生的状况。今天还有两个家长代表来过来参加咱们这个会议，给咱们提出一些好的意见。
```
那这条语音的最终的识别结果是最后一条吗

**Comment by wwfcnu** [comment]
使用镜像funasr-runtime-sdk-online-cpu-0.1.5

**Comment by wwfcnu** [comment]
@ lyblsgo

**Comment by lyblsgo** [comment]
`2pass-online` for real-time recognition results and `2pass-offline` for 2-pass corrected recognition results
https://github.com/alibaba-damo-academy/FunASR/blob/main/runtime/docs/websocket_protocol_zh.md#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%BE%80%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%8F%91%E6%95%B0%E6%8D%AE-1

**Comment by wwfcnu** [comment]
> `2pass-online` for real-time recognition results and `2pass-offline` for 2-pass corrected recognition results https://github.com/alibaba-damo-academy/FunASR/blob/main/runtime/docs/websocket_protocol_zh.md#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%BE%80%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%8F%91%E6%95%B0%E6%8D%AE-1

我这里mode写错了吗,应该是2pass-offline？

**Comment by wwfcnu** [comment]
> `2pass-online` for real-time recognition results and `2pass-offline` for 2-pass corrected recognition results https://github.com/alibaba-damo-academy/FunASR/blob/main/runtime/docs/websocket_protocol_zh.md#%E4%BB%8E%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%BE%80%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%8F%91%E6%95%B0%E6%8D%AE-1

<img width="524" alt="image" src="https://github.com/alibaba-damo-academy/FunASR/assets/109075309/9fa17a41-621b-4c1a-9ca8-a2d7688ffabb">

**Comment by lyblsgo** [comment]
If the issue persists, please reopen the issue and provide detailed steps to reproduce, as well as server and client logs.
