### ISSUE TITLE
中文cpu离线部署版本运行一段时间后服务挂掉

### ISSUE THREAD

**Issue by yq-xfl** [alibaba-damo-academy/FunASR#1200]
环境：ubuntu  4核8G
镜像：funasr:funasr-runtime-sdk-cpu-0.3.0

根据文档，使用docker部署。
已经成功部署，并且可以调用成功。

客户端调用命令：
python funasr_wss_client.py --host "127.0.0.1" --port 10095 --mode offline --audio_in t3.scp

scp文件里是24个mp4文件列表，长度为5分钟，运行到第20个时服务端出现：

![image](https://github.com/alibaba-damo-academy/FunASR/assets/28552878/21398153-4177-4ff4-b06e-4af3875c0d8e)

服务端被killed，是因为内存不够了吗，还是已运行的内存没有充分释放。

我应该如何解决此问题。
如果我想同时并行4个10分钟以内的视频，建议什么配置呢。

**Comment by LauraGPT** [comment]
We have no idea about you problem, would you please describe it with more details?

**Comment by yq-xfl** [comment]
> We have no idea about you problem, would you please describe it with more details?

简单来说就是服务端运行一段时间后挂了（出现killed）。

我用这个客户端进行测试：
python funasr_wss_client.py --host "127.0.0.1" --port 10095 --mode offline --audio_in t3.scp
t3.scp里按格式放了24个一样的mp4文件，长度5分钟

运行到第20个的时候服务端挂了

用的这个模型：damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx

是因为机器配置不行、视频长度太长 或什么原因呢

启动命令：
bash run_server.sh \
  --download-model-dir /workspace/models \
  --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx \
  --model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx  \
  --punc-dir damo/punc_ct-transformer_cn-en-common-vocab471067-large-onnx \
  --lm-dir damo/speech_ngram_lm_zh-cn-ai-wesp-fst \
  --itn-dir thuduj12/fst_itn_zh \
  --hotword /workspace/models/hotwords.txt

**Comment by lyblsgo** [comment]
try funasr-runtime-sdk-cpu-0.4.0，Please confirm if there has been a memory overflow or if the memory has maxed out.

**Comment by juzstu** [comment]
> try funasr-runtime-sdk-cpu-0.4.0，Please confirm if there has been a memory overflow or if the memory has maxed out.

funasr-runtime-sdk-cpu-0.4.0 相比于之前版本内存很快打满是怎么回事？
