### ISSUE TITLE
请教热词的问题

### ISSUE THREAD

**Issue by yourengod** [alibaba-damo-academy/FunASR#1201]
xxx 20
后边这个权重的范围是多大？
有没有热词数量上的限制？

**Comment by LauraGPT** [comment]
1~100, but 20 is recommended

**Comment by yourengod** [comment]
> 1~100, but 20 is recommended

好的，多谢。

**Comment by nianjiuhuiyi** [comment]
> 1~100, but 20 is recommended

你好，请问下，这个权重在代码上怎么体现啊？看onnx的示例：https://github.com/modelscope/FunASR/blob/main/runtime/python/onnxruntime/demo_seaco_paraformer.py
里面只有给热词，没有给权重啊，官网演示网页上有权重，该怎么给啊？
