### ISSUE TITLE
FsmnVadInferBuffer 当传入sz_buf==nullptr &&n_len==0时，结果不能正常析构导致异常

### ISSUE THREAD

**Issue by coocoin** [alibaba-damo-academy/FunASR#1206]
funasr::FUNASR_VAD_RESULT* p_result = new funasr::FUNASR_VAD_RESULT; // 这里没有初始化segments字段，析构时出现异常
		p_result->snippet_time = audio.GetTimeLen();
		if(p_result->snippet_time == 0){
            return p_result;
        }

**Comment by lyblsgo** [comment]
This bug has been fixed; please update the code.
