### ISSUE TITLE
【pipeline】如何加载本地模型

### ISSUE THREAD

**Issue by hexianbin1994** [alibaba-damo-academy/FunASR#1208]
环境：
系统--windows
python3.8
modelscope==1.10.0

模型下载到本地后，设置哪项参数可以加载本地模型，而不是从网络下载。

```sh
pipeline(
        task=Tasks.auto_speech_recognition,
        model='damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online',
        model_revision='v1.0.6',
        mode="paraformer_streaming"
    )

**Comment by LauraGPT** [comment]
Ref to [docs](https://alibaba-damo-academy.github.io/FunASR/en/modelscope_pipeline/quick_start.html#how-to-infer-from-local-model-path)

**Comment by hexianbin1994** [comment]
好的，可以了，谢谢

**Comment by hexianbin1994** [comment]
刚刚发现换了ubuntu系统上，又需要重新下载了，是不是有什么默认配置项需要配置的

```python
    inference_pipline = pipeline(
        task=Tasks.punctuation,
        model="workspace/funASR/modelscope/damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch'",
        model_revision="v1.1.7")
```

日志：
![image](https://github.com/alibaba-damo-academy/FunASR/assets/55222575/809899f6-937b-4ce9-a7eb-0471446af3ed)
