### ISSUE TITLE
How to ensure that a service continues to run after reporting an error？

### ISSUE THREAD

**Issue by 0902081008** [alibaba-damo-academy/FunASR#1209]
I can start the service normally using the official Docker image, and I can transcribe it normally, but as soon as I send the wrong ws.send to the server, the service just crashes and I have to run the command again to start it, Is there any better way to solve this problem?

**Comment by LauraGPT** [comment]
> I send the wrong ws.send to the server

Would you please detail the 'I send the wrong ws.send to the server' ?

**Comment by 0902081008** [comment]
I was working on another project ,  sent a json to this websocket service accidentally. E.g
```json
{
  "aaa": "bbb",
  "ccc": "ddd"
}
```
service crashed :(

**Comment by lyblsgo** [comment]
The issue has been fixed and will be released in the next version.
