### ISSUE TITLE
是不是没有同时支持热词和时间戳的长音频模型？

### ISSUE THREAD

**Issue by JVfisher** [alibaba-damo-academy/FunASR#1210]
https://github.com/alibaba-damo-academy/FunASR/tree/dev_gzf_funasr2/examples/industrial_data_pretraining 里面的例子中没有同时支持热词和时间戳的长音频模型

**Comment by R1ckShi** [comment]
seaco-paraformer现在同时支持时间戳和热词功能，在funasr1.0分支中可以提前体验：https://github.com/alibaba-damo-academy/FunASR/blob/funasr1.0/examples/industrial_data_pretraining/seaco_paraformer/demo.py

**Comment by jupinter** [comment]
我希望对一条1个小时的音频，实现带热词的识别，如何实现比较合适，seaco-paraformer看起来采用的是离线的识别方式。感谢。

**Comment by buaibieshanghai** [comment]
> seaco-paraformer现在同时支持时间戳和热词功能，在funasr1.0分支中可以提前体验：https://github.com/alibaba-damo-academy/FunASR/blob/funasr1.0/examples/industrial_data_pretraining/seaco_paraformer/demo.py

你好，链接失效了，我使用命令：bash run_server.sh --download-model-dir /workspace/models --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-pytorch  --model-dir damo/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch ，时间戳和热词仍然无法同时支持
