### ISSUE TITLE
C++下测试的小问题！！！

### ISSUE THREAD

**Issue by shijianyang520** [alibaba-damo-academy/FunASR#1211]
(base) sjy@sjy-System-Product-Name:~/FunASR/runtime/onnxruntime/build/bin$ ./funasr-onnx-offline --model-dir /home/sjy/asr/model  --wav-path  /home/sjy/asr/testAudio.wav  --quantize true  --hotword /home/sjy/asr/hotwords.txt 
I20231228 14:04:19.295624 14499 funasr-onnx-offline.cpp:37] model-dir : /home/sjy/asr/model
I20231228 14:04:19.295712 14499 funasr-onnx-offline.cpp:37] quantize : true
I20231228 14:04:19.295722 14499 funasr-onnx-offline.cpp:37] wav-path : /home/sjy/asr/testAudio.wav
I20231228 14:04:20.500519 14499 paraformer.cpp:42] Successfully load model from /home/sjy/asr/model/model_quant.onnx
I20231228 14:04:20.532739 14499 funasr-onnx-offline.cpp:116] hotword path: /home/sjy/asr/hotwords.txt
I20231228 14:04:20.532768 14499 util.cpp:1032] hotwords: 
I20231228 14:04:20.532784 14499 funasr-onnx-offline.cpp:122] Model initialization takes 1.23706 s
2023-12-28 14:04:20.747310850 [E:onnxruntime:, sequential_executor.cc:494 ExecuteKernel] Non-zero status code returned while running MatMul node. Name:'/decoder/bias_decoder/src_attn/linear_k_v/MatMul' Status Message: /onnxruntime_src/include/onnxruntime/core/framework/op_kernel_context.h:42 const T* onnxruntime::OpKernelContext::Input(int) const [with T = onnxruntime::Tensor] Missing Input: bias_embed

E20231228 14:04:20.747534 14499 paraformer.cpp:577] Non-zero status code returned while running MatMul node. Name:'/decoder/bias_decoder/src_attn/linear_k_v/MatMul' Status Message: /onnxruntime_src/include/onnxruntime/core/framework/op_kernel_context.h:42 const T* onnxruntime::OpKernelContext::Input(int) const [with T = onnxruntime::Tensor] Missing Input: bias_embed
I20231228 14:04:20.747574 14499 funasr-onnx-offline.cpp:171] wav_default_id : 
I20231228 14:04:20.747577 14499 funasr-onnx-offline.cpp:189] Audio length: 10.2 s
I20231228 14:04:20.747584 14499 funasr-onnx-offline.cpp:190] Model inference takes: 0.214767 s
I20231228 14:04:20.747587 14499 funasr-onnx-offline.cpp:191] Model inference RTF: 0.0210556
![6566C1166EF3446E1792F303F9B126CF](https://github.com/alibaba-damo-academy/FunASR/assets/41714876/a9862ce2-7c08-4d90-b97f-54c4f69fa749)
wav_default_id :  ，用 ./funasr-onnx-offline --model-dir /home/sjy/asr/model  --wav-path  /home/sjy/asr/testAudio.wav  --quantize true  --hotword /home/sjy/asr/hotwords.txt 这个命令，却没有出现文本，这是什么原因？

**Comment by shijianyang520** [comment]
模型量化的问题

**Comment by lvyilele** [comment]
同样得问题，怎么解决得
