### ISSUE TITLE
funasr1.0模型支持断句吗

### ISSUE THREAD

**Issue by yanchujian** [alibaba-damo-academy/FunASR#1221]
我在使用funasr1.0 这个模型，我看结果是没有进行断句的，有支持断句的模型吗

**Comment by yanchujian** [comment]
已解决，通过额外添加端点检测模型和标点检测模型。

**Comment by lonngxiang** [comment]
> 已解决，通过额外添加端点检测模型和标点检测模型。

只能分开部署吗，没有写一起的？
