### ISSUE TITLE
FunASR社区软件包windows版本

### ISSUE THREAD

**Issue by 13623667123** [alibaba-damo-academy/FunASR#1223]
1，win  10 系统
2，https://modelscope.cn/models/damo/funasr-runtime-win-cpu-x64/summary
3，Git Bash在项目目录启动服务端：./funasr-wss-server.exe  --vad-dir D:/funasr-runtime-resources/models/speech_fsmn_vad_zh-cn-16k-common-onnx --model-dir D:/funasr-runtime-resources/models/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-onnx --lm-dir D:/funasr-runtime-resources/models/speech_ngram_lm_zh-cn-ai-wesp-fst  --punc-dir D:/funasr-runtime-resources/models/punc_ct-transformer_cn-en-common-vocab471067-large-onnx --itn-dir D:/funasr-runtime-resources/models/fst_itn_zh --certfile ssl_key/server.crt --keyfile ssl_key/server.key
4，lifei@LAPTOP-ESHA85OH MINGW64 /d/funasr-runtime-resources/models
$ ./funasr-wss-server.exe  --vad-dir D:/funasr-runtime-resources/models/speech_fsmn_vad_zh-cn-16k-common-onnx --model-dir D:/funasr-runtime-resources/models/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-onnx --lm-dir D:/funasr-runtime-resources/models/speech_ngram_lm_zh-cn-ai-wesp-fst  --punc-dir D:/funasr-runtime-resources/models/punc_ct-transformer_cn-en-common-vocab471067-large-onnx --itn-dir D:/funasr-runtime-resources/models/fst_itn_zh --certfile ssl_key/server.crt --keyfile ssl_key/server.key
bash: ./funasr-wss-server.exe: No such file or directory

**Comment by lyblsgo** [comment]
"Git Bash在项目目录启动服务端"
Confirm that you are in the project directory, not the model directory.
