### ISSUE TITLE
funasr-runtime-sdk-online-cpu-0.1.6 docker中启动服务失败

### ISSUE THREAD

**Issue by liaoweiguo** [alibaba-damo-academy/FunASR#1225]
部署开发文档中在线服务的启动命令貌似有问题
https://bgithub.xyz/alibaba-damo-academy/FunASR/blob/main/runtime/docs/SDK_advanced_guide_online_zh.md

cd FunASR/runtime
nohup bash run_server_2pass.sh \
  --download-model-dir /workspace/models \
  --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx \
  --model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx  \
  --online-model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx  \
  --punc-dir damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727-onnx \
  --lm-dir damo/speech_ngram_lm_zh-cn-ai-wesp-fst \
  --itn-dir thuduj12/fst_itn_zh \
  --hotword /workspace/models/hotwords.txt > log.out 2>&1 &

错误提示：
bash run_server_2pass.sh 不支持--lm-dir

**Comment by lyblsgo** [comment]
The issue has been resolved, Update the Docker image using the command: 
sudo docker pull  registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-online-cpu-0.1.6
