### ISSUE TITLE
funasr1.0 版本不支持pcm格式的音频吗

### ISSUE THREAD

**Issue by yanchujian** [alibaba-damo-academy/FunASR#1228]
尝试修改代码，但还是有错误，这句代码有问题：
 waveform = pad_sequence(audio_sample_list, batch_first=True).to(device=kwargs["device"]) # data: [batch, N]

会报错:
TypeError: expected Tensor as element 0 in argument 0, but got numpy.ndarray

应该是audio_sample_list这个数据不对，我尝试修改代码，但最终还是解决，有大佬知道怎么解决吗。

**Comment by wwfcnu** [comment]
load_util.py那里ffmpeg转pcm格式存在问题
