### ISSUE TITLE
Paraformer语音识别-中文-通用-16k-离线-large-长音频版， 调用报错

### ISSUE THREAD

**Issue by cuiyingbao** [alibaba-damo-academy/FunASR#1236]
请问专家，我调用语音识别长音频 识别功能时，一直报这个错误，是什么问题？我的网络环境是可以连互联网的
![1b549f1267d652ba7242534ee76d583b](https://github.com/alibaba-damo-academy/FunASR/assets/19500590/d5adc2bd-1838-490e-af97-1b9fdaf175ea)

**具体代码为：**
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model='damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch',
    model_revision="v1.2.4")

rec_result = inference_pipeline(audio_in='1.wav')
print(rec_result)

**参考的文档连接为：**
https://www.modelscope.cn/models/damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/summary

**Comment by White-Friday** [comment]
我也一样，模型都已经下载到本地了，路径指定也正常

**Comment by cuiyingbao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by LauraGPT** [comment]
Ref to https://github.com/alibaba-damo-academy/FunASR/issues/1238#issuecomment-1888539294

**Comment by cuiyingbao** [comment]
> 我也一样，模型都已经下载到本地了，路径指定也正常

请问解决了没，怎么解决的呢

**Comment by White-Friday** [comment]
@cuiyingbao 在configuration.json里面有模型路径，需要指定，默认查询不到会联网下载

**Comment by ChuangLee** [comment]
> @cuiyingbao 在configuration.json里面有模型路径，需要指定，默认查询不到会联网下载

貌似查询到了也必须联网，联网然后校验本地模型文件，才能启动，最新的docker镜像是这样的。 离线环境无法启动

**Comment by cuiyingbao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by EasilyGoDie** [comment]
> > @cuiyingbao 在configuration.json里面有模型路径，需要指定，默认查询不到会联网下载
> 
> 貌似查询到了也必须联网，联网然后校验本地模型文件，才能启动，最新的docker镜像是这样的。 离线环境无法启动

你看看代码就知道了，不是为了校验，而是下载参数

**Comment by cuiyingbao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
