### ISSUE TITLE
出现：KeyError: 'funasr-pipeline is not in the pipelines registry group auto-speech-recognition. Please make sure the correct version of ModelScope library is used.'

### ISSUE THREAD

**Issue by White-Friday** [alibaba-damo-academy/FunASR#1238]
modelscope==1.11.0
funasr==0.8.0

**Comment by White-Friday** [comment]
使用旧版的模型，会出现下面的问题：

KeyError: "AutomaticSpeechRecognitionPipeline: 'model_config'"

请问有解决方案吗？谢谢

**Comment by luohao123** [comment]
Same 

KeyError: 'funasr-pipeline is not in the pipelines registry group voice-activity-detection. Please make sure the correct version of ModelScope library is used.'

**Comment by LauraGPT** [comment]
Please update funasr-1.0.0

```shell
git clone -b funasr1.0 --single-branch https://github.com/alibaba-damo-academy/FunASR.git && cd FunASR
pip install -e ./
```

Usage is the same with pipeline：[examples](https://github.com/alibaba-damo-academy/FunASR/tree/funasr1.0/examples/industrial_data_pretraining)

**Comment by LauraGPT** [comment]
> Please update funasr-1.0.0
> 
> ```shell
> git clone -b funasr1.0 --single-branch https://github.com/alibaba-damo-academy/FunASR.git && cd FunASR
> pip install -e ./
> ```
> 
> Usage is the same with pipeline：[examples](https://github.com/alibaba-damo-academy/FunASR/tree/funasr1.0/examples/industrial_data_pretraining)

For the funasr-1.0.0, we recommend you to use funasr directly, as [examples](https://github.com/alibaba-damo-academy/FunASR/tree/funasr1.0/examples/industrial_data_pretraining)
`e.g.`
```python
from funasr import AutoModel

model = AutoModel(model="damo/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch",
                  model_revision="v2.0.0",
                  vad_model="damo/speech_fsmn_vad_zh-cn-16k-common-pytorch",
                  vad_model_revision="v2.0.1",
                  punc_model="damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch",
                  punc_model_revision="v2.0.0",
                  #spk_model="damo/speech_campplus_sv_zh-cn_16k-common",
                  #spk_model_revision="v2.0.0"
                  )

res = model(input="https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/asr_example_zh.wav",
            hotword='达摩院 磨搭')
print(res)
```

But if you still want to use the modelscope pipeline, you could install modelscope from source code.
```shell
git clone https://github.com/modelscope/modelscope.git && cd modelscope
pip install -e ./
```

**Comment by LCY-789456123** [comment]
> > Please update funasr-1.0.0
> > ```shell
> > git clone -b funasr1.0 --single-branch https://github.com/alibaba-damo-academy/FunASR.git && cd FunASR
> > pip install -e ./
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Usage is the same with pipeline：[examples](https://github.com/alibaba-damo-academy/FunASR/tree/funasr1.0/examples/industrial_data_pretraining)
> 
> For the funasr-1.0.0, we recommend you to use funasr directly, as [examples](https://github.com/alibaba-damo-academy/FunASR/tree/funasr1.0/examples/industrial_data_pretraining) `e.g.`
> 
> ```python
> from funasr import AutoModel
> 
> model = AutoModel(model="damo/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch",
>                   model_revision="v2.0.0",
>                   vad_model="damo/speech_fsmn_vad_zh-cn-16k-common-pytorch",
>                   vad_model_revision="v2.0.1",
>                   punc_model="damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch",
>                   punc_model_revision="v2.0.0",
>                   #spk_model="damo/speech_campplus_sv_zh-cn_16k-common",
>                   #spk_model_revision="v2.0.0"
>                   )
> 
> res = model(input="https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/asr_example_zh.wav",
>             hotword='达摩院 磨搭')
> print(res)
> ```
> 
> But if you still want to use the modelscope pipeline, you could install modelscope from source code.
> 
> ```shell
> git clone https://github.com/modelscope/modelscope.git && cd modelscope
> pip install -e ./
> ```
Thanks a lot. But after taking the above operations, a new error occurred.
Traceback (most recent call last):
  File "/root/FunASR/runtime/python/websocket/funasr_wss_server.py", line 91, in <module>
    inference_pipeline_punc = pipeline(
  File "/root/FunASR/modelscope/package/modelscope/pipelines/builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/root/FunASR/modelscope/package/modelscope/pipelines/builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "/root/FunASR/modelscope/package/modelscope/utils/registry.py", line 198, in build_from_cfg
    raise KeyError(
KeyError: 'punc-inference is not in the pipelines registry group punctuation. Please make sure the correct version of ModelScope library is used.'

**Comment by luohao123** [comment]
Same, I would prefer using Modelscope, it's simpler, easy to understand, and maintained as well. it's from Alibaba as well, why not use it?

**Comment by hatrd** [comment]
> Please update funasr-1.0.0
> 
> ```shell
> git clone -b funasr1.0 --single-branch https://github.com/alibaba-damo-academy/FunASR.git && cd FunASR
> pip install -e ./
> ```
> 
> Usage is the same with pipeline：[examples](https://github.com/alibaba-damo-academy/FunASR/tree/funasr1.0/examples/industrial_data_pretraining)
git clone output.
```
Cloning into 'FunASR'...
warning: Could not find remote branch funasr1.0 to clone.
fatal: Remote branch funasr1.0 not found in upstream origin
```
Branch deleted? I cloned the latest main branch, same question.
KeyError: 'funasr-pipeline is not in the pipelines registry group auto-speech-recognition. Please make sure the correct version of ModelScope library is used.'

```

**Comment by zioli24** [comment]
> 使用旧版的模型，会出现下面的问题：
> 
> KeyError: "AutomaticSpeechRecognitionPipeline: 'model_config'"
> 
> 请问有解决方案吗？谢谢

funasr==0.8.7
modelscope==1.10.0

> 使用旧版的模型，会出现下面的问题：
> 
> KeyError: "AutomaticSpeechRecognitionPipeline: 'model_config'"
> 
> 请问有解决方案吗？谢谢

pip install funasr==0.8.7
pip install modelscope==1.10.0

**Comment by zioli24** [comment]
> 使用旧版的模型，会出现下面的问题：
> 
> KeyError: "AutomaticSpeechRecognitionPipeline: 'model_config'"
> 
> 请问有解决方案吗？谢谢

pip install funasr==0.8.7
pip install modelscope==1.10.0

**Comment by TzyTman** [comment]
subfix create modelscope --source_dir origin --language ZH
Checkout command with args: Namespace(command='create', solution='modelscope', source_dir='origin', target_dir='dataset', cache_dir='cache', sample_rate=44100, language='ZH', output='demo.list', max_seconds=15, absolute_path='False', func=<function handle_create at 0x7fb791a62280>)
find ffmpeg installed, use ffmpeg
files count: 1
max_threads = 72
file 1 start convert
2024-01-31 09:35:07,491 - modelscope - INFO - PyTorch version 2.2.0 Found.
2024-01-31 09:35:07,491 - modelscope - INFO - Loading ast index from /home/mk/.cache/modelscope/ast_indexer
2024-01-31 09:35:07,524 - modelscope - INFO - Loading done! Current index file version is 1.11.0, with md5 99d48e759d62c60fdfd350f0ab386c10 and a total number of 953 components indexed
2024-01-31 09:35:09,635 - modelscope - INFO - Use user-specified model revision: v1.2.4
2024-01-31 09:35:10,014 - modelscope - INFO - initiate model from /home/mk/.cache/modelscope/hub/damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch
2024-01-31 09:35:10,014 - modelscope - INFO - initiate model from location /home/mk/.cache/modelscope/hub/damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch.
2024-01-31 09:35:10,014 - modelscope - INFO - initialize model from /home/mk/.cache/modelscope/hub/damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch
2024-01-31 09:35:10,016 - modelscope - WARNING - No preprocessor field found in cfg.
2024-01-31 09:35:10,016 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2024-01-31 09:35:10,016 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': '/home/mk/.cache/modelscope/hub/damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch'}. trying to build by task and model information.
2024-01-31 09:35:10,016 - modelscope - WARNING - No preprocessor key ('generic-asr', 'auto-speech-recognition') found in PREPROCESSOR_MAP, skip building preprocessor.
2024-01-31 09:35:14,377 - modelscope - WARNING - Model revision not specified, use revision: v2.0.0
2024-01-31 09:35:14,811 - modelscope - INFO - loading vad model from /home/mk/.cache/modelscope/hub/damo/speech_fsmn_vad_zh-cn-16k-common-pytorch ...
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/SubFix/lib/python3.9/site-packages/modelscope/utils/registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "/home/mk/anaconda3/envs/SubFix/lib/python3.9/site-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 122, in __init__
    self.cmd = self.get_cmd(kwargs, model)
  File "/home/mk/anaconda3/envs/SubFix/lib/python3.9/site-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 376, in get_cmd
    self.load_vad_model(cmd)
  File "/home/mk/anaconda3/envs/SubFix/lib/python3.9/site-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 421, in load_vad_model
    model_cfg['model']['model_config']['vad_model_name'])
KeyError: 'model_config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/SubFix/bin/subfix", line 33, in <module>
    sys.exit(load_entry_point('SubFix', 'console_scripts', 'subfix')())
  File "/home/mk/SubFix-main/subfix/cli.py", line 120, in cli
    args.func(args)
  File "/home/mk/SubFix-main/subfix/cli.py", line 40, in handle_create
    run_task(args)
  File "/home/mk/SubFix-main/subfix/solution/modelscope_multi_lang.py", line 73, in run_task
    create_list(args.source_dir, args.target_dir, args.cache_dir, args.sample_rate, args.language, args.output, args.max_seconds, args.absolute_path)
  File "/home/mk/SubFix-main/subfix/solution/modelscope_multi_lang.py", line 55, in create_list
    asr_model = Speech_Paraformer_Large_Vad_Punc_Asr_zh()
  File "/home/mk/SubFix-main/subfix/models/audio/asr/speech_paraformer_large_vad_punc_asr_zh.py", line 9, in __init__
    self._inference_pipeline = pipeline(
  File "/home/mk/anaconda3/envs/SubFix/lib/python3.9/site-packages/modelscope/pipelines/builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/home/mk/anaconda3/envs/SubFix/lib/python3.9/site-packages/modelscope/pipelines/builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "/home/mk/anaconda3/envs/SubFix/lib/python3.9/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "AutomaticSpeechRecognitionPipeline: 'model_config'"
(SubFix) mk@my088:~/SubFix-main$ list

Command 'list' not found, did you mean:

  command 'mist' from snap mist (master)
  command 'last' from deb util-linux (2.34-0.1ubuntu9.4)
  command 'gist' from deb yorick (2.2.04+dfsg1-10)
  command 'dist' from deb mmh (0.4-2)
  command 'dist' from deb nmh (1.7.1-6)
  command 'flist' from deb mmh (0.4-2)
  command 'flist' from deb nmh (1.7.1-6)
  command 'mlist' from deb mblaze (0.6-1)
  command 'hist' from deb loki (2.4.7.4-10)
  command 'lift' from deb lift (2.5.0-1)
  command 'klist' from deb heimdal-clients (7.7.0+dfsg-1ubuntu1.4)
  command 'klist' from deb krb5-user (1.17-6ubuntu4.3)

See 'snap info <snapname>' for additional versions.

(SubFix) mk@my088:~/SubFix-main$ pip list
Package                   Version              Editable project location
------------------------- -------------------- -------------------------
absl-py                   2.1.0
addict                    2.4.0
aiofiles                  23.2.1
aiohttp                   3.9.3
aiosignal                 1.3.1
alias-free-torch          0.0.6
aliyun-python-sdk-core    2.14.0
aliyun-python-sdk-kms     2.16.2
altair                    5.2.0
aniso8601                 9.0.1
annotated-types           0.6.0
antlr4-python3-runtime    4.9.3
anyio                     4.2.0
async-timeout             4.0.3
attrs                     23.2.0
audioread                 3.0.1
beartype                  0.17.0
bidict                    0.22.1
bitarray                  2.9.2
bitstring                 4.1.4
cachetools                5.3.2
certifi                   2023.11.17
cffi                      1.16.0
charset-normalizer        3.3.2
click                     8.1.7
coloredlogs               14.0
contourpy                 1.2.0
crcmod                    1.7
cryptography              42.0.2
cycler                    0.12.1
Cython                    0.29.37
datasets                  2.16.1
decorator                 5.1.1
dill                      0.3.7
Distance                  0.1.3
dnspython                 2.3.0
editdistance              0.5.2
einops                    0.7.0
espnet-tts-frontend       0.0.3
et-xmlfile                1.1.0
eventlet                  0.35.1
exceptiongroup            1.2.0
fastapi                   0.109.0
ffmpy                     0.3.1
filelock                  3.13.1
Flask                     2.2.5
Flask-Cors                4.0.0
Flask-RESTful             0.3.10
Flask-SocketIO            5.3.6
flask-talisman            1.1.0
fonttools                 4.47.2
frozenlist                1.4.1
fsspec                    2023.10.0
funasr                    1.0.0
funcodec                  0.2.0
future                    0.18.3
g2p                       1.1.20230822
g2p-en                    2.1.0
gast                      0.5.4
google-auth               2.27.0
google-auth-oauthlib      1.2.0
gradio                    3.50.2
gradio_client             0.6.1
greenlet                  3.0.3
grpcio                    1.60.0
h11                       0.14.0
h5py                      3.10.0
hdbscan                   0.8.33
httpcore                  1.0.2
httpx                     0.26.0
huggingface-hub           0.20.3
humanfriendly             10.0
hydra-core                1.3.2
HyperPyYAML               1.2.2
idna                      3.6
importlib-metadata        7.0.1
importlib-resources       6.1.1
inflect                   7.0.0
itsdangerous              2.1.2
jaconv                    0.3.4
jamo                      0.4.1
jedi                      0.19.1
jieba                     0.42.1
Jinja2                    3.1.3
jmespath                  0.10.0
joblib                    1.3.2
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
kaldiio                   2.18.0
kantts                    1.0.1
kiwisolver                1.4.5
kwsbp                     0.0.6
lazy_loader               0.3
librosa                   0.10.1
llvmlite                  0.41.1
local-attention           1.9.0
lxml                      5.1.0
Markdown                  3.5.2
MarkupSafe                2.1.4
matplotlib                3.8.2
MinDAEC                   0.0.2
mir-eval                  0.7
modelscope                1.11.0
more-itertools            10.2.0
mpmath                    1.3.0
msgpack                   1.0.7
multidict                 6.0.4
multiprocess              0.70.15
munkres                   1.1.4
networkx                  2.8.4
nltk                      3.8.1
numba                     0.58.1
numpy                     1.26.3
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu12          2.19.3
nvidia-nvjitlink-cu12     12.3.101
nvidia-nvtx-cu12          12.1.105
oauthlib                  3.2.2
omegaconf                 2.3.0
openai-whisper            20231117
openpyxl                  3.1.2
orjson                    3.9.12
oss2                      2.18.4
packaging                 23.2
pandas                    2.2.0
panphon                   0.20.0
parso                     0.8.3
pexpect                   4.9.0
phaseaug                  1.0.1
pickleshare               0.7.5
pillow                    10.2.0
pip                       23.3.1
platformdirs              4.2.0
pooch                     1.8.0
prompt-toolkit            3.0.43
protobuf                  4.23.4
ptflops                   0.7.2.2
ptyprocess                0.7.0
py-sound-connect          0.2.1
pyarrow                   15.0.0
pyarrow-hotfix            0.6
pyasn1                    0.5.1
pyasn1-modules            0.3.0
pycparser                 2.21
pycryptodome              3.20.0
pydantic                  2.6.0
pydantic_core             2.16.1
pydub                     0.25.1
Pygments                  2.17.2
pynndescent               0.5.11
pyparsing                 3.1.1
pypinyin                  0.44.0
pysptk                    0.1.18
python-dateutil           2.8.2
python-engineio           4.8.2
python-multipart          0.0.6
python-socketio           5.11.0
pytorch-wavelets          1.3.0
pytorch-wpe               0.0.1
pytz                      2023.4
PyWavelets                1.5.0
PyYAML                    6.0.1
referencing               0.33.0
regex                     2023.12.25
requests                  2.31.0
requests-oauthlib         1.3.1
rotary-embedding-torch    0.5.3
rpds-py                   0.17.1
rsa                       4.9
ruamel.yaml               0.18.5
ruamel.yaml.clib          0.2.8
safetensors               0.4.2
scikit-learn              1.4.0
scipy                     1.12.0
semantic-version          2.10.0
sentencepiece             0.1.99
setuptools                68.2.2
simple-websocket          1.0.0
simplejson                3.19.2
six                       1.16.0
sniffio                   1.3.0
sortedcontainers          2.4.0
soundfile                 0.12.1
sox                       1.4.1
soxr                      0.3.7
speechbrain               0.5.16
starlette                 0.35.1
SubFix                    0.1.1                /home/mk/SubFix-main
sympy                     1.12
tensorboard               2.15.1
tensorboard-data-server   0.7.2
tensorboardX              2.6.2.2
text-unidecode            1.3
thop                      0.1.1.post2209072238
threadpoolctl             3.2.0
tiktoken                  0.5.2
tokenizers                0.15.1
tomli                     2.0.1
toolz                     0.12.1
torch                     2.2.0
torch-complex             0.4.3
torchaudio                2.2.0
tqdm                      4.66.1
traitlets                 5.14.1
transformers              4.37.2
triton                    2.2.0
ttsfrd                    0.2.1
typeguard                 2.13.3
typing_extensions         4.9.0
tzdata                    2023.4
umap                      0.1.1
umap-learn                0.5.5
unicodecsv                0.14.1
Unidecode                 1.3.8
urllib3                   2.2.0
uvicorn                   0.27.0.post1
wcwidth                   0.2.13
websockets                11.0.3
Werkzeug                  2.2.3
wheel                     0.41.2
wsproto                   1.2.0
xxhash                    3.4.1
yapf                      0.40.2
yarl                      1.9.4
zipp                      3.17.0       funasr == 1.0.0   modelscope== 1.11.0  还是报错 到底是什么问题了？
