### ISSUE TITLE
KeyError: 'funasr-pipeline is not in the pipelines registry group voice-activity-detection. Please make sure the correct version of ModelScope library is used.'

### ISSUE THREAD

**Issue by luohao123** [alibaba-damo-academy/FunASR#1239]
KeyError: 'funasr-pipeline is not in the pipelines registry group voice-activity-detection. Please make sure the correct version of ModelScope library is used.'

**Comment by LauraGPT** [comment]
ref to https://github.com/alibaba-damo-academy/FunASR/issues/1238
