### ISSUE TITLE
为什么我识别出来的结果全是像乱码字？

### ISSUE THREAD

**Issue by dsyrock** [alibaba-damo-academy/FunASR#1248]
[{'key': 'rand_key_2yW4Acq9GFz6Y', 'text': '沨 念 麻 绉 源 举 源 窠 汛 瘿 璩 箕 厂 绔 溜 瘦 杠 雁 逄 胱 凸 席 觜 赣 lok at 岭 讥 壸 谌 褭', 'timestamp': [[90, 210], [210, 330], [330, 450], [450, 570], [570, 690], [690, 810], [810, 930], [930, 1070], [1070, 1190], [1190, 1310], [1310, 1430], [1430, 1550], [1550, 1670], [1670, 1790], [1790, 1910], [1910, 2030], [2030, 2150], [2270, 2390], [2390, 2530], [2530, 2650], [2650, 2770], [2770, 2890], [2890, 3010], [3010, 3130], [3130, 3250], [3250, 3370], [3370, 3490], [3490, 3610], [3610, 3730], [3850, 3970], [3970, 4140]]}]

用的是 paraformer-zh 模型，代码用的是首页的非实时语音识别例子

**Comment by R1ckShi** [comment]
可以重新拉取代码尝试一下，如果还有问题可以提供你的脚本和测试用例。

**Comment by dsyrock** [comment]
代码是刚从主页下载的，用 pip install -e . 命令安装
```
from funasr import AutoModel
model = AutoModel(model="paraformer-zh", model_revision="v2.0.2")
res = model(input="e:\\w1.wav",)
print(res)
```

**Comment by dsyrock** [comment]
还有一个地方是在 load_pretrained_model.py 里，有一行是
```
sps = init_param.split(":", 4)
```
这里我不是很理解，因为我在win上用，模型地址都是 C:\XXXX\YYYYY\，这样分割以后模型地址只剩下个“C”，运行都是报错的，说模型“C”找不到，然后我就在下面的
```
path, src_key = sps
```
改成了
```
path, src_key = sps
path = init_param
```
然后才能成功找到模型并运行，但不知道这个对结果变成乱码是否有影响

**Comment by R1ckShi** [comment]
感谢反馈，我们在win下测试一下。

**Comment by LauraGPT** [comment]
> 还有一个地方是在 load_pretrained_model.py 里，有一行是
> 
> ```
> sps = init_param.split(":", 4)
> ```
> 
> 这里我不是很理解，因为我在win上用，模型地址都是 C:\XXXX\YYYYY\，这样分割以后模型地址只剩下个“C”，运行都是报错的，说模型“C”找不到，然后我就在下面的
> 
> ```
> path, src_key = sps
> ```
> 
> 改成了
> 
> ```
> path, src_key = sps
> path = init_param
> ```
> 
> 然后才能成功找到模型并运行，但不知道这个对结果变成乱码是否有影响

This bug has been fixed. Please update funasr and try it again:

https://github.com/alibaba-damo-academy/FunASR/commit/bb97d3ed19ee3a219e67b9568d662df489aa2823#diff-c83cd0708f6350de531cc4d67b74babd96e1d177e913723c51eaac7966aef995

**Comment by dsyrock** [comment]
谢谢。我重新完整下载和安装了一次，运行后得到新的错误信息：
```
WARNING:root:enable bias encoder sampling and contextual training
Traceback (most recent call last):
  File "K:\funasr\Scripts\demo.py", line 7, in <module>
    res = model(input="k:\\w1.wav")
  File "k:\funasr\main\funasr\auto\auto_model.py", line 198, in __call__
    res = self.model(*args, kwargs)
  File "K:\funasr\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "K:\funasr\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: SeacoParaformer.forward() missing 3 required positional arguments: 'speech_lengths', 'text', and 'text_lengths'
```

**Comment by dsyrock** [comment]
> Sorry, we have changed the usage, today. Please ref to the new [docs](https://github.com/alibaba-damo-academy/FunASR?tab=readme-ov-file#speech-recognition-non-streaming) . The difference is `model.generate()`: before today:
> 
> ```python
> res = model(input=f"{model.model_path}/example/asr_example.wav", 
>                      batch_size=64, 
>                      hotword='魔搭')
> ```
> 
> today:
> 
> ```python
> res = model.generate(input=f"{model.model_path}/example/asr_example.wav", 
>                      batch_size=64, 
>                      hotword='魔搭')
> ```

可以运行了，谢谢，但是现在又回到一开始的问题，就是识别出来的结果仍然是类似乱码的文字
```
[{'key': 'rand_key_2yW4Acq9GFz6Y', 'text': 'l 臑 害 祈 渡 枕 茳 橐 鳄 ase 桃 喷 墓 洎 吩 葬 型 拦 ther 孖 蟀 气 吩 魔 糙 汝 戡 遁 圮 坼 吩 吩', 'timestamp': [[90, 210], [210, 330], [330, 450], [450, 570], [570, 690], [690, 810], [810, 930], [930, 1070], [1070, 1190], [1190, 1310], [1310, 1430], [1430, 1550], [1550, 1670], [1670, 1790], [1790, 1910], [1910, 2030], [2030, 2150], [2150, 2270], [2270, 2390], [2390, 2530], [2530, 2650], [2650, 2770], [2770, 2890], [2890, 3010], [3010, 3130], [3130, 3250], [3370, 3490], [3490, 3610], [3610, 3730], [3730, 3850], [3850, 3970], [3970, 4140]]}]
```

**Comment by LauraGPT** [comment]
Please upload your wav

**Comment by LauraGPT** [comment]
> 我也是识别结果乱码。有解决办法吗？ 我就用tutorial里指定的 wav ，也是乱码
> 
> model = AutoModel(model="paraformer-zh", model_revision="v2.0.2", vad_model="fsmn-vad", vad_model_revision="v2.0.2", punc_model="ct-punc-c", punc_model_revision="v2.0.2", spk_model="cam++", spk_model_revision="v2.0.2") res = model.generate(input=f"{model.model_path}/example/asr_example.wav", batch_size=64, hotword='魔搭')
> 
> [{'key': 'rand_key_2yW4Acq9GFz6Y', 'text': '径 before 共 while 鹌 蔺 拮 淀 珦 蜢 靓 迎 壬 迁 悔 驮 迎 筹 婷 婷 襟 袪 梓 谥 僧 癌 垢 屌 缉', 'timestamp':

We have no ideas about you question, would you please describe it with more details?   Follow this template: https://github.com/alibaba-damo-academy/FunASR/issues/new/choose

**Comment by R1ckShi** [comment]
> 我也是识别结果乱码。有解决办法吗？ 我就用tutorial里指定的 wav ，也是乱码
> 
> model = AutoModel(model="paraformer-zh", model_revision="v2.0.2", vad_model="fsmn-vad", vad_model_revision="v2.0.2", punc_model="ct-punc-c", punc_model_revision="v2.0.2", spk_model="cam++", spk_model_revision="v2.0.2") res = model.generate(input=f"{model.model_path}/example/asr_example.wav", batch_size=64, hotword='魔搭')
> 
> [{'key': 'rand_key_2yW4Acq9GFz6Y', 'text': '径 before 共 while 鹌 蔺 拮 淀 珦 蜢 靓 迎 壬 迁 悔 驮 迎 筹 婷 婷 襟 袪 梓 谥 僧 癌 垢 屌 缉', 'timestamp':

感谢反馈，正在debug

**Comment by LauraGPT** [comment]
Sorry, bug has been fixed. Please update funasr and try it again. https://github.com/alibaba-damo-academy/FunASR/commit/e67ed1d45d5a9d7fb7bb22d15fd2bfef17e9076f

**Comment by dsyrock** [comment]
> Sorry, bug has been fixed. Please update funasr and try it again. [e67ed1d](https://github.com/alibaba-damo-academy/FunASR/commit/e67ed1d45d5a9d7fb7bb22d15fd2bfef17e9076f)

谢谢，这次终于可以正常识别了！

**Comment by dsyrock** [comment]
顺便问一下，timestamp的单位是秒吗？330代表0.33秒，4190代表4.19秒这样？

**Comment by R1ckShi** [comment]
> 顺便问一下，timestamp的单位是毫秒吗？330代表0.33秒，4190代表4.19秒这样？

是的，时间戳单位为毫秒。
