### ISSUE TITLE
训练数据集示例文件错误

### ISSUE THREAD

**Issue by xyx361100238** [alibaba-damo-academy/FunASR#1252]
![image](https://github.com/alibaba-damo-academy/FunASR/assets/19569322/cf18562d-21af-4027-a13c-a24f2b5b9f02)
使用该实例文档会出现找不到prompt字段，需要去掉逗号：
![image](https://github.com/alibaba-damo-academy/FunASR/assets/19569322/24fea855-aead-4ef8-8a3b-545d7356d908)

**Comment by LauraGPT** [comment]
Thank you for reminding. Data examples has been fixed.
