### ISSUE TITLE
希望能提供docker进程、FunASR进程崩溃后自动重启守护进程功能

### ISSUE THREAD

**Issue by leceshide** [alibaba-damo-academy/FunASR#1253]
如题。社区管理员回复已经在计划内，希望能尽快实现。造福广大用户

**Comment by lyblsgo** [comment]
Daemon functionality is supported in Docker: funasr-runtime-sdk-online-cpu-0.1.8 funasr-runtime-sdk-en-cpu-0.1.4 funasr-runtime-sdk-cpu-0.4.3
