### ISSUE TITLE
识别8000左右录音文件  程序假死?

### ISSUE THREAD

**Issue by LiSongRan** [alibaba-damo-academy/FunASR#1255]
### Before asking:
1. search the issues.
2. search the docs.

#### What is your question?
docker启动之后，启动 funasr-wss-server服务程序：

cd FunASR/runtime
nohup bash run_server.sh \
  --download-model-dir /workspace/models \
  --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx \
  --model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx  \
  --punc-dir damo/punc_ct-transformer_cn-en-common-vocab471067-large-onnx \
  --lm-dir damo/speech_ngram_lm_zh-cn-ai-wesp-fst \
  --itn-dir thuduj12/fst_itn_zh \
  --hotword /workspace/models/hotwords.txt > log.out 2>&1 &
运行这个  程序都在识别8000个的时候 假死 不在进行但不退出
#### What have you tried?
试过两次都是 内存占满之后 程序还在运行 但是不在往下识别了
#### What's your environment?
sudo docker pull \
  registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-cpu-0.4.1
mkdir -p ./funasr-runtime-resources/models
sudo docker run -p 10095:10095 -it --privileged=true \
  -v $PWD/funasr-runtime-resources/models:/workspace/models \
  registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-cpu-0.4.1

用的就是这个镜像
 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by LiSongRan** [comment]
****  how do u solve this problem

**Comment by lyblsgo** [comment]
Try version funasr-runtime-sdk-cpu-0.4.3 to see if the issue still persists.

**Comment by lyblsgo** [comment]
Try version funasr-runtime-sdk-cpu-0.4.2 to see if the issue still persists.
