### ISSUE TITLE
onnx的结果没有标点符号，并且使用quantize=True时会报错

### ISSUE THREAD

**Issue by DrewdropLife** [alibaba-damo-academy/FunASR#1256]
#### My question:
onnx模型输出的结果没有标点符号，并且使用quantize=True时会报错
#### Code
```
asr_model = Paraformer("damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch", batch_size=1, quantize=True, cache_dir="models")
vad_model = Fsmn_vad("damo/speech_fsmn_vad_zh-cn-16k-common-pytorch", quantize=True, cache_dir="models") 
ct_model = CT_Transformer("damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch", quantize=True, cache_dir="models")
result_vad = vad_model(wav_path)
result_asr = asr_model(wav_path)
result = ct_model(result_asr[0]["preds"])
```
1、我在pytorch框架下使用"damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch"这个名字的模型，结果是很不错的，带有标点符号的，例如：
“今天真是个好日子啊，你觉得呢？”

但是当我用onnxruntime推断时，使用了相同名字的这个模型，也即上述代码中result_asr的结果：
“今 天 真 是 个 好 日 子 啊 你 觉 得 呢”

2、onnx推断时是否有一个集语音活动检测、语音识别、标点恢复于一体的模型？而非像我上述代码一样分三步走？我上述代码依次进行了活动检测、语音识别、标点恢复，但是实测发现速度太慢了，整体耗时是pytorch的2倍！

我于是想要转成量化后的模型，设置quantize=True，但是export过程中报错了，我不清楚是什么原因：
![image](https://github.com/alibaba-damo-academy/FunASR/assets/50581411/b1e662ed-0877-46a5-8b67-ab6c3747d6c5)

我希望能尽可能快的得到带有标点符号的识别结果，请告诉我怎么做，谢谢！

#### What's your environment?
use registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-cpu-0.4.0

**Comment by jbang2004** [comment]
老哥，用pytorch模型时的推理是否会出现一些字词重复两三次的情况？我用最新的三模型管道推理，经常有重复词现象

**Comment by yuGAN6** [comment]
> 老哥，用pytorch模型时的推理是否会出现一些字词重复两三次的情况？我用最新的三模型管道推理，经常有重复词现象

@jbang2004 我用Onnx模型也有，但只在单条长音频输入才会出现，一般要大于30秒。加入大于30秒的音频微调之后重复字有减少，但还是存在。可能是CIF模块对齐的问题

**Comment by Nancis1130** [comment]
same here.

**Comment by Nancis1130** [comment]
请问最后如何解决的？
