### ISSUE TITLE
funasr1.0 似乎没有导出onnx功能了？

### ISSUE THREAD

**Issue by rookie0607** [alibaba-damo-academy/FunASR#1257]

**Comment by LauraGPT** [comment]
On the way

**Comment by rookie0607** [comment]
> On the way

uniasr也一并支持了吧  （狗头

**Comment by LauraGPT** [comment]
funasr-1.0 export onnx:

https://github.com/alibaba-damo-academy/FunASR?tab=readme-ov-file#export-onnx
