### ISSUE TITLE
docker 部署 funasr 用python调不通

### ISSUE THREAD

**Issue by geshihuatatata** [alibaba-damo-academy/FunASR#1258]
### Before asking:
1. search the issues.1
2. search the docs.

![3](https://github.com/alibaba-damo-academy/FunASR/assets/41822371/6035c56c-7c28-4d4a-be50-9f95c1312305)
![4](https://github.com/alibaba-damo-academy/FunASR/assets/41822371/cb17bc57-d052-4673-8516-da2036f302f9)

#### What's your environment?

 - OS (e.g., Linux):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Python   3.6.8
 - Any other relevant information:

**Comment by sssuzr1** [comment]
i get same error

**Comment by lyblsgo** [comment]
If the issue persists, please reopen the issue and provide detailed steps to reproduce, as well as server and client logs.
