### ISSUE TITLE
bug: wav.scp里如果有超过2个wav文件 就报错

### ISSUE THREAD

**Issue by anonymoussky** [alibaba-damo-academy/FunASR#1263]
## 🐛 Bug
2024-01-18 02:25:14,751 - modelscope - INFO - PyTorch version 2.0.1 Found.
2024-01-18 02:25:14,753 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2024-01-18 02:25:14,942 - modelscope - INFO - Loading done! Current index file version is 1.11.0, with md5 a89740e7f97cec8e58f9006c952870e4 and a total number of 953 components indexed
2024-01-18 02:25:15,848 - modelscope - INFO - Use user-specified model revision: v2.0.2
WARNING:root:enable bias encoder sampling and contextual training
2024-01-18 02:25:22,576 - modelscope - INFO - Use user-specified model revision: v2.0.2
2024-01-18 02:25:23,527 - modelscope - INFO - Use user-specified model revision: v2.0.2
2024-01-18 02:25:25,868 - modelscope - INFO - Use user-specified model revision: v2.0.2
WARNING:root:Many to print when using speaker model...
  0%|                                                                                                                                                                                             | 0/3 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/16T/lucayongxu/FunASR/rec.py", line 14, in <module>
    res = model.generate(input="wav.scp",
  File "/16T/lucayongxu/FunASR/funasr/auto/auto_model.py", line 208, in generate
    return self.inference_with_vad(input, input_len=input_len, **cfg)
  File "/16T/lucayongxu/FunASR/funasr/auto/auto_model.py", line 272, in inference_with_vad
    res = self.inference(input, input_len=input_len, model=self.vad_model, kwargs=self.vad_kwargs, **cfg)
  File "/16T/lucayongxu/FunASR/funasr/auto/auto_model.py", line 239, in inference
    results, meta_data = model.inference(**batch, **kwargs)
  File "/16T/lucayongxu/FunASR/funasr/models/fsmn_vad_streaming/model.py", line 548, in inference
    assert len(audio_sample_list) == 1, "batch_size must be set 1"
AssertionError: batch_size must be set 1

wav.scp里 kaldi格式 如果只有一个wav文件 ，没问题；wav.scp列表里只要有2个或以上的文件 就报错

执行的命令如下：
from funasr import AutoModel
model = AutoModel(model="paraformer-zh", model_revision="v2.0.2", \
                  vad_model="fsmn-vad", vad_model_revision="v2.0.2", \
                  punc_model="ct-punc-c", punc_model_revision="v2.0.2", \
                  spk_model="cam++", spk_model_revision="v2.0.2")
res = model.generate(input="wav.scp",
                     batch_size=64,
                     hotword='魔搭')

**Comment by LauraGPT** [comment]
> ## 🐛 Bug
> 2024-01-18 02:25:14,751 - modelscope - INFO - PyTorch version 2.0.1 Found. 2024-01-18 02:25:14,753 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer 2024-01-18 02:25:14,942 - modelscope - INFO - Loading done! Current index file version is 1.11.0, with md5 a89740e7f97cec8e58f9006c952870e4 and a total number of 953 components indexed 2024-01-18 02:25:15,848 - modelscope - INFO - Use user-specified model revision: v2.0.2 WARNING:root:enable bias encoder sampling and contextual training 2024-01-18 02:25:22,576 - modelscope - INFO - Use user-specified model revision: v2.0.2 2024-01-18 02:25:23,527 - modelscope - INFO - Use user-specified model revision: v2.0.2 2024-01-18 02:25:25,868 - modelscope - INFO - Use user-specified model revision: v2.0.2 WARNING:root:Many to print when using speaker model... 0%| | 0/3 [00:00<?, ?it/s]Traceback (most recent call last): File "/16T/lucayongxu/FunASR/rec.py", line 14, in res = model.generate(input="wav.scp", File "/16T/lucayongxu/FunASR/funasr/auto/auto_model.py", line 208, in generate return self.inference_with_vad(input, input_len=input_len, **cfg) File "/16T/lucayongxu/FunASR/funasr/auto/auto_model.py", line 272, in inference_with_vad res = self.inference(input, input_len=input_len, model=self.vad_model, kwargs=self.vad_kwargs, **cfg) File "/16T/lucayongxu/FunASR/funasr/auto/auto_model.py", line 239, in inference results, meta_data = model.inference(**batch, **kwargs) File "/16T/lucayongxu/FunASR/funasr/models/fsmn_vad_streaming/model.py", line 548, in inference assert len(audio_sample_list) == 1, "batch_size must be set 1" AssertionError: batch_size must be set 1
> 
> wav.scp里 kaldi格式 如果只有一个wav文件 ，没问题；wav.scp列表里只要有2个或以上的文件 就报错
> 
> 执行的命令如下： from funasr import AutoModel model = AutoModel(model="paraformer-zh", model_revision="v2.0.2", vad_model="fsmn-vad", vad_model_revision="v2.0.2", punc_model="ct-punc-c", punc_model_revision="v2.0.2", spk_model="cam++", spk_model_revision="v2.0.2") res = model.generate(input="wav.scp", batch_size=64, hotword='魔搭')

Please change the `batch_size=64` to `batch_size_s=300`
