### ISSUE TITLE
tls一直出

### ISSUE THREAD

**Issue by yourengod** [alibaba-damo-academy/FunASR#1266]
I20240118 13:19:08.676419    28 websocket-server-2pass.cpp:29] on_tls_init called with hdl: 0x7fa3bc084290
I20240118 13:19:08.676498    28 websocket-server-2pass.cpp:30] using TLS mode: Mozilla Intermediate
I20240118 13:19:12.852130    28 websocket-server-2pass.cpp:29] on_tls_init called with hdl: 0x7fa3bc08d070

请问 这个不正常吧？如何解决啊？

**Comment by Plwy** [comment]
我遇到同样的报错，这样解决了：docker服务启动命令添加参数 `--certfile 0 `以禁止ssl。[ref](https://github.com/modelscope/FunASR/issues/1995#issuecomment-2630113796)
