### ISSUE TITLE
2024.01.19 微调代码出现问题

### ISSUE THREAD

**Issue by xyx361100238** [alibaba-damo-academy/FunASR#1273]
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd 'finetune.sh'
2. See error
![1705651785730](https://github.com/alibaba-damo-academy/FunASR/assets/19569322/864df7e0-b503-4471-90a4-418c11609765)

#### Code sample

`
python3 funasr/bin/train.py \
+model="../modelscope_models/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch" \
+model_revision="v2.0.2" \
+train_data_set_list="data/list/audio_datasets.jsonl" \
+valid_data_set_list="data/list/audio_datasets.jsonl" \
++dataset_conf.batch_size=6000 \
++dataset_conf.num_workers=4 \
++train_conf.nax_epoch=5 \
+output_dir="outputs" \
+device="cuda"`
### Environment

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0):  1.0.0
 - ModelScope Version (e.g., 1.11.0): 1.11.0
 - PyTorch Version (e.g., 2.0.0): 1.13.1
 - How you installed funasr (pip, source): source
 - Python version: 3.8
 - GPU (e.g., V100M32) N3080
 - CUDA/cuDNN version (e.g., cuda11.7): 11.6
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by xyx361100238** [comment]
这个是曾经的训练过程：
![image](https://github.com/alibaba-damo-academy/FunASR/assets/19569322/f7e3da74-9607-4942-988f-1224e871504b)

**Comment by xyx361100238** [comment]
问题依然存在 ，请帮忙查看下

**Comment by pengpengzi** [comment]
> 问题依然存在 ，请帮忙查看下
"
![图片](https://github.com/alibaba-damo-academy/FunASR/assets/103752028/d5bd5ece-e73f-4375-8ac5-6f446edcb7c2)
"
我也遇到了同样的问题，请问解决了吗

**Comment by xyx361100238** [comment]
没有呢   社区里面也没有反馈

**Comment by xyx361100238** [comment]
@LauraGPT
