### ISSUE TITLE
iOS端Demo运行失败

### ISSUE THREAD

**Issue by lijingxiu** [alibaba-damo-academy/FunASR#1287]
已按照Readme文档添加了4个库。
<img width="834" alt="292761367-8d55ac7d-b453-4eb5-a433-460455cae9e1-2" src="https://github.com/alibaba-damo-academy/FunASR/assets/2345603/b4967072-b142-4187-9f8a-72399c1f2016">

**Comment by lyblsgo** [comment]
Use the latest version; if the issue still persists, you can reopen the issue and provide steps to reproduce.
