### ISSUE TITLE
time_speech_total_all_samples除零异常

### ISSUE THREAD

**Issue by spritelw** [alibaba-damo-academy/FunASR#1294]
## 🐛 Bug

FunASR/funasr/auto/auto_model.py

inference_with_vad函数中， 当分段结果为0时，time_speech_total_all_samples会除零异常

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

import torchaudio
    from funasr.download.file import download_from_url
    from funasr import AutoModel
    model = AutoModel(model="damo/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch",
                      model_revision="v2.0.2",
                      vad_model="damo/speech_fsmn_vad_zh-cn-16k-common-pytorch",
                      vad_model_revision="v2.0.2",
                      # punc_model="damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch",
                      # punc_model_revision="v2.0.3",
                      # spk_model="damo/speech_campplus_sv_zh-cn_16k-common",
                      # spk_model_revision="v2.0.2",
                      )
    input = "https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/asr_example_zh.wav"
    data_in = download_from_url(input)
    data_or_path_or_list, audio_fs = torchaudio.load(data_in)
    data_or_path_or_list = data_or_path_or_list.mean(0)
    numpy_array = data_or_path_or_list.numpy()
    res = model.generate(input=numpy_array,
                         hotword='达摩院 魔搭', chunk_size=60*1000)

### Environment

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by LauraGPT** [comment]
bug has been fixed. Please update funasr and try it again.

**Comment by spritelw** [comment]
不行，已附上复现代码
