### ISSUE TITLE
AutoModel， ngpu 判断有误

### ISSUE THREAD

**Issue by spritelw** [alibaba-damo-academy/FunASR#1295]
## 🐛 Bug

FunASR/funasr/auto/auto_model.py

build_model函数中， kwargs.get("ngpu", 0)判断有误
if not torch.cuda.is_available() or kwargs.get("ngpu", 0): //==>应该为 kwargs.get("ngpu", 0) == 0
    device = "cpu"
    kwargs["batch_size"] = 1

如果ngpu >= 1, 导致使用cpu
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd '....'
2. See error

### Environment

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by LauraGPT** [comment]
Thank you for feedback. Bug has been fixed.
