### ISSUE TITLE
[bug] the punc between sentence_info and text has difference 

### ISSUE THREAD

**Issue by fanlu** [alibaba-damo-academy/FunASR#1301]
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd 'funasr +model=paraformer-zh +vad_model="fsmn-vad" +punc_model="ct-punc" +model_revision="v2.0.4" +vad_model_revision="v2.0.4" +punc_model_revision="v2.0.4" +spk_model="cam++" +spk_model_revision="v2.0.2" +input=长音频.mp3'
2. See error
![image](https://github.com/alibaba-damo-academy/FunASR/assets/1620875/6e556bc9-2aa5-4c83-89a4-3c1a673edefe)
<img width="1002" alt="image" src="https://github.com/alibaba-damo-academy/FunASR/assets/1620875/80c3cd70-8e27-4447-98a3-cdabcecf2eb9">

there is a punc "，" between "开" and "始" in sentence_info， which is not exists in text. that is weired 
3. the latest version is used

![image](https://github.com/alibaba-damo-academy/FunASR/assets/1620875/e76d1c81-8002-4caf-9c15-b5f7971f041d)
![image](https://github.com/alibaba-damo-academy/FunASR/assets/1620875/2df381b7-10e9-4639-8b53-3f857e38cb67)

### Environment

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by R1ckShi** [comment]
可以分享一下测试用例吗

**Comment by fanlu** [comment]
> 使用用例python代码而非命令行调用是否有这个问题？ 可以分享一下测试用例吗

也会有问题，如果是一段长音频的话，后面的sentence_info里面的标点也是跟text里面的标点对不上的

**Comment by R1ckShi** [comment]
已经修复，重新拉取代码试下。

**Comment by fanlu** [comment]
没有问题了
