### ISSUE TITLE
SeACoParaformer热词语音识别-中文-通用-16k-离线-large模型报错：ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by JVfisher** [alibaba-damo-academy/FunASR#1303]
[Uploading 20200629054721_slice_26.zip…]()
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd '....'

from funasr import AutoModel
model = AutoModel(model="iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch", model_revision="v2.0.4",
                  vad_model="fsmn-vad", vad_model_revision="v2.0.4",
                  punc_model="ct-punc-c", punc_model_revision="v2.0.4",
                  lm_model='iic/speech_transformer_lm_zh-cn-common-vocab8404-pytorch',
                  lm_weight=0.15,
                  beam_size=10
                  # spk_model="cam++", spk_model_revision="v2.0.2",
                  )
res = model.generate(input=f"20200629054721_slice_26.wav", 
            batch_size_s=600, 
            hotword='大哥' )
print(res)
3. See error
![1706171712116_C323B867-D32C-4e5a-85AB-929B95390481](https://github.com/alibaba-damo-academy/FunASR/assets/392128/6cb4088e-1be4-46c3-bc39-c26eba8e4473)

### Expected behavior
使用iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch就没有问题
from funasr import AutoModel
model = AutoModel(model="iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch", model_revision="v2.0.4",
                  vad_model="fsmn-vad", vad_model_revision="v2.0.4",
                  punc_model="ct-punc-c", punc_model_revision="v2.0.4",
                  lm_model='iic/speech_transformer_lm_zh-cn-common-vocab8404-pytorch',
                  lm_weight=0.15,
                  beam_size=10
                  # spk_model="cam++", spk_model_revision="v2.0.2",
                  )
res = model.generate(input=f"20200629054721_slice_26.wav", 
            batch_size_s=600, 
            hotword='大哥' )
print(res)

### Environment

 - FunASR Version (1.0.2):
 - ModelScope Version (1.11.1 ):

**Comment by LauraGPT** [comment]
Bug has been fixed, please ref to https://github.com/alibaba-damo-academy/FunASR/issues/1294
