### ISSUE TITLE
长音频模型speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch 对于识别某些wav文件效果很差

### ISSUE THREAD

**Issue by jpyjpr** [alibaba-damo-academy/FunASR#1308]
## 🐛 Bug

- 我测试了很多wav文件都有很好的效果，而且比whisper准确度高，但是对于下面这段wav文件，识别效果很差，特别是有频繁的漏识别现象，准确度不如whisper不知道是什么原因导致的？
https://pan.baidu.com/s/1l30W0GX1RyMPvqfgLn2zLQ 
密码: x9t7

- 这段音频我是通过mp4文件转换的，转换代码如下：

```Python

from moviepy.editor import *

video = VideoFileClip('tea_multi.mp4')
audio = video.audio
# audio.write_audiofile('test.wav')
audio.write_audiofile('tea_multi.wav')

```

**Comment by wang-ship-it** [comment]
你好我想问一下，你是自己微调了模型吗

**Comment by R1ckShi** [comment]
sorry for missing your question, please share your audio again.

**Comment by jpyjpr** [comment]
> 抱歉错过了您的问题，请再次分享您的音频。

我知道问题在哪里了，我先通过人声分离提取纯人声之后，说话人识别效果就非常好了，应该是这个音频的噪音比较大

**Comment by jpyjpr** [comment]
> 你好我想问一下，你是自己微调了模型吗

没有微调， 直接用

**Comment by phpdancer** [comment]
> > 抱歉错过了您的问题，请再次分享您的音频。
> 
> 我知道问题在哪里了，我先通过人声分离提取纯人声之后，说话人识别效果就非常好了，应该是这个音频的噪音比较大

请问你是用什么做的提取纯人声的？

**Comment by lmxin123** [comment]
应该是用VAD模型吧，这个模型是不支持VAD的speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch。
可以使用这个模型，speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-onnx

**Comment by jpyjpr** [comment]
> > > 抱歉错过了您的问题，请再次分享您的音频。
> > 
> > 
> > 我知道问题在哪里了，我先通过人声分离提取纯人声之后，说话人识别效果就非常好了，应该是这个音频的噪音比较大
> 
> 请问你是用什么做的提取纯人声的？

用的是spleeter模型
