### ISSUE TITLE
请问有CPU版本的语音实时转写有ARM架构下的Docker镜像吗？

### ISSUE THREAD

**Issue by 0902081008** [alibaba-damo-academy/FunASR#1311]
### Before asking:
1. search the issues.
2. search the docs.

#### What's your environment?

 - OS (e.g., Linux): 
 - FunASR Version (e.g., 1.0.0):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by lyblsgo** [comment]
Currently, it is not available, but it will be supported in the future.

**Comment by lyblsgo** [comment]
Offline File Transcription Service 4.4, Offline File Transcription Service of English 1.5，Real-time Transcription Service 1.9 released，docker image supports ARM64 platform
