### ISSUE TITLE
如何在用私有语录训练好lm后用于asr的推理

### ISSUE THREAD

**Issue by JVfisher** [alibaba-damo-academy/FunASR#1312]
我参考https://github.com/alibaba-damo-academy/FunASR/blob/main/runtime/docs/lm_train_tutorial.md 完成了私有语料训练模型，得到了config.yaml 和 TLG.fst，请问如何把这个语言模型应用到asr的pipline或者generate中呀？

我看文档https://github.com/alibaba-damo-academy/FunASR/blob/4f224c88068b66bcb6f81570da59d99c9bba8288/runtime/websocket/bin/funasr-wss-server.cpp#L116中是说
lm_dir("", LM_DIR,
        "the LM model path, which contains compiled models: TLG.fst, config.yaml ", false, "damo/speech_ngram_lm_zh-cn-ai-wesp-fst", "string");我理解是在服务器端可以配置，如果

**Comment by muziling** [comment]
您好，这个问题最后怎么解决的？
