### ISSUE TITLE
标点模型(punc model)推理速度过慢

### ISSUE THREAD

**Issue by songyinghao** [alibaba-damo-academy/FunASR#1314]
#### What is your question?
使用标点模型(punc_ct-transformer_cn-en-common-vocab471067-large)时，推理速度很慢，20S左右
v2.0.4

#### Code

```
# punc_model
punc_model = AutoModel(model=punc_model_path,
                       device = "cuda",
                       ngpu = 1
                    )
sentence = punc_model.generate(input="你好，这是一个测试")[0]["text"]
print(sentence)
```

#### What's your environment?

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.3):直接拉取最新的git代码
 - 
 - Any other relevant information:
 - 
![Weixin Screenshot_20240129171203](https://github.com/alibaba-damo-academy/FunASR/assets/2515932/e030833d-e7b5-4151-9269-18ca10ebca45)
![Weixin Screenshot_20240129171243](https://github.com/alibaba-damo-academy/FunASR/assets/2515932/a4a45016-9d5f-47a3-901c-aa79de4945b2)

**Comment by songyinghao** [comment]
> 是不是gpu启动的开销？

不是，模型加载到内存后，每次推理都很慢，能帮忙试验一下吗？

**Comment by AlvinAi96** [comment]
> > 是不是gpu启动的开销？
> 
> 不是，模型加载到内存后，每次推理都很慢，能帮忙试验一下吗？

我也发现了，无论句子长度，基本都是单次输入耗时在20s左右，GPU均已调用。请问有解决方案吗？

**Comment by LauraGPT** [comment]
This is a bug, please update funasr.
