### ISSUE TITLE
onnx infer error

### ISSUE THREAD

**Issue by zhusy09** [alibaba-damo-academy/FunASR#132]
![IMG_20230217_113430_edit_35808707146618](https://user-images.githubusercontent.com/38637821/219543048-6f03592c-dcec-4f76-bcc9-0b281e0a611d.jpg)

**Comment by langgz** [comment]
It's the bug. Please use the pytorch1.11.0 to export the onnx. https://github.com/alibaba-damo-academy/FunASR/tree/main/funasr/export#export-model
