### ISSUE TITLE
About Seaco-paraformer bias_embed weights

### ISSUE THREAD

**Issue by locasxe** [alibaba-damo-academy/FunASR#1320]
## ❓ Questions and Help
I found that: in function load_pretrained_model:
	logging.debug("Loaded src_state keys: {}".format(src_state.keys()))
	logging.debug("Loaded dst_state keys: {}".format(dst_state.keys()))
	dst_state.update(src_state)
	obj.load_state_dict(dst_state, strict=True)
if dst_state.update(src_state) is removed:
    obj.load_state_dict(src_state, strict=True)
ERROR====》Missing key(s) in state_dict: “bias_embed.weight”

#### What is your question?
So, indeed, bias_embed.weight is missing in src_state, is this normal?  And why?

#### What's your environment?

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by R1ckShi** [comment]
bias_embed is initialized but not used, hotwords are embedded with the asr decoder embedding
