### ISSUE TITLE
AutoModel接口input参数传入tensor的不能正常使用vad模型

### ISSUE THREAD

**Issue by LuffyGT** [alibaba-damo-academy/FunASR#1331]
#### What is your question?
1. AutoModel接口，传入torchaudio 加载得到的tensor，只能使用单paraformer-zh模型(情况1正常)，加vad报错(情况2)

#### Code
下面是尝试的几种情况：asr_example_zh.wav是16khz音频文件

代码1：可以正常输出结果
```
model = AutoModel(
            model="paraformer-zh", model_revision="v2.0.4",
            # vad_model="fsmn-vad", vad_model_revision="v2.0.4",
            # punc_model="ct-punc-c", punc_model_revision="v2.0.4",
            device='cuda')
input_tensor, sample_rate = torchaudio.load("asr_example_zh.wav")
input_tensor = input_tensor.mean(0)
res = model.generate(input=[input_tensor_resample], batch_size_s=300)
```
正常输出结果

代码2：报错AssertionError: batch_size must be set 1
```
model = AutoModel(
            model="paraformer-zh", model_revision="v2.0.4",
            vad_model="fsmn-vad", vad_model_revision="v2.0.4",
            punc_model="ct-punc-c", punc_model_revision="v2.0.4",
            device='cuda')
input_tensor, sample_rate = torchaudio.load("asr_example_zh.wav")
input_tensor = input_tensor.mean(0)
res = model.generate(input=[input_tensor_resample], batch_size_s=300)
```

#### What have you tried?
看代码是vad模型和paraformer-zh的输入格式在传入tensor时并不一致？是bug么？

#### What's your environment?

 - OS: linux/mac
 - FunASR Version: 1.0.3
 - ModelScope Version: 1.11.1
 - PyTorch Version:  2.1.0
 - How you installed funasr: pip install -U modelscope>=1.11.1 funasr>=1.0.2
 - Python version: 3.10

**Comment by LauraGPT** [comment]
Bug has been fixed in https://github.com/alibaba-damo-academy/FunASR/commit/dec1c875b2fcf0161755b93717d3eac856c6d15d

Please uodate funasr and try it again.[demo](https://github.com/alibaba-damo-academy/FunASR/blob/main/examples/industrial_data_pretraining/seaco_paraformer/demo.py)
