### ISSUE TITLE
where is egs_modelscope

### ISSUE THREAD

**Issue by locasxe** [alibaba-damo-academy/FunASR#1332]
## ❓ Questions and Help
I cannot find it, It seems finetuning with modelscope is deleted?
 So, how to finetune seaco-paraformer with modelscope?
#### What's your environment?

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by R1ckShi** [comment]
finetuning related functions are still on going, scripts will be released once finished.
you can finetune models with branch v0.8.8, but finetuning seaco-paraformer is not supported.
