### ISSUE TITLE
funasr --model paraformer-zh vad_example.wav报错

### ISSUE THREAD

**Issue by LoveRiverLi** [alibaba-damo-academy/FunASR#1340]
[
![微信图片_20240201155933](https://github.com/alibaba-damo-academy/FunASR/assets/31496638/490cec33-4239-4f65-916e-248bc0ccec49)
](url)

**Comment by LoveRiverLi** [comment]
> ```shell
> funasr ++model=paraformer-zh ++vad_model="fsmn-vad" ++punc_model="ct-punc" ++input=asr_example_zh.wav
> ```
![image](https://github.com/alibaba-damo-academy/FunASR/assets/31496638/284c9060-c558-4110-bac0-355f1c89beed)

**Comment by LauraGPT** [comment]
> > ```shell
> > funasr ++model=paraformer-zh ++vad_model="fsmn-vad" ++punc_model="ct-punc" ++input=asr_example_zh.wav
> > ```
> 
> ![image](https://private-user-images.githubusercontent.com/31496638/301739568-284c9060-c558-4110-bac0-355f1c89beed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NTUyOTEsIm5iZiI6MTcwNjg1NDk5MSwicGF0aCI6Ii8zMTQ5NjYzOC8zMDE3Mzk1NjgtMjg0YzkwNjAtYzU1OC00MTEwLWJhYzAtMzU1ZjFjODliZWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA2MjMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NDczMDg5MTVlZjZmODA5M2IzOTVjN2IwMjhlZTQzNjViNWY4NDc3N2U2NWVjMmU0NzY5N2Y5MDY4NmE4YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3B1prXiIyPzYwiDgcazTYpvPLLUfRmOGMLD8_HfhK9k)

ref to the python code, add `model_revision` for asr, vad, punc
`++model_revision="v2.0.4" ++vad_model_revision="v2.0.4" ++punc_model_revision="v2.0.4"`

**Comment by LoveRiverLi** [comment]
> > > ```shell
> > > funasr ++model=paraformer-zh ++vad_model="fsmn-vad" ++punc_model="ct-punc" ++input=asr_example_zh.wav
> > > ```
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/31496638/301739568-284c9060-c558-4110-bac0-355f1c89beed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NTUyOTEsIm5iZiI6MTcwNjg1NDk5MSwicGF0aCI6Ii8zMTQ5NjYzOC8zMDE3Mzk1NjgtMjg0YzkwNjAtYzU1OC00MTEwLWJhYzAtMzU1ZjFjODliZWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA2MjMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NDczMDg5MTVlZjZmODA5M2IzOTVjN2IwMjhlZTQzNjViNWY4NDc3N2U2NWVjMmU0NzY5N2Y5MDY4NmE4YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3B1prXiIyPzYwiDgcazTYpvPLLUfRmOGMLD8_HfhK9k)
> 
> ref to the python code, add `model_revision` for asr, vad, punc `++model_revision="v2.0.4" ++vad_model_revision="v2.0.4" ++punc_model_revision="v2.0.4"`

![image](https://github.com/alibaba-damo-academy/FunASR/assets/31496638/285c7deb-6fa0-4896-a2ba-2dde4acd96fb)
