### ISSUE TITLE
MP3文件识别时读取文件报错

### ISSUE THREAD

**Issue by duanmenghui** [alibaba-damo-academy/FunASR#1353]
## 🐛 Bug

识别MP3文件报错，同样的代码WAV文件可以识别，报错内容如下

Steps to reproduce the behavior (**always include the command you ran**):

1. 直接运行

model = AutoModel(model="paraformer-zh", model_revision="v2.0.4",
                  vad_model="fsmn-vad", vad_model_revision="v2.0.4",
                  punc_model="ct-punc-c", punc_model_revision="v2.0.4",
                  #spk_model="cam++", spk_model_revision="v2.0.2",
                  )
import time
print(model.model_path)
print(time.time())
res = model.generate(input=f"asr_example.wav",
            batch_size_s=300,
            hotword='魔搭')
print(time.time())
print(res)

### Environment

 - OS (e.g., Linux): Ubuntu 20.04
 - FunASR Version (e.g., 1.0.0): 1.0.5
 - ModelScope Version (e.g., 1.11.0): 1.11.1
 - PyTorch Version (e.g., 2.0.0): 2.1.2
 - How you installed funasr (`pip`, source): pip
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by LauraGPT** [comment]
Please upload the audio file.

**Comment by duanmenghui** [comment]
[nba.md](https://github.com/alibaba-damo-academy/FunASR/files/14160971/nba.md)
下载后请把后缀名改为mp3

**Comment by LauraGPT** [comment]
Now you could update funasr and try it again. ffmpeg is added.
