### ISSUE TITLE
使用example中的finetune.sh之后获得的微调模型，推理乱码

### ISSUE THREAD

**Issue by xiulianzw** [alibaba-damo-academy/FunASR#1367]
#### What's your environment?

 - OS (e.g., Linux): Linux
 - FunASR Version (e.g., 1.0.0):1.0.0
 - ModelScope Version (e.g., 1.11.0):1.10.0
 - PyTorch Version (e.g., 2.0.0):2.0.1+cu117
 - How you installed funasr (`pip`, source):pip
 - Python version:3.8.16
 - GPU (e.g., V100M32):3090RTX
 - CUDA/cuDNN version (e.g., cuda11.7):11.7
 - Any other relevant information:
使用finetine.sh微调了2个epoch，通过tensorboard查看，loss和准确率如下
![image](https://github.com/alibaba-damo-academy/FunASR/assets/20657139/6078ff7f-bf35-4959-86d9-3afd62bc4c00)
![image](https://github.com/alibaba-damo-academy/FunASR/assets/20657139/36da37fd-bc85-42b0-91a7-8df7ea3e1b2d)

训练完成之后使用`infer_after_finetune.sh`脚本进行推理，将outputs的config.yaml中的tokenizer_conf.token_list和frontend_conf.cmvn_file进行替换，推理之后的输出的ASR结果乱码

如果将`++init_param`进行注释，输出的ASR结果是正常的

**Comment by LauraGPT** [comment]
Please update funasr, and try it again.
