### ISSUE TITLE
cpu版本的runtime，流式输入长语音后内存会增长后不释放

### ISSUE THREAD

**Issue by apple2333cream** [alibaba-damo-academy/FunASR#1368]
您好 我在windows下更新了新的版本（1.0.7）之后，部署的cpu版本的runtime/websocket,  online模式，当客户端的话筒输入一段较长时长的连续语音时（10s以上），服务端的funasr-wss-server-2pass.exe程序内存占用会缓慢增长，请问这个问题你们有遇到过吗？

#### What's your environment?

 - OS (e.g., win10,vs2019):
 - FunASR Version (e.g., 1.0.7):
 -

**Comment by huangdadahai2015** [comment]
我在linux中用docker部署，也遇到同样的问题

**Comment by Ostrich96** [comment]
我有遇到类似的问题，2pass本身既有online也有offline，初步怀疑是offline模型存在内存泄漏的问题。用offline模型在自己的环境压测几小时的音频，内存会缓慢增长。

**Comment by huangdadahai2015** [comment]
我也遇到这类问题，加热词越多，内存增长的越快

**Comment by lmxin123** [comment]
请问你用的是这个windows 社区版吗funasr-runtime-win-cpu-x64-v0.4.4?
这个是否支持边说话边识别的效果？
还有长文件录音支持边识别边输出的效果

**Comment by lyblsgo** [comment]
Use the latest version; if the issue still persists, you can reopen the issue and provide steps to reproduce.
