### ISSUE TITLE
本地热词文件导入bug

### ISSUE THREAD

**Issue by SoonSYJ** [alibaba-damo-academy/FunASR#137]
https://github.com/alibaba-damo-academy/FunASR/blob/2c3f49cd21a1da317b028878b27362c8af1ce8b5/funasr/bin/asr_inference_paraformer.py#L176

当hotword_list_or_file是错误的路径字符串，会进入if判定，同时hotword_list_or_file字符串会被建模成hotword_list，不会报错。

**Comment by langgz** [comment]
感谢反馈，已经修复，额外加了判断
