### ISSUE TITLE
KeyError: 'spk_embedding'

### ISSUE THREAD

**Issue by ihorizons2022** [alibaba-damo-academy/FunASR#1370]
<img width="827" alt="image" src="https://github.com/alibaba-damo-academy/FunASR/assets/121672603/1f05baa3-7f3d-4a6f-a994-8d35d7e437a1">
from funasr import AutoModel
# paraformer-zh is a multi-functional asr model
# use vad, punc, spk or not as you need
model = AutoModel(model="paraformer-zh", model_revision="v2.0.4",
                  vad_model="fsmn-vad", vad_model_revision="v2.0.4",
                  punc_model="ct-punc-c", punc_model_revision="v2.0.4",
                  # spk_model="cam++", spk_model_revision="v2.0.2",
                  )
res = model.generate(input=f"{model.model_path}/example/asr_example.wav", 
                     batch_size_s=300, 
                     hotword='魔搭')
print(res)

**Comment by skyrim-X** [comment]
你好，我funasr更新到了版本为1.0.10，python==3.8.18，也是同样的代码，还是报错KeyError: 'spk_embedding'，请问这是什么问题？

**Comment by skyrim-X** [comment]
> Thank you for your feedback, the bug has been fixed. Please update funasr, and try it again.

你好，我funasr更新到了版本为1.0.10，python==3.8.18，也是同样的代码，还是报错KeyError: 'spk_embedding'，请问这是什么问题？
