### ISSUE TITLE
A question about convolution fusion in MFCCA

### ISSUE THREAD

**Issue by hiranoyu0830** [alibaba-damo-academy/FunASR#1374]
Hello. Thank you for great works.
In the implementation of MFCCA encoder([funasr/models/mfcca/mfcca_encoder.py](https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/models/mfcca/mfcca_encoder.py)), I found that convolution channel fusion consists of **4 Conv2ds**. However, in the [MFCCA paper,](https://arxiv.org/pdf/2210.05265.pdf) convolution channel fusion consists of **5 Conv2ds**. And the kernel size is also different. 
Why is the implementation different from the one in the paper?

Thank you in advance!

**Comment by yufan-aslp** [comment]
Thank you for your question. The implementation of the funasr does indeed differ from the description in the paper, as subsequent attempts have shown that the current structure yields better results.
