### ISSUE TITLE
docker中onnx模型推理效果比较AutoModel采用pt模型差

### ISSUE THREAD

**Issue by AI-CNN** [alibaba-damo-academy/FunASR#1376]
### To Reproduce
pt模型测试代码：
model = AutoModel(model="model_zoo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch", model_revision="v2.0.4",
                  vad_model="fsmn-vad", vad_model_revision="v2.0.4",
                  punc_model="ct-punc-c", punc_model_revision="v2.0.4",
                  # spk_model="cam++", spk_model_revision="v2.0.2",
                  )

docker中测试代码：
nohup bash run_server_2pass.sh \
  --model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx \
  --online-model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx \
  --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx \
  --punc-dir damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727-onnx \
  --lm-dir damo/speech_ngram_lm_zh-cn-ai-wesp-fst \
  --itn-dir thuduj12/fst_itn_zh \
  --certfile  ../../../ssl_key/server.crt \
  --keyfile ../../../ssl_key/server.key \
  --hotword ../../hotwords.txt > log.txt 2>&1 &

### Environment

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.3)
  - Docker version (e.g., funasr-runtime-sdk-online-cpu-0.1.8)
 - Any other relevant information:

### Additional context
问题：
1、请问pt和onnx模型是不是版本不一样导致识别差异？
2、从哪里可以找到pt模型对应的onnx模型？
3、docker中目前使用的是c++的bin文件运行，可以使用AutoModel做推理吗？
4、docker中能否直接用pt模型做推理？

**Comment by wgfi110** [comment]
在使用过程中，发现使用pt模型推理比onnx模型推理效果要好。使用方式如下：
1.pt推理：CUDA_VISIBLE_DEVICES=3 python -m funasr.bin.asr_inference_launch --batch_size 1 --ngpu 1 --njob 1 --gpuid_list 1 --data_path_and_name_and_type /shuzi.data.scp,speech,sound --cmvn_file /damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/am.mvn  --key_file /shuzi.data.scp --asr_train_config /damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/config.yaml  --asr_model_file /damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/model.pb --output_dir ./res.1 --mode paraformer --config conf/decode_asr_transformer_noctc_1best.yaml

**Comment by iwanglei1** [comment]
是的，我也发现了这个问题。

**Comment by pony5551** [comment]
不是推理效果差，ONNX目前使用的模型是1.0.6而模型最新版本是2.0.4，所以差距很大，期待官方早点推出导出最新模型的代码
