### ISSUE TITLE
FunASR离线文件转写服务的python-client客户端用法通过pycharm执行没报错但也没成功

### ISSUE THREAD

**Issue by LoveRiverLi** [alibaba-damo-academy/FunASR#1378]
### Before asking:
1. search the issues.
2. search the docs.

#### What is your question?
FunASR离线文件转写服务的python-client客户端用法通过pycharm执行没报错但也没成功,而Html网页版是可以的
![0](https://github.com/alibaba-damo-academy/FunASR/assets/31496638/c7f7042b-171c-4582-82ce-cda44934b148)
![1](https://github.com/alibaba-damo-academy/FunASR/assets/31496638/3467abb6-68a0-498c-83be-0fa7b08935c6)

#### What's your environment?
win10+pycharm+docker
 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by LauraGPT** [comment]
Maybe you could debug it with `print`

**Comment by LoveRiverLi** [comment]
官方git文件,有打印结果
![1](https://github.com/alibaba-damo-academy/FunASR/assets/31496638/4052fab3-05c4-4f68-887b-6263d3ac09be)
![2](https://github.com/alibaba-damo-academy/FunASR/assets/31496638/f9261db3-e408-46aa-97d2-7d49ed6cc045)
