### ISSUE TITLE
How to adjust the parameter of VAD model using AutoModel

### ISSUE THREAD

**Issue by OswaldoBornemann** [alibaba-damo-academy/FunASR#1381]
For example, I would like to adjust the parameters of VAD like `max_end_sil`, how to pass this parameter in AutoModel?

**Comment by LauraGPT** [comment]
Please change it in the config.yaml of the vad model.

**Comment by OswaldoBornemann** [comment]
I see. Where is the `config.yaml` file ?

**Comment by R1ckShi** [comment]
by default, it will be downloaded to /YOUR_ROOT_PATH/.cache/modelscope/hub/iic/xxx
