### ISSUE TITLE
Error while finding module specification for 'funasr.export.export_model' (ModuleNotFoundError: No module named 'funasr.export')

### ISSUE THREAD

**Issue by jieqinian** [alibaba-damo-academy/FunASR#1382]
### Before asking:
1. search the issues.
2. search the docs.

#### What is your question?
python3 -m funasr.export.export_model --model-name damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch --export-dir ./export --type torch --quantize True
If you want to use the speaker diarization, please `pip install hdbscan`
If you want use mossformer, lease install rotary_embedding_torch by: 
 pip install -U rotary_embedding_torch
If you want use mossformer, lease install rotary_embedding_torch by: 
 pip install -U rotary_embedding_torch
Please Requires the ffmpeg CLI and `ffmpeg-python` package to be installed.
If you want use mossformer, lease install rotary_embedding_torch by: 
 pip install -U rotary_embedding_torch
If you want use mossformer, lease install rotary_embedding_torch by: 
 pip install -U rotary_embedding_torch
/usr/bin/python3: Error while finding module specification for 'funasr.export.export_model' (ModuleNotFoundError: No module named 'funasr.export')

#### What's your environment?

 - Python version:

**Comment by LauraGPT** [comment]
If you are exporting onnx in hurry, please do it in funasr-.0.8.8 ([this](https://github.com/alibaba-damo-academy/FunASR/tree/v0.8.8/funasr/export)). We would support it in funasr-1.0 before 20/3.

**Comment by LauraGPT** [comment]
funasr-1.0 export onnx:

https://github.com/alibaba-damo-academy/FunASR?tab=readme-ov-file#export-onnx
