### ISSUE TITLE
Incorrect Sentence Splitting and Timestamps in Transcription Output

### ISSUE THREAD

**Issue by jbang2004** [alibaba-damo-academy/FunASR#1383]
🐛 Bug Report: Incorrect Sentence Splitting and Timestamps in Transcription Output

### 1. Description

When enabling sentence_timestamp=True in auto_model.py (line 425) to obtain sentence timestamps in the transcription results, the output contains incorrect sentence splits and punctuation marks at unexpected positions. Despite the incorrect sentence splitting, the text field in the results appears accurate.

### 2. Steps to Reproduce

- Modify auto_model.py to set sentence_timestamp=True.

- Run the following code:
```
from funasr import AutoModel
model = AutoModel(
    model="paraformer-zh", model_revision="v2.0.4",
    vad_model="fsmn-vad", vad_model_revision="v2.0.4",
    punc_model="damo/punc_ct-transformer_cn-en-common-vocab471067-large", punc_model_revision="v2.0.4",
)
res = model.generate(input="test.wav", batch_size_s=300)
print(res)
```
- Observe the output, specifically the 'sentence_info' field, which shows incorrect sentence divisions and punctuation,like【'sentence_info': [{'text': '来创业最大的？', 'start': 1160, 'end': 2740, 'timestamp': [[1160, 1400], [1620, 1860], [1860, 2100], [2180, 2400], [2400, 2580], [2580, 2740]]}, {'text': '魅力在哪？', 'start': 2740, 'end': 3360, 'timestamp': [[2740, 2880], [2880, 3060], [3060, 3200], [3200, 3360]]}, {'text': '里，', 'start': 3360, 'end': 3600, 'timestamp': [[3360, 3600]]}, {'text': '最吸引，', 'start': 3600, 'end': 4140, 'timestamp': [[3600, 3800], [3800, 3960], [3960, 4140]]}, {'text': '的是什么哎呀。', 'start': 4140, 'end': 5580, 'timestamp': [[4140, 4380], [4380, 4620], [4640, 4740], [4740, 4980], [5280, 5440], [5440, 5580]]}】
but in 'text' field, the output is correct, like【'text': '来创业最大的魅力在哪里？最吸引的是什么？】

### 3. Expected Behavior

The expected output should correctly split sentences and place punctuation marks, aligning with the accurate text field in the results.

### 4. Environment

OS: Windows 11
FunASR Version: 1.0.10
PyTorch Version: 2.1.2+cu118
Python Version: 3.10
GPU: NVIDIA GeForce RTX 3060

### 5. Additional Context

**Upon examining the code, I discovered that the content of the text field is generated from punc_res[0]["text"] provided by the punctuation model, while the sentence_info field is produced by aligning punc_res[0]['punc_array'], result['timestamp'], and raw_text. I suspect the issue may lie in the mechanism for generating the punc_array—which dictates what punctuation follows each character—but I am unable to access the specific generation mechanism of the punctuation model.**

**Comment by R1ckShi** [comment]
use iic/punc_ct-transformer_zh-cn-common-vocab272727-pytorch instead of damo/punc_ct-transformer_cn-en-common-vocab471067-large, the former one is a word level punc model

**Comment by jbang2004** [comment]
> use iic/punc_ct-transformer_zh-cn-common-vocab272727-pytorch instead of damo/punc_ct-transformer_cn-en-common-vocab471067-large, the later one is a word level punc model

Thanks,it worked！
