### ISSUE TITLE
speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch配合speech_eres2net_sv_zh-cn_16k-common使用加载报错

### ISSUE THREAD

**Issue by NimbleDev** [alibaba-damo-academy/FunASR#1385]
如下图所示，使用speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch进行语音识别，配合使用speech_eres2net_sv_zh-cn_16k-common作为说话人识别，加载speech_eres2net_sv_zh-cn_16k-common时报错了，是还不支持吗？能否支持啊？
![image](https://github.com/alibaba-damo-academy/FunASR/assets/51120096/898dbd71-2c27-4a83-84dc-fa75566e9099)

**Comment by lmxin123** [comment]
请问你是在FunASR里使用speech_eres2net_sv_zh-cn_16k-common模型吗？

**Comment by NimbleDev** [comment]
> 请问你是在FunASR里使用speech_eres2net_sv_zh-cn_16k-common模型吗？
是的
