### ISSUE TITLE
使用0.8.8版本modelscope微调模型speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online报错

### ISSUE THREAD

**Issue by LGoldenDragon** [alibaba-damo-academy/FunASR#1390]
- OS (e.g., Linux):
 - FunASR Version (e.g., 0.8.8):
 - ModelScope Version (e.g., 1.10.0):
 - PyTorch Version (e.g., 2.0.0):
 - Python version: 3.8
 - CUDA/cuDNN version (e.g., cuda11.7):

使用0.8.8版本modelscope微调模型speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online报错

代码如下：
import os
from modelscope.metainfo import Trainers
from modelscope.trainers import build_trainer
from funasr.datasets.ms_dataset import MsDataset
from funasr.utils.modelscope_param import modelscope_args

def modelscope_finetune(params):
    if not os.path.exists(params.output_dir):
        os.makedirs(params.output_dir, exist_ok=True)
    # dataset split ["train", "validation"]
    ds_dict = MsDataset.load(params.data_path)
    kwargs = dict(
        model=params.model,
        # model_revision=params.model_revision,
        model_revision='v1.0.7',
        data_dir=ds_dict,
        dataset_type=params.dataset_type,
        work_dir=params.output_dir,
        batch_bins=params.batch_bins,
        max_epoch=params.max_epoch,
        lr=params.lr)
    trainer = build_trainer(Trainers.speech_asr_trainer, default_args=kwargs)
    trainer.train()

if __name__ == '__main__':
    params = modelscope_args(model="damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online", data_path="/datasets/ljl_file/FunASR/egs/aishell/paraformer/DATA/data")
    params.output_dir = "/datasets/ljl_file/FunASR/egs_modelscope/asr/paraformer/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/checkpoint"              # m模型保存路径
    params.data_path = "/datasets/ljl_file/FunASR/egs/aishell/paraformer/DATA/data"            # 数据路径
    params.dataset_type = "small"                   # 小数据量设置small，若数据量大于1000小时，请使用large
    params.batch_bins = 1000                       # batch size，如果dataset_type="small"，batch_bins单位为fbank特征帧数，如果dataset_type="large"，batch_bins单位为毫秒，
    params.max_epoch = 10                           # 最大训练轮数
    params.lr = 0.00005                             # 设置学习率
    
    modelscope_finetune(params)

报错如下：
![image](https://github.com/alibaba-damo-academy/FunASR/assets/80027101/1a5cc896-8c28-4478-929b-4b555ef5180c)

删除cache里面的modelscope缓存，并且降级modelscope为1.9.0依旧报此错误

**Comment by LauraGPT** [comment]
Bug has been fixed. Please ref to the docs: 
https://github.com/alibaba-damo-academy/FunASR/blob/main/docs/tutorial/README_zh.md
