### ISSUE TITLE
英文微调后输出字符没有用空格隔开

### ISSUE THREAD

**Issue by tuocheng0824** [alibaba-damo-academy/FunASR#1399]
微调英文模型 speech_paraformer_asr-en-16k-vocab4199-pytorch 
我微调后生成的英文 如下所示，有些英文是没有空格隔开：
we're heretohelp ifyou have questionsabout anexisting orrder

**Comment by LauraGPT** [comment]
Sorry, it is a bug. Please ref to https://github.com/alibaba-damo-academy/FunASR/issues/1463
