### ISSUE TITLE
check_latest typo in download_from_hub.py

### ISSUE THREAD

**Issue by sweetcard** [alibaba-damo-academy/FunASR#1409]
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd '....'
2. See error

### Environment

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

### Additional context

Check this line:
https://github.com/alibaba-damo-academy/FunASR/blob/14ecc9c281a80d95d4088505e216a3db37148c54/funasr/download/download_from_hub.py#L21

<img width="1302" alt="image" src="https://github.com/alibaba-damo-academy/FunASR/assets/17595667/1cfc74e7-6907-47aa-b507-6b00766cd702">

`check_latest=kwargs.get("kwargs", True)) `

**"kwargs"** should be **"check_latest"**

**Comment by LauraGPT** [comment]
Thank you for feedback. It has been fixed.
