### ISSUE TITLE
"ct-punc" model: length mismatch between punc and timestamp

### ISSUE THREAD

**Issue by atomiechen** [alibaba-damo-academy/FunASR#1410]
## 🐛 Bug

When using `punc_model="iic/punc_ct-transformer_cn-en-common-vocab471067-large` (which I believe is aliased to `ct-punc`) along with `spk_model`, I found that `sentence_info` in the output result is not complete, and I encountered this warning revealing the cause:

> WARNING:root:length mismatch between punc and timestamp

This bug would not happen in `v2.0.2`, and would show up in `v2.0.3` and `v2.0.4` (current revision).

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd `python sample.py`
2. See log warning `WARNING:root:length mismatch between punc and timestamp`
3. Check that `res[0]["sentence_info"]` is incomplete comparing to `res[0]["timestamp"]`. Please check screenshot below, where I added some debug output in the `FunASR` source.
<img width="1005" alt="image" src="https://github.com/alibaba-damo-academy/FunASR/assets/36685998/bc3053d7-d673-4a6d-a8b8-2162f69e525a">
4. In `sample.py`, uncomment `punc_model_revision="v2.0.2",` and run cmd `python sample.py` again to see no above warning and complete result. See screenshot below.
<img width="997" alt="image" src="https://github.com/alibaba-damo-academy/FunASR/assets/36685998/1b80e0be-6d9f-4b90-9da5-4ece6a542476">

#### Code sample

```python
# sample.py
from funasr import AutoModel
model = AutoModel(
    model="paraformer-zh",
    vad_model="fsmn-vad",
    punc_model="ct-punc", 
    # uncomment this to see things work
    # punc_model_revision="v2.0.2",
    spk_model="cam++", 
)
res = model.generate(input=f"{model.model_path}/example/asr_example.wav")
print(res)
```

### Expected behavior

There should be no warning of length mismatch between punc and timestamp, and `sentence_info` should contain complete recognition result.

### Environment

 - OS: Linux
 - FunASR Version: 1.0.10
 - ModelScope Version: 1.12.0
 - PyTorch Version: 2.1.0+cu118
 - How you installed funasr (`pip`, source): pip
 - Python version: 3.10.13
 - GPU: NVIDIA GeForce RTX 4090
 - CUDA/cuDNN version: cuda11.8
 - Docker version: registry.cn-hangzhou.aliyuncs.com/modelscope-repo/modelscope:ubuntu22.04-cuda11.8.0-py310-torch2.1.0-tf2.14.0-1.10.0
 - Any other relevant information:

**Comment by R1ckShi** [comment]
please use iic/punc_ct-transformer_zh-cn-common-vocab272727-pytorch (ct-punc-c) instead of iic/punc_ct-transformer_cn-en-common-vocab471067-large. the later one is a word level punc model

**Comment by atomiechen** [comment]
> please use iic/punc_ct-transformer_zh-cn-common-vocab272727-pytorch (ct-punc-c) instead of iic/punc_ct-transformer_cn-en-common-vocab471067-large. the later one is a word level punc model

@R1ckShi Thank you, but I know that ct-punc-c is working. I just don't know the reason.

The problem is that the paraformer pipeline `iic/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch` also uses `iic/punc_ct-transformer_cn-en-common-vocab471067-large` (ct-punc) (check its [`configuration.json`](https://modelscope.cn/models/iic/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/file/view/master/configuration.json?status=1)). 

When I ran that pipeline and added spk model using modelscope, I saw a lot about this length mismatch problem. **This is exactly when I firstly encountered this issue, and it took me a lot of time to drill down to find the culprit, the punc model.**

I will appreciate it if there are more documentations about the difference between these punc models (sorry if I missed something, but I found nothing from model pages), and how we should choose to make things work.

**Comment by R1ckShi** [comment]
> > please use iic/punc_ct-transformer_zh-cn-common-vocab272727-pytorch (ct-punc-c) instead of iic/punc_ct-transformer_cn-en-common-vocab471067-large. the later one is a word level punc model
> 
> @R1ckShi Thank you, but I know that ct-punc-c is working. I just don't know the reason.
> 
> The problem is that the paraformer pipeline `iic/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch` also uses `iic/punc_ct-transformer_cn-en-common-vocab471067-large` (ct-punc) (check its [`configuration.json`](https://modelscope.cn/models/iic/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/file/view/master/configuration.json?status=1)).
> 
> When I ran that pipeline and added spk model using modelscope, I saw a lot about this length mismatch problem. **This is exactly when I firstly encountered this issue, and it took me a lot of time to drill down to find the culprit, the punc model.**
> 
> I will appreciate it if there are more documentations about the difference between these punc models (sorry if I missed something, but I found nothing from model pages), and how we should choose to make things work.

you may pull thje latest code and try the "ct-punc" again, i fixed the problem hours ago

**Comment by atomiechen** [comment]
Thanks! Fixed indeed.

**Comment by MuBai-He** [comment]
您好，使用了iic/punc_ct-transformer_zh-cn-common-vocab272727-pytorch依旧有相同问题 

![Image](https://github.com/user-attachments/assets/17203b69-4c41-499f-b0eb-281cfaeaf3b3)
