### ISSUE TITLE
fsmn_vad_streaming 有实时读取麦克风的案例吗

### ISSUE THREAD

**Issue by lonngxiang** [alibaba-damo-academy/FunASR#1413]
这里案例只是加载离线音频文件
https://github.com/alibaba-damo-academy/FunASR/blob/5608bee0accea5e12030f8e1b6f7d62eee4dd892/examples/industrial_data_pretraining/fsmn_vad_streaming/demo.py

**Comment by LauraGPT** [comment]
https://github.com/alibaba-damo-academy/FunASR/tree/main/runtime/python/websocket
