### ISSUE TITLE
UnsupportedValueType: FunASRPipeline: GenericFunASR: Value 'CharTokenizer' is not a supported primitive type

### ISSUE THREAD

**Issue by domoretry** [alibaba-damo-academy/FunASR#1423]
#### What is your question?
遵循链接：
https://www.modelscope.cn/models/iic/speech_paraformer_asr_nat-zh-cn-16k-common-vocab8358-tensorflow1/summary
https://github.com/alibaba-damo-academy/FunASR#installation
进行funasr modelscope安装并尝试调用api进行推理

from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model='iic/speech_paraformer_asr_nat-zh-cn-16k-common-vocab8358-tensorflow1', model_revision="v2.0.4")

rec_result = inference_pipeline('https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/asr_example_zh.wav')
print(rec_result)

遇到如下错误：
omegaconf.errors.UnsupportedValueType: FunASRPipeline: GenericFunASR: Value 'CharTokenizer' is not a supported primitive type
    full_key: tokenizer
    object_type=dict

#### What have you tried?
尝试更新funasr 和modelscope版本，并未奏效，Google不到相关错误信息。
#### What's your environment?

 - OS :Linux
 - FunASR Version :1.0.12
 - ModelScope Version :1.12.0
 - PyTorch Version :2.2.1
 - How you installed funasr (`pip`, source):source
 - Python version:3.10.13
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version: cuda 12.1 /cudnn 8902

**Comment by LauraGPT** [comment]
Sorry, bug has been fixed. https://github.com/alibaba-damo-academy/FunASR/pull/1425/files
Please update funasr-1.0.13 and try it again.

**Comment by daocodedao** [comment]
pip install 找不到1.0.13

**Comment by LauraGPT** [comment]
> pip install 找不到1.0.13

pip install -U funasr -i https://pypi.org/simple
