### ISSUE TITLE
Paraformer: Fast and Accurate Parallel Transformer for Non-autoregressive End-to-End Speech Recognition论文结果复现

### ISSUE THREAD

**Issue by zsLin177** [alibaba-damo-academy/FunASR#1437]
# 复现论文中Table1的4.6/5.2结果
* 你好，我正在认真paraformer进行学习和复现，在复现上述实验结果的时候，我参照了https://github.com/alibaba-damo-academy/FunASR/blob/main/examples/aishell/paraformer/conf/paraformer_conformer_12e_6d_2048_256.yaml
* 但是在该config中我看到使用了论文中没有提到的一些东西，比如训练时的ctc loss，解码时使用了ctc based beam search
* 请问我想复现4.6/5.2的结果的话，应该follow哪个config，是否要使用ctc loss、ctc based beam search，以及nbest avg等？

**Comment by LauraGPT** [comment]
https://github.com/alibaba-damo-academy/FunASR/tree/v0.8.8/egs/aishell/paraformer

**Comment by zsLin177** [comment]
哇，感谢这么快的回复，继续学习去了。

**Comment by zsLin177** [comment]
> 你好，我还在学习复现paraformer，也参照了您昨天提供的config，但是目前使用aishell1训练集进行训练，得到的性能距离论文中汇报的结果还有不小的差距，我的结果dev-cer:5.67 (解码时avg10，ctc weight=0，greedy decoding，without lm。训练时ctc weight=0.3，use_1st_decoder_loss=true)。对于代码和论文我还有以下几点疑问，希望您能帮我解答：
> 
> * 论文中table 1使用的模型是否是对应https://github.com/alibaba-damo-academy/FunASR/blob/v0.8.8/funasr/models/e2e_asr_paraformer.py 中的Paraformer模型？
> * 论文中提到在predictor的训练和解码中都使用了dynamic threshold，但是代码和config中我看到使用的是固定threshold=1.0，如果我要复现结果的是这个会不会有影响？
> * 论文中提到使用负采样的MWER loss，我在仓库中没找到对应的代码，请问table1 中模型是否使用？
> * 在论文中我看到pass 1的梯度是不回传，而在config中我注意到使用了use_1st_decoder_loss=true，且该版本代码中在use_1st_decoder_loss=true时会计算pass 1的CE loss并回传？不知道这点对复现论文结果是否有影响？
> * 训练的epoch数量，我现在是按照config中写到max epoch=150进行训练，但是在readme中提到epoch=50，不知道应该按照哪个进行设置？
> 
> **希望能得到您的解答，感谢🙏**

不好意思，问题解决了，非常感谢您的帮助～

**Comment by zsLin177** [comment]
> 请问您的问题最后是如何解决的？想请教一下，感

不好意思，有点久远了，我有点忘了，怎么解决的了。印象中是可以复现出来的，然后MWER loss啥的好像没用就可以
