### ISSUE TITLE
实时的paraformer模型微调问题

### ISSUE THREAD

**Issue by dospeech** [alibaba-damo-academy/FunASR#1439]
H i～有个关于微调的问题：
开源出来的实时paraformer模型可以用FunASR/examples/industrial_data_pretraining/paraformer/finetune.sh脚本里面的微调方式进行微调吗？

**Comment by pony5551** [comment]
可以的，不过2.0.4版模型暂时不能转onnx,官方说快了

**Comment by dsh54054** [comment]
> 可以的，不过2.0.4版模型暂时不能转onnx,官方说快了

hi，你成功finetune过流式模型么，我finetune时报错，但finetune damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch可以

**Comment by dospeech** [comment]
> > 可以的，不过2.0.4版模型暂时不能转onnx,官方说快了
> 
> hi，你成功finetune过流式模型么，我finetune时报错，但finetune damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch可以

我跑时也报错，还没调通，有什么思路吗？

**Comment by LauraGPT** [comment]
Bug has been fixed. Please ref to the docs: 
https://github.com/alibaba-damo-academy/FunASR/blob/main/docs/tutorial/README_zh.md
