### ISSUE TITLE
middle layer output 

### ISSUE THREAD

**Issue by HaiFengZeng** [alibaba-damo-academy/FunASR#144]
Great work. I want to apply some middle layer output for other purpose(Voice Conversion), how can I get this feature from a given audio?

**Comment by langgz** [comment]
Maybe you could return any outputs from some layers in encoder at :https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/bin/asr_inference_paraformer.py#L224

Then return it outside, and add it in asr_result_list  at https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/bin/asr_inference_paraformer.py#L754
