### ISSUE TITLE
在Windows版本中怎么添加说话人识别功能？

### ISSUE THREAD

**Issue by CWJ-NB** [alibaba-damo-academy/FunASR#1441]
在魔搭中有`FunASR社区软件包windows版本`的集成包。
添加了说话人识别的模型应该是`iic/speech_paraformer-large-vad-punc-spk_asr_nat-zh-cn`，如何在上面的集成包中使用这个模型，是要将这个模型量化为onnx吗？或者如何在windows集成包中添加识别说话人的功能？

**Comment by lyblsgo** [comment]
Currently, the speaker model is not supported in c++ runtime

**Comment by lmxin123** [comment]
我看钉钉群里说已经支持C++了
