### ISSUE TITLE
funasr1.0 finetune问题

### ISSUE THREAD

**Issue by dsh54054** [alibaba-damo-academy/FunASR#1444]
funasr和modelscope版本：
funasr=1.0.14
modelscope=1.12.0

问题:使用FunASR/examples/industrial_data_pretraining/paraformer/finetune_from_local.sh进行finetune，damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch整句模型可以正常finetune，damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404长文本模型和damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online流式模型都会报错。
damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404报错信息：
<img width="1432" alt="截屏2024-03-07 15 02 24" src="https://github.com/alibaba-damo-academy/FunASR/assets/37110787/b168bc00-76af-4073-ac4f-5ad5be6ddf15">
damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online报错信息：
<img width="1415" alt="截屏2024-03-07 15 06 50" src="https://github.com/alibaba-damo-academy/FunASR/assets/37110787/bfee1cca-cf10-4e4f-ad83-ac12df433717">

**Comment by LauraGPT** [comment]
Bug has been fixed. Please ref to the docs: 
https://github.com/alibaba-damo-academy/FunASR/blob/main/docs/tutorial/README_zh.md
