### ISSUE TITLE
Is "paraformer-zh" same with "'iic/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch'"?

### ISSUE THREAD

**Issue by MengHao666** [alibaba-damo-academy/FunASR#1451]
model1:  https://github.com/alibaba-damo-academy/FunASR/tree/main  "paraformer-zh" model

model2:  https://www.modelscope.cn/models/iic/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/summary

**Comment by MengHao666** [comment]
ok, I find that:

model 1 use `.cache\modelscope\hub\damo\speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch\model.pt`

model2 uses `.cache\modelscope\hub\iic\speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch\model.pt`

the result model2 is better. But in your github documents. You suggest to use model1 with funasr library.

I think the documentation of funasr should be more clear. As there are 3 ways to get models: huggingface, modelscope, `funasr` libraray itself. These might be confusing if you do not give their unified description.

**Comment by MengHao666** [comment]
and I did found performance drop comapred with the old ways. I think it might be very confusing for the recent updfates

I use following config and code to get model before:

 "model_name": "damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch",
 "model_revision": "v1.2.4"

asr_inference_pipeline = modelscope.pipelines.pipeline(
            task=Tasks.auto_speech_recognition,
            model=model,
            model_revision=model_revision)

**Comment by LauraGPT** [comment]
> and I did found performance drop comapred with the old ways. I think it might be very confusing for the recent updfates in funasr 1.0.
> 
> I use following config and code to get model before:
> 
> "model_name": "damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch", "model_revision": "v1.2.4"
> 
> asr_inference_pipeline = modelscope.pipelines.pipeline( task=Tasks.auto_speech_recognition, model=model, model_revision=model_revision)

What the `performance drop` means? The update about 1.0 is here: https://github.com/alibaba-damo-academy/FunASR/discussions/1319

**Comment by MengHao666** [comment]
I see there might be some failures to add punctuation to the result, and it might due to the updates in the punctuation model. I don't know how to update wav file in the github

**Comment by LauraGPT** [comment]
> I see there might be some failures to add punctuation to the result, and it might due to the updates in the punctuation model. I don't know how to update wav file in the github

just `CTR + V` to upload.

**Comment by kongzijian** [comment]
i could not  get sentence_timestamp in speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch but in speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch .why?
