### ISSUE TITLE
传入input为wav的路径时，key不起作用

### ISSUE THREAD

**Issue by LRY1994** [alibaba-damo-academy/FunASR#1459]
## 🐛 Bug
FunASR/funasr/auto/auto_model.py 
这里应该要判断传入的key是否为空，传入input为wav的路径时，key不起作用。

![image](https://github.com/alibaba-damo-academy/FunASR/assets/17881352/819541dd-c09a-4ce4-8ad2-6cdf29c00cd9)

### To Reproduce

res = model.generate(input=path,
                                chunk_size=chunk_size,
                                encoder_chunk_look_back=encoder_chunk_look_back,
                                decoder_chunk_look_back=decoder_chunk_look_back,
                                is_final=True,
                                output_dir=local_path,
                                device='cuda:0',
                                key=key 
                                )

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd '....'
2. See error

### Environment

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by LauraGPT** [comment]
You could change the `max_single_segment_time` in vad_kwargs:

https://github.com/alibaba-damo-academy/FunASR/blob/main/examples/industrial_data_pretraining/paraformer/demo.py#L12

**Comment by LauraGPT** [comment]
Thank you for your feedback, it has been changed. https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/auto/auto_model.py#L71
