### ISSUE TITLE
模型训练之后英文能力退化成了 只输出大写英文字母且没有空格

### ISSUE THREAD

**Issue by vergil-ong** [alibaba-damo-academy/FunASR#1463]
#### Code

使用https://github.com/alibaba-damo-academy/FunASR/blob/main/examples/industrial_data_pretraining/paraformer/finetune_from_local.sh 下的脚本 自己进行模型微调。
微调 20epoch 之后，新模型 英文能力几乎没有了 输出成了“HELLOWORLD” 这种样子

#### What's your environment?
微调日志正常输出，没见异常
微调数据 100+小时的音频wav数据
音频本身包含了英文，中文
类似这个文件https://github.com/vergil-ong/show-files/blob/main/english.wav
但是 实际训练时，音频文件不会超过10s，自己用代码调用 ffmpeg 进行阶段

看效果 感觉像是 模型不理解英文的分词能力，把英文也按照中文一样按照一个字一个字的分词了一样

**Comment by LauraGPT** [comment]
Sorry, bug has been fixed. Please update funasr and try it again.
https://github.com/alibaba-damo-academy/FunASR/commit/e02f361de6516227ac46b9e1033329823664841f

**Comment by vergil-ong** [comment]
Thanks it worked
