### ISSUE TITLE
FunASR/runtime /csharp/ 版本有内存泄漏问题

### ISSUE THREAD

**Issue by Geek-Bob** [alibaba-damo-academy/FunASR#1464]
## 🐛 Bug

复现条件，直接运行起来，通过定时器500ms调用一次 OfflineRecognizer实例的GetResults函数或者AliFsmnVad实例的GetSegments函数，内存就会无限上涨，我怀疑是他们各自对应的WavFrontend类里面代码有问题

# # #环境
-操作系统(如windows10):
- FunASR版本最新版
- Microsoft.ML.OnnxRuntime 最新版本:

附加的上下文

**Comment by lyblsgo** [comment]
C# was open-sourced by the community users @manyeyes  
when convenient, please take a moment to review it.

**Comment by Geek-Bob** [comment]
It takes a while to DEBUG because memory growth is slow, but there is a memory leak.  Thank you for your open source efforts so that our .NET c# community can keep pace with the AI era

**Comment by manyeyes** [comment]
We will resolve this issue as soon as possible. Before the next version is released, you can try upgrading "KaldiNativeFbankSharp" to version 1.2.0 through NUGET. @Geek-Bob

**Comment by manyeyes** [comment]
This PR may be able to solve the current issue:
https://github.com/alibaba-damo-academy/FunASR/pull/1497
usage examples:
`
SegmentEntity[] segments_duration = aliFsmnVad.GetSegmentsByStep(samples);
aliFsmnVad.Dispose();
`

**Comment by Geek-Bob** [comment]
> We will resolve this issue as soon as possible. Before the next version is released, you can try upgrading "KaldiNativeFbankSharp" to version 1.1.2 through NUGET.

@manyeyes 



Thanks for the answers, the "KaldiNativeFbankSharp" version has been upgraded to 1.1.2, and the "OfflineRecognizer" memory leak has been fixed.   But the "AliFsmnVad" memory leak solution you mentioned is to call the "Dispose" method every time, but this class has no "Dispose" method.   And each Dispose to create a new instance, will not be poor performance

**Comment by Geek-Bob** [comment]
<img width="488" alt="内存泄漏1" src="https://github.com/alibaba-damo-academy/FunASR/assets/95834538/b7fb1715-53f7-4dfe-b9ea-902d44142d65">
![Uploading 内存泄漏2.png…]()
<img width="560" alt="内存泄漏3" src="https://github.com/alibaba-damo-academy/FunASR/assets/95834538/f8e9084c-4d87-4254-a6d4-d0a23af2341f">
![Uploading 内存泄漏2.png…]()

**Comment by Geek-Bob** [comment]
<img width="488" alt="内存泄漏1" src="https://github.com/alibaba-damo-academy/FunASR/assets/95834538/2cec7ffa-b706-475d-a858-40f33bb1189f">
<img width="818" alt="内存泄漏2" src="https://github.com/alibaba-damo-academy/FunASR/assets/95834538/9ee25445-f5c9-4c5b-b94f-33275fbfca24">
<img width="560" alt="内存泄漏3" src="https://github.com/alibaba-damo-academy/FunASR/assets/95834538/371f201d-c8eb-4799-9073-34d1108f2e55">

**Comment by Geek-Bob** [comment]
> We will resolve this issue as soon as possible. Before the next version is released, you can try upgrading "KaldiNativeFbankSharp" to version 1.1.2 through NUGET.  and usage examples: SegmentEntity[] segments_duration = aliFsmnVad.GetSegmentsByStep(samples); aliFsmnVad.Dispose();

@manyeyes 
Thanks for your answers, the "KaldiNativeFbankSharp" version has been upgraded to 1.1.2 and the "OfflineRecognizer" memory leak has been fixed.  However, the "AliFsmnVad" memory leak solution you mentioned is to call the "Dispose" method every time, I have tested it, which will add about 150ms of time, is there a better way, and there are still memory leaks

<img width="331" alt="内存泄漏1" src="https://github.com/alibaba-damo-academy/FunASR/assets/95834538/61742e87-ae45-43f3-8f6c-de768ce55f53">
<img width="656" alt="内存泄漏3" src="https://github.com/alibaba-damo-academy/FunASR/assets/95834538/a70b1b16-3e8c-438b-ba1f-ed3bdbfbc4bb">
<img width="665" alt="内存泄漏2" src="https://github.com/alibaba-damo-academy/FunASR/assets/95834538/457e4b04-3b9e-41bb-bb95-ea91d3592240">

**Comment by Geek-Bob** [comment]
@manyeyes Thank you very much. Thank you again. .NET efforts and contributions. There may have been some problems with my earlier tests. Looks like the memory leak has been fixed. We will track the issue post-fix for a certain duration to verify its complete resolution
