### ISSUE TITLE
contextual_paraformer和seaco_paraformer 热词模型finetune似乎和funasr1.0.14不兼容

### ISSUE THREAD

**Issue by dsh54054** [alibaba-damo-academy/FunASR#1470]
环境：funasr==1.0.14, modelscope==1.13.0
尝试finetune contextual_paraformer报错：
TypeError: embedding(): argument 'indices' (position 2) must be Tensor, not NoneType,
打印了contextual_paraformer/model.py中约180行hw_embed = self.bias_embed(hotword_pad)中的hotword_pad显示为None，应该是由hotword_pad引起的
<img width="1400" alt="截屏2024-03-11 18 29 25" src="https://github.com/alibaba-damo-academy/FunASR/assets/37110787/0bc40ba3-eb39-457f-8aae-e7e07dae746b">

尝试finetune seaco_paraformer也报错： 
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list' 
maxlen = int(max(lengths))，打印了funasr/models/transformer/utils/nets_utils.py约两百行左右的lengths，发现其为二位列表导致报错
<img width="1390" alt="截屏2024-03-11 19 39 39" src="https://github.com/alibaba-damo-academy/FunASR/assets/37110787/91a26e14-bfbc-4c24-8ce0-e3d1f98c324c">
是不是社区开发者开发的funasr版本和funasr==1.0.14不一致导致的呢

**Comment by R1ckShi** [comment]
可以通过源代码安装，然后参考examples/industrial_data_pretraining/seaco_paraformer/finetune.py
这两个热词模型的finetune主要涉及到dataloader里面的热词筛选，在config里面配置了dataset: AudioDatasetHotword，
seaco模型需要进一步配置seaco_id: 8377
可以参考最新的模型资源：https://modelscope.cn/models/iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/file/view/master/config.yaml?status=1

**Comment by myboyliu2025** [comment]
配置seaco_id 具体如何配置，有没有相关文档？
