### ISSUE TITLE
Paraformer进行ASR的时候，测试中文场景出现大量重复性词汇！！！

### ISSUE THREAD

**Issue by jiafuz** [alibaba-damo-academy/FunASR#1476]
## 🐛 Bug

**如下，在使用如下Paraformer模型**

![image](https://github.com/alibaba-damo-academy/FunASR/assets/35124113/7540aad3-85f2-4e4d-a6ec-3b8668f0d8f2)

**对如下wav音频文件进行转录时**
[3月12日.zip](https://github.com/alibaba-damo-academy/FunASR/files/14567302/3.12.zip)

**出现了大量的重复性转录词汇（eg. 红框处所示等；而whisper并不存在此类情况），我这边采用paraformer进行转录的结果如下：**
![image](https://github.com/alibaba-damo-academy/FunASR/assets/35124113/4dd02fc7-3756-4556-8598-1e59e4641595)

### Code sample
```
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks
inference_pipeline = pipeline(
task = Tasks.auto_speech_recognition,model='iic/speech_paraformer-large-vad-punc-spk_asr_nat-zh-cn', model revision='v2.0.4',vad model='iic/speech_fsmn_vad_zh-cn-16k-common-pytorch', vad_model_revision='v2.0.4',punc_model='iic/punc_ct-transformer_zh-cn-common-vocab272727-pytorch', punc_model_revision='v2.0.4')
rec_result = inference_pipeline('path-to-your-wav-file', batch_size_s=300, batch_size_token_threshold_s=40)
print(rec_result[0]['text'])
```

### Expected behavior
同时，我测试了这段录音的whisper-largev2的asr结果，与paraformer效果对比如下（**可以发现whisper没这么多重复性的转录词汇，它似乎具备智能去重，简化，纠错和重整的功能**）
![image](https://github.com/alibaba-damo-academy/FunASR/assets/35124113/b1aa0075-1269-4a5e-8c7f-ed369c8d350e)

所以想请教以下：**对于大量有很多“结巴、口吃”的实际录音场景中，paraformer是否可以调某些参数，像whisper一样做到智能“去重，简化，纠错，重整”的功能呢？**我感觉这一点对于实际应用场景还是很重要的。

### Environment
- Ubuntu 20.04
- FunASR 1.0.10
- ModelScope 1.12.0
- PyTorch 2.0.1
- How you installed funasr (pip)
- Python 3.8.0
- GPU A40
- CUDA 11.4

**Comment by jiafuz** [comment]
所以想请教以下：**对于大量有很多“结巴、口吃”的实际录音场景中，paraformer是否可以调某些参数，像whisper一样做到智能“去重，简化，纠错，重整”的功能呢？**我感觉这一点对于实际应用场景还是很重要的。

**Comment by jiafuz** [comment]
所以想请教以下：**对于大量有很多 结巴、口吃 的实际录音场景中，paraformer是否可以调某些参数，像whisper一样做到智能“去重，简化，纠错，重整”的功能呢？** 我感觉这一点对于实际应用场景还是很重要的。

**Comment by xingchensong** [comment]
whisper能“智能”去除是因为训练数据很多是视频字幕，在训练源头就带了所谓去重的效果

**Comment by LauraGPT** [comment]
我测试了你提供的音频，paraformer的识别结果是对的，符合音频内容。音频中，说话人在重复说，导致模型输出了重复的文字，但是这个不是模型的问题，paraformer仅仅只是asr模型，功能只是把音频转文字，忠实于音频本身。至于你说的“智能”，可以通过后处理除掉。whisper是多任务模型，训练数据涵盖了这个情况，具有一定的后处理能力。

**Comment by aguang1201** [comment]
我怎么感觉这恰恰是paraformer的优点，whisper反而没有正确转录出音频的结巴文字
