### ISSUE TITLE
AttributeError: 'AutoModel' object has no attribute 'export'

### ISSUE THREAD

**Issue by ChenPengf** [alibaba-damo-academy/FunASR#1479]
## 🐛 Bug

funasr=1.0.14 : 'AutoModel' object has no attribute 'export'.
使用最新main分支源码安装版本，能够正常导出onnx模型。
最近是否会发布一个新版本到pypi仓库。

**Comment by LauraGPT** [comment]
When we finish the exporting of `SeaCo-Paraformer`, the new funasr would be release to pypi.
