### ISSUE TITLE
使用auto_model进行ASR转写特定语音的时候出现OOM

### ISSUE THREAD

**Issue by chenfuckthesky** [alibaba-damo-academy/FunASR#1484]
## 🐛 Bug
使用auto_model进行ASR转写特定语音的时候出现OOM，报错内容

`  File "/usr/local/python3/lib/python3.9/site-packages/funasr/auto/auto_model.py", line 215, in generate
    return self.inference_with_vad(input, input_len=input_len, **cfg)
  File "/usr/local/python3/lib/python3.9/site-packages/funasr/auto/auto_model.py", line 338, in inference_with_vad
    results = self.inference(speech_j, input_len=None, model=model, kwargs=kwargs, **cfg)
  File "/usr/local/python3/lib/python3.9/site-packages/funasr/auto/auto_model.py", line 248, in inference
    res = model.inference(**batch, **kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/funasr/models/seaco_paraformer/model.py", line 344, in inference
    decoder_out = self._seaco_decode_with_ASF(encoder_out, encoder_out_lens,
  File "/usr/local/python3/lib/python3.9/site-packages/funasr/models/seaco_paraformer/model.py", line 260, in _seaco_decode_with_ASF
    merged_pred = _merge_res(decoder_pred, dha_pred)
  File "/usr/local/python3/lib/python3.9/site-packages/funasr/models/seaco_paraformer/model.py", line 257, in _merge_res
    logits = dec_output * dha_mask + dha_output[:,:,:] * (1-dha_mask)
RuntimeError: CUDA out of memory. Tried to allocate 190.00 MiB (GPU 0; 15.89 GiB total capacity; 14.43 GiB already allocated; 13.88 MiB free; 14.88 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
`
调用方法：
`
model = AutoModel(model="paraformer-zh", model_revision="v2.0.4",
                  vad_model="fsmn-vad", vad_model_revision="v2.0.4",
                  punc_model="ct-punc-c", punc_model_revision="v2.0.4",
                  # spk_model="cam++", spk_model_revision="v2.0.2",                  )
result = model.generate(input=file,
            batch_size_s=150,
            hotword='地调')
`

### Environment

 - OS : Centos7.2
 - FunASR Version :1.0.14
 - ModelScope Version :1.13.0
 - PyTorch Version :1.10.2+cu111
 - How you installed funasr (`pip`, source):pip
 - Python version:3.9.5
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):12.0
 - Any other relevant information:

**Comment by chenfuckthesky** [comment]
[error.zip](https://github.com/alibaba-damo-academy/FunASR/files/14581358/error.zip)
有问题的录音文件

**Comment by LauraGPT** [comment]
You could change the `max_single_segment_time` in vad_kwargs:

https://github.com/alibaba-damo-academy/FunASR/blob/main/examples/industrial_data_pretraining/paraformer/demo.py#L12
