### ISSUE TITLE
在C++中读取token出错

### ISSUE THREAD

**Issue by OgataAsatsuki** [alibaba-damo-academy/FunASR#1490]
https://github.com/alibaba-damo-academy/FunASR/blob/5e7eb6f160c48861cbcd39825a0cb98f98538772/runtime/onnxruntime/src/vocab.cpp#L29-L44
我是用的paraformer-zh-streaming模型，代码中在YAML文件中读取token，但是config.yaml中并没有token_list，执行函数会导致vocab为空，然后在
https://github.com/alibaba-damo-academy/FunASR/blob/5e7eb6f160c48861cbcd39825a0cb98f98538772/runtime/onnxruntime/src/vocab.cpp#L156
出错

token_list应该从token.json中读取

**Comment by lyblsgo** [comment]
c++ runtime now only support model version V1.x.x, please use v1.0.6
