### ISSUE TITLE
使用speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch模型FunASR/examples/industrial_data_pretraining/seaco_paraformer/finetune_from_local.sh进行finetune报错

### ISSUE THREAD

**Issue by D1ner-che** [alibaba-damo-academy/FunASR#1491]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

### Before asking:
1. search the issues.
2. search the docs.

#### What is your question?
使用speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch模型FunASR/examples/industrial_data_pretraining/seaco_paraformer/finetune_from_local.sh进行finetune报错
![4 3HVIM(P%3GBR})MNN(J11](https://github.com/alibaba-damo-academy/FunASR/assets/77615242/4818c048-fd46-47c5-9616-37961fe95aa4)

#### Code
my finetune_from_local.sh
# Copyright FunASR (https://github.com/alibaba-damo-academy/FunASR). All Rights Reserved.
#  MIT License  (https://opensource.org/licenses/MIT)

# method2, finetune from local model

workspace=`pwd`

echo "current path: ${workspace}" # /xxxx/funasr/examples/industrial_data_pretraining/paraformer

# download model
local_path_root=${workspace}/modelscope_models
mkdir -p ${local_path_root}
local_path=${local_path_root}/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
git clone https://www.modelscope.cn/iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch.git ${local_path}

# which gpu to train or finetune
export CUDA_VISIBLE_DEVICES="0"
gpu_num=$(echo $CUDA_VISIBLE_DEVICES | awk -F "," '{print NF}')

# data dir, which contains: train.json, val.json
data_dir="../../../data/list"

train_data="${data_dir}/train.jsonl"
val_data="${data_dir}/val.jsonl"

# generate train.jsonl and val.jsonl from wav.scp and text.txt
python -m funasr.datasets.audio_datasets.scp2jsonl \
++scp_file_list='["../../../data/list/train_wav.scp", "../../../data/list/train_text.txt"]' \
++data_type_list='["source", "target"]' \
++jsonl_file_out="${train_data}"

python -m funasr.datasets.audio_datasets.scp2jsonl \
++scp_file_list='["../../../data/list/val_wav.scp", "../../../data/list/val_text.txt"]' \
++data_type_list='["source", "target"]' \
++jsonl_file_out="${val_data}"

tokens="${local_path}/tokens.json"
cmvn_file="${local_path}/am.mvn"

# output dir
output_dir="./outputs"
log_file="${output_dir}/log.txt"

config_name="config.yaml"

init_param="${local_path}/model.pt"

mkdir -p ${output_dir}
echo "log_file: ${log_file}"

torchrun \
--nnodes 1 \
--nproc_per_node ${gpu_num} \
../../../funasr/bin/train.py \
--config-path "${local_path}" \
--config-name "${config_name}" \
++train_data_set_list="${train_data}" \
++valid_data_set_list="${val_data}" \
++tokenizer_conf.token_list="${tokens}" \
++frontend_conf.cmvn_file="${cmvn_file}" \
++dataset_conf.batch_size=32 \
++dataset_conf.batch_type="example" \
++dataset_conf.num_workers=4 \
++train_conf.max_epoch=20 \
++optim_conf.lr=0.0002 \
++train_conf.log_interval=1 \
++init_param="${init_param}" \
++output_dir="${output_dir}" &> ${log_file}

#### What's your environment?

 - OS (e.g., Linux):ubuntu22.04
 - FunASR Version (e.g., 1.0.0):1.0.15
 - ModelScope Version (e.g., 1.11.0):1.13.1
 - PyTorch Version (e.g., 2.0.0):2.1.3
 - How you installed funasr (`pip`, source):pip
 - Python version:
 - GPU (e.g., V100M32)V100M32
 - CUDA/cuDNN version (e.g., cuda11.7):12.1.0
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by LauraGPT** [comment]
Ok, we would fix it soon.

**Comment by LauraGPT** [comment]
Bug has been fixed. Please ref to the docs: 
https://github.com/alibaba-damo-academy/FunASR/blob/main/docs/tutorial/README_zh.md
