### ISSUE TITLE
请教热词正确使用方法

### ISSUE THREAD

**Issue by wanghanyang123** [alibaba-damo-academy/FunASR#1499]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## ❓ Questions and Help
请教热词正确使用方法，最好能提供有效示例，

### Before asking:
1. search the issues.
2. search the docs.

#### What is your question?
不知道是不是我的使用方法有问题，最好提供热词使用方法的有效示例

#### Code

我使用了如下代码，语音识别中加入热词“胜太路”，但是识别的文字中  “生态路” 并未转换成 “胜太路”。
该语句识别结果为 

 `'text': '江宁的话我就知道这边生态路就地铁站胜态路这个大的业地。' `

from funasr import AutoModel
# paraformer-zh is a multi-functional asr model
# use vad, punc, spk or not as you need
model = AutoModel(model="paraformer-zh", model_revision="v2.0.4",
                  vad_model="fsmn-vad", vad_model_revision="v2.0.4",
                  punc_model="ct-punc-c", punc_model_revision="v2.0.4",
                  spk_model="cam++", spk_model_revision="v2.0.2",
                  )
res = model.generate(input="./20240314-test.wav", 
            batch_size_s=300, 
            hotword='胜太路')
print(res)

#### What's your environment?

 - OS (e.g., Linux): ubuntu 20.04
 - FunASR Version (e.g., 1.0.0): 1.03
 - ModelScope Version (e.g., 1.11.0):  1.11.1
 - PyTorch Version (e.g., 2.0.0): 2.2.0
 - How you installed funasr (`pip`, source): pip
 - Python version: 3.10.1
 - GPU (e.g., V100M32): Tesla T4
 - CUDA/cuDNN version (e.g., cuda11.7): 12.2
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by LauraGPT** [comment]
Hotword does not work for all the inputs.

**Comment by wwfcnu** [comment]
> Hotword does not work for all the inputs.

不支持热词吗
