### ISSUE TITLE
支持多个音频批次推理吗

### ISSUE THREAD

**Issue by tuotuoshao** [alibaba-damo-academy/FunASR#1501]
我要做并发服务的话，多个用户的多段音频同时请求，能用一个模型实例并行推理而不是一个个排队推理吗，可以的话代码该怎么写？

**Comment by LauraGPT** [comment]
www.funasr.com

**Comment by tuotuoshao** [comment]
@LauraGPT 看了使用文档都是cpu推理呀没看到gpu，我理解就是弄多个模型实例多线程。我说的是gpu推理在一个模型实例进行多批次呀，就好比图像识别，想办法让n张图的shape一致都是(1,3,h,w)，就可以进行一次推理，此时输入为(n,3,h,w)

**Comment by LauraGPT** [comment]
> @LauraGPT 看了使用文档都是cpu推理呀没看到gpu，我理解就是弄多个模型实例多线程。我说的是gpu推理在一个模型实例进行多批次呀，就好比图像识别，想办法让n张图的shape一致都是(1,3,h,w)，就可以进行一次推理，此时输入为(n,3,h,w)

You could inference with batch via pytorch, such as:  https://github.com/alibaba-damo-academy/FunASR?tab=readme-ov-file#speech-recognition-non-streaming

**Comment by tuotuoshao** [comment]
将多个音频文件作为一个list传给input，可以推理，但是推理耗时表明内部实现是一个个音频串行推理

**Comment by YuChaoM** [comment]
> 我要做并发服务的话，多个用户的多段音频同时请求，能用一个模型实例并行推理而不是一个个排队推理吗，可以的话代码该怎么写？

大佬，有解决方法吗，我也是想做成http的服务，多个请求并发进来的话同时处理，现在看到尽管是并发发起调用，但是请求是一个个处理的，显卡的利用也没拉满。

**Comment by AliceShen122** [comment]
+1

**Comment by WangFeiji0928** [comment]
佬们，有解决了这个问题的吗？

**Comment by zj1123581321** [comment]
[FunASR多段语音并行识别中的线程安全问题分析 - GitCode博客](https://blog.gitcode.com/73b6bd11dd0e3dca97ed0f76664c92c4.html)

目前我是使用多进程来解决。缺点是比较占用内存空间。

**Comment by AngGaGim** [comment]
> [FunASR多段语音识别中的线程安全问题分析 - GitCode博客](https://blog.gitcode.com/73b6bd11dd0e3dca97ed0f76664c92c4.html)
> 
> 目前我是使用多进程来解决的。缺点是占用内存空间较多。

页面挂了佬

**Comment by zj1123581321** [comment]
> > [FunASR多段语音识别中的线程安全问题分析 - GitCode博客](https://blog.gitcode.com/73b6bd11dd0e3dca97ed0f76664c92c4.html)
> > 目前我是使用多进程来解决的。缺点是占用内存空间较多。
> 
> 页面挂了佬

https://github.com/zj1123581321/funasr_spk_server

**Comment by AngGaGim** [comment]
> > > [FunASR多段语音识别中的线程安全问题分析 - GitCode博客](https://blog.gitcode.com/73b6bd11dd0e3dca97ed0f76664c92c4.html)
> > > 目前我是使用多进程来解决的。缺点是占用内存空间较多。
> > 
> > 
> > 页面挂了佬
> 
> https://github.com/zj1123581321/funasr_spk_server

我在接口处，加了个参数workers，就是太占用内存了
