### ISSUE TITLE
speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch 用onnx推理时候报错

### ISSUE THREAD

**Issue by acetotot** [alibaba-damo-academy/FunASR#1504]
#### Code
model_dir = "iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/"
model = Paraformer(model_dir, batch_size=1, quantize=True)
result = model("norm.wav")

#### What's your environment?
 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0):1.0.16
 - funasr-onnx Version：0.3.1
 - ModelScope Version (e.g., 1.11.0):1.12.0
 - PyTorch Version (e.g., 2.0.0):1.11.0
 - How you installed funasr (`pip`, source):source
 - Python version:3.8.18

报错：
return self.session.run(self.get_output_names(), input_dict)
"Required inputs (['bias_embed']) are missing from input feed (['speech', 'speech_lengths'])."

**Comment by LauraGPT** [comment]
Update the code and try it again.

**Comment by TengLi931128** [comment]
+1, same error.

funasr                 1.0.24
funasr-onnx            0.3.1

**Comment by R1ckShi** [comment]
可以在现在最新的代码中通过如下的方法导出：
```python
from funasr import AutoModel

model = AutoModel(
    model="iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch",
)

res = model.export(type="onnx", quantize=False)
print(res)
```
