### ISSUE TITLE
哪个模型能支持，传输一段录音文件，支持输出对应文本，切每段对话得时间戳范围以及说话人区分呢，比如张三 在 1-10s 说话内容是 ’xxxx‘，李四在 11-20s说话内容是’yyyyy‘

### ISSUE THREAD

**Issue by bianjie1314** [alibaba-damo-academy/FunASR#1507]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

### Before asking:
1. search the issues.
2. search the docs.

#### What's your environment?

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by LauraGPT** [comment]
All the model could be found in: https://github.com/alibaba-damo-academy/FunASR/blob/main/README_zh.md#%E6%A8%A1%E5%9E%8B%E4%BB%93%E5%BA%93

We suggest you to follow the tutorial.

**Comment by bianjie1314** [comment]
不知道怎么进行整合对应onnx，对于小白来说去看文档门槛有点高；

**Comment by bianjie1314** [comment]
像https://github.com/alibaba-damo-academy/FunASR/blob/main/runtime/docs/SDK_advanced_guide_offline_zh.md  这个在启动得适合告诉我们应该选择哪个onnx，大家就知道了有哪些onnx可以供选择得
