### ISSUE TITLE
Unexpected asr text and timestamp output for individual channels of stereo audio

### ISSUE THREAD

**Issue by jianganghan** [alibaba-damo-academy/FunASR#1509]
For a given stereo audio which has two channels, the asr result and corresponding timestamp for each individual channel is not as expected. Specifically, when taking AudioSegment tensor as input, the timestamp seems to be half of the ground truth and asr text  
does not look as normal as expected.

#### test data
[Archive.zip](https://github.com/alibaba-damo-academy/FunASR/files/14634388/Archive.zip)

#### model instance

from funasr import AutoModel
from pydub import AudioSegment

model = AutoModel(model='iic/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch', model_revision="v2.0.4",
                  vad_model='iic/speech_fsmn_vad_zh-cn-16k-common-pytorch', vad_model_revision="v2.0.4",
                  punc_model='iic/punc_ct-transformer_zh-cn-common-vocab272727-pytorch', punc_model_revision="v2.0.4",
                  sentence_timestamp=False,
                  return_raw_text=False,)

#### original stereo audio being split into left and right channel
audio_data = AudioSegment.from_file("data.mp3")
left_audio, right_audio = audio_data.split_to_mono()
left_audio.export("left.mp3", format="mp3")
right_audio.export("right.mp3", format="mp3")

#### inference with original stereo audio
res1 = model.generate(input="data.mp3",)
audio_data = AudioSegment.from_file("data.mp3")
res2 = model.generate(input=audio_data.raw_data,)

#### inference with left channel audio
res3 = model.generate(input= "left.mp3",)
left_audio = AudioSegment.from_file("left.mp3")
res4 = model.generate(input=left_audio.raw_data,)

#### inference with right channel audio
res5 = model.generate(input= "right.mp3",)
right_audio = AudioSegment.from_file("right.mp3")
res6 = model.generate(input=right_audio.raw_data,)

#### current output

res1:
'text': '哎，你好，那个大厂，咱北京换暖机片能弄吗？我去不了那边儿，我是廊坊的，嗯，哎好。', 
'timestamp': [[350, 570],..., [8800, 9040]]

res2:
'text': '唉，你好，那个大厂，咱北京或者机配能弄吗？我去不了那边儿，我是廊坊的，嗯，哎好。',
'timestamp': [[360, 600], ..., [9290, 9565]]

res3:
'text': '那个大厂保安，北京换者低配能供吗？好嘞，对。', 
'timestamp': [[2110, 2250], ..., [8800, 9295]]

res4:
'text': '这个大盘转北京或者一天能工吗？好。', 
'timestamp': [[1030, 1170], ..., [3790, 4035]]

res5:
'text': '哎，你好，我去不了那边儿，我是廊坊的嗯。', 
'timestamp': [[360, 580], ..., [8400, 8665]]

res6:
text': '还有吗？我去哪里了？我老哪里？', 
'timestamp': [[130, 250],..., [4150, 4585]]

### Expected behavior
For the original stereo audio, the inference result seems correct as expected.  The left and right channel audio, however, would only output correct results using the file directly as input. There would be wrong text and timestamps if using AudioSegment tensor as input. I tried the frequency of sampling parameter (fs), which is 8000 for original data, left and right audio, but failed to produce an normal output.

### Environment
OS: Linux
FunASR Version: 1.0.17
PyTorch Version: 1.12.0
How you installed funasr: pip
Python version: 3.9
GPU: p40
CUDA/cuDNN version: 113

**Comment by LauraGPT** [comment]
If you input a file with an audio header, it will be pre-processed internally, for example by merging channels, resampling, etc. However, if you input raw samples or PCM data without a header, there will be no internal preprocessing. In this case, you will need to preprocess the audio yourself to 16kHz sampling rate, single channel, 16 bit depth, etc.

Source code: https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/utils/load_utils.py#L37
