### ISSUE TITLE
Qwen-Audio-Chat模型不支持，tables中model_classes没有注册，是不是template.yaml文件搞错了？

### ISSUE THREAD

**Issue by bjfk2006** [alibaba-damo-academy/FunASR#1523]
-----------    ** model_classes **    --------------
| register name          | class name             | class location                                     |
| BAT                    | BAT                    | funasr/models/bat/model.py:35                      |
| BiCifParaformer        | BiCifParaformer        | funasr/models/bicif_paraformer/model.py:37         |
| Branchformer           | Branchformer           | funasr/models/branchformer/model.py:6              |
| CAMPPlus               | CAMPPlus               | funasr/models/campplus/model.py:30                 |
| CTTransformer          | CTTransformer          | funasr/models/ct_transformer/model.py:33           |
| CTTransformerStreaming | CTTransformerStreaming | funasr/models/ct_transformer_streaming/model.py:27 |
| Conformer              | Conformer              | funasr/models/conformer/model.py:8                 |
| ContextualParaformer   | ContextualParaformer   | funasr/models/contextual_paraformer/model.py:40    |
| EBranchformer          | EBranchformer          | funasr/models/e_branchformer/model.py:6            |
| Emotion2vec            | Emotion2vec            | funasr/models/emotion2vec/model.py:34              |
| FsmnVADStreaming       | FsmnVADStreaming       | funasr/models/fsmn_vad_streaming/model.py:267      |
| LCBNet                 | LCBNet                 | funasr/models/lcbnet/model.py:26                   |
| LLMASR                 | LLMASR                 | funasr/models/llm_asr/model.py:23                  |
| LLMASRNAR              | LLMASRNAR              | funasr/models/llm_asr_nar/model.py:24              |
| LLMASRNARPrompt        | LLMASRNARPrompt        | funasr/models/llm_asr_nar/model.py:353             |
| MonotonicAligner       | MonotonicAligner       | funasr/models/monotonic_aligner/model.py:24        |
| OpenAIWhisperLIDModel  | OpenAIWhisperLIDModel  | funasr/models/whisper_lid/model.py:453             |
| OpenAIWhisperModel     | OpenAIWhisperModel     | funasr/models/whisper_lid/model.py:21              |
| Paraformer             | Paraformer             | funasr/models/paraformer/model.py:27               |
| ParaformerStreaming    | ParaformerStreaming    | funasr/models/paraformer_streaming/model.py:37     |
| SANM                   | SANM                   | funasr/models/sanm/model.py:13                     |
| SCAMA                  | SCAMA                  | funasr/models/scama/model.py:38                    |
| SeacoParaformer        | SeacoParaformer        | funasr/models/seaco_paraformer/model.py:43         |
| Transducer             | Transducer             | funasr/models/transducer/model.py:34               |
| Transformer            | Transformer            | funasr/models/transformer/model.py:20              |
| UniASR                 | UniASR                 | funasr/models/uniasr/model.py:25                   |
-----------    ** predictor_classes **    --------------

**Comment by LauraGPT** [comment]
As the instruction in demo: https://github.com/alibaba-damo-academy/FunASR/blob/main/examples/industrial_data_pretraining/qwen_audio/demo_chat.py#L6

To install requirements: pip3 install -U "funasr[llm]"

**Comment by dadapaopaotangabc** [comment]
照上面安装了，所有依赖也不好使，同样的报错
