### ISSUE TITLE
推理OOM

### ISSUE THREAD

**Issue by AnsongLi** [alibaba-damo-academy/FunASR#1527]
使用modelscope里pipeline进行推理，设置那些参数可以有效减少GPU内存的使用？
model = Model.from_pretrained('/model/speech_paraformer-large-vad-punc-spk_asr_nat-zh-cn')
inference_pipeline = pipeline(
task=Tasks.auto_speech_recognition,
model=model
            )
inference_pipeline(audio_in=wav_path, batch_size_s=300, batch_size_token_threshold_s=40)

**Comment by LauraGPT** [comment]
Ref to: https://github.com/alibaba-damo-academy/FunASR/blob/main/docs/tutorial/README_zh.md#%E9%9D%9E%E5%AE%9E%E6%97%B6%E8%AF%AD%E9%9F%B3%E8%AF%86%E5%88%AB
