### ISSUE TITLE
请问FunASR的非实时本地推理，能否输出每条语音推理的置信度？

### ISSUE THREAD

**Issue by colstone** [alibaba-damo-academy/FunASR#1529]
现在正在缝合[qiuqiao/SOFA](https://github.com/qiuqiao/SOFA)来做自动化的音素标注推理，需要一个置信度用来判断最终的音素标注准确率，目前sofa能提供置信度，所以我来问问funasr是否能够输出置信度信息。

**Comment by LauraGPT** [comment]
Source code is open, debug is all you need.
