### ISSUE TITLE
assert x.size(2) == self.size AssertionError

### ISSUE THREAD

**Issue by LRY1994** [alibaba-damo-academy/FunASR#1530]
https://github.com/alibaba-damo-academy/FunASR/issues/1478
https://www.modelscope.cn/models/dengcunqin/speech_paraformer-large_asr_nat-zh-cantonese-en-16k-vocab8501-online/summary
model_name_or_model_dir="dengcunqin/speech_paraformer-large_asr_nat-zh-cantonese-en-16k-vocab8501-online"
model_revision="master"
torchrun \
    --nnodes 1 \
    --nproc_per_node ${gpu_num} \
    funasr/bin/train.py \
    ++model="${model_name_or_model_dir}" \
    ++model_revision="${model_revision}" \
    ++train_data_set_list="${train_data}" \
    ++valid_data_set_list="${val_data}" \
    ++dataset_conf.batch_size=64 \
    ++dataset_conf.batch_type="token" \
    ++dataset_conf.num_workers=4 \
    ++train_conf.max_epoch=50 \
    ++train_conf.log_interval=1 \
    ++train_conf.resume=true \
    ++train_conf.validate_interval=2000 \
    ++train_conf.save_checkpoint_interval=2000 \
    ++train_conf.keep_nbest_models=20 \
    ++optim_conf.lr=0.0002 \
    ++output_dir="${output_dir}" &> ${log_file}

我已经git pull更新了，finetune还是出现这个错误

return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
File "/data/linry/anaconda3/envs/asr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "/data/linry/FunASR/funasr/models/paraformer_streaming/model.py", line 120, in forward
loss_att, acc_att, cer_att, wer_att, loss_pre, pre_loss_att = self._calc_att_predictor_loss(
File "/data/linry/FunASR/funasr/models/paraformer_streaming/model.py", line 259, in _calc_att_predictor_loss
loss_att = self.criterion_att(decoder_out, ys_pad)
File "/data/linry/anaconda3/envs/asr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "/data/linry/FunASR/funasr/losses/label_smoothing_loss.py", line 51, in forward
assert x.size(2) == self.size
AssertionError

x.size(2) is 512, self.size is 8501

**Comment by LauraGPT** [comment]
git pull 
pip install -e ./

**Comment by R1ckShi** [comment]
这是用户提供的模型，config中的相关参数我们不保证是对的
这个原因看起来像是decoder内部少了一个输出层，所以没有把隐层维度转为8501
