### ISSUE TITLE
打包成exe执行的时候报错缺少文件或文件夹'C:\\Users\\82437\lAppData\\Locall\\Temp\\ MEI32122\lfuasr\\version.txt'

### ISSUE THREAD

**Issue by eugeneYz** [alibaba-damo-academy/FunASR#1531]
## 🐛 Bug

python程序 pycharm直接运行没问题，用pyinstaller打包了之后运行exe 报错缺少这个文件。

使用pipeline，   task='speaker-verification', 
模型：speech_campplus_sv_zh-cn_16k-common'
funasr版本：1.0.14
modelscope版本：1.13.1

![38782d9a69ec7ebf38a6d2d22414382](https://github.com/alibaba-damo-academy/3D-Speaker/assets/80690882/8a5e6be0-2b78-4b65-8e02-c85f7879f9a9)

**Comment by LauraGPT** [comment]
Ref to https://github.com/alibaba-damo-academy/FunASR/discussions/1549
