### ISSUE TITLE
我按照文档全部安装成功了环境，我的电脑没有N显卡，但是在运行 下面这段代码from funasr import AutoModel  model = AutoModel(model="paraformer-zh",model_path='')  res = model.generate(input="https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/vad_example.wav") print(res) 抛出异常ModuleNotFoundError: No module named 'torch' 请问这是什么情况 

### ISSUE THREAD

**Issue by anstonjie** [alibaba-damo-academy/FunASR#1533]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## 🐛 Bug

ModuleNotFoundError: No module named 'torch' 

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run py test.py
   from funasr import AutoModel

model = AutoModel(model="paraformer-zh",model_path='')

res = model.generate(input="https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/vad_example.wav")
print(res)

2. See error

ModuleNotFoundError: No module named 'torch' 

### Environment

 - OS (e.g., windows):
 - FunASR Version 最新的版本从github上3月24号下载的
 - ModelScope Version 无
 - PyTorch Version (e.g., 2.0.0): 
 - How you installed funasr (`pip`, source):
 - Python version: 3.11.8

 - CUDA/cuDNN version 无
 -
 - Any other relevant information:

**Comment by LauraGPT** [comment]
pip install torch aorchaudio
