### ISSUE TITLE
Seaco-paraformer进行finetune时，单卡没有问题，跑多卡时卡住不动

### ISSUE THREAD

**Issue by wjyfelicity** [alibaba-damo-academy/FunASR#1539]
环境安装：​
python==3.8.10
torch==2.0.1
funasr==1.0.18​
modelscope==1.13.2
使用模型：​
[[https://www.modelscope.cn/models/damo/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/summary]]
参考示例：​
[[https://github.com/alibaba-damo-academy/FunASR/blob/5e7eb6f160c48861cbcd39825a0cb98f98538772/examples/industrial_data_pretraining/seaco_paraformer/finetune.sh]​]
将FunASR-main/funasr/bin/train.py的第105行的"find_unused_parameters"的False改成True，不然会报错
代码修改将GPU卡设置成4卡
export CUDA_VISIBLE_DEVICES="0,1,2,3"

完整错误：​
跑到1106step就卡住不动了，4个GPU利用率均为100%
![20240325-172527](https://github.com/alibaba-damo-academy/FunASR/assets/24841439/a0eae7d5-4e1b-4399-bed9-016cfba1fef7)

**Comment by LauraGPT** [comment]
Update funasr and try it again.
