### ISSUE TITLE
The model's quickstart document needs to update

### ISSUE THREAD

**Issue by fangd123** [alibaba-damo-academy/FunASR#154]
The model `speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch` , if I follow it's quickstart document, it will report error.

Finally, I found that for the version of `funasr(0.2.1)` and `modelscope(1.3.0)`, it should use the code as follows:

```python
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks
inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model='damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch',
    model_revision="v1.2.1",
    vad_model='damo/speech_fsmn_vad_zh-cn-16k-common-pytorch',
    vad_model_revision="v1.1.8",
    punc_model='damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch',
    punc_model_revision="v1.1.6",
)
result = inference_pipeline('http://www.modelscope.cn/api/v1/models/damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/repo?Revision=master\u0026FilePath=example/asr_example.wav',)
print(result)
```

Please update the document.

**Comment by langgz** [comment]
The quickstart docs are generated automatically by modelscope, we could not change them. Usually, you could follow the quickstart to run the pipeline. However, we introduced a bug of vad model in modelscope-1.3.0, and this is the reason you run in error. For the  moment, you could run the pipeline with the pipeline above, until to modelscope-1.3.1 on 2023/03/01. In modelscope-1.3.1, you could run the pipeline follow the  quickstart docs without erros.
