### ISSUE TITLE
测试funasr的parafomerm模型在aishell数据集上测试CER

### ISSUE THREAD

**Issue by wenjiwei** [alibaba-damo-academy/FunASR#1541]
准备根据examples/aishell/paraformer/run.sh文件测试得到CER指标，但是发现代码中似乎都是写的计算WER，对于中文语音一般测试的指标都是CER，请问在中文语音识别中，在数据集上测试得出的WER指标是不是就是等同于CER指标。
![Uploading {62B2EB8B-C27C-4900-9848-806136E880F7}.png…]()

**Comment by LauraGPT** [comment]
Yes, but wo suggest you ref to chatgpt for such questions.
