### ISSUE TITLE
离线下载模型后，使用Automodel加载模型，仍然需要连接网络

### ISSUE THREAD

**Issue by EasilyGoDie** [alibaba-damo-academy/FunASR#1581]
版本 funasr==1.0.0, modelscope == 1.10.0
看了代码，虽然模型已经下载了，但仍然需要从download_model函数那里获得模型参数。

**Comment by LauraGPT** [comment]
https://github.com/alibaba-damo-academy/FunASR/blob/main/examples/README_zh.md#automodel-%E5%AE%9A%E4%B9%89

**Comment by EasilyGoDie** [comment]
> https://github.com/alibaba-damo-academy/FunASR/blob/main/examples/README_zh.md#automodel-%E5%AE%9A%E4%B9%89

应该支持默认的参数。
