### ISSUE TITLE
按照如下方式更新funasr后，依然报错 cannot import name 'asr_utils' from 'funasr.utils'

### ISSUE THREAD

**Issue by ridiculers** [alibaba-damo-academy/FunASR#1583]
需要更新funasr1.0，
更新方法：
git clone -b main --single-branch https://github.com/alibaba-damo-academy/FunASR.git && cd FunASR
pip install -e ./

新的用法：
https://github.com/alibaba-damo-academy/FunASR?tab=readme-ov-file#quick-start

_Originally posted by @LauraGPT in https://github.com/alibaba-damo-academy/FunASR/issues/1262#issuecomment-1895758777_

![Uploading image.png…]()

**Comment by ridiculers** [comment]
Environment OS (e.g., Linux): Ubuntu 22.04
FunASR Version (e.g., 1.0.0): main 1.0.20
ModelScope Version (e.., 1.11.0):1.4.1
PyTorch Version (e.g., 2.0.0): 2.0.0
Python version: 3.10.9
GPU : 3080TI
CUDA/cuDNN version (e.g., cuda11.7): 12.4

**Comment by LauraGPT** [comment]
> Environment OS (e.g., Linux): Ubuntu 22.04 FunASR Version (e.g., 1.0.0): main 1.0.20 ModelScope Version (e.., 1.11.0):1.4.1 PyTorch Version (e.g., 2.0.0): 2.0.0 Python version: 3.10.9 GPU : 3080TI CUDA/cuDNN version (e.g., cuda11.7): 12.4

```shell
pip install -U funasr modelscope
```

Usage is [here](https://github.com/alibaba-damo-academy/FunASR/tree/main/examples)

**Comment by ridiculers** [comment]
> > Environment OS (e.g., Linux): Ubuntu 22.04 FunASR Version (e.g., 1.0.0): main 1.0.20 ModelScope Version (e.., 1.11.0):1.4.1 PyTorch Version (e.g., 2.0.0): 2.0.0 Python version: 3.10.9 GPU : 3080TI CUDA/cuDNN version (e.g., cuda11.7): 12.4
> 
> ```shell
> pip install -U funasr modelscope
> ```
> 
> Usage is [here](https://github.com/alibaba-damo-academy/FunASR/tree/main/examples)

Thank you!
