### ISSUE TITLE
TypeError: 'list' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by lonngxiang** [alibaba-damo-academy/FunASR#1588]
```
from funasr import AutoModel
# paraformer-zh is a multi-functional asr model
# use vad, punc, spk or not as you need
model = AutoModel(model="paraformer-zh",  vad_model="fsmn-vad",  punc_model="ct-punc", 
                  # spk_model="cam++", 
                  )
res = model.generate(input=f"{model.model_path}/example/asr_example.wav", 
                     batch_size_s=300, 
                     hotword='魔搭')
print(res)
```
用的这个音频
[ezyzip·.zip](https://github.com/alibaba-damo-academy/FunASR/files/14895601/ezyzip.zip)

![image](https://github.com/alibaba-damo-academy/FunASR/assets/40717349/ab9e6de6-ea28-4fd4-9302-079f402d8deb)

**Comment by ArboterJams** [comment]
是什么原因啊，我也遇到了这个问题。

**Comment by R1ckShi** [comment]
fixed, please pull the latest code

**Comment by lonngxiang** [comment]
> fixed, please pull the latest code

重启pip 安装funasr吗？

**Comment by R1ckShi** [comment]
> > fixed, please pull the latest code
> 
> 重启pip 安装funasr吗？

这种即时修复的问题只能通过源码安装，clone funasr仓库，pip install -e ./
pip安装的方式需要等funasr在pypi上发版才可以

**Comment by lonngxiang** [comment]
> > > fixed, please pull the latest code
> > 
> > 
> > 重启pip 安装funasr吗？
> 
> 这种即时修复的问题只能通过源码安装，clone funasr仓库，pip install -e ./ pip安装的方式需要等funasr在pypi上发版才可以

好的，辛苦了
