### ISSUE TITLE
KeyError: 'asr-inference is not in the pipelines registry group auto-speech-recognition. Please make sure the correct version of ModelScope library is used.'

### ISSUE THREAD

**Issue by suyufan** [alibaba-damo-academy/FunASR#1595]
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model='damo/speech_UniASR_asr_2pass-cn-dialect-16k-vocab8358-tensorflow1-offline',
    output_dir='./output_dir'
)

rec_result = inference_pipeline(audio_in='asr_example_zh.wav')
print(rec_result)

### Environment
 - FunASR Version (e.g., 1.0.0):   1.0.20 
 - ModelScope Version (e.g., 1.11.0):   1.12.0
 - How you installed funasr (`pip`, source):  pip
 - Python version:   3.9

**Comment by suyufan** [comment]
- 试过降低modelscope版本为1.8.0
- 推理方式改为FunASR，报错TypeError: ‘NoneType’ object is not callable
- 使用FunASR推理其他模型，可以成功
- 使用ModelScope推理其他模型，可以成功
- 参考文档https://alibaba-damo-academy.github.io/FunASR/en/egs_modelscope/asr/TEMPLATE/README_zh.html中UniASR的使用示例，报错KeyError: 'asr-inference is not in the pipelines registry group auto-speech-recognition.
- 求助：是UniASR模型的问题 还是 我的环境配置 有误

补充环境信息：
Unbuntu
tensorflow  2.4.1
torch  2.2.2
cuda  11.7

**Comment by R1ckShi** [comment]
贴一下通过funasr推理时typeerror的详细信息吗，现在主要维护的是funasr的推理方式

**Comment by LauraGPT** [comment]
uniasr模型不在维护，如果想使用，请降低版本：
```shell
funasr-0.8.8
modelscope-1.10.0
```
同时模型，删除，让它自动下载，不指定任何model_revision

**Comment by Raven528** [comment]
同时，如果是在funasr项目下跑脚本，注意是不是引用了funasr自带的版本。
![image](https://github.com/alibaba-damo-academy/FunASR/assets/66229704/fb5158f8-6b1e-4e80-a239-5f1419683ce7)

**Comment by MonolithFoundation** [comment]
能否升级一下模型，而非强制用低版本的modelscope？
