### ISSUE TITLE
ASR batch推理时能否支持标点？

### ISSUE THREAD

**Issue by wincing2** [alibaba-damo-academy/FunASR#1601]
使用FunASR-main/examples/industrial_data_pretraining/paraformer/infer.sh进行batch推理时的结果没有标点。加了punc_model后再运行则提示batch size只能为1。能否在batch size大于1的情况下支持标点的输出？

**Comment by LauraGPT** [comment]
https://github.com/alibaba-damo-academy/FunASR/blob/main/examples/README_zh.md#%E9%9D%9E%E5%AE%9E%E6%97%B6%E8%AF%AD%E9%9F%B3%E8%AF%86%E5%88%AB
