### ISSUE TITLE
用最新的版本，会出现NameError: name 'ClusterBackend' is not defined 报错

### ISSUE THREAD

**Issue by eleven-monkey** [alibaba-damo-academy/FunASR#1603]
我在colab上使用funasr,基本上每天都会使用，每次使用时都是通过git clone 克隆最新的文件，但是昨天使用funasr进行语音识别时，没有成功，出现报错：
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-93753e28cf49> in <cell line: 5>()
      3 # paraformer-zh is a multi-functional asr model
      4 # use vad, punc, spk or not as you need
----> 5 model = AutoModel(model="paraformer-zh", model_revision="v2.0.4",
      6                   vad_model="fsmn-vad", vad_model_revision="v2.0.4",
      7                   punc_model="ct-punc-c", punc_model_revision="v2.0.4",

/content/FunASR/funasr/auto/auto_model.py in __init__(self, **kwargs)
    135             spk_kwargs["device"] = kwargs["device"]
    136             spk_model, spk_kwargs = self.build_model(**spk_kwargs)
--> 137             self.cb_model = ClusterBackend().to(kwargs["device"])
    138             spk_mode = kwargs.get("spk_mode", 'punc_segment')
    139             if spk_mode not in ["default", "vad_segment", "punc_segment"]:

NameError: name 'ClusterBackend' is not defined

后来，我用git checkout 命令切换到之前的提交：54af9b7841235c60d3dbe8622910b1a26fe91bd8。就又可以使用了。应该是更新后引入了新的bug。

**Comment by hello989898** [comment]
我也碰到同样的问题

**Comment by eleven-monkey** [comment]
今天去掉checkout使用最新的提交，仍然有这个报错。希望能够修复一下。让我们能够使用到最新的更新，谢谢。

**Comment by R1ckShi** [comment]
最新的代码应该没有这个问题了，如果有的话可以考虑重新安装你的python环境，因为它可能是依赖错误导致的：）

**Comment by chendoit** [comment]
用最新的版本
model = AutoModel(model="paraformer-zh",  
                  vad_model="fsmn-vad", 
                  vad_kwargs={"max_single_segment_time": 60000},
                  punc_model="ct-punc", 
#                   spk_model="cam++"
                  ) 
在打開spk_model 後 還會遇到這個問題

**Comment by R1ckShi** [comment]
可以重新安装一下python环境，使用最新的requirments一键安装

**Comment by polarisGitHub** [comment]
新环境，遇到同样问题

**Comment by haoren110147** [comment]
注意注意！我也遇到了 'ClusterBackend' is not defined的问题，升级python版本以及modelscope和funasr版本都不管用，因为是说话人spk模型的加载出了问题，我就去https://www.modelscope.cn/models/iic/speech_campplus_sv_zh-cn_16k-common/file/view/master?fileName=requirements.txt&status=1 这个模型仓库的requirements.txt文件中查看依赖，要求scikit-learn>=1.3.2，然后我本地的scikit-learn的版本是0.24.2，我升级scikit-learn==1.3.2就解决了

**Comment by hsw409328** [comment]
pip install scikit-learn==1.3.2  需要指定为1.3.2版本。我用最新1.6.0和1.3.0都有问题。
另外更新： pip install -U  pyparsing 要求大于2.3.1版本，默认更新完是pyparsing    3.2.1。
目前正常了。
