### ISSUE TITLE
重新开启服务端后发现客户端无法正常连接

### ISSUE THREAD

**Issue by wenjiwei** [alibaba-damo-academy/FunASR#1607]
按照https://github.com/alibaba-damo-academy/FunASR/blob/main/runtime/docs/SDK_advanced_guide_online_zh.md在同一台主机上部署实时语音识别的服务端和客户端，部署后第一次测试成功，客户端可以连接上服务端并返回识别结果。但是使用命令ps -x | grep funasr-wss-server-2pass \kill -9 PID查询并关闭服务端后，再使用命令nohup bash run_server_2pass.sh \
  --model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx \
  --online-model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx \
  --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx \
  --punc-dir damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727-onnx \
  --lm-dir damo/speech_ngram_lm_zh-cn-ai-wesp-fst \
  --itn-dir thuduj12/fst_itn_zh \
  --certfile  ../../../ssl_key/server.crt \
  --keyfile ../../../ssl_key/server.key \
  --hotword ../../hotwords.txt > log.txt 2>&1 &
重新开启服务端后发现客户端无法正常连接上，但是过一段时间，大概一个多小时后又能正常连接上。请问这是什么原因导致的呢？

**Comment by lyblsgo** [comment]
The model is loaded when the server starts. When the client connects, it needs to verify that the server has completed its startup.
if the issue persists, you can reopen the issue.
