### ISSUE TITLE
finetune训练多轮后，推理含英文的音频结果为空

### ISSUE THREAD

**Issue by WjMessi1** [alibaba-damo-academy/FunASR#1612]
## ❓ Questions and Help
我以iic/speech_paraformer_asr_nat-zh-cn-8k-common-vocab8358-tensorflow1模型为基础，进行finetune训练。训练到model.pt.ep0.10000，此时所有的音频均可推理，并且可以得到比较准确的结果。

但是从model.pt.ep0之后，逐渐开始对于一些包含wifi，KD，IP，APP，NBA等英文字母的音频，推理出的结果为空（到model.pt.ep1之后，包含英文的音频全部推理结果为空），而对于全中文的音频，识别结果很准确。这种情况是逐步出现的。我检查了train数据集中的label数据没问题。

![image](https://github.com/alibaba-damo-academy/FunASR/assets/87363191/1c88c484-6206-4ec7-ae1f-fd27e7769220)

我对onnx模型的推理代码进行单步调试，发现对于可以推理英文音频的模型与不可以推理的模型，推理同一条音频时，在这一步两者有些区别，提取的特征feats与feats_len都是一样的，但是output不同。在paraformer_bin.py文件中

![image](https://github.com/alibaba-damo-academy/FunASR/assets/87363191/7f69bc45-a9fe-40db-a0d4-33fd1940bb61)

![image](https://github.com/alibaba-damo-academy/FunASR/assets/87363191/d81d5c09-be7e-4ed6-b50b-b8b0642eb4bc)

请问是我finetune训练的问题吗？这是我finetune训练的参数，感觉有可能是当前版本的funasr在处理数据集时，把包含英文的音频的label删除掉了，导致finetune训练后的模型出现这样的问题，下面是我的finetune参数：

torchrun \
--nnodes 1 \
--node_rank 0 \
--nproc_per_node ${gpu_num} \
funasr/bin/train.py \
++model="${model_name_or_model_dir}" \
++train_data_set_list="${train_data}" \
++valid_data_set_list="${val_data}" \
++dataset_conf.batch_size=20000 \
++dataset_conf.batch_type="token" \
++dataset_conf.num_workers=4 \
++train_conf.max_epoch=50 \
++train_conf.log_interval=20 \
++train_conf.resume=true \
++train_conf.validate_interval=2000 \
++train_conf.save_checkpoint_interval=2000 \
++train_conf.keep_nbest_models=8 \
++train_conf.avg_nbest_model=5 \
++optim_conf.lr=0.0002 \
++output_dir="${output_dir}" &> ${log_file}

#### What's your environment?
FunASR Version (1.0.22):
ModelScope Version (1.13.3):
PyTorch Version (2.2.0):
How you installed funasr (source):
Python version: 3.8
GPU (A100)

**Comment by WjMessi1** [comment]
我发现了问题。当前版本的funasr在处理训练集时，对于包含英文音频的label，程序会处理成乱码或者是tokens的结尾符"<unk>"，导致finetune训练后的模型对于包含英文的音频推理结果为空。

比如对于某音频
正确的label是：这个应该是就是目前来说的话IPTV的话是还是要另外付费的
当前funasr在训练时处理成："<unk>"或者是“嗯支好帐思一三三多物”

请问这个问题是不是我设置的finetune参数有问题，或者是config.yaml中的某个参数我没有修改正确？

**Comment by WjMessi1** [comment]
补充：
调试发现是encoder的原因：
![image](https://github.com/alibaba-damo-academy/FunASR/assets/87363191/76c2f9c7-7de5-4a88-abf0-ad7309b698fa)
<img width="449" alt="d408a54611eac6905c6e7161037130e" src="https://github.com/alibaba-damo-academy/FunASR/assets/87363191/91baa832-56ba-4665-8429-eda2b195123b">

是否与config.yaml中的tokenizer: CharTokenizer参数相关

**Comment by LauraGPT** [comment]
I have tested it. We would fix it soon.

**Comment by LauraGPT** [comment]
Bugfix: https://github.com/alibaba-damo-academy/FunASR/blob/90bc3ad02eee3745188be3960036ae3e9e746049/funasr/tokenizer/char_tokenizer.py#L97
