### ISSUE TITLE
中文都支持哪些方言

### ISSUE THREAD

**Issue by jianking123** [alibaba-damo-academy/FunASR#1614]
请问中文都支持哪些方言

**Comment by bird-9** [comment]
mark

**Comment by tramphero** [comment]
支持吴语、闽南语、东北话、甘肃话、贵州话、河南话、湖北话、湖南话、宁夏话、山西话、陕西话、山东话、四川话、天津话的方言口音识别，但是由于训练数据量比较有限，具体效果需要结合自己的场景进行评估，看看是否满足要求。

**Comment by hildazzz** [comment]
> 支持吴语、闽南语、东北话、甘肃话、贵州话、河南话、湖北话、湖南话、宁夏话、山西话、陕西话、山东话、四川话、天津话的方言口音识别，但是由于训练数据量比较有限，具体效果需要结合自己的场景进行评估，看看是否满足要求。

请问需要指定模型是闽南语那个吗？还是默认以下？
`model = AutoModel(model="paraformer-zh", vad_model="fsmn-vad", punc_model="ct-punc", device=device,
                  # spk_model="cam++", 
                  )
`

**Comment by yumianhuli1** [comment]
> > 支持吴语、闽南语、东北话、甘肃话、贵州话、河南话、湖北话、湖南话、宁夏话、山西话、陕西话、山东话、四川话、天津话的方言口音识别，但是由于训练数据量比较有限，具体效果需要结合自己的场景进行评估，看看是否满足要求。
> 
> 请问需要指定模型是闽南语那个吗？还是默认以下？ `model = AutoModel(model="paraformer-zh", vad_model="fsmn-vad", punc_model="ct-punc", device=device, # spk_model="cam++", ) `

顶

**Comment by KongNan** [comment]
> 山东话

求助能否给出一段能在现有FunASR上执行的代码片段，谢谢您！
