### ISSUE TITLE
utils/misc.py里面的deep_update方法感觉有问题

### ISSUE THREAD

**Issue by r00mz** [alibaba-damo-academy/FunASR#1622]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## 🐛 Bug

如果传入的参数是一个空的字典，那么递归的时候这个参数不会生效。

例如参考/runtime/python/websocket/funasr_wss_server.py 
segments_result = model_vad.generate(input=audio_in, **websocket.status_dict_vad)[0]["value"]

设置websocket.status_dict_vad = {'cache': {}, "is_final": False}
cache并不会成功设置成{}

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd '....'
2. See error

### Environment

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.9):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by LauraGPT** [comment]
Bugfix: https://github.com/alibaba-damo-academy/FunASR/commit/e8f80e96f99cb856423d030c7d055c302a6d3278
