### ISSUE TITLE
多次调用出现大量重复

### ISSUE THREAD

**Issue by ChenjieXu** [alibaba-damo-academy/FunASR#1628]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## 🐛 Bug

多次调用出现大量词汇重复，第一次运行就没问题。

### To Reproduce
运行第二次就可以得到
![image](https://github.com/alibaba-damo-academy/FunASR/assets/31937673/4b3a18a7-9833-42c6-8905-570406441d3a)

1. Run cmd '....'
2. See error

### Environment

 - OS (e.g., Linux):centos
 - FunASR Version (e.g., 1.0.0):1.0.23
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):2.2.0
 - How you installed funasr (`pip`, source):pip
 - Python version:3.10
 - GPU (e.g., V100M32) 3090
 - CUDA/cuDNN version (e.g., cuda11.7):12.1
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by LauraGPT** [comment]
Bugfix: https://github.com/alibaba-damo-academy/FunASR/issues/1622
Please update funasr and try it again.

**Comment by ChenjieXu** [comment]
> Bugfix: #1622 Please update funasr and try it again.

你好，更新完之后，还是相同的问题

**Comment by ChenjieXu** [comment]
我怀疑是环境的问题，和cuda有关。
