### ISSUE TITLE
paraformer-online模型和funasr的在线服务测试结果不一致

### ISSUE THREAD

**Issue by wwfcnu** [alibaba-damo-academy/FunASR#1630]
直接通过modelscope库，测试paraformer-online 模型的结果和通过funasr在线服务（mode=online）测试的结果不一样，
funasr的结果是要比前者好的，这是为什么，funasr的在线服务用的模型也是paraformer-online 呀

**Comment by LauraGPT** [comment]
Please check the differences of config

**Comment by wwfcnu** [comment]
是不是funasr的在线docker服务对结果做了后处理

**Comment by wwfcnu** [comment]
> It is a bug. Please update funasr and use the `AutoModel`
改成fuansr的Automodel，结果就和在线服务对齐了
