### ISSUE TITLE
实时转写docker服务中的标点预测能否设置为关闭？

### ISSUE THREAD

**Issue by 184653090** [alibaba-damo-academy/FunASR#1636]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

### Before asking:
1. search the issues.
2. search the docs.

#### What is your question?
目前在使用FunASR的实时语音听写服务，文字识别比较准确，但是标点预测不太符合期望，请问能否关闭docker中的标点预测。

 - Docker version (funasr-runtime-sdk-online-cpu-0.1.6)

**Comment by lyblsgo** [comment]
set: --punc-dir ""

**Comment by 184653090** [comment]
按该参数启动服务后，不能返回文字了。
![Uploading f6da3f62eb50b000ec50a433be457d3.png…]()
