### ISSUE TITLE
内存溢出

### ISSUE THREAD

**Issue by huangdadahai2015** [alibaba-damo-academy/FunASR#1642]
## ❓ Questions and Help
内存溢出，当部署完在线识别服务器之后，进行语音识别（启用热词的情况下），内存占用增长特快，

#### What's your environment?

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.9):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (docker):
 - Docker version (e.g., funasr-runtime-sdk-cpu-online-1.0.9)

**Comment by LauraGPT** [comment]
Please raise issues follow the template.
