### ISSUE TITLE
runtime docker部署里的所有模型版本已经写死，不支持指定版本

### ISSUE THREAD

**Issue by juzstu** [alibaba-damo-academy/FunASR#1644]
我线下用最新的模型训练好替换官方的模型，但docker启动后仍然下载已经写死版本的模型并覆盖了我的模型，请问下这个能支持自定义吗？
在 FunASR/runtime/websocket/bin/funasr-wss-server.cpp 和  FunASR/runtime/websocket/bin/funasr-wss-server-2pass.cpp 中模型指定版本均已写死，如下所示。
`TCLAP::ValueArg<std::string> model_revision(
        "", "model-revision",
        "ASR model revision",
        false, "v1.2.1", "string");`

**Comment by lyblsgo** [comment]
不支持自定义模型版本，因为c++ runtime支持的模型种类与版本与python 不一致
