### ISSUE TITLE
推理的音频中包含"@"时，出现bug：ValueError: invalid character: @

### ISSUE THREAD

**Issue by WjMessi1** [alibaba-damo-academy/FunASR#1671]
## 🐛 Bug
测试自己fintune训练得到的模型，在onnx推理时，当推理的测试音频中包含“@”时，有报错

<img width="453" alt="1b1441daa030b98561765f59130cc8a" src="https://github.com/alibaba-damo-academy/FunASR/assets/87363191/3a10057a-7a14-40c6-bb61-bd8a85ab2423">

经过调试定位到这个地方无法处理“@”字符，请问自己fintune训练时，对于@可以标注为@吗？（我目前是这样做的）我看官方推理的结果是“艾特”

<img width="373" alt="53169100b033ed0fb46da04418685d8" src="https://github.com/alibaba-damo-academy/FunASR/assets/87363191/edb1acbe-cfcb-49cd-bd4d-a5943ad00ffd">

 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.25):

**Comment by LauraGPT** [comment]
@为特殊token，确实无法处理，训练时候需要处理成`艾特`
