### ISSUE TITLE
同一mp4重复运行，spk结果不一样

### ISSUE THREAD

**Issue by GioGioBond** [alibaba-damo-academy/FunASR#1677]
#### 
下图中，左边是第一次结果，右边是第二次结果，虚线隔开的spk不一样
![1](https://github.com/alibaba-damo-academy/FunASR/assets/39087265/08a13a97-f082-43d7-abd5-cd6247ffb99c)

####环境如下

 - Ubuntu 20.04.5
 - FunASR 1.0.22
 - PyTorch 2.2.2
 - pip 安装funasr
 - Python 3.8.19
 - GPU (V100
 - CUDA/cuDNN 11.8

**Comment by LauraGPT** [comment]
Please update you mp4
