### ISSUE TITLE
speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch  这个模型识别中文乱码

### ISSUE THREAD

**Issue by likaiqiang** [alibaba-damo-academy/FunASR#1687]
```python
from funasr import AutoModel
path_asr = '/kaggle/input/models/models/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch'
path_vad = '/kaggle/input/models/models/speech_fsmn_vad_zh-cn-16k-common-pytorch'
path_punc = '/kaggle/input/models/models/punc_ct-transformer_zh-cn-common-vocab272727-pytorch'


model = AutoModel(
    model=path_asr,
    model_revision="v2.0.4",
    vad_model=path_vad,
    vad_model_revision="v2.0.4",
    punc_model=path_punc,
    punc_model_revision="v2.0.4",
)

text = model.generate(input="/kaggle/input/music123/output.wav")[0]["text"]
print(text)
```
鲽郭卅曳赋痨，旌calskprice倢榄buy垤荞蹿坤邦，淠吭姘寸饥吩楷怎送易甑滴，缒得芒栾携锶曡睬埔尤涖traburly go篪糜启嫂渫found牵唧瘙茁，考俭欠猿癍吝虺屠ly杮淘哝橡披姊楷栗孙忸folfacproduct7懦菜锶烟敲。

**Comment by AIDeepx** [comment]
请问这个如何解决的呢？

**Comment by likaiqiang** [comment]
好像是，我系统的编码设置有问题

**Comment by AIDeepx** [comment]
你的报错存在这个问题吗？
```bash
error, init_param does not exist!: ./outputs\model.pb
```

**Comment by likaiqiang** [comment]
> 你的报错存在这个问题吗？
> 
> ```shell
> error, init_param does not exist!: ./outputs\model.pb
> ```

https://github.com/modelscope/FunASR/blob/c761f3543ed45b6c5b7cc3b7310b1f3718c2664c/funasr/auto/auto_model.py#L232
看起来像是./outputs\model.pb 这个文件不存在，或者你的路径拼的有问题

**Comment by AIDeepx** [comment]
模型跑成功了，但是返回的是个空切片
![微信图片_20240614174050](https://github.com/modelscope/FunASR/assets/20198428/d84cb76e-3294-4813-a74b-07b6202f36d9)

**Comment by likaiqiang** [comment]
![image](https://github.com/modelscope/FunASR/assets/14501725/2eb90003-c993-4fd2-8989-cf04c2075a39)
我用官方的例子试一下，是好的
