### ISSUE TITLE
FunASR要怎么结合说话人日志模型进行部署

### ISSUE THREAD

**Issue by lmxin123** [alibaba-damo-academy/FunASR#1688]
我看3d-speaker已经支持C++了
![image](https://github.com/alibaba-damo-academy/FunASR/assets/12029452/b6d335c3-7c6e-42a4-a4cb-85ce9792176b)
请要funasr要怎么才能使用说话人日志模型，没找到有对应参数传入这个模型。
或者结合这个模型使用[iic/speech_campplus_speaker-diarization_common](https://www.modelscope.cn/models/iic/speech_campplus_speaker-diarization_common/files)

**Comment by LauraGPT** [comment]
On the way

**Comment by lmxin123** [comment]
> On the way
好的，多谢，请问大概是什么时候支持呢
