### ISSUE TITLE
文档中热词部分不明确

### ISSUE THREAD

**Issue by whk6688** [alibaba-damo-academy/FunASR#1691]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## ❓ Questions and Help
理论上
   SeACoParaformer-zh 支持热词
   paraformer-zh 不支持热词
但从别处看到：
![image](https://github.com/alibaba-damo-academy/FunASR/assets/17873056/0adb737b-3879-4f36-8fe4-9dedc07375fb)

那是说：SeACoParaformer-zh== paraformer-zh？

---------------------------
 - OS (e.g., Linux):
 - FunASR Version (e.g., 1.0.0):
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0):
 - How you installed funasr (`pip`, source):
 - Python version:
 - GPU (e.g., V100M32)
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by LauraGPT** [comment]
> 你去funasr python库的代码可以找到这个 ![image](https://private-user-images.githubusercontent.com/18463426/328106974-28d8266a-156f-4552-9b5a-a5f96365b7df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTkyMzUsIm5iZiI6MTcxNTA5ODkzNSwicGF0aCI6Ii8xODQ2MzQyNi8zMjgxMDY5NzQtMjhkODI2NmEtMTU2Zi00NTUyLTliNWEtYTVmOTYzNjViN2RmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE2MjIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhOTFjMDJhNjcxYzkxZTlkYzI4ZTBkZGJmZjMwOGNlZjYxZjFlZDQ4ODExNjE5Mzg2ZTUyZDBhZWUwNGU3ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OXsQ_U6OWezxBYV6APhsqPB3SGdoz6hssd-nG6ScrjY)

Yes
