### ISSUE TITLE
value's shape in forward_fsmn()

### ISSUE THREAD

**Issue by deyituo** [alibaba-damo-academy/FunASR#17]
What's the shape for inputs and mask of this line ? 
funasr: https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/modules/attention.py#L351
It seems like [b, T, self.h*self.d_k] and [b, T, T] ? 

wenet: https://github.com/wenet-e2e/wenet/blob/main/wenet/transformer/attention.py#L138

**Comment by langgz** [comment]
inputs: [b, T,self.h*self.d_k], see: https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/modules/attention.py#L376
mask: [b, T, 1]
