### ISSUE TITLE
README里的Model Zoo一节中`Whisper-large`的参数有误"Model Zoo" section in the README.md is marking the wrong parameters for Whisper model. 

### ISSUE THREAD

**Issue by zhong-yiyu** [alibaba-damo-academy/FunASR#1702]
https://github.com/alibaba-damo-academy/FunASR/blob/b1c186fd00fef54bcad3aa1d073a1a313642d641/README.md#L86-L87
中的whisper-large-v2和whisper-large-v3的参数量标注存在错误。
依据[Hugging Face上OpenAI的Whisper-Large的文档](https://github.com/alibaba-damo-academy/FunASR/blob/b1c186fd00fef54bcad3aa1d073a1a313642d641/setup.py#L8)，README.md中的两个参数应该修改为**1550 M**.

相同的问题也出现在README_zh.md文件中，可以进行相同的修改。

**Comment by tramphero** [comment]
Thanks for the reminder, we have fixed it.
