### ISSUE TITLE
windows社区软件包不支持spk_model参数？

### ISSUE THREAD

**Issue by lmxin123** [alibaba-damo-academy/FunASR#1717]
社区软件包是还不支持结合说话人模型iic/speech_campplus_sv_zh-cn_16k-common实现说话日志功能吗？
我加了spk_model参数，报错了
PARSE ERROR: Argument: --spk_model
             Couldn't find match for argument

**Comment by R1ckShi** [comment]
sdk目前不支持speaker模型，主要是cam++相关模型还没有进行onnx实现

**Comment by lmxin123** [comment]
> sdk目前不支持speaker模型，主要是cam++相关模型还没有进行onnx实现

cam++相关模型已经支持onnx导出了啊
https://github.com/alibaba-damo-academy/3D-Speaker/tree/main/runtime/onnxruntime
@R1ckShi
