### ISSUE TITLE
benchmark_onnx_cpp中cpp编译失败

### ISSUE THREAD

**Issue by GioGioBond** [alibaba-damo-academy/FunASR#1742]
自己数据用软件包run_server_2pass.sh转写很慢，二十分钟的数据需要30分钟才可以，看官方测试10h转写1h不到就可以完成。但是在调试benchmark_onnx_cpp的时候cpp编译失败，前面缺失的部分文件在ffmpeg-master-latest-linux64-gpl-shared和onnxruntime-linux-x64-1.14.0中找到，但是下面的已经找不到了

<img width="543" alt="23268be2fad799a9695ae419bcca03e" src="https://github.com/alibaba-damo-academy/FunASR/assets/39087265/973d60f0-877f-4b05-8995-133f238c7ceb">

####环境如下
Ubuntu 20.04.5
FunASR 1.0.22
PyTorch 2.2.2
pip 安装funasr
Python 3.8.19
GPU (V100
CUDA/cuDNN 11.8

**Comment by LauraGPT** [comment]
Please try it in docker

**Comment by lyblsgo** [comment]
https://github.com/alibaba-damo-academy/FunASR/blob/main/runtime/docs/SDK_advanced_guide_online_zh.md
