### ISSUE TITLE
h5 只显示部分内容，后台可以拿到所有内容

### ISSUE THREAD

**Issue by hausen1012** [alibaba-damo-academy/FunASR#1743]
![image](https://github.com/alibaba-damo-academy/FunASR/assets/50026605/2d526192-a098-4758-a4b8-35658022b722)
日志
![image](https://github.com/alibaba-damo-academy/FunASR/assets/50026605/1950ca75-b9c6-4964-94bd-393eb6015cb7)

**Comment by Ignalxy** [comment]
main.js的handleWithTimestamp函数有问题
```js
	tmptext=tmptext.replace(/。|？|，|、|\?|\.|\ /g, ","); // in case there are a lot of "。"
        // 加这两行
	tmptext=tmptext.replace(/([a-zA-Z]+)/g, ',$1,'); 
	tmptext=tmptext.replace(',,', ','); 
	var words=tmptext.split(",");  // split to chinese sentence or english words
```

**Comment by hausen1012** [comment]
> main.js的handleWithTimestamp函数有问题
> 
> ```js
> 	tmptext=tmptext.replace(/。|？|，|、|\?|\.|\ /g, ","); // in case there are a lot of "。"
>         // 加这两行
> 	tmptext=tmptext.replace(/([a-zA-Z]+)/g, ',$1,'); 
> 	tmptext=tmptext.replace(',,', ','); 
> 	var words=tmptext.split(",");  // split to chinese sentence or english words
> ```
![image](https://github.com/alibaba-damo-academy/FunASR/assets/50026605/a3bbbe0f-cfef-47d3-bc69-dace792642d4)

似乎还是一样。
![image](https://github.com/alibaba-damo-academy/FunASR/assets/50026605/6243fd32-d49e-49ff-81d3-c06b800b35d7)

**Comment by zhaomingwork** [comment]
@hausen1012 
请把测试wav发过来，好复现

**Comment by hausen1012** [comment]
> @hausen1012 请把测试wav发过来，好复现

感谢回复，我发现是h5的关闭 ws 判断有误，改为 true 以后可以识别全部了。

![e11278a1acd0273962f705ee5e39109](https://github.com/alibaba-damo-academy/FunASR/assets/50026605/c8eb7ea7-2b14-4da3-a0bc-b72d65f3ccbf)

**Comment by zhaomingwork** [comment]
> > @hausen1012 请把测试wav发过来，好复现
> 
> 感谢回复，我发现是h5的关闭 ws 判断有误，改为 true 以后可以识别全部了。
> 
> ![e11278a1acd0273962f705ee5e39109](https://private-user-images.githubusercontent.com/50026605/332626958-c8eb7ea7-2b14-4da3-a0bc-b72d65f3ccbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNDQ5NjMsIm5iZiI6MTcxNjM0NDY2MywicGF0aCI6Ii81MDAyNjYwNS8zMzI2MjY5NTgtYzhlYjdlYTctMmIxNC00ZGEzLWEwYmMtYjcyZDY1ZjNjY2JmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDAyMjQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwZmI2NTFkODdjOTAwM2M0ZDExMzkwMzFhMTdkZDMwZWVmYzU4MmZlODZjZTdkOThlODU3Yzc5YjY3Nzk0NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rte58K2fI-azz0PqjI2ThgmRx04XJprQU4tyCexbdNQ)

是true，最新的代码应该已改过这个问题

**Comment by hausen1012** [comment]
> > > @hausen1012 请把测试wav发过来，好复现
> > 
> > 
> > 感谢回复，我发现是h5的关闭 ws 判断有误，改为 true 以后可以识别全部了。
> > ![e11278a1acd0273962f705ee5e39109](https://private-user-images.githubusercontent.com/50026605/332626958-c8eb7ea7-2b14-4da3-a0bc-b72d65f3ccbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNDQ5NjMsIm5iZiI6MTcxNjM0NDY2MywicGF0aCI6Ii81MDAyNjYwNS8zMzI2MjY5NTgtYzhlYjdlYTctMmIxNC00ZGEzLWEwYmMtYjcyZDY1ZjNjY2JmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDAyMjQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwZmI2NTFkODdjOTAwM2M0ZDExMzkwMzFhMTdkZDMwZWVmYzU4MmZlODZjZTdkOThlODU3Yzc5YjY3Nzk0NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rte58K2fI-azz0PqjI2ThgmRx04XJprQU4tyCexbdNQ)
> 
> 是true，最新的代码应该已改过这个问题

可能是文档没更新，导致我下载的还是旧版本
