### ISSUE TITLE
paraformer-en与vad联合使用时报错result中没有'timestamp'字段

### ISSUE THREAD

**Issue by Wu-Jiayang** [alibaba-damo-academy/FunASR#1747]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## 🐛 Bug

paraformer-en与vad联合使用时报错result中没有'timestamp'字段

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd '....'
2. See error

![image](https://github.com/alibaba-damo-academy/FunASR/assets/62842862/218df8d8-e877-43d2-af95-e16a77e0a333)

KeyError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
'timestamp'
  File "/opt/conda/lib/python3.10/site-packages/funasr/auto/auto_model.py", line 458, in inference_with_vad
    result['timestamp'],
  File "/opt/conda/lib/python3.10/site-packages/funasr/auto/auto_model.py", line 232, in generate
    return self.inference_with_vad(input, input_len=input_len, **cfg)
  File "/workspace/insurance-text-data/test.py", line 11, in <module>
    res = model.generate(input='asr_example_en.wav')  # 文档说只支持wav
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,
KeyError: 'timestamp'

#### Code sample

```py
from funasr import AutoModel


model = AutoModel(
    model="paraformer-en", 
    vad_model="fsmn-vad",
    punc_model="ct-punc", 
    spk_model="cam++"
)

res = model.generate(input='asr_example_en.wav')  # 文档说只支持wav
print(res)

```

### Environment

 - OS (e.g., Linux): linux
 - FunASR Version (e.g., 1.0.0):1.0.25（1.0.27同样）
 - ModelScope Version (e.g., 1.11.0):
 - PyTorch Version (e.g., 2.0.0): 2.2.1
 - How you installed funasr (`pip`, source): pip
 - Python version: 3.10.13
 - GPU (e.g., V100M32) 3090
 - CUDA/cuDNN version (e.g., cuda11.7):
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1)
 - Any other relevant information:

**Comment by R1ckShi** [comment]
paraformer-en模型不支持返回时间戳

**Comment by Upcreat** [comment]
![局部截取_20241206_155959](https://github.com/user-attachments/assets/2b3cd46b-db0d-417a-a06b-8d993d767263)
paraformer-en模型好像是支持时间戳的呀
