### ISSUE TITLE
我的funasr离线用不了，client-server

### ISSUE THREAD

**Issue by 851543** [alibaba-damo-academy/FunASR#1751]
server：
E:\FunASR\Test>python funasr_wss_server.py
model loading
2024-05-23 15:51:03,247 - modelscope - INFO - PyTorch version 2.3.0 Found.
2024-05-23 15:51:03,249 - modelscope - INFO - Loading ast index from E:\FunASR\modelscope\ast_indexer
2024-05-23 15:51:03,453 - modelscope - INFO - Loading done! Current index file version is 1.14.0, with md5 c554e3afd3d59e49236523ff934fdc29 and a total number of 976 components indexed
2024-05-23 15:51:03,894 - modelscope - INFO - Use user-specified model revision: v2.0.4
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19.1k/19.1k [00:00<00:00, 322kB/s]
ckpt: E:\FunASR\modelscope\iic\speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch\model.pt
2024-05-23 15:51:07,242 - modelscope - INFO - Use user-specified model revision: v2.0.4
ckpt: E:\FunASR\modelscope\iic\speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online\model.pt
2024-05-23 15:51:10,432 - modelscope - INFO - Use user-specified model revision: v2.0.4
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8.45k/8.45k [00:00<?, ?B/s]
ckpt: E:\FunASR\modelscope\iic\speech_fsmn_vad_zh-cn-16k-common-pytorch\model.pt
2024-05-23 15:51:11,407 - modelscope - INFO - Use user-specified model revision: v2.0.4
ckpt: E:\FunASR\modelscope\iic\punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727\model.pt
model loaded! only support one client at the same time now!!!!
E:\FunASR\Test\funasr_wss_server.py:329: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(start_server)
E:\FunASR\Test\funasr_wss_server.py:330: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_forever()
new user connected
error in vad
-----------------------------------------------------------------------------------------------------------------------
client：
E:\FunASR\Test>python funasr_wss_client.py --host "127.0.0.1" --port 10095 --mode offline --audio_in "./data/test.mp4" --output_dir "./results"
Namespace(host='127.0.0.1', port=10095, chunk_size=[5, 10, 5], encoder_chunk_look_back=4, decoder_chunk_look_back=0, chunk_interval=10, hotword='', audio_in='./data/test.mp4', audio_fs=16000, send_without_sleep=True, thread_num=1, w
ords_max_print=10000, output_dir='./results', ssl=1, use_itn=1, mode='offline')
Namespace(host='127.0.0.1', port=10095, chunk_size=[5, 10, 5], encoder_chunk_look_back=4, decoder_chunk_look_back=0, chunk_interval=10, hotword='', audio_in='./data/test.mp4', audio_fs=16000, send_without_sleep=True, thread_num=1, w
ords_max_print=10000, output_dir='./results', ssl=1, use_itn=1, mode='offline')
connect to wss://127.0.0.1:10095

**Comment by 851543** [comment]
我尝试用wav文件去请求E:\FunASR\Test>python funasr_wss_client.py --host "127.0.0.1" --port 10095 --mode offline --audio_in "./data/test.wav" --output_dir "./results"
Namespace(host='127.0.0.1', port=10095, chunk_size=[5, 10, 5], encoder_chunk_look_back=4, decoder_chunk_look_back=0, chunk_interval=10, hotword='', audio_in='./data/test.wav', audio_fs=16000, send_without_sleep=True, thread_num=1, w
ords_max_print=10000, output_dir='./results', ssl=1, use_itn=1, mode='offline')
Namespace(host='127.0.0.1', port=10095, chunk_size=[5, 10, 5], encoder_chunk_look_back=4, decoder_chunk_look_back=0, chunk_interval=10, hotword='', audio_in='./data/test.wav', audio_fs=16000, send_without_sleep=True, thread_num=1, w
ords_max_print=10000, output_dir='./results', ssl=1, use_itn=1, mode='offline')
connect to wss://127.0.0.1:10095
server：
new user connected
error in vad
ConnectionClosed... {<websockets.legacy.server.WebSocketServerProtocol object at 0x000001AF69D815A0>}
ws reset now, total num is  1
new user connected

client久久不能响应 我的CPU拉满了 这个是什么问题。

**Comment by 851543** [comment]
我尝试把funasr-client断了发现我的funasr-server还在运行把我的cpu拉满了

**Comment by 851543** [comment]
我发才现这个文件的FunASR\runtime\python\websocket\funasr_wss_server.py的函数
async def async_vad(websocket, audio_in):

    segments_result = model_vad.generate(input=audio_in, **websocket.status_dict_vad)[0]["value"]
    print("deb"+segments_result)

    speech_start = -1
    speech_end = -1

    if len(segments_result) == 0 or len(segments_result) > 1:
        return speech_start, speech_end
    if segments_result[0][0] != -1:
        speech_start = segments_result[0][0]
    if segments_result[0][1] != -1:
        speech_end = segments_result[0][1]
    return speech_start, speech_end

segments_result 为一个[]一直死循环输出

**Comment by 851543** [comment]
此外我发现html5交给funasr-server的热词没有效果。

**Comment by lyblsgo** [comment]
try docker：
https://github.com/alibaba-damo-academy/FunASR/blob/main/runtime/docs/SDK_advanced_guide_offline_zh.md

**Comment by yangkkk233** [comment]
你好，请问一下解决了吗，我用HTML5也是，实时能用，但是上传文件就一直用不了。mp3文件还会在服务端报错，wav文件倒是不报错，就是一直没结果

**Comment by Alexander-Jim** [comment]
> 我发才现这个文件的FunASR\runtime\python\websocket\funasr_wss_server.py的函数 async def async_vad(websocket, audio_in):
> 
> ```
> segments_result = model_vad.generate(input=audio_in, **websocket.status_dict_vad)[0]["value"]
> print("deb"+segments_result)
> 
> speech_start = -1
> speech_end = -1
> 
> if len(segments_result) == 0 or len(segments_result) > 1:
>     return speech_start, speech_end
> if segments_result[0][0] != -1:
>     speech_start = segments_result[0][0]
> if segments_result[0][1] != -1:
>     speech_end = segments_result[0][1]
> return speech_start, speech_end
> ```
> 
> segments_result 为一个[]一直死循环输出

我也遇到了同样的问题，3天没解决

**Comment by 851543** [comment]
> > 我发才现这个文件的FunASR\runtime\python\websocket\funasr_wss_server.py的函数 async def async_vad(websocket, audio_in):
> > ```
> > segments_result = model_vad.generate(input=audio_in, **websocket.status_dict_vad)[0]["value"]
> > print("deb"+segments_result)
> > 
> > speech_start = -1
> > speech_end = -1
> > 
> > if len(segments_result) == 0 or len(segments_result) > 1:
> >     return speech_start, speech_end
> > if segments_result[0][0] != -1:
> >     speech_start = segments_result[0][0]
> > if segments_result[0][1] != -1:
> >     speech_end = segments_result[0][1]
> > return speech_start, speech_end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > segments_result 为一个[]一直死循环输出
> 
> 我也遇到了同样的问题，3天没解决

建议自己使用实例配合fastapi开发

**Comment by 851543** [comment]
> 你好，请问一下解决了吗，我用HTML5也是，实时能用，但是上传文件就一直用不了。mp3文件还会在服务端报错，wav文件倒是不报错，就是一直没结果

楼下有建议

**Comment by Alexander-Jim** [comment]
> > > 我发才现这个文件的FunASR\runtime\python\websocket\funasr_wss_server.py的函数 async def async_vad(websocket, audio_in):
> > > ```
> > > segments_result = model_vad.generate(input=audio_in, **websocket.status_dict_vad)[0]["value"]
> > > print("deb"+segments_result)
> > > 
> > > speech_start = -1
> > > speech_end = -1
> > > 
> > > if len(segments_result) == 0 or len(segments_result) > 1:
> > >     return speech_start, speech_end
> > > if segments_result[0][0] != -1:
> > >     speech_start = segments_result[0][0]
> > > if segments_result[0][1] != -1:
> > >     speech_end = segments_result[0][1]
> > > return speech_start, speech_end
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > segments_result 为一个[]一直死循环输出
> > 
> > 
> > 我也遇到了同样的问题，3天没解决
> 
> 建议自己使用实例配合fastapi开发

本地docker+wss调用这个模式是没问题的，但是我的业务中不太适用，我希望使用py（PyTorch）直接来调用.pt模型文件

**Comment by 851543** [comment]
> > > > 我发才现这个文件的FunASR\runtime\python\websocket\funasr_wss_server.py的函数 async def async_vad(websocket, audio_in):
> > > > ```
> > > > segments_result = model_vad.generate(input=audio_in, **websocket.status_dict_vad)[0]["value"]
> > > > print("deb"+segments_result)
> > > > 
> > > > speech_start = -1
> > > > speech_end = -1
> > > > 
> > > > if len(segments_result) == 0 or len(segments_result) > 1:
> > > >     return speech_start, speech_end
> > > > if segments_result[0][0] != -1:
> > > >     speech_start = segments_result[0][0]
> > > > if segments_result[0][1] != -1:
> > > >     speech_end = segments_result[0][1]
> > > > return speech_start, speech_end
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > segments_result 为一个[]一直死循环输出
> > > 
> > > 
> > > 我也遇到了同样的问题，3天没解决
> > 
> > 
> > 建议自己使用实例配合fastapi开发
> 
> 本地docker+wss调用这个模式是没问题的，但是我的业务中不太适用，我希望使用py（PyTorch）直接来调用.pt模型文件

本项目中官方有提供py的fastApi写法 推荐使用那个或者参考
