### ISSUE TITLE
通过pip安装后，python代码调用返回错误（cannot import name 'AutoModel' from partially initialized module 'funasr'）

### ISSUE THREAD

**Issue by kyle-cao** [alibaba-damo-academy/FunASR#1759]
安装步骤：pip install -U funasr modelscope torchaudio
问题描述：根据说明文档进行安装，通过命令调用可以正常执行 但是通过python代码调用报错
错误内容：
<img width="1115" alt="image" src="https://github.com/alibaba-damo-academy/FunASR/assets/36940587/a8c77ae4-dd86-4968-b4d6-026fa739d4de">
python代码：
<img width="603" alt="image" src="https://github.com/alibaba-damo-academy/FunASR/assets/36940587/b11262fa-2b6f-4533-a8ac-658f5d71428e">

环境：
 - OS: Linux:
 - FunASR Version : 1.0.27:
 - ModelScope Version: 1.14.0:
 - PyTorch Version: 2.3.0:
 - How you installed funasr: pip
 - Python version: 3.12.3

**Comment by LauraGPT** [comment]
try python-3.10

**Comment by kyle-cao** [comment]
换成了3.10 通过代码调用还是不行
<img width="1276" alt="image" src="https://github.com/alibaba-damo-academy/FunASR/assets/36940587/84779695-f1ec-473b-8ef5-9fcc23fbaaae">

**Comment by LauraGPT** [comment]
Sorry, we don not know what happened.
