### ISSUE TITLE
Suggest: offer a script to convert the model to onnx/ncnn

### ISSUE THREAD

**Issue by znsoftm** [alibaba-damo-academy/FunASR#19]
As title mentioned.

**Comment by langgz** [comment]
https://github.com/alibaba-damo-academy/FunASR/tree/main/funasr/export

**Comment by zcy618** [comment]
https://github.com/alibaba-damo-academy/FunASR/tree/main/funasr/export
这个现在访问不了了，有其他地方可以看吗？
