### ISSUE TITLE
使用c++推理结果是乱码

### ISSUE THREAD

**Issue by laosiji123456** [alibaba-damo-academy/FunASR#195]
OS:  win10
Python Version：3.7.16
Package Version：modelscope1.3.2
funasr0.2.3
Model：speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
Command：tester.exe  F:\FunASR-main\funasr\runtime\onnxruntime\models    F:\RapidASR-main\cpp_onnx\wave\long.wav
Error log：无
问题描述:使用c++推理结果是乱码

![image](https://user-images.githubusercontent.com/25971102/223895466-97dcb1fb-3441-419d-b79a-8c7801c40204.png)

**Comment by langgz** [comment]
@znsoftm 请协助解决一下哈

**Comment by chenkui164** [comment]
在cmd中输入CHCP 65001即可解决

**Comment by laosiji123456** [comment]
> 在cmd中输入CHCP 65001即可解决

谢谢大佬，已经解决问题

**Comment by GlocKieHuan** [comment]
![image](https://user-images.githubusercontent.com/77883010/232789805-f9fdb7de-58c9-4fcc-baf3-741bd1c4c7bb.png)
我试了以上办法还是乱码，希望大佬帮忙看下

**Comment by chenkui164** [comment]
编译完成以后，不要在vs里面点击运行。重新启动一个cmd窗口，在里面先执行CHCP 65001，然后在运行tester这个程序。

也可以试试下面这个方法，修改下代码试试。
https://stackoverflow.com/questions/1371012/how-do-i-print-utf-8-from-c-console-application-on-windows

**Comment by GlocKieHuan** [comment]
你好呀，这里是GH的邮件自动回复，你的邮件我已经收到啦，祝好~~~

**Comment by GlocKieHuan** [comment]
可以了，谢谢大佬
