### ISSUE TITLE
模型微调的效果

### ISSUE THREAD

**Issue by ziyu123** [alibaba-damo-academy/FunASR#197]
我在用paraformer的common大模型在内部数据集上进行微调后的结果如下：
（1）用2kh 进行微调，cer 相对降低6%左右
（2）用1wh进行微调，cer 相对降低5%左右 
微调使用的学习率是一样的，设置的很小，原始微调参数的十分之一。
现在的问题是，
（1）这样的结果是跟实际情况一致吗，数据大的，结果相对差一些
（2）对于大数据1wh，是否再进一步调低学习率？
（3）有没有其他的对微调有帮助的参数呢(finetune.yaml中的参数）？

**Comment by langgz** [comment]
通常来说，数据量越小，学习率设置越小，尤其是1000小时一下；数据量超过1000小时，可以适当调大学习率，一般是0.0005，最大0.001

**Comment by ziyu123** [comment]
好的，谢谢，我试试。
