### ISSUE TITLE
some audio files can not be recognized well by funasr

### ISSUE THREAD

**Issue by CodingFatman** [alibaba-damo-academy/FunASR#198]
here comes some audio files that can not be recognized well by funasr.
you can use these audio files to find out the reason and imporve the funasr.
[普通话合集.zip](https://github.com/alibaba-damo-academy/FunASR/files/10928939/default.zip)

**Comment by hnluo** [comment]
Currently，multiple audio formats and sampling rate adaptation are not support on demo service。You can install funasr and modelscope for audio inference，please refer to https://github.com/alibaba-damo-academy/FunASR/wiki/%E5%BF%AB%E9%80%9F%E6%8E%A8%E7%90%86

**Comment by CodingFatman** [comment]
i create a new issue to give you a new idea to solve the audio formats and sampling rate problems.
please refer to #200

**Comment by langgz** [comment]
新版本已经发布，包括在线体验也已经支持，兼容多种音频格式，可以更新版本，或者到网页在线体验（已经测试，你上传的wav都是ok的）：https://www.modelscope.cn/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/summary
