### ISSUE TITLE
some excellent code for dealing with various audio files format which learn from whisper of openai

### ISSUE THREAD

**Issue by CodingFatman** [alibaba-damo-academy/FunASR#200]
i has been copied some execllent code from whisper project which can dealing with various audio files format easily.
the whisper project uses ffmpeg to deal with the input audio files that user inputed. they give the convenience to user and leave the complexity to self.
i think this can be learned by us to improve the quality of funasr.
good lunk, guys! :)
# Code Block 1
![1](https://user-images.githubusercontent.com/38900882/224218128-5d24294b-32c4-4ee8-bc8c-a934665d6416.png)
# Code Block 2
![2](https://user-images.githubusercontent.com/38900882/224218141-e4a6969c-a200-4daa-9627-469f0b87ca8e.png)
# Code Block 3
![3](https://user-images.githubusercontent.com/38900882/224218146-d2932586-b1bd-4e69-84a2-b49676d1a4fa.png)
# Code Block 4
![4](https://user-images.githubusercontent.com/38900882/224218152-882eb61e-c583-4d14-9950-21251f261b61.png)

**Comment by langgz** [comment]
Thank you for suggestion. FunASR now supports many types of audio, you could test it. If you have any problem, any feedback is welcome.

**Comment by CodingFatman** [comment]
@langgz amazing! :)

**Comment by wwfcnu** [comment]
load_utils.py文件里ffmpeg处理pcm格式有问题
