### ISSUE TITLE
saying noting but get  irrelevant recognition result

### ISSUE THREAD

**Issue by v-yunbin** [alibaba-damo-academy/FunASR#206]
环境：
```
os：centos 7.9
python：3.8.3
package: torch 1.13.1,modelscope 1.3.2 funasr 0.2.2
model:speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
commad: inference_pipeline = pipeline(task=Tasks.auto_speech_recognition,  model="./speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404", param_dict=param_dict)
rec_result = inference_pipeline(audio_in=audio.wav)
```
audio.wav其实是从麦克风采集后实时传递给服务端，累积到20s后送给模型做解码。
没有说任何东西，输出一些奇怪的识别结果。
```
哦每庭有诉讼都一一包括括你你你认觉有问题题的话那么我们就就问问题没有其他他他这个这个这边
呃三呃十三十三三三三三三三呃三有三有三的证据
四一二三三三现在那个国务要的个个东题就是呃a呃是是在呃呃还进出去西话还有个光标幺幺二二二二是a二的是lt的
那个个那个那诉那个嗯你现在用卡来换了吗那那个个十二号
我们分是这个就是刚管里的这个被个破板抓住抓住呢然然相于就是在在推电子的时候候这个电
呃是三个的个个个个个个个个呃的的的的的的的的的的的的的的的的的的是的有的证据
证明的这是我证时间第四年是一个八月六月的范围这是应该回事就是他在因为这次共同发的的个个政府保存的收 的被告外外的的这个承包这个
```

**Comment by langgz** [comment]
需要外接一个vad模型来过滤掉静音，只把有效音频输入到asr模型里面计算

**Comment by v-yunbin** [comment]
如果有背景人声的话，应该也过滤不掉吧？

**Comment by langgz** [comment]
是的，但是有vad的话，只是背景人声的话，模型会把背景人声识别成文字，不会输出无意义的文字，你现在是环境噪声导致的无意义输出，这个vad是可以过滤掉的

**Comment by v-yunbin** [comment]
> 是的，但是有vad的话，只是背景人声的话，模型会把背景人声识别成文字，不会输出无意义的文字，你现在是环境噪声导致的无意义输出，这个vad是可以过滤掉的

加了VAD似乎不起作用。

**Comment by langgz** [comment]
> > 是的，但是有vad的话，只是背景人声的话，模型会把背景人声识别成文字，不会输出无意义的文字，你现在是环境噪声导致的无意义输出，这个vad是可以过滤掉的
> 
> 加了VAD似乎不起作用。

用的是webrtcvad，还是我们的vad？  https://www.modelscope.cn/models?page=1&tasks=voice-activity-detection&type=audio

**Comment by v-yunbin** [comment]
> > > 是的，但是有vad的话，只是背景人声的话，模型会把背景人声识别成文字，不会输出无意义的文字，你现在是环境噪声导致的无意义输出，这个vad是可以过滤掉的
> > 
> > 
> > 加了VAD似乎不起作用。
> 
> 用的是webrtcvad，还是我们的vad？ https://www.modelscope.cn/models?page=1&tasks=voice-activity-detection&type=audio
webrtcvad和阿里的vad都用了。

**Comment by v-yunbin** [comment]
@langgz 我在做这样一件事情：在本地电脑读取麦克风，麦克风实时采集语音数据，通过websockets发送实时采集的数据到ASR服务端，由于咱们的asr模型是离线的，所有暂时以20s为界限，超过20s的时候会送入vad做检测，如果有声音片段，则将整个片段送入ASR解码。不知道有没有更好的建议。

**Comment by langgz** [comment]
> @langgz 我在做这样一件事情：在本地电脑读取麦克风，麦克风实时采集语音数据，通过websockets发送实时采集的数据到ASR服务端，由于咱们的asr模型是离线的，所有暂时以20s为界限，超过20s的时候会送入vad做检测，如果有声音片段，则将整个片段送入ASR解码。不知道有没有更好的建议。

3月发布，我们会发布流式vad来代替webrtcvad，和流式paraformer，到时候可以再试试

**Comment by v-yunbin** [comment]
solved. @langgz

**Comment by zhuhao528** [comment]
这个问题怎么解决的

**Comment by zhuhao528** [comment]
现在有流式的vad了不

**Comment by MooWeii** [comment]
> 现在有流式的vad了不

如果有了喊我一声
