### ISSUE TITLE
a bug in funasr/models/pooling/statistic_pooling.py:85

### ISSUE THREAD

**Issue by xuelx63** [alibaba-damo-academy/FunASR#219]
![image](https://user-images.githubusercontent.com/116239077/224645265-a443ed67-353e-4e25-935b-58fcb2bab19d.png)

请检查下，`if xs_pad.shape == 4:` 是否应改为 `if len(xs_pad.shape) == 4:`

**Comment by ZhihaoDU** [comment]
是的，多谢提醒，已修改
