### ISSUE TITLE
TypeError is reported when using the punctuation model in both the online environment and the local environment

### ISSUE THREAD

**Issue by WuS-1997** [alibaba-damo-academy/FunASR#231]
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_355/1084747498.py in <module>
----> 1 p('我们都是木头人不会讲话不会动',)

/opt/conda/lib/python3.7/site-packages/modelscope/pipelines/audio/punctuation_processing_pipeline.py in __call__(self, text_in, output_dir, cache, param_dict)
     77             self.cmd['param_dict'] = param_dict
     78 
---> 79         output = self.forward(self.text_in)
     80         result = self.postprocess(output)
     81         return result

/opt/conda/lib/python3.7/site-packages/modelscope/pipelines/audio/punctuation_processing_pipeline.py in forward(self, text_in)
    152         self.cmd['name_and_type'] = data_cmd
    153         self.cmd['raw_inputs'] = raw_inputs
--> 154         punc_result = self.run_inference(self.cmd)
    155 
    156         return punc_result

/opt/conda/lib/python3.7/site-packages/modelscope/pipelines/audio/punctuation_processing_pipeline.py in run_inference(self, cmd)
    164                 output_dir_v2=cmd['output_dir'],
    165                 cache=cmd['cache'],
--> 166                 param_dict=cmd['param_dict'])
    167         else:
    168             raise ValueError('model type is mismatching')

TypeError: 'NoneType' object is not callable

**Comment by langgz** [comment]
版本问题，更新版本就可以了：

modelscope-1.4.1与funasr-0.3.0版本更新，正式release notes：

https://github.com/alibaba-damo-academy/FunASR/releases/tag/v0.3.0


如需体验，更新指令：

pip install "modelscope[audio_asr]" --upgrade -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html


git clone https://github.com/alibaba/FunASR.git && cd FunASR

pip install --editable ./
