### ISSUE TITLE
docker image can't work

### ISSUE THREAD

**Issue by CodingFatman** [alibaba-damo-academy/FunASR#232]
i download the docker image from here
![image](https://user-images.githubusercontent.com/38900882/224948458-44efbb13-c701-408d-92a1-4f799ae912fc.png)
but an error occurred when i run the example code 
below is the error information:
![8717595ead9b1e539629bc226cd1c4d](https://user-images.githubusercontent.com/38900882/224948260-082a2887-eb5e-45e8-a4bc-32b68c3756be.png)
![a321f24cef6d5f41c0e5eee68b7aa78](https://user-images.githubusercontent.com/38900882/224948295-3bb3a937-6e3a-4720-a888-2bf723efa830.png)

**Comment by liuyhwangyh** [comment]
Please ensure the disk is not full,  /mnt/workspace/.cache
