### ISSUE TITLE
Error when loading the speechio paraformer model

### ISSUE THREAD

**Issue by zywang20** [alibaba-damo-academy/FunASR#24]
Error "pickle.UnpicklingError: invalid load key, 'v'." occurs when running paraformer_large_infer.sh in egs_modelscope/speechio. The decoding model is downloaded from modelscope in advance.
![image](https://user-images.githubusercontent.com/71959408/209915832-d2b7f49e-ff84-46bb-8f68-7d12126ff7bb.png)

**Comment by langgz** [comment]
do you run the model in notebook？

**Comment by zywang20** [comment]
> 

No, I run locally

**Comment by zywang20** [comment]
Solved. The downloaded file was corrupt.
