### ISSUE TITLE
nv的runtime如何指定gpu

### ISSUE THREAD

**Issue by kFoodie** [alibaba-damo-academy/FunASR#243]
https://github.com/alibaba-damo-academy/FunASR/tree/main/funasr/runtime/triton_gpu 中 启动docker服务时，docker run --gpus 只能指定all吗？如何指定gpu?

**Comment by kFoodie** [comment]
![image](https://user-images.githubusercontent.com/16017418/225540399-6c749198-4392-4993-a062-50633c281957.png)
有显卡被占用的时候，启动不了……不确定是不是GPU被占用的原因..
另外，可以只用cpu跑吗？

**Comment by langgz** [comment]
@yuekaizhang @songtaoshi  请帮忙看看哈

**Comment by yuekaizhang** [comment]
> ![image](https://user-images.githubusercontent.com/16017418/225540399-6c749198-4392-4993-a062-50633c281957.png) 有显卡被占用的时候，启动不了……不确定是不是GPU被占用的原因.. 另外，可以只用cpu跑吗？

https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md#instance-groups 看这里指定gpu id, cpu

**Comment by yuekaizhang** [comment]
docker run --rm --gpus "device=1" 这样也行
