### ISSUE TITLE
Paraformer热词版有finetune的脚本吗？

### ISSUE THREAD

**Issue by mengyanggithub** [alibaba-damo-academy/FunASR#253]
请问Paraformer热词版有finetune的脚本吗？

**Comment by uloveqian2021** [comment]
> 请问Paraformer热词版有finetune的脚本吗？

同问

**Comment by zyjcsf** [comment]
目前用的热词模块是用lstm模型，可以用transformer模块搭建吗？热词模块训练的时候，需要对标注文本做修改吗？
