### ISSUE TITLE
今天应该是有更新，CPU推理出错了

### ISSUE THREAD

**Issue by cgisky1980** [alibaba-damo-academy/FunASR#264]
/www/miniconda3/envs/vits2/lib/python3.7/site-packages/torch/amp/autocast_mode.py:214: UserWarning: In CPU autocast, but the target dtype is not supported. Disabling autocast.
CPU Autocast only supports dtype of torch.bfloat16 currently.

我跑的那个模型  把  FunASR/funasr/models/e2e_asr_paraformer.py  文件中 两处 with autocast(False):
改为
···
       #with autocast(False):
       if True:
···

好了

**Comment by cgisky1980** [comment]
另外问一句 能把自动更新给关了么？？ /(ㄒoㄒ)/~~

**Comment by langgz** [comment]
好的，感谢反馈，我们内部测试一下

**Comment by langgz** [comment]
刚才确认了一下，代码一直是with autocast(False)，应该是你那边自己有修改，更新funasr以后，被覆盖了，导致的问题。请问你做这个修改，是有什么特殊用途么？如果涉及到自己的项目，可以把这块pr，merge进funasr。funasr是需要更新的，不然无法使用最新feature，也没法下载modelscope最新的模型

**Comment by cgisky1980** [comment]
> 

奇怪 我啥也没改啊，之前好好的，然后突然就报错了  CPU Autocast only supports dtype of torch.bfloat16 currently. @@  
不是特殊用途 而是报错执行不了啊  
就是跑了两个模型
# 创建一个VAD对象
inference_pipline = pipeline(
        task=Tasks.voice_activity_detection,
        model="damo/speech_fsmn_vad_zh-cn-16k-common-pytorch",
        model_revision='v1.2.0',
        output_dir=None,
        batch_size=1,
    )

param_dict = dict()
param_dict['hotword']="小五 小五月" #设置热词，用空格隔开

inference_pipeline2 = pipeline(
        task=Tasks.auto_speech_recognition,
        model="damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404",
        param_dict=param_dict)

**Comment by cgisky1980** [comment]
https://github.com/pytorch/pytorch/issues/55374

**Comment by cgisky1980** [comment]
> 刚才确认了一下，代码一直是with autocast(False)，应该是你那边自己有修改，更新funasr以后，被覆盖了，导致的问题。请问你做这个修改，是有什么特殊用途么？如果涉及到自己的项目，可以把这块pr，merge进funasr。funasr是需要更新的，不然无法使用最新feature，也没法下载modelscope最新的模型

我觉得这块可不可以做个设置开关  比如跑在生产环境中，不是太希望保持最新环境。

不是这块代码有问题，而是之前cpu环境应该跑不到这一块？6天前那次更新 是不是给打开了 autocast

[这个警告是因为你在使用PyTorch的自动混合精度（autocast）功能时，指定了一个不受支持的数据类型（dtype）。目前，CPU autocast只支持torch.bfloat16这一种数据类型](https://github.com/pytorch/pytorch/blob/master/torch/amp/autocast_mode.py)[1](https://github.com/pytorch/pytorch/blob/master/torch/amp/autocast_mode.py)[2](https://github.com/pytorch/pytorch/issues/55374)[。如果你想使用其他的数据类型，你需要禁用autocast或者切换到其他设备](https://github.com/pytorch/pytorch/issues/55374)[2](https://github.com/pytorch/pytorch/issues/55374)。

**Comment by cgisky1980** [comment]
/www/miniconda3/envs/vits2/lib/python3.7/site-packages/torch/amp/autocast_mode.py:214: UserWarning: In CPU autocast, but the target dtype is not supported. Disabling autocast.
CPU Autocast only supports dtype of torch.bfloat16 currently.
  warnings.warn(error_message)
Traceback (most recent call last):
  File "asr.py", line 161, in <module>
    rec_result = inference_pipeline2(audio_in=audio_in)
  File "/www/miniconda3/envs/vits2/lib/python3.7/site-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 258, in __call__
    output = self.forward(output, **kwargs)
  File "/www/miniconda3/envs/vits2/lib/python3.7/site-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 533, in forward
    inputs['asr_result'] = self.run_inference(self.cmd, **kwargs)
  File "/www/miniconda3/envs/vits2/lib/python3.7/site-packages/modelscope/pipelines/audio/asr_inference_pipeline.py", line 612, in run_inference
    cmd['fs'], cmd['param_dict'], **kwargs)
  File "/www/FunASR/funasr/bin/asr_inference_paraformer.py", line 728, in _forward
    results = speech2text(**batch)
  File "/www/miniconda3/envs/vits2/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/www/FunASR/funasr/bin/asr_inference_paraformer.py", line 226, in __call__
    enc, enc_len = self.asr_model.encode(**batch)
  File "/www/FunASR/funasr/models/e2e_asr_paraformer.py", line 278, in encode
    with autocast(False):
  File "/www/miniconda3/envs/vits2/lib/python3.7/site-packages/torch/cuda/amp/autocast_mode.py", line 30, in __enter__
    return super().__enter__()
  File "/www/miniconda3/envs/vits2/lib/python3.7/site-packages/torch/amp/autocast_mode.py", line 238, in __enter__
    torch.set_autocast_cpu_dtype(self.fast_dtype)  # type: ignore[arg-type]
RuntimeError: Currently, AutocastCPU only support Bfloat16 as the autocast_cpu_dtype

**Comment by langgz** [comment]
好的，问题收到。关于更细遇到报错的问题，可以加我们钉钉群，更新前会提前1个礼拜在群里通知，你可以自己先测试，如果有问题，可以及时反馈给我们
