### ISSUE TITLE
speechio自测结果与官方给的不一致

### ISSUE THREAD

**Issue by kFoodie** [alibaba-damo-academy/FunASR#265]
你们的speechio的测试结果，为啥cer这么低啊？
比如 speechio 12
我的结果：
%WER 3.21 [ 2344 / 73114, 332 ins, 803 del, 1209 sub ]
%SER 72.91 [ 853 / 1170 ]
我的设置
<img width="507" alt="71f9e569e0d016dd5b46ed9f1df57e3e" src="https://user-images.githubusercontent.com/16017418/226230951-c152c66b-9829-47e9-8d56-31aaa38b9bab.png">

另外，不管我有没有加语言模型，测出来的wer都是3.21。。

**Comment by langgz** [comment]
@Lizerui9926 加一下text norm的recipe，方便用户复现speechio的实验结果

**Comment by Lizerui9926** [comment]
@kFoodie 已更新paraformer-large模型的recipe，https://github.com/alibaba-damo-academy/FunASR/blob/main/egs_modelscope/asr/paraformer/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/infer.sh在最新的脚本中stage=3包含了text norm，可尝试复现speechio实验结果

**Comment by Lizerui9926** [comment]
加语言模型，还需要在pipeline配置lm_weight和beam_size参数，我们的结果使用的是lm_weight=0.15和beam_size=10

**Comment by JVfisher** [comment]
> 你们的speechio的测试结果，为啥cer这么低啊？ 比如 speechio 12 我的结果： %WER 3.21 [ 2344 / 73114, 332 ins, 803 del, 1209 sub ] %SER 72.91 [ 853 / 1170 ] 我的设置 <img alt="71f9e569e0d016dd5b46ed9f1df57e3e" width="507" src="https://user-images.githubusercontent.com/16017418/226230951-c152c66b-9829-47e9-8d56-31aaa38b9bab.png">
> 
> 另外，不管我有没有加语言模型，测出来的wer都是3.21。。

请问您是如何添加lm并设置lm_weight和beam_size参数的，我在文档中没有找到相关的内容
