### ISSUE TITLE
asr inference 不支持mp3格式

### ISSUE THREAD

**Issue by wwfcnu** [alibaba-damo-academy/FunASR#269]
使用paraformer模型推理时，pipeline不支持mp3格式

**Comment by langgz** [comment]
按照说明，升级modelscope-1.4.1与funasr-0.3.0版本，支持mp3格式输入：
https://github.com/alibaba-damo-academy/FunASR#installation

**Comment by wwfcnu** [comment]
> 按照说明，升级modelscope-1.4.1与funasr-0.3.0版本，支持mp3格式输入： https://github.com/alibaba-damo-academy/FunASR#installation

可以pip -U的方式更新吗

**Comment by wwfcnu** [comment]
我更新了版本，但是测试的时候报错RuntimeError: Failed to load audio

**Comment by wwfcnu** [comment]
> 按照说明，升级modelscope-1.4.1与funasr-0.3.0版本，支持mp3格式输入： https://github.com/alibaba-damo-academy/FunASR#installation

还是不支持mp3格式呀

**Comment by hnluo** [comment]
麻烦看下torchaudio版本，torchaudio 0.12目前不支持加载mp3文件，torchaudio 0.8我这边试了是没问题的。具体可以参考https://stackoverflow.com/questions/73379250/runtime-error-failed-to-load-audio-for-mp3-file-waveform-torchaudio

**Comment by wwfcnu** [comment]
> 麻烦看下torchaudio版本，torchaudio 0.12目前不支持加载mp3文件，torchaudio 0.8我这边试了是没问题的。具体可以参考https://stackoverflow.com/questions/73379250/runtime-error-failed-to-load-audio-for-mp3-file-waveform-torchaudio

更改torchaudio的版本会影响torch的版本，有没有其他办法可以解决

**Comment by hnluo** [comment]
抱歉，目前只能重新安装torch了，可以参考以下表格
cuda |  
-- | --
9.2 | conda install pytorch==1.7.0 torchvision==0.8.0 torchaudio==0.7.0 cudatoolkit=9.2 -c pytorch
10.2 | conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=10.2 -c pytorch
11.1 | conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=11.1 -c pytorch

**Comment by wwfcnu** [comment]
> 抱歉，目前只能重新安装torch了，可以参考以下表格
> 
> cuda	 
> 9.2	conda install pytorch==1.7.0 torchvision==0.8.0 torchaudio==0.7.0 cudatoolkit=9.2 -c pytorch
> 10.2	conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=10.2 -c pytorch
> 11.1	conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=11.1 -c pytorch

好的，谢谢

**Comment by wwfcnu** [comment]
> pip install pytorch不行，只有torch
