### ISSUE TITLE
AssertionError / TypeError 两处报错疑问

### ISSUE THREAD

**Issue by mattzheng** [alibaba-damo-academy/FunASR#295]
系统：ubuntu/gpu docker
模型：Paraformer语音识别-中文-通用-16k-离线-large-长音频版
地址：https://modelscope.cn/models/damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/summary
其他配置：funasr:0.3.1，modelspace:0.4.1，pytorch

报错一：
```
/automatic_speech_recognition/FunASR-main/funasr/utils/timestamp_tools.py in ts_prediction_lfr6_standard(us_alphas, us_peaks, char_list, vad_offset, force_time_shift, sil_in_str)
     37     fire_place = torch.where(peaks>1.0-1e-4)[0].cpu().numpy() + force_time_shift  # total offset
     38     num_peak = len(fire_place)
---> 39     assert num_peak == len(char_list) + 1 # number of peaks is supposed to be number of tokens + 1
     40     # begin silence
     41     if fire_place[0] > START_END_THRESHOLD:

AssertionError: 
```
不确定什么情况，测试音频文件时候，有几个一直报错如上信息
看了issue#266
难道还是这个问题？
`rapid_paraformer推理时当语音中包含英文时，由于英文tokens已经合并，会导致跟时间戳无法对齐`
（https://github.com/alibaba-damo-academy/FunASR/issues/266）

报错二：
```
inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model='damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch',
    vad_model="",
    punc_model='damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch',
    punc_model_revision="v1.1.6")
```
该模型无法设置vad_model = ‘’，会报错：
```
TypeError: 'NoneType' object is not callable
```

**Comment by langgz** [comment]
报错一：音频是什么样的？方便上传么？
报错二：是的，目前长音频版本是需要加vad的，去了vad就不支持长音频输入了，你为什么要去掉vad么？能不能用paraformer-large模型？

**Comment by mattzheng** [comment]
报错一：音频不方便上传，但是这个音频在【Paraformer语音识别-中文-通用-16k-离线-large】是可以识别在【Paraformer语音识别-中文-通用-16k-离线-large-长音频版】是不行的
报错二：我看你在，https://github.com/alibaba-damo-academy/FunASR/discussions/134，提到过取消vad的用法，是最新版本无法取消了？


对了，各个模型VAD,ASR等模型的版本在哪查啊，挖了半天文档没找到地儿。。

**Comment by langgz** [comment]
那方便把【Paraformer语音识别-中文-通用-16k-离线-large】识别结果发一下么？可以先脱敏再发，方便我们排查。
版本号，设成None就可以，只要modelscope版本是最新的，None会自动拉取最新的模型资源，比如，vad模型版本好，你在这里看：
![image](https://user-images.githubusercontent.com/18321252/227787451-cee57c04-b636-42f4-8808-c50142bf7577.png)

**Comment by mattzheng** [comment]
（1）【Paraformer语音识别-中文-通用-16k-离线-large】结果可以节选一部分，当然估计也看不懂：
```
没嗯哎你好，我刚刚其实我刚刚对这个xxxx，我想把地址改一下，
能改吗？对对对对对对啊，是备婚的那个，还是我自己打电话这个啊，
明天你就是那个那个xxxx把他电话告诉你呀。哦，行，等一下会啊，幺三四我知道，
哎，我知道不是不，你不就说对集结那个那个地址的呃，对那个xxx那个地址电话吗？
啊，幺三四嗯嗯啊啊啊，x嗯，姓姓名就改个x女士，谢谢。
```
个人觉得还是【长音频】时间戳出现问题，这些有问题的长音频一般时间较长，近20min，其中一阵子基本没有声音

（2）【长音频】VAD模型处理时候会有部分信息丢失不显示，
VAD这里是否可以放开一些参数，可以调节阈值？

**Comment by azraelkuan** [comment]
@langgz for the second problem, it seems the code miss an implement of paraformer_punc:
![image](https://user-images.githubusercontent.com/23380152/229668677-a0fd16d1-08ad-486d-b082-c8b6c5e4cc46.png)
https://github.com/alibaba-damo-academy/FunASR/blob/cbbb3007436bf7cefa45af9a5aad60c696da9732/funasr/bin/asr_inference_launch.py#L225
