### ISSUE TITLE
流式代码可以看到首尾字延迟吗？

### ISSUE THREAD

**Issue by kFoodie** [alibaba-damo-academy/FunASR#296]
如题。或者有计划写一个这样的工具吗？

**Comment by langgz** [comment]
好想法，我们目前没有人力去做这个事情，如果你方便的话，可以写一个tool哈，可以借助于我们长音频版本的时间戳功能，得到每个字对应的时间，然后安装chunk来送入到流式模型，统计首字时间与时间戳得到的时间做个差值，是首字延时，尾字延时同理哈
