### ISSUE TITLE
更新模型和运行环境modelscope后large模型输出有部分字不是预期内容

### ISSUE THREAD

**Issue by C-Shawn** [alibaba-damo-academy/FunASR#298]
OS: Linux
Python/C++ Version：python 3.7
Package Version：torch==1.13.1、modelscope==1.4.3 、funasr==0.3.2
Model：speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
Command：
        self.inference_16k_pipeline = pipeline(
            task=Tasks.auto_speech_recognition, 
            model=self.model_dir
            )
asr_result = self.inference_16k_pipeline(audio_in=request.audio_data, audio_fs = self.sample_rate)
问题描述：
部分字的输出变为[UNK][UNK][UNK][UNK]，更新模型前输出为汉字内容

**Comment by hnluo** [comment]
我这边把funasr更新到0.3.2，modelscope升级到1.4.3，用speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch模型解码了压缩包里的音频，没有出现解码出unk的情况，你可以拷贝代码跑下解码试试，代码结果如下图：
```python
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model='damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch')

rec_result = inference_pipeline(audio_in="debug.wav")
print(rec_result)
```
![image](https://user-images.githubusercontent.com/42902471/228460220-fd0b75d0-7801-4ae3-bfdf-d634d30a940f.png)

**Comment by C-Shawn** [comment]
找到原因了，是用的paddlespeech的标点模型造成的
