### ISSUE TITLE
训练uniasr

### ISSUE THREAD

**Issue by daizuozhuo** [alibaba-damo-academy/FunASR#3]
https://www.modelscope.cn/models/damo/speech_UniASR_asr_2pass-cn-en-moe-16k-vocab8358-tensorflow1-offline/summary
训练这个uniasr的文档有吗？

**Comment by langgz** [comment]
uniasr模型finetune，需要等modelscope下一个版本发布，预计在12月10号左右，FunASR会同步推出推理&finetune recipe

**Comment by hnluo** [comment]
抱歉，中英自由说uniasr模型的训练pipeline还没集成到代码里面，目前只支持在modelscope上进行推理。预计2023年一月左右会把finetune pipeline集成到FunASR里面，敬请关注。
