### ISSUE TITLE
uniasr模型解码模式

### ISSUE THREAD

**Issue by spxia** [alibaba-damo-academy/FunASR#30]
你好，在使用uniasr模型解码的时候，如何指定不同的解码模式呢？

**Comment by hnluo** [comment]
可以通过修改模型资源目录下的decoding.yaml文件来指定不同的解码模式, 具体如下：
- fast: decoding_ind=0, decoding_mode=model1 
- normal: decoding_ind=0, decoding_mode=model2
- offline：decoding_ind=1, decoding_mode=model2

**Comment by spxia** [comment]
好的。那使用funasr.bin.modelscope_infer调用Tensorflow的模型能这样指定进行流式识别吗？
