### ISSUE TITLE
runtime c++ 测试

### ISSUE THREAD

**Issue by kFoodie** [alibaba-damo-academy/FunASR#302]
能否支持一下本地读取音频进行测试啊.. linux上没麦克风，测试不了啊..
https://github.com/alibaba-damo-academy/FunASR/tree/main/funasr/runtime/grpc
中第5步使用到如下代码
https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/runtime/python/grpc/grpc_main_client_mic.py

**Comment by langgz** [comment]
可以直接读取wav.scp进行测试
