### ISSUE TITLE
UniASR语音识别-中文英文混-训练数据

### ISSUE THREAD

**Issue by Guodong0712** [alibaba-damo-academy/FunASR#31]
@jmwang66 @langgz @onlybetheone @Lizerui9926 
大佬好，我看 mode scope 网站上的介绍，UniASR语音识别-中文英文混-离线/实时 使用到的训练数据是 “5万小时16K中文通用数据、5万小时16K英文通用数据”， 请问是没有用到 中英混合的数据吗？如果用到，大概的数据量是多大呢？
非常感谢。

**Comment by uloveqian2021** [comment]
> 有中英混杂数据的，包含在5万小时16K中文通用数据里面，具体数据量没有统计。您也可以加入我们钉钉服务群（群号：27215013275），方便及时沟通。

请问这5W个小时的数据保函开源的语音识别数据集吗，比如aishell4,wenetspeech等
