### ISSUE TITLE
长音频模型经过vad分割后比large模型多了很多识别错误

### ISSUE THREAD

**Issue by C-Shawn** [alibaba-damo-academy/FunASR#321]
运行环境：modelscope网页

Paraformer-large识别结果：在主会场参会的由国网数字发布会主任告金同志技术处国网处相关同志在分会场参会的有各省公司中国电科院单位集团国网智研院国网新闻产业集团国网新闻公司国网大数据中心相关组织公司领导高度重视人工智能的相关工作要求聚焦规模化和实木化推进相关工作魏主任上周啊也专门召开十一家省公司六家直属单位人工智能规模化应用的研究工作在会上啊魏准也指出啊我们当前人工智能在相关的场景上取得了相应的成果国也进入了一个评定期需要进一步谋定后洞魏主任推求我们人工智能的规模化应用也要求后期的工作作为两个阶段开展一阶段段深入基基进国相相的集团以及公关工作在充分了解

长音频版识别结果：在准备上忘记我国网职演院国网新工厂、国网新闻公司、国网大数据相关组据公司领导高度重视智能的相关工作要求，聚焦规模化和实用化推进效。魏主任上周啊就专门召开十一家省公司六家直属单位的人工智能规模化应维在会上为主。也指出啊，我们当前在相关的场景上取得了相应的成，但也进入了一个稳定期，需要进一步谋定后动系统性推进我们人工智能的规模化应用，也要求后期的工作分为两个阶段，开展一阶段是深入基层进行相应的调研，以及公关工作在充分了解。

[huiyi_pianduan.zip](https://github.com/alibaba-damo-academy/FunASR/files/11121526/huiyi_pianduan.zip)

**Comment by langgz** [comment]
我们vad有做抗噪声训练，具有一定的噪声拒识能力，我听了音频前面有噪声，被vad过滤掉了，如果不想被过滤掉，可以适当调小噪声拒识阈值，具体如下：
![image](https://user-images.githubusercontent.com/18321252/229129366-b8502359-15b6-4d07-adc1-2b1af75c2ba4.png)
