### ISSUE TITLE
ONNX  导出成功，但量化失败

### ISSUE THREAD

**Issue by locasxe** [alibaba-damo-academy/FunASR#327]
OS: linux 
Python : 3.7, C++: 4.8.5
Package Version: pytorch 1.11.0 modelscope 1.4.2 funasr 0.3.2
Model: speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
Command: python -m funasr.export.export_model --model-name ./export/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch --export-dir ./export --type onnx --quantize true
问题描述; onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Protobuf serialization failed. 导出onnx成功，但量化失败

**Comment by locasxe** [comment]
line 481, in quantize_dynamic
    model = load_model(Path(model_input), optimize_model)
是在这一句

**Comment by langgz** [comment]
what is the onnxruntime version

**Comment by locasxe** [comment]
onnxruntime 1.13.1

**Comment by langgz** [comment]
I have tested with these version:
onnx                      1.13.1                   pypi_0    pypi
onnxruntime               1.14.1                   pypi_0    pypi

**Comment by locasxe** [comment]
Thx for your reply.
It seems onnxruntime 1.14.1 doesn't work.
I fix this issue with setting "optimize_model=False" or "use_external_data_format=True" .

**Comment by Chen1399** [comment]
> I have tested with these version: onnx 1.13.1 pypi_0 pypi onnxruntime 1.14.1 pypi_0 pypi

I had the same problem with this configuration.
