### ISSUE TITLE
Cuda OOM when decoding long audio

### ISSUE THREAD

**Issue by treya-lin** [alibaba-damo-academy/FunASR#354]
Hi, I am trying out this model https://modelscope.cn/models/damo/speech_UniASR_asr_2pass-cn-dialect-16k-vocab8358-tensorflow1-online/summary . It worked ok when I tested it with a short wav file, but failed when trying to decode a long wav audio with duration of 22 min. 

On the website it says the model can process the audio directly without doing VAD in advance. But when I used it to decode this long audio, it took about half an hour and then returned a Cuda OOM error, is this normal? If not how may I fix it? 

And May I know how to integrate the VAD models and ASR models from model scope to process multiple long audio files? I didn't find much documentation about that. I mean like in kaldi we do vad on the dataset and get segments and then we do asr on segments. How to accomplish the same result in modelscope and funasr? Thanks

codes I used
```
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks
p = pipeline(Tasks.auto_speech_recognition, 'damo/speech_UniASR_asr_2pass-cn-dialect-16k-vocab8358-tensorflow1-offline')
wavpath = 'samples/0004.wav' # long wav audio
text = p(wavpath) 
```
at `p(wavpath)`  it got stuck, doing decoding for like half an hour and threw a cuda oom error saying it needed about 19.+GB (my gpu has 10GB memory)

my environment:
```
Name: torch
Version: 1.9.0+cu102

Name: tensorflow-gpu
Version: 2.2.0

Name: funasr
Version: 0.4.0

Name: modelscope
Version: 1.4.3
```

**Comment by hnluo** [comment]
Hi, you can combine vad and asr model by pipeline to decode a long wav audio, please refer to [how to use vad, asr and punc model by pipeline](https://github.com/alibaba-damo-academy/FunASR/discussions/278)
