### ISSUE TITLE
Modelscope Funasr版本语音识别性能疑问

### ISSUE THREAD

**Issue by icylord** [alibaba-damo-academy/FunASR#368]
如下代码：
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

import time

inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model=
    'damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch')

rec_result = inference_pipeline(audio_in='./test_audio/asr_example_zh.wav')

st = time.time()
rec_result = inference_pipeline(audio_in='./test_audio/asr_example_zh.wav')
et = time.time()
print(et - st)

Modelscope依赖中funasr的不同版本耗时差距有点大。
其中 funasr==0.3.1 耗时：0.29877328872680664
而 funasr==0.4.1 耗时：0.670555830001831 
具体是什么原因？

**Comment by icylord** [comment]
> Do you use the pipeline on cpu?

cpu版本，其它都一样，除了funasr我切换了不同的版本

**Comment by langgz** [comment]
> > Do you use the pipeline on cpu?
> 
> cpu版本，其它都一样，除了funasr我切换了不同的版本

We have set the torch.set_num_threads(1) for the  num_threads of cpu (faster speed), if you want to decode with 1 threads, you could change it:

https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/bin/asr_inference_launch.py#L6

**Comment by langgz** [comment]
> > > > Do you use the pipeline on cpu?
> > > 
> > > 
> > > cpu版本，其它都一样，除了funasr我切换了不同的版本
> > 
> > 
> > We have set the torch.set_num_threads(1) for the num_threads of cpu (faster speed), if you want to decode with 1 threads, you could change it:
> > https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/bin/asr_inference_launch.py#L6
> 
> funasr==0.4.1 加了 torch.set_num_threads(1) 或者 torch.set_num_threads(4) 耗时并没有什么变化。 我的疑问是否是0.3.1 与 0.4.1的代码差异导致了整个耗时变化？

delete 
torch.set_num_threads(1)

then 
pip install -e ./

**Comment by icylord** [comment]
> 

3Q
