### ISSUE TITLE
large-asr推理问题

### ISSUE THREAD

**Issue by wwfcnu** [alibaba-damo-academy/FunASR#372]
asr推理时，输出的text和token一样，每个字之间都有空格

**Comment by wwfcnu** [comment]
modelscope1.4.3版本是正常的，更新之后，推理速度快了很多，但是使用你们提供的推理代码，输出到output/1best_recog中的text中每个字中都有空格

**Comment by wwfcnu** [comment]
生成的text文本如下
<img width="612" alt="image" src="https://user-images.githubusercontent.com/109075309/232747068-e6731272-a125-43bb-a6a1-9ebb40a1ffbc.png">

**Comment by wwfcnu** [comment]
egs_modelscope/asr/paraformer/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch)/infer.sh

**Comment by Lizerui9926** [comment]
相较以前版本，当前版本的recipe在执行infer.sh脚本写入text文件时会在字之间加入空格，同时改为使用text文件来计算WER(中文CER/英文WER)，修复了之前英文计算WER的问题，具体可以看下这个commit：https://github.com/alibaba-damo-academy/FunASR/commit/cf843d144aef53a668daea6c373c29bd89a0e19d

**Comment by wwfcnu** [comment]
> 相较以前版本，当前版本的recipe在执行infer.sh脚本写入text文件时会在字之间加入空格，同时改为使用text文件来计算WER(中文CER/英文WER)，修复了之前英文计算WER的问题，具体可以看下这个commit：[cf843d1](https://github.com/alibaba-damo-academy/FunASR/commit/cf843d144aef53a668daea6c373c29bd89a0e19d)
在text之间加入空格不是和token一样了，这么做是出于什么考虑呢，如果我不想在字之间加空格，应该修改哪块的代码

**Comment by Lizerui9926** [comment]
考虑对英文的处理。
https://github.com/alibaba-damo-academy/FunASR/blob/cf843d144aef53a668daea6c373c29bd89a0e19d/funasr/bin/asr_inference_paraformer.py#L800  
可以将这行代码改为 `ibest_writer["text"][key] = text_postprocessed`

**Comment by wwfcnu** [comment]
而且用infer.sh计算的wer好像有点问题
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/109075309/233030198-b41893a5-abef-411c-901d-6bdf9d6823d0.png">

**Comment by wwfcnu** [comment]
> 测试数据的text标注需要以空格进行分隔开

好的，多谢
