### ISSUE TITLE
特征抽取进度问题

### ISSUE THREAD

**Issue by hzfei** [alibaba-damo-academy/FunASR#373]
系统： ubuntu20.04
CPU： 72core
内存:    256G
提特征进程数:   8
第一次学习funasr，在aishell paraformer提特征过程中，一直看不到进度。目前提了4个多小时了，查看feats.N.scp文件，大胆预测还有2个多小时才能完成。可否在run.sh提特征相关代码里加个进度条？

**Comment by jmwang66** [comment]
你好，感谢反馈，我们后续会增加关于特征提取进度的提示

**Comment by langgz** [comment]
我测试了一下，32进程，大概3个小时

**Comment by hzfei** [comment]
我的电脑配置：
128核+256G内存，处理完要20个小时。64进程，处理完要20小时了，，，

**Comment by jmwang66** [comment]
In the academic recipe, "wav" is used as the default input format and only CMVN is computed in the feature extraction stage without saving the extracted features. It has been tested that the computation can be completed within 1.5 hours using 64 processes for AISHELL-1 dataset. For more details, please refer to stage 1 of the academic recipe.

**Comment by kli017** [comment]
请问必须要在stage1提取feature并保存吗？有没有参数在train时候提取呢

**Comment by hnluo** [comment]
In the academic recipe, stage 1 just computes cmvn feature without saving fbank features, you can try run.sh.
