### ISSUE TITLE
Parformer-large模型时间戳和token如何对应

### ISSUE THREAD

**Issue by qier777** [alibaba-damo-academy/FunASR#374]
OS: linux 
Python3.7
Package Version：pytorch1.3.0、modelscope1.2.0与funasr 0.1.6  
Model：damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch
Command：python infer.py
问题描述：
运行后得到results文件夹，从文件夹中，提取text和timestamp文件，统计里面的元素，text和timpstape元素数量不一致，如何确定token和时间戳的对应关系？

Error log：运行后得到results文件夹，从文件夹中，提取text和timestamp文件，统计里面的元素，text和timpstape元素数量不一致，如何确定token和时间戳的对应关系？

**Comment by R1ckShi** [comment]
首先请务必更新modelscope与funasr至最新，截止目前最新的版本是modelscope 1.4.3和funasr 0.4.0
在inference的结果rec_result中除了text字段之外还包含text_postprocessed字段，按空格分隔之后与timestamp字段中的时间戳列表是等长的
