### ISSUE TITLE
How to release cuda memory when inferencing with uniASR?

### ISSUE THREAD

**Issue by treya-lin** [alibaba-damo-academy/FunASR#377]
Hi , I am basically following this pipeline https://github.com/alibaba-damo-academy/FunASR/discussions/278 to decode many long audio files. And I noticed that the pipeline of modelscope is not releasing the memory on gpu after processing an audio, making the cuda memory usage keeps going up.

I am basically processing each audio with the vad, asr, and  punc model step by step

```
for wav,path in tqdm(wav2path_all.items()):
    filename,ext = os.path.splitext(wav)
    outpath = os.path.join(outdir,filename + '.txt')
    if os.path.exists(outpath):
      continue
    wav2path = {wav:path}
    wav2waveform = load_wav(wav2path,model_sr = 16000)
    wav2segments = vad(wav2waveform) # doing vad for the current audio
    wav2results = asr(wav2waveform,wav2segments) # doing asr and adding punc for the current audio
    write_results(wav2results,outdir)
```

Below shows the models I used and how the models were loaded in the first place:
```
# vad pipeline
  inference_pipeline_vad = pipeline(
    task=Tasks.voice_activity_detection,
    model='damo/speech_fsmn_vad_zh-cn-16k-common-pytorch',
    model_revision=None,
  )
  # asr pipeline
  inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model='damo/speech_UniASR_asr_2pass-cn-dialect-16k-vocab8358-tensorflow1-offline')
  # punc pipeline
  inference_pipeline_punc = pipeline(
    task=Tasks.punctuation,
    model='damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727',
    model_revision=None,
  )
  param_punc_dict = {"cache": []}

```
Supposedly only the models themselves and the current audio information are taking up the memory on GPU right? But it turns out that the used cuda memory keeps going up, originally only 2G was taken up when initializing the model, and as the script has processed about 80 audios, the gpu memory has reached 10GB, obvioiusly at some point the memory was not released in time.
Do you have any idea what shall be done to avoid this? Thank you very much

**Comment by langgz** [comment]
Thank you for feedback, and we will look for it.

**Comment by langgz** [comment]
Bug has been fixed, please update funasr
git pull
pip install -e ./

https://github.com/alibaba-damo-academy/FunASR/commit/49be65031b2510b6b94516174ea93019407a1aad

**Comment by treya-lin** [comment]
> Bug has been fixed, please update funasr git pull pip install -e ./
> 
> [49be650](https://github.com/alibaba-damo-academy/FunASR/commit/49be65031b2510b6b94516174ea93019407a1aad)

Cool! Thanks!
