### ISSUE TITLE
bug exists in funasr/models/e2e_vad.py

### ISSUE THREAD

**Issue by ospeech** [alibaba-damo-academy/FunASR#38]
def ComputeDecibel(self) -> None:
        frame_sample_length = int(self.vad_opts.frame_length_ms * self.vad_opts.sample_rate / 1000)
        frame_shift_length = int(self.vad_opts.frame_in_ms * self.vad_opts.sample_rate / 1000)
        self.data_buf = self.waveform[0]  # 指向self.waveform[0]
        
        for offset in range(0, self.waveform.shape[1] - frame_sample_length, frame_shift_length):
            self.decibel.append(
                10 * math.log10((self.waveform[0][offset: offset + frame_sample_length]).square().sum() + \
                                0.000001))

if  ( self.waveform.shape[1] - frame_sample_length) % frame_shift_length == 0  will cause "assert len(self.decibel) == len(self.scores[0])  # 保证帧数一致"  fail. 
len(self.decibel) is  1 less than len(self.scores[0]).

maybe duplicate last item for self.decibel while no remainder.

**Comment by lingyunfly** [comment]
We has modify the range by adding 1 on dev branch, later will merge it in to main branch.
