### ISSUE TITLE
aishell paraformer 3090*2 core dumped

### ISSUE THREAD

**Issue by hzfei** [alibaba-damo-academy/FunASR#381]
![企业微信截图_16818706894229](https://user-images.githubusercontent.com/42926130/232949940-d4eb9601-0964-4757-9a0f-d6eb2d230d5a.png)

**Comment by hnluo** [comment]
麻烦按照这种格式提问，这样方便看问题：
OS: [e.g. linux] 说明操作系统
Python/C++ Version：说明语言及版本号
Package Version：pytorch、modelscope与funasr版本
Model：什么模型
Command：运行命令和输入
问题描述：
Error log：错误提示

**Comment by hzfei** [comment]
这样提问题也太累了吧

**Comment by hzfei** [comment]
OS: ubuntu20.04
Python：3.7.16
Package Version：pytorch==1.13.1+cu117、modelscope==1.4.3、funasr==0.4.0
Model：funasr/egs/aishell/paraformer,直接run.sh
Command：taskset -c c1--cN bash run.sh --stage 3 --stop_stage 3
问题描述：
Error log：
![企业微信截图_16818706894229](https://user-images.githubusercontent.com/42926130/232956925-7bdacecc-dc70-406d-93d1-e63867400f06.png)

**Comment by hzfei** [comment]
同上环境，aishell抽取特征速度怎么那么慢呢？
GPU： 4090*4
内存： 256G
cpu: 128c
目测，特征抽完大概要12小时。

**Comment by hzfei** [comment]
aishell抽取特征，占用64core,nj=64,256内存，目前运行17小时，大概只运行了三分之二。请问这咋回事？

**Comment by hzfei** [comment]
数据生成完之后，训练几分钟就停了。
[train.log.0.txt](https://github.com/alibaba-damo-academy/FunASR/files/11280854/train.log.0.txt)
[train.log.1.txt](https://github.com/alibaba-damo-academy/FunASR/files/11280864/train.log.1.txt)
