### ISSUE TITLE
paraformer streaming model has no attribute 'encode_chunk'?

### ISSUE THREAD

**Issue by ospeech** [alibaba-damo-academy/FunASR#382]
while running egs_modelscope/asr/paraformer/speech_paraformer_asr_nat-zh-cn-16k-common-vocab8404-online/infer.py ,get the error as follows:
===============
File "/root/FunASR_2/funasr/bin/asr_inference_paraformer_streaming.py", line 226, in __call__
    enc, enc_len = self.asr_model.encode_chunk(feats, feats_len, cache)
  File "/root/miniconda3/envs/funasr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1270, in __getattr__
    type(self).__name__, name))
AttributeError: 'Paraformer' object has no attribute 'encode_chunk'
===============
check the conda envs:
funasr---0.4.1
modelscope---1.5.0
python---3.7.16
torch---1.13.1

any advice for this?

**Comment by hnluo** [comment]
Please update model revision

**Comment by ospeech** [comment]
> Please update model revision

how to update it? i have tried some values, like 'v1.5.0' , in inferece_pipeline().
inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model='damo/speech_paraformer_asr_nat-zh-cn-16k-common-vocab8404-online',
    model_revision='v1.5.0')
 it didn't work.

**Comment by hnluo** [comment]
```python
import os
import logging
import torch
import soundfile

from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks
from modelscope.utils.logger import get_logger

logger = get_logger(log_level=logging.CRITICAL)
logger.setLevel(logging.CRITICAL)

inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model='damo/speech_paraformer_asr_nat-zh-cn-16k-common-vocab8404-online',
    model_revision='v1.0.3'
)

rec_result = inference_pipeline(audio_in='https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/asr_example_zh.wav')
print(rec_result)
```

**Comment by ospeech** [comment]
it still doesn't work! maybe something wrong with environment. Thanks!
