### ISSUE TITLE
Paraformer-large热词版模型如何加时间戳

### ISSUE THREAD

**Issue by qier777** [alibaba-damo-academy/FunASR#387]
OS: linux
Python：python3.7
Package Version：pytorch=  1.3.0   、modelscope 1.5.0      与funasr 0.4.1  
Model：speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404
Command：python infer.py
问题描述：
Error log：在热词版模型上，加入时间戳模型，报错。 No such file or directory: 'cpu'

**Comment by langgz** [comment]
Ref to [docs](https://alibaba-damo-academy.github.io/FunASR/en/modescope_pipeline/quick_start.html)

**Comment by buaibieshanghai** [comment]
> OS: linux Python：python3.7 Package Version：pytorch= 1.3.0 、modelscope 1.5.0 与funasr 0.4.1 Model：speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404 Command：python infer.py 问题描述： Error log：在热词版模型上，加入时间戳模型，报错。 No such file or directory: 'cpu'

问题解决了吗，热词和时间戳能否同时生效？
