### ISSUE TITLE
关于asr推理的问题

### ISSUE THREAD

**Issue by wwfcnu** [alibaba-damo-academy/FunASR#393]
> > ref to [recipe](https://github.com/alibaba-damo-academy/FunASR/blob/main/egs/aishell/transformer/utils/process_opus.py) 参考食谱
> 
> 这个脚本是提前对语音进行了切割，并输出了切割后的语音 我的意思是可不可以不提前切割，而是按照segment的start，end去读语音做推理呢
#390

**Comment by wwfcnu** [comment]
如果要支持这种输入的话，应该怎么修改pipeline

**Comment by langgz** [comment]
自己手动处理一下，再送到pipeline里面推理，pipeline支持采样点作为输入，具体用法见[docs](https://alibaba-damo-academy.github.io/FunASR/en/modescope_pipeline/asr_pipeline.html#infer-pipeline)

**Comment by wwfcnu** [comment]
> 自己手动处理一下，再送到pipeline里面推理，pipeline支持采样点作为输入，具体用法见[docs](https://alibaba-damo-academy.github.io/FunASR/en/modescope_pipeline/asr_pipeline.html#infer-pipeline)

目前asr的推理代码infer.sh的输入应该是wav.scp的形式吧

**Comment by wwfcnu** [comment]
> 自己手动处理一下，再送到pipeline里面推理，pipeline支持采样点作为输入，具体用法见[docs](https://alibaba-damo-academy.github.io/FunASR/en/modescope_pipeline/asr_pipeline.html#infer-pipeline)

采样点输入可以多批次吗，我输入一个列表不行呀
