### ISSUE TITLE
aishell paraformer finetune之后，如何使用微调后的模型

### ISSUE THREAD

**Issue by hzfei** [alibaba-damo-academy/FunASR#394]
https://github.com/alibaba-damo-academy/FunASR/blob/main/egs_modelscope/asr/paraformer/speech_paraformer_asr_nat-zh-cn-16k-aishell1-vocab4234-pytorch/infer.py
直接python infer.py就是用已微调的模型了？恕我直言，这文档写得稀里糊涂的。生成的checkpoint里一堆东西，也没一个文档来解释一下。

**Comment by langgz** [comment]
所有文档都在github.io里面，如果有写的不清楚的可以来反馈，文档建设中，[docs](https://alibaba-damo-academy.github.io/FunASR/en/modescope_pipeline/asr_pipeline.html#inference-with-multi-thread-cpus-or-multi-gpus)

**Comment by hzfei** [comment]
怎么确定是用了自己微调的模型？model="damo/XXX"这个参数不用改吗？
checkpoint_dir=“./checkpoint”
checkpoint_name=r"XXX" 就是用了自己finetune之后的模型了？

**Comment by langgz** [comment]
是的，model不用修改。aishell上的模型，只能batch_size=1，建议cpu多线推理

**Comment by langgz** [comment]
model是你finetune之前的原来modelscope里面的model name
