### ISSUE TITLE
为何同一个数据，bytes类型输入和wav文件读取成numpy再输入，结果预测会不一致呢？

### ISSUE THREAD

**Issue by shumeirao** [alibaba-damo-academy/FunASR#409]

**Comment by langgz** [comment]
提问格式：

OS: [e.g. linux] 说明操作系统
Python/C++ Version：说明语言及版本号
Package Version：pytorch、modelscope与funasr版本
Model：什么模型
Command：运行命令和输入
问题描述：
Error log：错误提示

**Comment by shumeirao** [comment]
> 提问格式：
> 
> OS: [e.g. linux] 说明操作系统 Python/C++ Version：说明语言及版本号 Package Version：pytorch、modelscope与funasr版本 Model：什么模型 Command：运行命令和输入 问题描述： Error log：错误提示

模型为：speech_paraformer_asr_nat-zh-cn-16k-common-vocab8358-tensorflow1
用的AMD显卡，AMD版本的pytorch，modelscope:1.3.2 funasr:0.4.3

**Comment by langgz** [comment]
modelscope版本太低了，按照这个文档升级一下modelscope版本就可以了（modelscope-1.5.3）：
https://alibaba-damo-academy.github.io/FunASR/en/installation.html#install-modelscope-optional

**Comment by shumeirao** [comment]
> modelscope版本太低了，按照这个文档升级一下modelscope版本就可以了（modelscope-1.5.3）： https://alibaba-damo-academy.github.io/FunASR/en/installation.html#install-modelscope-optional

好的，感谢
