### ISSUE TITLE
开源的预训练模型跑起来很慢

### ISSUE THREAD

**Issue by ziyu123** [alibaba-damo-academy/FunASR#41]
请问，我在跑speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch 开源模型的时候，无论是用modelscope.pipelines 调用，还是funasr.bin.asr_inference_paraformer下的Speech2Text 调用，都很慢，大概5s的音频需要4点多秒，rtf大概0.9左右，这个情况正常吗？(cpu下运行，linux系统，内存 256G和cpu核数 64)

**Comment by langgz** [comment]
不正常，您是单条wav推理么？funasr版本是多少？以前的版本对于单条音频输入，确实存在rtf很高的现象，我们在funasr0.1.6种修复了这个问题。可以加我们钉钉群，详细讨论一下

**Comment by ziyu123** [comment]
我用的0.1.4版本的，好的，我试试最新版本的，谢谢。

**Comment by langgz** [comment]
请问问题解决了么？如果已经结局了，请close问题哈
