### ISSUE TITLE
Failed to run funasr-onnx-offline demo.

### ISSUE THREAD

**Issue by Darlig** [alibaba-damo-academy/FunASR#425]
OS: Ubuntu 18.04
Python: 3.8.15, C++: 7.5.0
Package Version: torch 2.0.0 modelscope 1.5.2 funasr 0.4.3 (onnx 1.13.1 onnxruntime 1.14.1)
Model: speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
Command: bin/funasr-onnx-offline export/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/ asr_vad_punc_example.wav false false false
问题描述：按照readme编译onnxruntime后，运行demo验证，遇到报错。(使用音频文件为16kHz, 16bit PCM, 约13s的文件）
Error log: 
Model initialization takes 1.611325s.
2023-04-26 16:22:01.185645992 [E:onnxruntime:, sequential_executor.cc:494 ExecuteKernel] Non-zero status code returned while running Conv node. Name:'/encoder/encoders0/encoders0.0/self_attn/fsmn_block/Conv' Status Message: Invalid input shape: {10}
Non-zero status code returned while running Conv node. Name:'/encoder/encoders0/encoders0.0/self_attn/fsmn_block/Conv' Status Message: Invalid input shape: {10}Result:  
Audio length 0.000813s.
Model inference takes 0.000510s.
Model inference RTF: 0.627692.

**Comment by lyblsgo** [comment]
拉下最新的代码试试，欢迎加入钉钉群：群号 27215013275

**Comment by Darlig** [comment]
拉取了最新代码（commit: 5dcfaeec14909eb0bd739f7c1b2dddd6f1b84f02) ，还是报错。换了其他音频文件，或者把原来的出错的音频文件使用sox截取0-10s片段，都可以正常识别。出错的情况如下：

Command: bin/funasr-onnx-offline --am-config ../export/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/config.yaml --am-cmvn ../export/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/am.mvn --am-model ../export/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/model.onnx --wav-path ../testdata/asr_vad_punc_example.wav

Error log:
I20230427 16:57:03.447063  9930 funasr-onnx-offline.cpp:27] am-model : ../export/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/model.onnx
I20230427 16:57:03.447172  9930 funasr-onnx-offline.cpp:27] am-cmvn : ../export/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/am.mvn
I20230427 16:57:03.447187  9930 funasr-onnx-offline.cpp:27] am-config : ../export/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/config.yaml
I20230427 16:57:03.447199  9930 funasr-onnx-offline.cpp:27] wav-path : ../testdata/asr_vad_punc_example.wav
I20230427 16:57:05.054219  9930 funasr-onnx-offline.cpp:90] Model initialization takes 1.60701 s
2023-04-27 16:57:05.054703596 [E:onnxruntime:, sequential_executor.cc:494 ExecuteKernel] Non-zero status code returned while running Conv node. Name:'/encoder/encoders0/encoders0.0/self_attn/fsmn_block/Conv' Status Message: Invalid input shape: {10}
Non-zero status code returned while running Conv node. Name:'/encoder/encoders0/encoders0.0/self_attn/fsmn_block/Conv' Status Message: Invalid input shape: {10}Result:
I20230427 16:57:05.054764  9930 funasr-onnx-offline.cpp:138] Audio length: 0.0008125 s
I20230427 16:57:05.054774  9930 funasr-onnx-offline.cpp:139] Model inference takes: 0.000513 s
I20230427 16:57:05.054780  9930 funasr-onnx-offline.cpp:140] Model inference RTF: 0.631385

**Comment by lanlli** [comment]
请问这个问题解决了吗，我也遇到了这个问题

**Comment by lyblsgo** [comment]
@Darlig @lanlli 已解决，拉下最新的代码

**Comment by jinwater88** [comment]
@lyblsgo ./funasr-onnx-offline --model-dir /media/DataWork/code/sensevoice0825/funasr_models/iic/SenseVoiceSmall --wav-path /media/DataWork/code/sensevoice0825/data/asr_example_zh.wav
I20250828 10:56:56.403805 59868 funasr-onnx-offline.cpp:37] model-dir : /media/DataWork/code/sensevoice0825/funasr_models/iic/SenseVoiceSmall
I20250828 10:56:56.403862 59868 funasr-onnx-offline.cpp:37] quantize : true
I20250828 10:56:56.403868 59868 funasr-onnx-offline.cpp:37] bladedisc : true
I20250828 10:56:56.403872 59868 funasr-onnx-offline.cpp:37] vad-dir : 
I20250828 10:56:56.403877 59868 funasr-onnx-offline.cpp:37] vad-quant : true
I20250828 10:56:56.403883 59868 funasr-onnx-offline.cpp:37] punc-dir : 
I20250828 10:56:56.403887 59868 funasr-onnx-offline.cpp:37] punc-quant : true
I20250828 10:56:56.403891 59868 funasr-onnx-offline.cpp:37] itn-dir : 
I20250828 10:56:56.403895 59868 funasr-onnx-offline.cpp:37] lm-dir : 
I20250828 10:56:56.403898 59868 funasr-onnx-offline.cpp:37] wav-path : /media/DataWork/code/sensevoice0825/data/asr_example_zh.wav
I20250828 10:56:56.403923 59868 offline-stream.cpp:22] VAD model file is not exist, skip load vad model.
I20250828 10:56:57.631628 59868 sensevoice-small.cpp:39] Successfully load model from /media/DataWork/code/sensevoice0825/funasr_models/iic/SenseVoiceSmall/model_quant.onnx
I20250828 10:56:57.647794 59868 offline-stream.cpp:123] PUNC model file is not exist, skip load punc model.
I20250828 10:56:57.647818 59868 funasr-onnx-offline.cpp:124] hotword path: 
I20250828 10:56:57.647821 59868 funasr-onnx-offline.cpp:130] Model initialization takes 1.24392 s
段错误    这是怎么回事呢
