### ISSUE TITLE
batch_size not work while inference with  Paraformer-large长音频模型

### ISSUE THREAD

**Issue by ospeech** [alibaba-damo-academy/FunASR#43]
refer to egs_modelscope/asr_vad_punc/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch/infer.py, batch_size seems not to work with different setting, getting almost 8x relative speed. 
Computing resourse (mem, gpu-util) remains alots, so is there any method to get more relative speech ?
the version of funasr is 0.1.6, and modelscope is 1.2.0

**Comment by langgz** [comment]
Sorry, the paraformer-large长音频模型could not decode with batch due to the vad model. We would soon improve it by decoding vad with batch of 1, while decoding the paraformer with batch >1. Please join our dingding group or wechat for the newest updates.
