### ISSUE TITLE
编译ONNXRuntime-cpp时报错

### ISSUE THREAD

**Issue by lanlli** [alibaba-damo-academy/FunASR#451]
In file included from /root/FunASR/funasr/runtime/onnxruntime/src/precomp.h:36,
                 from /root/FunASR/funasr/runtime/onnxruntime/src/alignedmem.cpp:1:
/root/FunASR/funasr/runtime/onnxruntime/src/e2e-vad.h: In member function ‘void E2EVadModel::PopDataToOutputBuf(int, int, bool, bool, bool)’:
/root/FunASR/funasr/runtime/onnxruntime/src/e2e-vad.h:509:38: error: ‘data_buf’ was not declared in this scope
             cur_seg.buffer.push_back(data_buf.back());
                                      ^~~~~~~~
/root/FunASR/funasr/runtime/onnxruntime/src/e2e-vad.h:509:38: note: suggested alternative: ‘setvbuf’
             cur_seg.buffer.push_back(data_buf.back());
                                      ^~~~~~~~
                                      setvbuf
/root/FunASR/funasr/runtime/onnxruntime/src/e2e-vad.h:513:38: error: ‘data_buf’ was not declared in this scope
             cur_seg.buffer.push_back(data_buf.back());
                                      ^~~~~~~~
/root/FunASR/funasr/runtime/onnxruntime/src/e2e-vad.h:513:38: note: suggested alternative: ‘setvbuf’
             cur_seg.buffer.push_back(data_buf.back());
                                      ^~~~~~~~
                                      setvbuf
make[2]: *** [src/CMakeFiles/funasr.dir/build.make:76: src/CMakeFiles/funasr.dir/alignedmem.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:293: src/CMakeFiles/funasr.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by langgz** [comment]
Bug has been fixed. Please update the code.
https://github.com/alibaba-damo-academy/FunASR/issues/451
