### ISSUE TITLE
 Paraformer-Tiny

### ISSUE THREAD

**Issue by uloveqian2021** [alibaba-damo-academy/FunASR#49]
目前支持Paraformer-Tiny模型的推理吗

**Comment by R1ckShi** [comment]
you can check out egs_modelscope/asr/paraformer/speech_paraformer-tiny-commandword_asr_nat-zh-cn-16k-vocab544-pytorch for paraforer-tiny inference, note that funasr-0.1.6, modelscope-1.2.0 is required.
