### ISSUE TITLE
导出模型有问题,local variable 'model' referenced before assignment

### ISSUE THREAD

**Issue by monkeycc** [alibaba-damo-academy/FunASR#502]
grpc-python教程,

`python -m funasr.export.export_model --model-name damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch --export-dir ./export --type onnx --quantize True`
```

python -m funasr.export.export_model --model-name damo/speech_UniASR_asr_2pass-zh-cn-8k-common-vocab3445-pytorch-online --export-dir ./export --type onnx --quantize True
output dir: export
2023-05-11 22:15:52,796 - modelscope - INFO - Model revision not specified, use the latest revision: v1.1.8
Downloading: 100%|████████████████████████████████████████████████████████████████████████| 11.0k/11.0k [00:00<?, ?B/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████| 173k/173k [00:00<00:00, 1.22MB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████| 27.6k/27.6k [00:00<?, ?B/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████| 459/459 [00:00<?, ?B/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████| 148/148 [00:00<?, ?B/s]
Downloading: 100%|████████████████████████████████████████████████████████████████| 1.51k/1.51k [00:00<00:00, 1.54MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████| 402M/402M [00:12<00:00, 34.8MB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████| 8.14k/8.14k [00:00<?, ?B/s]
Downloading: 100%|████████████████████████████████████████████████████████████████| 11.3M/11.3M [00:00<00:00, 20.2MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████| 83.8k/83.8k [00:00<00:00, 895kB/s]
Traceback (most recent call last):
  File "D:\anaconda3\envs\funasr\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\anaconda3\envs\funasr\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\0SDXX\FunASR\funasr\export\export_model.py", line 285, in <module>
    export_model.export(args.model_name)
  File "D:\0SDXX\FunASR\funasr\export\export_model.py", line 221, in export
    self._export(model, tag_name)
UnboundLocalError: local variable 'model' referenced before assignment
```

**Comment by langgz** [comment]
online model is not supported to export onnx yet

**Comment by LRY1994** [comment]
> online model is not supported to export onnx yet

python -m funasr.export.export_model --model-name damo/speech_UniASR_asr_2pass-cantonese-CHS-16k-common-vocab1468-tensorflow1-offline --export-dir ./export --type onnx --quantize false

the same problem with the offline model

**Comment by LauraGPT** [comment]
> > online model is not supported to export onnx yet
> 
> python -m funasr.export.export_model --model-name damo/speech_UniASR_asr_2pass-cantonese-CHS-16k-common-vocab1468-tensorflow1-offline --export-dir ./export --type onnx --quantize false
> 
> the same problem with the offline model

UniASR model could not export onnx

**Comment by LRY1994** [comment]
> > > online model is not supported to export onnx yet
> > 
> > 
> > python -m funasr.export.export_model --model-name damo/speech_UniASR_asr_2pass-cantonese-CHS-16k-common-vocab1468-tensorflow1-offline --export-dir ./export --type onnx --quantize false
> > the same problem with the offline model
> 
> UniASR model could not export onnx

any plan to support it ?

**Comment by LRY1994** [comment]
model = AutoModel(model="dengcunqin/speech_paraformer-large_asr_nat-zh-cantonese-en-16k-vocab8501-online")
res = model.export(type="onnx", quantize=False)

is it caused by the reason 'online model is not supported to export onnx yet' ???

Traceback (most recent call last):
  File "/data/linry/FunASRv1.0/my.py", line 107, in <module>
    export()
  File "/data/linry/FunASRv1.0/my.py", line 82, in export
    res = model.export(type="onnx", quantize=False)
  File "/data/linry/FunASRv1.0/funasr/auto/auto_model.py", line 495, in export
    export_dir = export_utils.export_onnx(
  File "/data/linry/FunASRv1.0/funasr/utils/export_utils.py", line 11, in export_onnx
    model_scripts = model.export(**kwargs)
  File "/data/linry/FunASRv1.0/funasr/models/paraformer/model.py", line 560, in export
    self.encoder = encoder_class(self.encoder, onnx=is_onnx)
TypeError: 'NoneType' object is not callable
