### ISSUE TITLE
vad模型导出后，在ONNXRuntime-cpp下运作，推理结果与导出前不一致

### ISSUE THREAD

**Issue by Mumasr** [alibaba-damo-academy/FunASR#535]
/modelscope/hub/damo/speech_fsmn_vad_zh-cn-16k-common-pytorch/  这个模型

导出前结果：
2023-05-22 14:31:08,739 (voice_activity_detection_pipeline:218) INFO: VAD Processing ...
[[3550, 10850], [11130, 16640], [17570, 20310], [20760, 25740], [26020, 27850], [28290, 29890], [30400, 32310], [33110, 34430], [35850, 37550], [38060, 40910], [41190, 42720], [43380, 51660], [52690, 55950], [56380, 60360], [60820, 78710], [79910, 83520]]

导出后结果：
I20230522 14:31:46.772238  5096 funasr-onnx-offline-vad.cpp:58] [[4600,10720],[11040,12570],[12850,13830],[14110,16520],[17580,20250],[20770,25420],[26110,27530],[28320,29710],[30410,32110],[33110,34260],[35870,37400],[38060,40690],[41180,42650],[43410,51620],[52760,53820],[54100,55830],[56320,60240],[60820,65600],[65910,78610],[79910,83520]]

测试音频见附件
没改动过源码，都是跟着文档测试
对了下Onnxruntime/fsmn-vad内跟funasr/vad_inferernce下读到的模型参数
都是一致的，读的同一个模型下的模型参数，暂时不知道问题出在哪

[test16000.zip](https://github.com/alibaba-damo-academy/FunASR/files/11529529/test16000.zip)

**Comment by lyblsgo** [comment]
![Uploading image.png…]()

**Comment by lyblsgo** [comment]
https://github.com/alibaba-damo-academy/FunASR/blob/1ee853bff5a0ddd1247bc05ccde128f875361746/funasr/runtime/onnxruntime/src/fsmn-vad.cpp#L177

**Comment by lyblsgo** [comment]
https://github.com/alibaba-damo-academy/FunASR/blob/1ee853bff5a0ddd1247bc05ccde128f875361746/funasr/runtime/onnxruntime/src/fsmn-vad.cpp#L177
cpp、python提特征的输入是一样的

**Comment by Mumasr** [comment]
> https://github.com/alibaba-damo-academy/FunASR/blob/1ee853bff5a0ddd1247bc05ccde128f875361746/funasr/runtime/onnxruntime/src/fsmn-vad.cpp#L177
> 
> 
> cpp、python提特征的输入是一样的

噢我上两周拉的仓库，没有这几行，你上周修了，那可以关了

**Comment by xiangyun-hz** [comment]
想问下，您是怎么导出vad的onnx模型的？
