### ISSUE TITLE
如何取消输出INFO和Warning？

### ISSUE THREAD

**Issue by damengdameng** [alibaba-damo-academy/FunASR#537]
如上
尝试了[论坛里的方法](https://developer.aliyun.com/ask/485457?spm=a2c6h.14164896.0.0.2e481fa6zLabTH)，结果并没有用😂

**Comment by langgz** [comment]
https://github.com/alibaba-damo-academy/FunASR/discussions/236

**Comment by damengdameng** [comment]
> 依然有这三行INFO
> 
> 2023-05-23 10:25:49,147 - modelscope - INFO - PyTorch version 1.13.1 Found. 2023-05-23 10:25:49,150 - modelscope - INFO - Loading ast index from /home/xxx/.cache/modelscope/ast_indexer 2023-05-23 10:25:49,205 - modelscope - INFO - Loading done! Current index file version is 1.6.0, with md5 xxxxxxxx and a total number of 848 components indexed

已解决，将
`import logging
from modelscope.utils.logger import get_logger
logger = get_logger(log_level=logging.CRITICAL)
logger.setLevel(logging.CRITICAL)`
添加到modelscope/utils/registry.py里面即可。
