### ISSUE TITLE
您好，onnx cpp版本的推理有考虑加上时间戳的输出吗？

### ISSUE THREAD

**Issue by 1311004771** [alibaba-damo-academy/FunASR#548]

**Comment by mdys** [comment]
同样期待 时间戳 功能，期待大佬更新！

**Comment by lyblsgo** [comment]
Timestamp is now supported.: https://github.com/alibaba-damo-academy/FunASR/blob/main/runtime/docs/SDK_advanced_guide_offline_zh.md
If the issue persists, please reopen the issue and provide detailed steps to reproduce, as well as server and client logs.
