### ISSUE TITLE
python websocket demo丢失第一段vad内容

### ISSUE THREAD

**Issue by Darlig** [alibaba-damo-academy/FunASR#556]
OS: Ubuntu 18.04
Python: 3.8.15
Package Version: torch 1.13.0 modelscope 1.5.2 funasr 0.5.6 (onnx 1.13.1 onnxruntime 1.14.1)
Model: offline asr: speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch; vad: speech_fsmn_vad_zh-cn-16k-common-pytorch
Command: 
server: python ws_server_2pass.py --asr_model models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/ --asr_model_online models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/ --vad_model models/damo/speech_fsmn_vad_zh-cn-16k-common-pytorch/ --punc_model models/damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch/
client: python ws_client.py --audio_in ../../../../data/wav/asr_vad_punc_example.wav
问题描述：python websocket demo的offline asr输出的结果可能缺少开头的一段内容，与online asr输出对比可以更明显地看出offline asr内容缺失。
pid0: 正是因                    
pid0: 正是因为存在                                                                                                                               
pid0: 正是因为存在绝对正    
pid0: 正是因为存在绝对正义所以我                                                                                                                        
pid0: 正是因为存在绝对正义所以我们接受
pid0: 正是因为存在绝对正义所以我们接受现实的                                     
pid0: 正是因为存在绝对正义所以我们接受现实的相对正
pid0: 正是因为存在绝对正义所以我们接受现实的相对正但是                                                                               
pid0: 正是因为存在绝对正义所以我们接受现实的相对正但是不要因为                                                                                                                                                                   
pid0: 正是因为存在绝对正义所以我们接受现实的相对正但是不要因为现实的
pid0: 正是因为存在绝对正义所以我们接受现实的相对正但是不要因为现实的相对正义
pid0: 正是因为存在绝对正义所以我们接受现实的相对正但是不要因为现实的相对正义我们就认
pid0: 正是因为存在绝对正义所以我们接受现实的相对正但是不要因为现实的相对正义我们就认为这个
pid0: 正是因为存在绝对正义所以我们接受现实的相对正但是不要因为现实的相对正义我们就认为这个世界
pid0: 正是因为存在绝对正义所以我们接受现实的相对正但是不要因为现实的相对正义我们就认为这个世界没有争
pid0: 不要因为现实的相对正义，我们就认为这个世界没有正义。
pid0: 不要因为现实的相对正义，我们就认为这个世界没有正义。因为
pid0: 不要因为现实的相对正义，我们就认为这个世界没有正义。因为如果当你
pid0: 不要因为现实的相对正义，我们就认为这个世界没有正义。因为如果当你认为这个世
pid0: 不要因为现实的相对正义，我们就认为这个世界没有正义。因为如果当你认为这个世界没有正
pid0: 不要因为现实的相对正义，我们就认为这个世界没有正义。如果当你认为这个世界没有正义。

**Comment by langgz** [comment]
I have tested the case as the [docs](https://alibaba-damo-academy.github.io/FunASR/en/runtime/websocket_python.html). It      only happens when you kill the client and restart it. We will fix it soon.

**Comment by langgz** [comment]
> I have tested the case as the [docs](https://alibaba-damo-academy.github.io/FunASR/en/runtime/websocket_python.html). It only happens when you kill the client and restart it. We will fix it soon.

Bug has been fixed. Ref to https://github.com/alibaba-damo-academy/FunASR/issues/578#issuecomment-1573142215
