### ISSUE TITLE
paraformer微调设置超参数

### ISSUE THREAD

**Issue by HenryYuen128** [alibaba-damo-academy/FunASR#56]
是否有相关文档可以查看可以设置的超参数？比如优化器等。
根据 https://modelscope.cn/docs/Configuration%E8%AF%A6%E8%A7%A3 设置后似乎并不生效

**Comment by jmwang66** [comment]
您好，可以参考您使用的模型对应的modelcard，模型可以在modelscope网页上搜索，网址为https://www.modelscope.cn/models。如果您使用的模型在egs_modelscope目录下已经提供，也可以参考对应模型目录下的README。

**Comment by HenryYuen128** [comment]
> 

你好，目前看到的超参数只有几个类型
```python
output_dir: # result dir
data_dir: # the dataset dir needs to include files: train/wav.scp, train/text; validation/wav.scp, validation/text
dataset_type: # for dataset larger than 1000 hours, set as large, otherwise set as small
batch_bins: # batch size. For dataset_type is small, batch_bins indicates the feature frames. For dataset_type is large, batch_bins indicates the duration in ms
max_epoch: # number of training epoch
lr: # learning rate
```
是否只支持以上超参调整？

**Comment by langgz** [comment]
> > 
> 
> 你好，目前看到的超参数只有几个类型
> 
> ```python
> output_dir: # result dir
> data_dir: # the dataset dir needs to include files: train/wav.scp, train/text; validation/wav.scp, validation/text
> dataset_type: # for dataset larger than 1000 hours, set as large, otherwise set as small
> batch_bins: # batch size. For dataset_type is small, batch_bins indicates the feature frames. For dataset_type is large, batch_bins indicates the duration in ms
> max_epoch: # number of training epoch
> lr: # learning rate
> ```
> 
> 是否只支持以上超参调整？

目前从pipeline层面来指定是以上鸡哥参数类型，其他参数修改，可以找到模型保存路径，修改finetune.yaml

**Comment by HenryYuen128** [comment]
在以下链接提到的参数，如回调函数等是否都支持？
https://modelscope.cn/docs/Configuration%E8%AF%A6%E8%A7%A3

**Comment by HenryYuen128** [comment]
修改fintune.yaml后，后台挂起方式启动任务修改的配置项似乎不生效

**Comment by langgz** [comment]
> 

好的，方便加我们钉钉群，详细沟通么？
