### ISSUE TITLE
ssl_key问题

### ISSUE THREAD

**Issue by hzfei** [alibaba-damo-academy/FunASR#567]
系统:   ubuntu22
python:   3.10.11
funasr:    0.5.7
modelscope:   1.6.0
在/FunASR/funasr/runtime/python/websocket 运行：
python wss_srv_asr.py --port 10095 --asr_model "damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch"  --asr_model_online "damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online"
报:    
![企业微信截图_16855201494312](https://github.com/alibaba-damo-academy/FunASR/assets/42926130/541723c9-d795-4213-ad1d-da6625fb3e69)

**Comment by zhaomingwork** [comment]
try generate ssl key with size 2048, provided key is 1024.
