### ISSUE TITLE
paraformer online finetune valid pre_loss_att=nan

### ISSUE THREAD

**Issue by hzfei** [alibaba-damo-academy/FunASR#576]
系统:    docker ubuntu22
python:    3.10
pytorch:    '2.0.0+cu117
funasr:    0.5.7
modelscope:    1.6.0
Model:   speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online
command:   taskset -c 0-32 python finetune.py
问题描述:
出现多个error,但也能运行，在valid的时候出现pre_loss_att=nan
Error log: 
[log.txt](https://github.com/alibaba-damo-academy/FunASR/files/11620390/log.txt)

**Comment by hnluo** [comment]
Pre_loss_att is currently not being used in the training, with a value of None, causing NaN to be displayed in the log. So it doesn't affect the training effectiveness of the model

**Comment by hzfei** [comment]
在demo_online.py上面修改了点代码，多次运行，出现：
1.重复下载damo模型
2.偶然几次下载的模型还不一样
代码如下：
![企业微信截图_16856061316898](https://github.com/alibaba-damo-academy/FunASR/assets/42926130/df67c9d1-f121-4f67-a410-4c38e54f7116)
下载的mo模型如下：
speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online  
speech_paraformer_asr_nat-zh-cn-16k-common-vocab8404-online

**Comment by hzfei** [comment]
微调speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online,数据105万条音频（其中30万条加了噪音），目前只完成2个epoch。测试发现：paraformer版本在第一个epoch（效果最好的也是第一个epoch），句准可达到95。而online版本同样也是第一个epoch效果最好，但句准只有60多。训练log.txt如下：
[log.txt](https://github.com/alibaba-damo-academy/FunASR/files/11631344/log.txt)

**Comment by hzfei** [comment]
> Bugfix. Please pull the latest code(demo_online.py)

仍然会出现重复下载模型的情况

**Comment by hzfei** [comment]
系统: docker ubuntu22
python: 3.10
pytorch: '2.0.0+cu117
funasr: 0.5.7
modelscope: 1.6.0
Model: speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online
command: taskset -c 0-32 python finetune.py

finetune.py的时候，90万条音频，每个epoch都在2000steps结束。
![企业微信截图_16860360312197](https://github.com/alibaba-damo-academy/FunASR/assets/42926130/b92580c0-e3e4-4a0e-8e1e-499d53b88d5e)
![企业微信截图_16860361231671](https://github.com/alibaba-damo-academy/FunASR/assets/42926130/29406824-1b88-472b-b26b-b26491e2e50f)
[log.txt](https://github.com/alibaba-damo-academy/FunASR/files/11661550/log.txt)

**Comment by Gxhappiness** [comment]
> 微调speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online,数据105万条音频（其中30万条加了噪音），目前只完成2个epoch。测试发现：paraformer版本在第一个epoch（效果最好的也是第一个epoch），句准可达到95。而online版本同样也是第一个epoch效果最好，但句准只有60多。测试句准的数据是独立于train/validation之外，但即使用validation数据测句准，目前看也只是70左右。训练log.txt如下：
> 
> [log.txt](https://github.com/alibaba-damo-academy/FunASR/files/11631344/log.txt)

大佬，怎么微调实时的ASR啊，没瞅见
