### ISSUE TITLE
随着连接次数(识别次数)增加识别速度变慢问题

### ISSUE THREAD

**Issue by chenmiaotian** [alibaba-damo-academy/FunASR#578]
服务端启用后，使用demo里面的h5 online模式识别，第1次速度正常，当随着使用次数增加(大概20次连接，每连接和断开算1次连接)识别的速度会变慢很多，比第1次大概慢了5-7倍，系统CentOS 8 8核 32G CPU最高使用 36% 内存最高使用12G，最大同时3个连接，单个连接断开20次左右也是一样的结果

**Comment by zhaomingwork** [comment]
提了个PR #582, 可以试试看。目前同一时间只支持1个连接，多了不行。
