### ISSUE TITLE
install failed in python 3.8

### ISSUE THREAD

**Issue by lawindman666** [alibaba-damo-academy/FunASR#584]
OS: win10 x64
Python/C++ Version：conda python 3.8

当时使用 
pip install "modelscope[audio_asr]" --upgrade -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html 
命令在python 3.8, 3.9, 3.11 (win10 x64)安装时候提示如下信息：
 editdistance/_editdistance.cpp(117): error C2059: 语法错误:“if”
      editdistance/_editdistance.cpp(118): error C2059: 语法错误:“else”
      editdistance/_editdistance.cpp(119): error C2059: 语法错误:“else”
      editdistance/_editdistance.cpp(120): error C2059: 语法错误:“else”
      editdistance/_editdistance.cpp(121): error C2059: 语法错误:“else”
      editdistance/_editdistance.cpp(122): error C2059: 语法错误:“else”
      editdistance/_editdistance.cpp(123): error C2059: 语法错误:“else”
      editdistance/_editdistance.cpp(124): error C2059: 语法错误:“else”
      editdistance/_editdistance.cpp(125): error C2059: 语法错误:“else”
      editdistance/_editdistance.cpp(126): error C2059: 语法错误:“else”
      editdistance/_editdistance.cpp(127): error C2059: 语法错误:“return”
      editdistance/_editdistance.cpp(128): error C2059: 语法错误:“}”
      editdistance/_editdistance.cpp(128): error C2143: 语法错误: 缺少“;”(在“}”的前面)
      error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

从上面信息看出是editdistance安装失败，如果在python3.7 环境下执行没有这样的问题。

**Comment by fenglui** [comment]
怪事，如果单独下载git仓库编译确是没有问题的。只有pip install "modelscope[audio_asr]" 才会出问题
