### ISSUE TITLE
请问paraformer online的finetune数据集格式，和offline的一样吗

### ISSUE THREAD

**Issue by I-am-little-curly-hair** [alibaba-damo-academy/FunASR#589]
![image](https://github.com/alibaba-damo-academy/FunASR/assets/34257532/a797807b-c8db-45be-82f7-d8eecc709868)
如图

**Comment by hnluo** [comment]
Yes, the data format is the same

**Comment by I-am-little-curly-hair** [comment]
> Yes, the data format is the same

Thank you very much.
