### ISSUE TITLE
Paraformer语音识别-中文-通用-16k-离线-large-热词版

### ISSUE THREAD

**Issue by gerry520** [alibaba-damo-academy/FunASR#594]
OS：Window
python==3.7.16
torch==1.13.1
modelscope==1.6.1
torchaudio ==0.13.1
funasr==0.5.3
模型：Paraformer语音识别-中文-通用-16k-离线-large-热词版  speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404
运行demo
报错：
AutomaticSpeechRecognitionPipeline: --model must be one of ('asr', 'uniasr', 'paraformer', 'paraformer_online', 'paraformer_bert', 'bicif_paraformer', 'contextual_paraformer', 'mfcca', 'timestamp_prediction'): --model neatcontextual_paraformer
  File "E:\PyCharm\FunASR-main\funasr\bin\asr_inference_launch.py", line 268, in inference_launch
    return inference_modelscope(**kwargs)
  File "E:\PyCharm\FunASR-main\funasr\bin\asr_inference_paraformer_vad_punc.py", line 545, in inference_modelscope
    speech2text = Speech2Text(**speech2text_kwargs)
  File "E:\PyCharm\FunASR-main\funasr\bin\asr_inference_paraformer_vad_punc.py", line 96, in __init__
    asr_train_config, asr_model_file, cmvn_file=cmvn_file, device=device
  File "E:\PyCharm\FunASR-main\funasr\tasks\asr.py", line 1074, in build_model_from_file
    model = cls.build_model(args)
  File "E:\PyCharm\FunASR-main\funasr\tasks\asr.py", line 1015, in build_model
    model_class = model_choices.get_class(args.model)
  File "E:\PyCharm\FunASR-main\funasr\train\class_choices.py", line 76, in get_class
    f"--{self.name} must be one of {self.choices()}: "
ValueError: --model must be one of ('asr', 'uniasr', 'paraformer', 'paraformer_online', 'paraformer_bert', 'bicif_paraformer', 'contextual_paraformer', 'mfcca', 'timestamp_prediction'): --model neatcontextual_paraformer

During handling of the above exception, another exception occurred:

  File "E:\PyCharm\FunASR-main\hotWord.py", line 12, in <module>
    param_dict=param_dict,
ValueError: AutomaticSpeechRecognitionPipeline: --model must be one of ('asr', 'uniasr', 'paraformer', 'paraformer_online', 'paraformer_bert', 'bicif_paraformer', 'contextual_paraformer', 'mfcca', 'timestamp_prediction'): --model neatcontextual_paraformer

异常断点：
 inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model='damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404',
    vad_model='damo/speech_fsmn_vad_zh-cn-16k-common-pytorch',
    vad_model_revision="v1.1.8",
    punc_model='damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch',
    param_dict=param_dict,
)

**Comment by jmwang66** [comment]
Please update FunASR to the latest version and try again.

**Comment by gerry520** [comment]
问题是一样的，不是版本的问题

**Comment by jmwang66** [comment]
I have tested and there's no problem. You can check if "neatcontextual_paraformer" is included in the "model_choices" in "funasr/tasks/asr.py".

**Comment by gerry520** [comment]
thanks!
