### ISSUE TITLE
asr pipeline函数输入参数ngpu=0没有作用，通过nvidia-smi可以看到gpu内存占用较多，gpu有6%-10%左右的使用率，创建多个pipeline，gpu内存会逐渐增加直到爆。

### ISSUE THREAD

**Issue by zh11311** [alibaba-damo-academy/FunASR#595]
问题：asr pipeline函数输入参数ngpu=0没有作用，通过nvidia-smi可以看到gpu内存占用较多，gpu有6%-10%左右的使用率，创建多个pipeline，gpu内存会逐渐增加直到爆。
OS: ubuntu20.04
Python/C++ Version：pytyon 3.7.12
Package Version：pytorch 1.13.1、modelscope 1.6.1 funasr 0.5.7版本号
Model："damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online"
Command：运行funasr/runtime/python/websocket的wss_srv_asr.py

**Comment by langgz** [comment]
It is a bug of modelscope, not the FunASR. We will fix it with modelscope soon.

**Comment by zh11311** [comment]
@langgz Thank you, if modelscope fix this bug, please tell me.

> It is a bug of modelscope, not the FunASR. We will fix it with modelscope soon.

**Comment by langgz** [comment]
Bug has been fixed. Please update modelscope-1.8.0
