### ISSUE TITLE
Paraformer语音识别-中文-通用-16k-离线-large-长音频版 badcase 分析

### ISSUE THREAD

**Issue by airstillblue** [alibaba-damo-academy/FunASR#599]
你好，我们使用Paraformer语音识别-中文-通用-16k-离线-large-长音频版整套模型（vad+asr+aligner）进行长视频字幕生成，测试了5段视频，整体效果很好，但有一条非常差的badcase（长时间的识别错误和对齐错误）。想看一下是什么原因导致的？是否有方法解决？这里无法上传附件，麻烦相关同学联系一下我（钉钉 airstillblue），我把badcase数据发给你。多谢。

**Comment by airstillblue** [comment]
Please ask your question in the following format
OS: linux
Python/C++ Version：Python 3.7.16
Package Version：
funasr                   0.4.1        
modelscope               1.5.0
pytorch-wpe              0.0.1
torchaudio               0.13.1
Model：damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch
Command：python 脚本。都能正常运行，无报错。脚本读取mp4.lst里的视频路径，输出srt字幕。本次issue提交的是一个模型准确率有关的性能问题。主脚本如下：
import os
import sys
import re
import moviepy.editor as mpe

import json
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

from make_sub import make_sub

fs = 16000 
nbytes = 16 #声明位长
ffmpeg_params = ["-ac", "1"]

def mp4_to_wav(mp4fp, wavfp):
  #video = mpe.VideoFileClip(mp4fp)
  #audio = video.audio
  #audio.write_audiofile(wavfp, fs, ffmpeg_params=ffmpeg_params)

  os.system("ffmpeg -i {} -vn -async 1 -acodec pcm_s16le -ar 16000 -ac 1 {}".format(mp4fp, wavfp))
  print('{} mp4 to {} wav done.'.format(mp4fp, wavfp))

def make(mp4fp, inference_pipeline, asr_outdir):
  # prepare audio wav
  wavfp=re.sub(r"mp4$", "wav", mp4fp)
  srtfp=re.sub(r"mp4$", "srt", mp4fp)
  mp4_to_wav(mp4fp, wavfp)

  # audio recognition
  inference_pipeline(audio_in=wavfp)

  # make srt
  vadfp=os.path.join(asr_outdir, "1best_recog", "vad")
  vadinfo=eval(''.join(open(vadfp,"r").readlines()[0].strip().split()[1:]))
  assert len(vadinfo) == 1
  vadinfo=vadinfo[0]
  
  time_stamp_fp=os.path.join(asr_outdir, "1best_recog", "time_stamp")
  tsinfo=eval(''.join(open(time_stamp_fp,"r").readlines()[0].strip().split()[1:]))
  
  textfp=os.path.join(asr_outdir, "1best_recog", "text")
  textinfo=open(textfp,"r").readlines()[0].strip().split()[1:]
  
  text_with_punc_fp=os.path.join(asr_outdir, "1best_recog", "text_with_punc")
  puncline=open(text_with_punc_fp, "r").readlines()[0].strip()
  punchead=puncline.split()[0]
  puncinfo=re.sub(r"^{}".format(punchead),'',puncline).strip()

  make_sub(srtfp, vadinfo, tsinfo, textinfo, puncinfo)
  print(f"{srtfp} done.", flush = True)

if __name__ == "__main__":
  asr_outdir="./asr_out"
  os.system("[ -d {0} ] && rm -rf {0}; mkdir -p {0}".format(asr_outdir))

  inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model='damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch',
    model_revision="v1.2.4",
    output_dir=asr_outdir)

  for line in open("mp4.lst"):
    os.system(f"rm -rf {asr_outdir}/*")
    mp4fp=line.strip()
    make(mp4fp, inference_pipeline, asr_outdir)
    print(f"finish processing {mp4fp}.", flush = True)
    
  #os.system("[ -d {0} ] && rm -rf {0}".format(asr_outdir))

Details：
你好，我们使用Paraformer语音识别-中文-通用-16k-离线-large-长音频版整套模型（vad+asr+aligner）进行长视频字幕生成，测试了5段视频，整体效果很好，但有一条非常差的badcase（长时间的识别错误和对齐错误）。想看一下是什么原因导致的？是否有方法解决？这里无法上传附件，麻烦相关同学联系一下我（钉钉 airstillblue），我把badcase数据发给你。多谢。
Error log：空

**Comment by hnluo** [comment]
Please update FunASR to the latest version and try again. If there are still problems, you can join the DingTalk group(27215013275) to send the wav data.
