### ISSUE TITLE
语音增强对asr的识别准确率有帮助吗？

### ISSUE THREAD

**Issue by lkocok** [alibaba-damo-academy/FunASR#604]
用webrtc的agc模块对实时语音进行语音增强，然后再送入模型进行转写，这样对提升识别准确率有帮助吗？

**Comment by hnluo** [comment]
According to previous experience, after speech enhancement, the damage to the speech spectrum is relatively large, which has a negative impact on the accuracy of speech recognition. You can try it and see the effect.

**Comment by junjiem** [comment]
那是否有方式可以进行语音降噪或语音增强来降低ASR的CER，或者是否有其他前处理方式

**Comment by 123WT-LANG** [comment]
同问
