### ISSUE TITLE
Error meg['mode'] in python websocket server

### ISSUE THREAD

**Issue by lhanzl** [alibaba-damo-academy/FunASR#605]
1. the two line:
https://github.com/alibaba-damo-academy/FunASR/blob/ec70d21816f27897237b5ec6f2f5b7bc87f7a387/funasr/runtime/python/websocket/wss_client_asr.py#L192
https://github.com/alibaba-damo-academy/FunASR/blob/ec70d21816f27897237b5ec6f2f5b7bc87f7a387/funasr/runtime/python/websocket/wss_client_asr.py#L197
meg['mode'] always be online, should be offline and online?
2. I don't quite understand web-socket services, why does "model loaded! only support one client at the same time now!!!!"

**Comment by hnluo** [comment]
Q1：Bug fixed, please update funasr code。
Q2：Currently, there is a problem with the Python version of web-socket multi-threading, we will fix this problem later. You can try the C++ version of the web-socket service, which supports multiple clients。[https://alibaba-damo-academy.github.io/FunASR/en/runtime/websocket_cpp.html](https://alibaba-damo-academy.github.io/FunASR/en/runtime/websocket_cpp.html)
