### ISSUE TITLE
请问offline paraformer的时间戳是怎么得来的？有论文或者介绍文档吗？

### ISSUE THREAD

**Issue by I-am-little-curly-hair** [alibaba-damo-academy/FunASR#606]
是训练的时候，每一个字的start，end时间都标好，然后送进模型里面训练，最后预测的时候也按训练流程预测
还是说训练的时候，没有特别的训练时间戳，而是在cif输出的得分的基础上，开展了进一步处理
debug了下代码，发现在预测时间戳的时候，又接了cnn，bilstm，直接懵逼了

**Comment by hnluo** [comment]
Speech timestamp prediction model introduction can refer to the paper [https://arxiv.org/abs/2301.12343](https://arxiv.org/abs/2301.12343)
