### ISSUE TITLE
多线程调用vad pipline报错：

### ISSUE THREAD

**Issue by ReinhartLee** [alibaba-damo-academy/FunASR#607]
OS: win10
Python/C++ Version：Python3.7
Package Version：pytorch：1.13.1、torchaudio： 0.13.1、modelscope：1.5.2、funasr：0.5.7
Model：damo/speech_fsmn_vad_zh-cn-16k-common-pytorch
Command：
Details：我用FastAPI和uvicorn建了一个wss服务，通过线程池的方式多线程调用vad的pipline，但是只要有两个人同时访问这个wss服务，vad pipline就会报错。请问vad pipline是否支持多线程并发呢？
代码如下：
![image](https://github.com/alibaba-damo-academy/FunASR/assets/24267561/8a9c921c-a378-4c18-a6a5-8927575ac178)
![image](https://github.com/alibaba-damo-academy/FunASR/assets/24267561/19651d66-365b-4452-96b6-9d0eec17ea7f)

Error log：
![image](https://github.com/alibaba-damo-academy/FunASR/assets/24267561/bd426b12-5c20-4d7c-a932-ea6b7fa50e80)

**Comment by langgz** [comment]
If you want use pipeline with thread pool, you could ref the this branch: https://github.com/zhaomingwork/FunASR/tree/add_ws_threads_pool_srv
