### ISSUE TITLE
h5的demo，第一次点击开始，会等很久才有识别结果出来，大约要8秒左右

### ISSUE THREAD

**Issue by yuanmaitian** [alibaba-damo-academy/FunASR#614]
一个可能的bug，h5的demo，第一次点击开始，会等很久才有识别结果出来，大约要8秒左右。但有的时候又是正常，我想可能是跟vad的策略有关系，
![iwEcAqNwbmcDAQTRAnQF0QDsBrCGwE_t7ImESAR6e9AngNUAB9IB6eq2CAAJomltCgAL0RGP png_720x720q90](https://github.com/alibaba-damo-academy/FunASR/assets/39802447/92d1c1af-314f-4868-bff3-8f72b77fc84c)

**Comment by langgz** [comment]
I have tested it. The python-client prints the words quickly, but the h5 is slow in the begin. Could you @zhaomingwork please look into this question?

**Comment by zhaomingwork** [comment]
add connect button for html5 that may help for such delay.  refer to pr #621
