### ISSUE TITLE
训练好的模型pb应该怎么进行推理使用

### ISSUE THREAD

**Issue by ChuXNobody** [alibaba-damo-academy/FunASR#616]

**Comment by ChuXNobody** [comment]
OS:parformen pb 模型怎么推理使用，已经训练好了，可是一使用，就会报错，无法使用

**Comment by langgz** [comment]
ref to [doc](https://alibaba-damo-academy.github.io/FunASR/en/modelscope_pipeline/asr_pipeline.html#inference-with-your-finetuned-model)

**Comment by ChuXNobody** [comment]
> 参考文档
已经参考完毕，其中文档中的GPU解码以及 data_dir 里存放什么呢？

**Comment by Lilboat-Wohoo** [comment]
使用pipeline指定到本地模型文件夹，记得更换model.pb文件成自己训练好的pb文件
