### ISSUE TITLE
OS：根据文档训练了模型，并且使用了模型，GPU推理解码

### ISSUE THREAD

**Issue by ChuXNobody** [alibaba-damo-academy/FunASR#618]
根据文档，是对自己设定好的wac.scp和text为data.dir

如果我想要对实时音频进行识别，或者是个别音频识别，该怎么使用

根据文档下载的官方模型，替换了model.pb 出现了无法使用的情况

**Comment by langgz** [comment]
You could use the pipeline to the local path, [doc](https://alibaba-damo-academy.github.io/FunASR/en/modelscope_pipeline/asr_pipeline.html#define-pipeline)

**Comment by ChuXNobody** [comment]
我用了本地路径训练好的模型文件，如pipeline中的格式，改为自己的path

无法使用， TyepError: type must be a ste or valid type, but got <class "NoneType">
