### ISSUE TITLE
vad识别无声文件报错

### ISSUE THREAD

**Issue by liuchenustb** [alibaba-damo-academy/FunASR#619]
OS:  linux
Python Version：3.7.6
Package Version：funasr==0.5.8 modelscope==1.6.1
Model：damo/speech_fsmn_vad_zh-cn-16k-common-pytorch

Command：
![image](https://github.com/alibaba-damo-academy/FunASR/assets/24645232/dad50bb5-2c42-4c7b-959c-454d0129e168)

Details：
当wav.scp文件中包含无声文件时，报错如下，请问下～现在是不可以输入无声文件了吗：
![image](https://github.com/alibaba-damo-academy/FunASR/assets/24645232/80638276-04a6-4222-97a6-b13d37b19e8a)

无声文件：
[111.wav.zip](https://github.com/alibaba-damo-academy/FunASR/files/11720460/111.wav.zip)

**Comment by liuchenustb** [comment]
OS:  linux
Python Version：3.7.6
Package Version：funasr==0.5.8 modelscope==1.6.1
Model：damo/speech_fsmn_vad_zh-cn-16k-common-pytorch

Command：
![image](https://github.com/alibaba-damo-academy/FunASR/assets/24645232/dad50bb5-2c42-4c7b-959c-454d0129e168)

Details：
当wav.scp文件中包含无声文件时，报错如下，请问下～现在是不可以输入无声文件了吗：
![image](https://github.com/alibaba-damo-academy/FunASR/assets/24645232/80638276-04a6-4222-97a6-b13d37b19e8a)

无声文件：
[111.wav.zip](https://github.com/alibaba-damo-academy/FunASR/files/11720460/111.wav.zip)

**Comment by langgz** [comment]
It is a bug, which is introduced by[changes](https://github.com/alibaba-damo-academy/FunASR/pull/612). Please help to fix it. @lingyunfly

**Comment by langgz** [comment]
> It is a bug, which is introduced by[changes](https://github.com/alibaba-damo-academy/FunASR/pull/612). Please help to fix it. @lingyunfly

Bug has been fixed. Please update funasr to 0.6.1. [pr](https://github.com/alibaba-damo-academy/FunASR/commit/3da40ad9fe5d1c9003014fdce75fffca23fd6900)
