### ISSUE TITLE
Android客户端使用ASR出现文字叠加情况

### ISSUE THREAD

**Issue by chenmiaotian** [alibaba-damo-academy/FunASR#620]
出现的结果
    不知不知知道正常很正常我现现在你你什么我家我觉得得干干啥啥别养生养生就行行生是考的坑人养的养生的人没有几个是活的真的时间长的
原话是(同时录制成wav后通过modelscope转换)
    不知道很正常我觉得干啥别养生就行养生是真坑人养生的人没有几个是活的真的时间长的
下面是我Android采集麦克风的代码
//声音列表
Queue<Byte> audioDataList = new LinkedList<>();
//缓冲区大小
int tBufferSizeInBytes = AudioRecord.getMinBufferSize(sampleRate,channelConfig,audioFormat);
//创建
AudioRecord tAudioRecord = new AudioRecord(MediaRecorder.AudioSource.MIC, 16000, AudioFormat.CHANNEL_IN_MONO, AudioFormat.ENCODING_PCM_16BIT, tBufferSizeInBytes);
//开始录制
tAudioRecord.startRecording();
//长度
int tSplitLength = 960;
while(true)
{
	//创建缓冲区
	byte[] tBuffer = new byte[tBufferSizeInBytes];
	//读取数据大小,这里永远不会为0,是缓冲区bufferSizeInBytes的大小,如果没有数据,会阻塞到有数据为止
	int tReadSize = tAudioRecord.read(tBuffer, 0, tBufferSizeInBytes);
	for(int i = 0;i < tBuffer.length;i++)
	{
		//喂养
		audioDataList.offer(tBuffer[i]);
	}
	if(audioDataList.size() >= tSplitLength)
	{
		//数据
		byte[] tChunkDatas = new byte[tSplitLength];
		for(int j = 0;j < tSplitLength;j++)
		{
			//赋值
			tChunkDatas[j] = audioDataList.poll();
		}
		//发送
		ASRTest.getInstance().speak(tChunkDatas);
	}
}
下面是我发送数据的代码
    //单例
    private final static ASRTest instance = new ASRTest();
    //WebSocketPeer
    private WebSocketPeer webSocketPeer;
    //模型(2pass || online || offline)
    private String asrMode = "2pass";
    //内容
    private String offlineText = "";
    //结果
    private String asrText = "";
    //地址
    private final String serverUrl = "wss://122.45.189.161:2521/";
    //块数组,大小[5,10,5]=600ms [8,8,4]=480ms
    private int[] chunkSizes = new int[]{5,10,5};
    //块间隔,"20": 600/12=30ms "10": 600/10=60ms "5"=600/5=120ms
    private int chunkInterval = 10;

    //获取单例
    public static ASRTest getInstance()
    {
        //返回结果
        return instance;
    }
    //连接(回调)
    public void connect(WebSocketCallback connectCallback)
    {
        //Log
        Log.i(AppApplication.logTag,"---------------> ASRTest 连接:" + serverUrl);
        //新建连接
        webSocketPeer = new WebSocketPeer();
        //连接
        webSocketPeer.connect(serverUrl, new WebSocketCallback()
        {
            @Override
            public void onConnectSuccess()
            {
                //Log
                Log.i(AppApplication.logTag,"---------------> ASRTest 连接成功");
                //执行回调
                connectCallback.onConnectSuccess();
                //添加回调
                webSocketPeer.addReceiveCallback(new WebSocketReceiveCallback()
                {
                    @Override
                    public void onReceive(String receiveData)
                    {
                        //Log
                        Log.i(AppApplication.logTag,"---------------> ASRTest 接收数据:" + receiveData);
                        //内容
                        String tText = "";
                        try
                        {
                            //数据
                            JSONObject tReceiveData = new JSONObject(receiveData);
                            //内容
                            tText = tReceiveData.getString("text");
                            if(asrMode.equals("2pass-offline"))
                            {
                                //内容
                                offlineText = offlineText + tText.replaceAll("\\s+", "");
                                //结果
                                asrText = offlineText;
                            }
                            else
                            {
                                asrText = asrText + tText.replaceAll("\\s+", "");
                            }
                            //Log
                            Log.i(AppApplication.logTag,"---------------> ASRTest 接收数据:" + asrText);
                        }
                        catch(Exception e)
                        {
                            //Log
                            Log.e(AppApplication.logTag,"---------------> ASRTest 解析失败:" + e.getMessage());
                        }
                        //Log
                        Log.i(AppApplication.logTag,"---------------> ASRTest 识别内容:" + tText);
                        if(asrCallback != null)
                        {
                            //执行回调
                            asrCallback.onResult(true,tText);
                        }
                    }
                });
                try
                {
                    //开始
                    start();
                }
                catch(Exception e)
                {

                }
            }

            @Override
            public void onConnectFail(String failReason)
            {
                //Log
                Log.i(AppApplication.logTag,"---------------> ASRTest 连接失败");
                //执行回调
                connectCallback.onConnectFail(failReason);
            }

            @Override
            public void onError(String errorMessage)
            {
                //Log
                Log.i(AppApplication.logTag,"---------------> ASRTest 错误:" + errorMessage);
                //执行回调
                connectCallback.onError(errorMessage);
            }

            @Override
            public void onClosing()
            {
                //Log
                Log.i(AppApplication.logTag,"---------------> ASRTest 关闭中");
                //执行回调
                connectCallback.onClosing();
            }

            @Override
            public void onClosed()
            {
                //Log
                Log.i(AppApplication.logTag,"---------------> ASRTest 已关闭");
                //执行回调
                connectCallback.onClosed();
            }
        });
    }
    //开始
    public void start() throws JSONException
    {
        //Log
        Log.i(AppApplication.logTag,"---------------> ASRTest 开始");
        if(webSocketPeer != null)
        {
            //数据
            JSONObject tSendData = new JSONObject();
            //块
            JSONArray tChunkSizes = new JSONArray();
            for(int i = 0;i < chunkSizes.length;i++)
            {
                //添加
                tChunkSizes.put(chunkSizes[i]);
            }
            //块
            tSendData.put("chunk_size",tChunkSizes);
            //文件名称
            tSendData.put("wav_name","microphone");
            //是否说话中
            tSendData.put("is_speaking",true);
            //块间隔
            tSendData.put("chunk_interval",chunkInterval);
            //模式(2pass || online || offline)
            tSendData.put("mode",asrMode);
            //发送数据
            webSocketPeer.sendMessage(tSendData.toString());
        }
    }
    //说话(数据,回调)
    public void speak(byte[] audioData) throws JSONException
    {
        if(webSocketPeer != null)
        {
            //Log
            Log.i(AppApplication.logTag,"---------------> ASRTest 说话,长度:" + audioData.length);
            //发送数据
            webSocketPeer.sendMessage(audioData);
        }
    }
    //停止
    public void stop() throws JSONException
    {
        //Log
        Log.i(AppApplication.logTag,"---------------> ASRTest 停止");
        if(webSocketPeer != null)
        {
            //数据
            JSONObject tSendData = new JSONObject();
            //块
            JSONArray tChunkSize = new JSONArray();
            //0
            tChunkSize.put(5);
            //1
            tChunkSize.put(10);
            //2
            tChunkSize.put(5);
            //块
            tSendData.put("chunk_size",tChunkSize);
            //文件名称
            tSendData.put("wav_name","microphone");
            //是否说话中
            tSendData.put("is_speaking",false);
            //块间隔
            tSendData.put("chunk_interval",10);
            //模式(2pass || online || offline)
            tSendData.put("mode",asrMode);
            //发送数据
            webSocketPeer.sendMessage(tSendData.toString());
        }
    }

    我是按照咱们demo里面的h5方式改造的，我不知道哪里出了问题，麻烦帮我分析下

**Comment by zhaomingwork** [comment]
@chenmiaotian 
试试把 int tSplitLength = 960;
改为 int tSplitLength = 960*2;

**Comment by zhaomingwork** [comment]
@langgz I can provide a java ws client example if needed

**Comment by langgz** [comment]
> @langgz I can provide a java ws client example if needed

If it is convenient to you, we are glad that you could provide the java client.
