### ISSUE TITLE
使用torch_quant量化自己的模型报错

### ISSUE THREAD

**Issue by xuancaiqisehua** [alibaba-damo-academy/FunASR#646]
torch 版本 1.1.0
 Conv1d = _conv_type('Conv1d', nnqat.Conv1d)
AttributeError: module 'torch.nn.qat' has no attribute 'Conv1d

**Comment by langgz** [comment]
Please offer more details about envs and models.
OS: [e.g. linux]
Python/C++ Version：
Package Version：pytorch、torchaudio、modelscope、funasr version（pip list）
Model：
Command：
Details：
Error log：

**Comment by xuancaiqisehua** [comment]
Sorry, I trained a model using PyTorch  not Funasr (the model contains Conformer, Attention and Embedding) 。
I want to quantize the model using the torch_quantize in Funasr. According to funasr/export/export_model.py, the model is defined. I'm not sure if I can use it like this. 
OS: linux
Python/C++ Version：python
Package Version：pytorch 1.10.0 、torchaudio 0.10.0、torch-quant 0.4.0 、not installed modelscope、funasr
Model：My own model trained using pytorch
Command：python ExportParaformer.py
Error log：
   Conv1d = _conv_type('Conv1d', nnqat.Conv1d)
AttributeError: module 'torch.nn.qat' has no attribute 'Conv1d'

**Comment by langgz** [comment]
> 

If you want to use torch-quant, your model must be an instance of `nn.Module`. As the https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/export/models/e2e_vad.py#L11

**Comment by xuancaiqisehua** [comment]
Thanks a lot, I will try again

**Comment by xuancaiqisehua** [comment]
I tried to export the pretrained model speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch in ModelScope and got the same error.
OS: linux
Python/C++ Version： python
Package Version：pytorch 1.10.1、torchaudio 0.10.1、modelscope 1.4.1 、funasr 0.3.0  torch-quant  0.4.0 
Model：damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
Command： python export_model.py --model-name damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch --export-dir export --type torch --audio_in wav.lst --quantize >myout 2>&1 &
Details：
Error log：
 /data/anaconda3/envs/funasr/lib/python3.7/site-packages/torch_quant/observed_module.py", line 39, in <module>
    Conv1d = _conv_type('Conv1d', nnqat.Conv1d)
AttributeError: module 'torch.nn.qat' has no attribute 'Conv1d

**Comment by langgz** [comment]
Please update the versions, and try it again:
torch>=1.11 (1.13.1 is recommend)
funasr>=0.6.0
modelscope>=1.6.1
