### ISSUE TITLE
如何finetuning断句模型ct-transformer

### ISSUE THREAD

**Issue by Alan-6666** [alibaba-damo-academy/FunASR#647]
我自己写个一个finetuning的代码，推理过程中，batch为1，不padding加标点没有问题，但是一个batch的输入pad到相同长度，这样和batch=1的结果不同，断句不对。请教下微调的代码，感谢！

**Comment by langgz** [comment]
On going

**Comment by Alan-6666** [comment]
> 
请教一下，训练过程中，如何处理不同长度不同的数据

**Comment by Alan-6666** [comment]
> On going
请教一下，训练过程中，如何处理不同长度不同的数据

**Comment by xuancaiqisehua** [comment]
You can refer to this code : https://github.com/yeyupiaoling/PunctuationModel/blob/master/utils/reader.py

**Comment by Alan-6666** [comment]
> You can refer to this code : https://github.com/yeyupiaoling/PunctuationModel/blob/master/utils/reader.py

ok，thanks

**Comment by ROAD2018** [comment]
可以参考：https://github.com/alibaba-damo-academy/FunASR/issues/893

**Comment by Alan-6666** [comment]
> 可以参考：#893

感谢
