### ISSUE TITLE
请问说话人日志支持开集识别嘛？

### ISSUE THREAD

**Issue by kamisugi** [alibaba-damo-academy/FunASR#652]
这里看了论文发现这个模型理论上来说应该是可以支持开集的，但是这里看了一下代码好像是以profile作为目标说话人。
请问可以修改代码做到识别不在提供的音频片段中的人嘛，（类似基于threshold去提供一个默认值识别为unknown_speaker0\1\2)
[modelscope地址](https://www.modelscope.cn/models/damo/speech_diarization_sond-zh-cn-alimeeting-16k-n16k4-pytorch/summary)
[论文地址（中文）](https://mp.weixin.qq.com/s/iU09MDjcFTaIJXIjc9isIA)
[论文地址（英文）](http://arxiv.org/abs/2211.10243)

**Comment by tramphero** [comment]
支持，对于SOND的说话人日志会通过clustering-based method先聚类得到speaker profile，然后再进行NN model-based speaker assignment来得到更高精度的说话人日志，同时解决speaker overlapping的问题。
