### ISSUE TITLE
热词版本能导出onnx吗？

### ISSUE THREAD

**Issue by dengcunqin** [alibaba-damo-academy/FunASR#663]
热词版本能导出onnx吗？

**Comment by lancelee98** [comment]
热词版本能支持时间戳吗？

**Comment by R1ckShi** [comment]
可以，见https://github.com/alibaba-damo-academy/FunASR/tree/v0.8.8/funasr/export 。export目前支持的模型见https://github.com/alibaba-damo-academy/FunASR/blob/v0.8.8/funasr/export/models/__init__.py。现在在改版到funasr1.0 export还没有完成，可以用0.8.8分支的代码。
