### ISSUE TITLE
载入NPU-ASLP/speech_mfcca_asr-zh-cn-16k-alimeeting-vocab4950模型时报错

### ISSUE THREAD

**Issue by boxter007** [alibaba-damo-academy/FunASR#665]
AutomaticSpeechRecognitionPipeline: Error(s) in loading state_dict for MFCCA:
	size mismatch for frontend.logmel.melmat: copying a param with shape torch.Size([257, 80]) from checkpoint, the shape in current model is torch.Size([201, 80]).
RuntimeError: Error(s) in loading state_dict for MFCCA:
	size mismatch for frontend.logmel.melmat: copying a param with shape torch.Size([257, 80]) from checkpoint, the shape in current model is torch.Size([201, 80]).

During handling of the above exception, another exception occurred:

  File "/home/abc/asr.py", line 18, in <module>
    p = pipeline('auto-speech-recognition', 'NPU-ASLP/speech_mfcca_asr-zh-cn-16k-alimeeting-vocab4950',
RuntimeError: AutomaticSpeechRecognitionPipeline: Error(s) in loading state_dict for MFCCA:
	size mismatch for frontend.logmel.melmat: copying a param with shape torch.Size([257, 80]) from checkpoint, the shape in current model is torch.Size([201, 80]).

**Comment by langgz** [comment]
OS: [e.g. linux]
Python/C++ Version：
Package Version：pytorch、torchaudio、modelscope、funasr version（pip list）
Model：
Command：
Details：
Error log：

**Comment by yufan-aslp** [comment]
It seems that there is a mismatch in the parameters of the front-end module, please provide your "config.yaml" file.

**Comment by yufan-aslp** [comment]
Please pull the "funasr/models/frontend/default.py" file again.
A previous pr had bugs, which have since been fixed.
