### ISSUE TITLE
websocket-python 客户端的输入和输出不一致

### ISSUE THREAD

**Issue by liuchenustb** [alibaba-damo-academy/FunASR#677]
OS：Linux
Python Version：3.7
Package Version：pytorch==1.13.1、modelscope==1.6.1、funasr==0.6.5
问题描述：
websocket-python：
(i)server：python wss_srv_asr.py --port 10095 --asr_model "damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch" --asr_model_online "damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online"
(ii)client：python wss_client_asr.py --host "0.0.0.0" --port 10095 --mode offline --chunk_interval 10 --words_max_print 100 --audio_in "./wav.scp" --send_without_sleep --output_dir "./results"

wav.scp文件中有多个音频文件，但是客户端只返回了第一个音频文件的asr结果

**Comment by liuchenustb** [comment]
(ii)client命令：--mode online，--mode 2pass都可以返回正常数量的音频文件转写结果，--mode offline却只返回第一个

**Comment by langgz** [comment]
I have tested it. It is a bug, we will fix it soon.

**Comment by zhaomingwork** [comment]
see PR#710

**Comment by langgz** [comment]
Please update FunASR. Bug has been fixed. https://github.com/alibaba-damo-academy/FunASR/commit/4413d1eb47fa400277c8a9625aa0bd5c424a2fab
