### ISSUE TITLE
egs_modelscope UniASR 8k-common infer.py 解码中断

### ISSUE THREAD

**Issue by kli017** [alibaba-damo-academy/FunASR#679]
使用FunASR/egs_modelscope/asr/uniasr/speech_UniASR_asr_2pass-zh-cn-8k-common-vocab3445-pytorch-online 目录下的infer.py 对指定的wav.scp进行批量解码，音频文件约7w但是每次解码部分音频后就中断，日志在文件中不知道是什么原因？
[decode.log](https://github.com/alibaba-damo-academy/FunASR/files/11891136/decode.log)

**Comment by hnluo** [comment]
Bug fixed, please update funasr。
```
git clone https://github.com/alibaba/FunASR.git && cd FunASR
pip install -e ./
```
