### ISSUE TITLE
是否支持导onnx?

### ISSUE THREAD

**Issue by Ht-zhang-xianyu** [alibaba-damo-academy/FunASR#68]
您好 最近想要使用下paraformer进行推理
想请教下是否有现成的api可以进行paraformer的onnx导出？

**Comment by langgz** [comment]
您好，我们正在做，预计明天早上可以提供，如果方便可以加我们钉钉群，方便信息交流

**Comment by langgz** [comment]
https://github.com/alibaba-damo-academy/FunASR/tree/main/funasr/runtime/python/onnxruntime
