### ISSUE TITLE
No input and output in macbook microphone

### ISSUE THREAD

**Issue by snakeninny** [alibaba-damo-academy/FunASR#683]
| - | - |
| --- | --- |
| OS | macOS 13.4.1 |
| Python Version | 3.10 |
| Package Version | pytorch-wpe 0.0.1, torchaudio 2.0.2, modelscope 1.6.1, funasr 0.6.5 |
| Model | `asr_model='damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch', asr_model_online='damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online', vad_model='damo/speech_fsmn_vad_zh-cn-16k-common-pytorch', punc_model='damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727'` |
| Command | server `python wss_srv_asr.py --port 10095`, client `python wss_client_asr.py --host "0.0.0.0" --port 10095 --mode 2pass --chunk_size "8,8,4"` |

I have followed the [document](https://alibaba-damo-academy.github.io/FunASR/en/runtime/websocket_python.html) and ran server and client successfully. The server output is:
```
python wss_srv_asr.py --port 10095

Namespace(host='0.0.0.0', port=10095, asr_model='damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch', asr_model_online='damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online', vad_model='damo/speech_fsmn_vad_zh-cn-16k-common-pytorch', punc_model='damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727', ngpu=1, ncpu=4, certfile='./ssl_key/server.crt', keyfile='./ssl_key/server.key')
2023-06-28 16:00:09,791 - modelscope - INFO - PyTorch version 2.0.1 Found.
2023-06-28 16:00:09,792 - modelscope - INFO - Loading ast index from /Users/snakeninny/.cache/modelscope/ast_indexer
2023-06-28 16:00:09,856 - modelscope - INFO - Loading done! Current index file version is 1.6.1, with md5 12deaac1caf82e054d12ac335996c4e1 and a total number of 849 components indexed
model loading
[W ParallelNative.cpp:230] Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
model loaded! only support one client at the same time now!!!!
new user connected
```
While the client output is:
```
python wss_client_asr.py --host "0.0.0.0" --port 10095 --mode 2pass --chunk_size "8,8,4"                 
      
Namespace(host='0.0.0.0', port=10095, chunk_size=[8, 8, 4], chunk_interval=10, audio_in=None, send_without_sleep=False, test_thread_num=1, words_max_print=10000, output_dir=None, ssl=1, mode='2pass')
Namespace(host='0.0.0.0', port=10095, chunk_size=[8, 8, 4], chunk_interval=10, audio_in=None, send_without_sleep=False, test_thread_num=1, words_max_print=10000, output_dir=None, ssl=1, mode='2pass')
connect to wss://0.0.0.0:10095
```
***The problem is that there's no input and output in microphone.***

I have checked macOS -> System Settings -> Sound -> Output & Input, microphone seems OK.
<img width="479" alt="Screenshot 2023-06-28 at 17 36 00" src="https://github.com/alibaba-damo-academy/FunASR/assets/641869/a79fd0a3-6e17-4c5e-ac23-6d60e5bd0469">

I have also tested with a wav file rather than the microphone:
```
python wss_client_asr.py --host "0.0.0.0" --port 10095 --mode 2pass --chunk_size "8,8,4" --audio_in "/Users/snakeninny/Downloads/asr_example.wav"

Namespace(host='0.0.0.0', port=10095, chunk_size=[8, 8, 4], chunk_interval=10, audio_in='/Users/snakeninny/Downloads/asr_example.wav', send_without_sleep=False, test_thread_num=1, words_max_print=10000, output_dir=None, ssl=1, mode='2pass')
Namespace(host='0.0.0.0', port=10095, chunk_size=[8, 8, 4], chunk_interval=10, audio_in='/Users/snakeninny/Downloads/asr_example.wav', send_without_sleep=False, test_thread_num=1, words_max_print=10000, output_dir=None, ssl=1, mode='2pass')
connect to wss://0.0.0.0:10095
pid0_0: 欢迎大家来体验达摩院推出的语音识别模型
Exception: sent 1000 (OK); then received 1000 (OK)
end
```
Worked as expected.

Any ideas why ***microphone*** is not working? Thank you!

**Comment by langgz** [comment]
Sorry, it is a bug!. We have fixed it https://github.com/alibaba-damo-academy/FunASR/commit/4ee715e70e36cdba7b05fe044fecab9cf4fa16ff .Please update funasr and try it again.
