### ISSUE TITLE
C++版本websocket 服务端运行失败 

### ISSUE THREAD

**Issue by MyWestCity** [alibaba-damo-academy/FunASR#689]
OS：Linux
Python Version：3.7
Package Version：pytorch==1.13.1、modelscope==1.6.1、funasr==0.6.5
问题描述：
按照提供的文档配置C++ websocket服务，
运行
./funasr-wss-server --model-dir /download/ASRC++/FunASR/funasr/runtime/onnxruntime/export/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
会报错
ERROR: something wrong with flag 'timestamp_in_logfile_name' in file '/download/ASRC++/FunASR/funasr/runtime/onnxruntime/third_party/glog/src/logging.cc'.  One possibility: file '/download/ASRC++/FunASR/funasr/runtime/onnxruntime/third_party/glog/src/logging.cc' is being linked both statically and dynamically into this executable.
在/usr/local/lib也安装了libglog.a  libglog.so  libglog.so.0.7.0  libglog.so.1这几个库

**Comment by MyWestCity** [comment]
重新按照README配置编译，还是会报这个错

**Comment by mdys** [comment]
onnx-runtime 一定要用 1.14.0 版本。。 其他版本报错 无法编译成功。

**Comment by langgz** [comment]
You could try the deploy tool:

https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/runtime/readme_cn.md

**Comment by shop668** [comment]
> You could try the deploy tool:
> 
> https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/runtime/readme_cn.md

我也碰到一样的问题，用的方法就是说明里的方法

**Comment by shop668** [comment]
> onnx-runtime 一定要用 1.14.0 版本。。 其他版本报错 无法编译成功。

我用的就是这个版本，但是报一样的错

**Comment by shop668** [comment]
> 重新按照README配置编译，还是会报这个错

请教，你解决了么？

**Comment by MyWestCity** [comment]
> > 重新按照README配置编译，还是会报这个错
> 
> 请教，你解决了么？

https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/runtime/docs/SDK_advanced_guide_offline_zh.md
用他们提供的docker，可以正常运行，你可以试试
