### ISSUE TITLE
感谢大佬，websocket-cpp响应速度很快，但没有时间戳，请问 能否增加下时间戳输出呢？

### ISSUE THREAD

**Issue by mdys** [alibaba-damo-academy/FunASR#699]
如题，感谢大佬！
C++ 不熟，看了一阵源码，没搞懂在什么地方处理时间戳数据，还请大佬们能帮助下 无比感谢。！

**Comment by langgz** [comment]
OK, we would support it soon

**Comment by 1547481339** [comment]
> OK, we would support it soon

请问大概什么时候能支持时间戳输出

**Comment by shijianyang520** [comment]
请问下

> 如题，感谢大佬！ C++ 不熟，看了一阵源码，没搞懂在什么地方处理时间戳数据，还请大佬们能帮助下 无比感谢。！

请问下，c++是怎么在本地下运行该项目的呢？可否给个大概的流程？

**Comment by lyblsgo** [comment]
Timestamp is now supported.: https://github.com/alibaba-damo-academy/FunASR/blob/main/runtime/docs/SDK_advanced_guide_offline_zh.md
If the issue persists, please reopen the issue and provide detailed steps to reproduce, as well as server and client logs.
