### ISSUE TITLE
java-client报错：FunasrWsClient --host localhost --port 10095 --audio_in ./asr_example.wav --mode offline

### ISSUE THREAD

**Issue by liuchenustb** [alibaba-damo-academy/FunASR#702]
我在本地测试java客户端代码时（我本地的是mac，java8），会报错连接失败，但是测试python客户端的是成功的。
![image](https://github.com/alibaba-damo-academy/FunASR/assets/24645232/7ab066a9-8afc-4521-8874-997cf0034450)

**Comment by zhaomingwork** [comment]
@liuchenustb 发下服务器的运行代码和python测试的运行代码或截屏

**Comment by liuchenustb** [comment]
服务器运行命令：sudo bash funasr-runtime-deploy-offline-cpu-zh.sh install --workspace ./funasr-runtime-resources

本地python测试：
![截屏2023-07-04 上午9 43 27](https://github.com/alibaba-damo-academy/FunASR/assets/24645232/699691ce-26ff-452d-af7c-6bcb998f3573)

**Comment by zhaomingwork** [comment]
@liuchenustb 目前java client只支持服务器ws模式，不支持wss。服务器默认可能是ws。

**Comment by zhaomingwork** [comment]
> > @zhaomingwork
> 
> ./funasr-wss-server --download-model-dir /workspace/models --model-dir /workspace/yuyin_model/model_weight --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx --punc-dir damo/punc_ct-transformer_zh-cn-common-vocab272727-onnx --decoder-thread-num 32 --io-thread-num 8 --port 10095 --certfile False --keyfile False --quantize false 那官方目前给的wss启动方式，能通过参数设置变为ws模式吗

yes, add --certfile ''. In this way, the server will run in ws mode.

**Comment by 1547481339** [comment]
> 

你问题解决了吗，我这样启动的不行，还是连接不上

**Comment by huangch1024** [comment]
已经解决了 你看官方的issue回答
















在 2023-07-25 18:44:33，"李立强" ***@***.***> 写道：

你问题解决了吗，我这样启动的不行，还是连接不上

**Comment by HbeH** [comment]
sudo bash funasr-runtime-deploy-offline-cpu-zh.sh install --workspace --certfile ''. ./funasr-runtime-resources  我用的是这个命令，也是没有解决

**Comment by yourengod** [comment]
> @liuchenustb 目前java client只支持服务器ws模式，不支持wss。服务器默认可能是wss。

ws是什么，还有wss？
