### ISSUE TITLE
使用client请求triton服务器失败

### ISSUE THREAD

**Issue by standyyyy** [alibaba-damo-academy/FunASR#704]
使用client请求triton失败，以下是一些简要配置情况。
OS: [e.g. linux]  linux
Python/C++ Version：client环境python3.9
Package Version：pytorch、torchaudio、modelscope、funasr version（pip list）
Model：infer_pipeline
Command：python3 client/decode_manifest_triton.py \
    --server-addr $serveraddr \
    --compute-cer \
    --model-name infer_pipeline \
    --num-tasks $num_task \
    --manifest-filename $manifest_path
Details：无 ，按照文档操作，文档地址是https://github.com/alibaba-damo-academy/FunASR/tree/main/funasr/runtime/triton_gpu
Error log：tritonclient.utils.InferenceServerException: [StatusCode.INTERNAL] in ensemble 'infer_pipeline', Failed to process the request(s) for model instance 'scoring_0_0', message: Failed to open the cudaIpcHandle. error: invalid resource handle

服务端这边按照文档上的命令 ，已经搭建了，在容器中也映射了端口出来 。
![image](https://github.com/alibaba-damo-academy/FunASR/assets/39285732/8587c485-ba39-479c-af0c-5425940794f6)

自己本机用的是windows ，triton是docker启的。下面是本机的cuda环境
![image](https://github.com/alibaba-damo-academy/FunASR/assets/39285732/6152815e-259f-4a59-89c2-071492d6e5db)
![image](https://github.com/alibaba-damo-academy/FunASR/assets/39285732/cb9a3381-e38c-4ab7-ad3b-7145ad86a558)

**Comment by langgz** [comment]
@yuekaizhang Please help to solve this issue.

**Comment by yuekaizhang** [comment]
> Failed to open the cudaIpcHandle. error: invalid resource handle

tritonserver --model-repository /workspace/model_repo_paraformer_large_offline \
             --pinned-memory-pool-byte-size=512000000.

Please remove cuda pool size and try again.

https://github.com/triton-inference-server/server/issues/5798

**Comment by standyyyy** [comment]
尝试了，还是会报错，和上面报错一样。

**Comment by standyyyy** [comment]
不知道是不是因为是windows发起的请求，看到下面说CUDA shared memory is not supported on Windows:

**Comment by standyyyy** [comment]
测试了，用企业级别显卡测试过，是通的。
