### ISSUE TITLE
使用speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch，识别转录不出文字的音频时，会报错

### ISSUE THREAD

**Issue by I-am-little-curly-hair** [alibaba-damo-academy/FunASR#705]
OS: windows、ubuntu
Python/C++ Version：python3.7、python3.8
Package Version：modelscope-1.6.0、funasr-0.5.8
Model：speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch
Command：文档中的python实例
Details：随便找一段静音，只要转录不出文字的音频都能复现这个错误
Error log：timestamp = result[4] if len(result[4]) > 0 else None

**Comment by jmwang66** [comment]
Please provide the detailed error log

**Comment by I-am-little-curly-hair** [comment]
> Please provide the detailed error log

帅哥，你随便录一段100ms的静音，按照demo试一下就知道了

**Comment by R1ckShi** [comment]
报错信息是什么呢？
Error log：timestamp = result[4] if len(result[4]) > 0 else None是报错的内容吗？

**Comment by langgz** [comment]
Bug has been fixed https://github.com/alibaba-damo-academy/FunASR/commit/11daec8222410848c2302f11f664911bf8280374
