### ISSUE TITLE
windows平台下如何集成客户端？

### ISSUE THREAD

**Issue by GlocKieHuan** [alibaba-damo-academy/FunASR#717]
我的应用场景是Windows，想把客户端集成到其它项目中，昨天Cmake了下cpp-client，在vs上编译太多错误了，想咨询下关于Windows平台下的客户端会不会出单独sdk，或者有没有什么办法可以解决我这种问题呢？

**Comment by langgz** [comment]
@lyblsgo Please support the cpp-client on windows.

**Comment by endink** [comment]
#726

我提供了编译好的静态库。   

已经在游戏引擎里使用，未发现异常。

**Comment by LauraGPT** [comment]
windows has been supported. [download](https://www.modelscope.cn/api/v1/models/damo/funasr-runtime-win-cpu-x64/repo?Revision=master&FilePath=funasr-runtime-win-cpu-x64-v0.1.0.zip)

**Comment by GlocKieHuan** [comment]
你好呀，这里是GH的邮件自动回复，你的邮件我已经收到啦，祝好~~~
