### ISSUE TITLE
微调paraformer模型报错 RuntimeError: 0 lines found

### ISSUE THREAD

**Issue by gz-d** [alibaba-damo-academy/FunASR#718]
在finetune paraformer模型的时候遇到了如下报错：
RuntimeError: 0 lines found:
![02efed6420e5b677bcbb5f1d4f09887](https://github.com/alibaba-damo-academy/FunASR/assets/90494164/bd79d6f7-40db-47c9-b51a-7719fad5ec69)

OS: Linux
Python version: 3.9.16
Torch version: 2.0.1
Torchaudio version: 2.0.2
Modelscope version: 1.7.0
Funasr version: 0.6.7
Model: speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
Command: python finetune.py

Details:
我用的模型是speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch，借用的finetune代码如下，唯一的改动是output_dir和data_path改成了自定义的checkpoint和data路径：

![image](https://github.com/alibaba-damo-academy/FunASR/assets/90494164/d4d2d784-b331-4b94-8b3f-8c5b37bfc6fb)

代码链接：https://github.com/alibaba-damo-academy/FunASR/blob/main/egs_modelscope/asr/TEMPLATE/finetune.py

数据是自己的数据，按照github上的格式要求生成，并按照要求的路径保存

数据格式和路径要求：https://github.com/alibaba-damo-academy/FunASR/blob/main/egs_modelscope/asr/TEMPLATE/finetune.py

![image](https://github.com/alibaba-damo-academy/FunASR/assets/90494164/4c64a234-f65a-40af-bf47-fc65049f9161)

![image](https://github.com/alibaba-damo-academy/FunASR/assets/90494164/c4362e0c-ba05-46b2-9b52-62e0ea651219)

![image](https://github.com/alibaba-damo-academy/FunASR/assets/90494164/f0ed9070-3505-49de-8112-6bfb33aa559b)
[log.txt](https://github.com/alibaba-damo-academy/FunASR/files/11964181/log.txt)

**Comment by Lizerui9926** [comment]
By default, audio that exceeds 15s in model training will be filtered out. This may be the reason why the generated speech_shape files are all empty. You can cut the long audio to short and then use it for training.

**Comment by Shicc** [comment]
When I use aishell1, the code will also report the same error

**Comment by qingjiaozyn** [comment]
My audio are all under 5 seconds long and have the same issue

**Comment by miningant511** [comment]
Please check if the path in wav.scp in the training dataset is correct
