### ISSUE TITLE
How to deploy the streaming asr paraformer model?

### ISSUE THREAD

**Issue by yangb05** [alibaba-damo-academy/FunASR#720]
Hi, I tried to deploy the streaming asr paraformer model published on [Modelscope](https://www.modelscope.cn/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/summary) with triton according to the [README](https://github.com/alibaba-damo-academy/FunASR/tree/main/funasr/runtime/triton_gpu), but the provided model is named 'model.pb' instead of 'model.onnx'. The questions are:
1. Is it possible to deploy the streaming paraformer with triton according to the [README](https://github.com/alibaba-damo-academy/FunASR/tree/main/funasr/runtime/triton_gpu)?
2. How can I deploy the 'model.pb'?

**Comment by langgz** [comment]
We have released the deployment of the streaming asr model(Paraformer-online). Please ref to the [docs](https://alibaba-damo-academy.github.io/FunASR/en/funasr/runtime/docs/SDK_tutorial_online.html)

**Comment by langgz** [comment]
We have release the onnx of streaming model, please ref to [docs](https://github.com/alibaba-damo-academy/FunASR/tree/main/funasr/runtime/python/onnxruntime)
