### ISSUE TITLE
中文ITN无法使用

### ISSUE THREAD

**Issue by wy192** [alibaba-damo-academy/FunASR#724]
<img width="927" alt="企业微信截图_126dfc70-5a6a-417b-9cbf-0afc86e8e55f" src="https://github.com/alibaba-damo-academy/FunASR/assets/20884858/0ccb3c46-102d-4aaf-bd1f-bbbd07b7fb00">

**Comment by langgz** [comment]
We would delete the ITN-zh model, because the performance is bad.
