### ISSUE TITLE
How much data (in hours) do I need to train my own VAD model?

### ISSUE THREAD

**Issue by egorsmkv** [alibaba-damo-academy/FunASR#725]

**Comment by hnluo** [comment]
Generally, 1000 hours of data can train a usable vad model. Of course, the more data, the better the effect. Moreover, welcome to experience funasr open source vad model。[fsmn vad](https://alibaba-damo-academy.github.io/FunASR/en/modelscope_pipeline/vad_pipeline.html#voice-activity-detection)

**Comment by egorsmkv** [comment]
Thank you

**Comment by Li-jianqun** [comment]
how to train fsmn vad？
