### ISSUE TITLE
显存使用会不断增加，到最高后显存占用会保持不变。

### ISSUE THREAD

**Issue by lingfengchencn** [alibaba-damo-academy/FunASR#728]
存在内存占用不释放的情况，已经更新funasr至最新
```
git clone https://github.com/alibaba/FunASR.git  
cd FunASR
git pull
pip install --use-pep517 -e ./

funasr == 0.6.9
```

# 显存占用情况

| 操作| 显存占用|
| ----------| -----|
|加载model| 3256MiB|
|转写43s| 3488MiB|
|转写97s |5892MiB|
|转写242s|14952MiB|
|转写43s| 14952MiB|
|保持10分钟不动|14952MiB|

# load models 
``` python
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks
inference_pipeline = pipeline(
            task=Tasks.auto_speech_recognition,
            model='damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch',
            # vad_model='damo/speech_fsmn_vad_zh-cn-16k-common-pytorch',
            # punc_model='damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch',
            # output_dir="./output",
        )
```
## GPU Memory Usage : 3256MiB
![image](https://github.com/alibaba-damo-academy/FunASR/assets/2757011/99fcec69-948e-4a0b-a575-d1e9dfb487bb)

# 1、43s｜3488MiB
```python
file = 'storage/audios/2.wav' # 43s
import soundfile
speech,sample_rate = soundfile.read(file)
print(f"音频时长:{len(speech)/1000*sample_rate}")
result = inference_pipeline(audio_in=speech)
print(result)
```
## GPU Memory Usage: 3488MiB
![image](https://github.com/alibaba-damo-academy/FunASR/assets/2757011/061ec812-747a-4911-acca-1553d7ed6ead)

# 2、97s ｜5892MiB
```python
file = 'storage/audios/1单声道.wav' # 97s
import soundfile
speech,sample_rate = soundfile.read(file)
print(f"音频时长:{len(speech)/1000*sample_rate}")
result = inference_pipeline(audio_in=speech)
print(result)
```
## GPU Memory Usage: 5892MiB
![image](https://github.com/alibaba-damo-academy/FunASR/assets/2757011/71bd7514-d456-49a2-af79-476cb932c7d1)

# 3、 242s｜ 14952MiB
```python
file = 'storage/audios/2单声道.wav' # 242s
import soundfile
speech,sample_rate = soundfile.read(file)
print(f"音频时长:{len(speech)/1000*sample_rate}")
result = inference_pipeline(audio_in=speech)
print(result)
```
## GPU Memory Usage: 14952MiB
![image](https://github.com/alibaba-damo-academy/FunASR/assets/2757011/f3e4bb4e-4c5b-4c2e-a004-daca3f854427)

# 4 依然转写43s音频，
代码同1
## GPU Memory Usage: 14952MiB
![image](https://github.com/alibaba-damo-academy/FunASR/assets/2757011/7f93360f-c9e6-40bc-b163-a9339113f815)

**Comment by hnluo** [comment]
Please provide the complete script, I can't reproduce the problem you mentioned。

**Comment by lingfengchencn** [comment]
> Please provide the complete script, I can't reproduce the problem you mentioned。

yes， that's complete script, just use `inference_pipeline(audio_in=speech)`  for 4 times with longer audios.

after longer audio, it uses more GPU Memory, then I use short audio,GPU Meory does not change. 
so , step 3、4 use 14952MiB ，Although the 4th audio is shorter than third audio.

**Comment by lingfengchencn** [comment]
update codes  for test

first download audio from [link](https://vb.stream.tencentmusic.com/asdb/fiction/xuanhuan/shenmu/w8yaoij7.mp3?uid=4&lrid=bHJpZGFINXc4bUs4R3hMZz0=&res=96100000001&ct=1689306603212&ttl=86400000&fromTag=5&vkey=8377725DB77AE8DE1CBFBFBEAAA8903DCBD32CEB5DF7C231CBA65F85C3CE928202157AEF1871990373C88401201086D334DB6CF683241B86B1EBCC8ADDD6B952&tmeType=0)

convert to wav
```
ffmpeg -i w8yaoij7.mp3 -ar 16000 -ac 1 23.wav
```


```python

import subprocess

def get_gpu_memory(): # get GPU memory 
    memory_output = subprocess.check_output(['nvidia-smi', '--query-gpu=memory.used,memory.total', '--format=csv,nounits,noheader'], encoding='utf-8')
    memory_output = memory_output.strip().split('\n')
    gpu_memory = [tuple(map(int, item.split(', '))) for item in memory_output]

    for index, (used_memory, total_memory) in enumerate(gpu_memory):
        print(f"GPU {index}: Used Memory: {used_memory}, Total Memory: {total_memory}")

from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

inference_pipeline = pipeline(
            task=Tasks.auto_speech_recognition,
            model='damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch',
            # vad_model='damo/speech_fsmn_vad_zh-cn-16k-common-pytorch',
            # punc_model='damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch',
            # output_dir="./output",
        )
get_gpu_memory()

file = '23.wav' # 23 minutes
import soundfile
speech,sample_rate = soundfile.read(file)
get_gpu_memory()
for i in range(1,5):
    sound = speech[0:i*20*sample_rate]
    result = inference_pipeline(audio_in=sound)
    print(f'seconds: {i*20}')
    get_gpu_memory()
for i in range(5,1,-1):
    sound = speech[0:i*20*sample_rate]
    result = inference_pipeline(audio_in=sound)
    print(f'seconds: {i*20}')
    get_gpu_memory()
```

result:
```
GPU 0: Used Memory: 3258, Total Memory: 32768
seconds: 20
GPU 0: Used Memory: 3490, Total Memory: 32768
seconds: 40
GPU 0: Used Memory: 3490, Total Memory: 32768
seconds: 60
GPU 0: Used Memory: 3490, Total Memory: 32768
seconds: 80
GPU 0: Used Memory: 3734, Total Memory: 32768
seconds: 100
GPU 0: Used Memory: 4036, Total Memory: 32768
seconds: 80
GPU 0: Used Memory: 4036, Total Memory: 32768
seconds: 60
GPU 0: Used Memory: 4036, Total Memory: 32768
seconds: 40
GPU 0: Used Memory: 4036, Total Memory: 32768
```

**Comment by langgz** [comment]
We have investigated this issue and found that it is a feature of Torch. In order to improve inference speed, Torch caches intermediate results of the model for future inference. This leads to a problem of not releasing GPU memory. To solve this, adding the code to manually release the cache is necessary. https://github.com/alibaba-damo-academy/FunASR/commit/579afd6ac81570438c7e95164333155a9cca163c
