### ISSUE TITLE
怎么样才能输出文字识别的时间戳

### ISSUE THREAD

**Issue by chendanyu** [alibaba-damo-academy/FunASR#737]
怎么样才能输出文字识别的时间戳？就是每一个字或者句子都包含其出现的时间。我采用的是C++的版本，linxu系统。使用./funasr-wss-client --server-ip 127.0.0.1 --port 10095 --wav-path 3min_16000_1c.wav --thread-num 1 --is-ssl 1这个命令行

**Comment by langgz** [comment]
On going

**Comment by eisneim** [comment]
非常需要时间信息，期待大佬的更新
