### ISSUE TITLE
在线手册里的Speaker Diarization部分存在拼写错误

### ISSUE THREAD

**Issue by HuXinjing** [alibaba-damo-academy/FunASR#741]
https://alibaba-damo-academy.github.io/FunASR/en/modelscope_pipeline/sd_pipeline.html

Note: The modelscope pipeline supports all the models in [model zoo](https://alibaba-damo-academy.github.io/FunASR/en/model_zoo/modelscope_models.html#pretrained-models-on-modelscope) to inference and **finetine.**
是想写finetune吧

**Comment by lyblsgo** [comment]
thx，we will fix it.
