### ISSUE TITLE
speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404 finetune报错

### ISSUE THREAD

**Issue by hzfei** [alibaba-damo-academy/FunASR#743]
OS:ubuntu20.04
python:3.9.16
funasr:0.6.9
modelscope:1.7.1
command: finetune.py
报错：
![企业微信截图_16895624478939](https://github.com/alibaba-damo-academy/FunASR/assets/42926130/1974c4df-f61c-46b0-b042-4ec562fb9584)

**Comment by hnluo** [comment]
Bug fixed, please update funasr
[https://github.com/alibaba-damo-academy/FunASR/pull/745](https://github.com/alibaba-damo-academy/FunASR/pull/745)
