### ISSUE TITLE
模型许可协议中没有明确商用和分发

### ISSUE THREAD

**Issue by endink** [alibaba-damo-academy/FunASR#749]
如有限制，麻烦告知~谢谢

**Comment by langgz** [comment]
1 Definitions
In this agreement, [FunASR software] refers to the FunASR open source model, and its derivatives, including fine-tuned models. [You] refer to individuals or organizations who use, modify, share, and learn from [FunASR software].

2 License and Restrictions

2.1 License
You are **free to use, copy, modify, and share** [FunASR software] under the conditions of this agreement.

2.2 Restrictions
You should indicate the code and model source and author information when using, copying, modifying and sharing [FunASR software]. You should keep the relevant names of models in [FunASR software].

**Comment by endink** [comment]
ok,我理解为商业用途这个许可协议也适用，感谢回复。
