### ISSUE TITLE
微调出现报错

### ISSUE THREAD

**Issue by appleLK** [alibaba-damo-academy/FunASR#751]
OS:  linux
Python Version：3.7.16
Package Version：pytorch 1.13.1、torchaudio 0.13.1、modelscope 1.7.1、funasr 0.7.0
Model：speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
Command：python finetune.py
Details：使用本地数据微调
Error log：RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

**Comment by hnluo** [comment]
Please check that you have an NVIDIA driver installed on your system or the installed driver is not compatible with the current version of CUDA
