### ISSUE TITLE
wav.scp中包含url时，vad识别报错

### ISSUE THREAD

**Issue by liuchenustb** [alibaba-damo-academy/FunASR#752]
wav.scp文件内容如下：
1   http://record-internal.didapinche.com/2023-07-19/1368896709903515648/mp3/16897375239fe2a374c91G.mp3
2   /home/ai_user/liuchen/FunASR/egs_modelscope/asr/paraformer/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/test/16897375239fe2a374c91G.mp3

2是在1的url中wget的，但是在识别的时候就会报打不开这个url的错误：Error opening 'http://record-internal.didapinche.com/2023-07-19/1368896709903515648/mp3/16897375239fe2a374c91G.mp3': System error.

版本信息：
python=3.7、funasr=0.7.0、modelscope=1.7.1

识别代码：
def modelscope_infer(args):
    os.environ['CUDA_VISIBLE_DEVICES'] = str(args.gpuid)
    inference_pipeline = pipeline(
    task=Tasks.voice_activity_detection,
    model='damo/speech_fsmn_vad_zh-cn-16k-common-pytorch',
    model_revision=None,
    output_dir=args.output_dir
    )
    try:
        inference_pipeline(audio_in=args.audio_in)
    except Exception as e:
        print(e)
        pass

**Comment by hnluo** [comment]
When audio input type is scp file, only supports local audio file decoding，you can try audio_in="url audio"。

**Comment by liuchenustb** [comment]
好的，多谢，那我关闭这个问题了
