### ISSUE TITLE
kaldi-native-fbank-dll.dll环境依赖问题

### ISSUE THREAD

**Issue by DearVa** [alibaba-damo-academy/FunASR#753]
开发者您好，我在客户机上使用C#的样例时，出现`kaldi-native-fbank-dll.dll or one of its dependencies: 找不到指定的模块。(0x8007007E)`错误，应当系该dll依赖vc++运行库所致。由于在客户机上安装vc++运行库有很大的不便，我打算自行编译静态链接的dll，但是我并没有找到该dll的源代码，其中的一些导出函数我未在[kaldi-native-fbank](https://github.com/csukuangfj/kaldi-native-fbank)当中找到（如AcceptWaveformxxx等）。请问可否提供`kaldi-native-fbank-dll.dll`项目的源代码，或者是发布静态链接的版本（使用/MD编译选项）。

**Comment by manyeyes** [comment]
@DearVa，您好，kaldi-native-fbank-dll.dll项目的源代码：https://github.com/manyeyes/KaldiNativeFbankSharp
您可以使用nuget更新项目中引用的KaldiNativeFbankSharp到1.0.2版本，在runtimes中有已编译好的版本，目前已支持linux-x64 和 osx.10.14-x64

**Comment by DearVa** [comment]
十分感谢
