### ISSUE TITLE
热词模型微调过程中遇到的问题

### ISSUE THREAD

**Issue by David19970306** [alibaba-damo-academy/FunASR#756]
OS: linux
Python Version：3.7.16
Package Version：pytorch 1.13.1、funasr 0.7.0
Model：speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404
Command：python finetune.py
Details：使用本地数据微调，微调过程中无法进行提督更新
![image](https://github.com/alibaba-damo-academy/FunASR/assets/29672477/2d64cd99-299e-47ce-b41b-716aabf9de38)

**Comment by David19970306** [comment]
the lengths of my audios are less than 15s，and i had checked the filter wav text fun，it does not filter any audio



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ 原始邮件 ------------------
From: Lizerui9926 ***@***.***&gt;
发送时间: 07/20/2023, 20:09
To: alibaba-damo-academy/FunASR ***@***.***&gt;
抄送: 吴伟鹏 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [alibaba-damo-academy/FunASR] 热词模型微调过程中遇到的问题 (Issue #756)





 
Please check if the dataset is correct and if it is too long. The audio exceeding 15 seconds will be filtered by default during training.

**Comment by yata0** [comment]
> 

请问热词版微调的数据格式应该是什么样子的

**Comment by Lizerui9926** [comment]
> > 
> 
> 请问热词版微调的数据格式应该是什么样子的

The training data format is the same as base paraformer, you can refer to https://alibaba-damo-academy.github.io/FunASR/en/egs_modelscope/asr/TEMPLATE/README.html#finetune-with-your-data
