### ISSUE TITLE
微调报错

### ISSUE THREAD

**Issue by appleLK** [alibaba-damo-academy/FunASR#759]
OS:ubuntu20.04-cuda11.7.1-py38-torch2.0.1-tf1.15.5-1.7.0Python 
Version：3.8.16
Package Version：torchaudio 2.0.2、modelscope 1.7.0、funasr version 0.7.0
Model：speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
Command：python finetune.py
![lQLPJwh4FUeFclrNAzvNBJuws0WySOWsuIEErkKbeoDfAA_1179_827](https://github.com/alibaba-damo-academy/FunASR/assets/18184062/f3290e13-beff-4020-b817-2cf0a44a6cb5)

**Comment by Lizerui9926** [comment]
Please check if the data path is correct according to the sample wav.scp format.

**Comment by appleLK** [comment]
![bc1ea03e1930d4d893ca09ead69ed1ba](https://github.com/alibaba-damo-academy/FunASR/assets/18184062/baa4e314-a5d4-43bc-a7ca-8d0bc0b3b064)
请看我的数据格式是否有问题

**Comment by babysor** [comment]
兄弟，我解决方式就是把所有语音都转成单声道。你可以试下。
