### ISSUE TITLE
Where is the  "funasr/bin/lm_inference.py"?

### ISSUE THREAD

**Issue by yata0** [alibaba-damo-academy/FunASR#760]
https://github.com/alibaba-damo-academy/FunASR/blob/b9d6be45fb7da977be51a89455a61149c463aae9/egs/aishell2/transformerLM/run.sh#L235C5-L235C47

**Comment by langgz** [comment]
Bug has been fixed. Please see the updated version.
https://github.com/alibaba-damo-academy/FunASR/blob/main/egs/aishell2/transformerLM/run.sh#L235C4-L235C4
