### ISSUE TITLE
采用websocket协议的c++ Windows部署方案

### ISSUE THREAD

**Issue by cgisky1980** [alibaba-damo-academy/FunASR#762]
希望有采用websocket协议的c++ windows部署方案  最好出个Relese包

**Comment by codezc** [comment]
我也需要

**Comment by leorusLao** [comment]
同求

**Comment by 13623667123** [comment]
![image](https://github.com/alibaba-damo-academy/FunASR/assets/155942318/7499c286-0053-4f5a-ae30-8713f9399d71)
![image](https://github.com/alibaba-damo-academy/FunASR/assets/155942318/5966c603-40d9-4734-a3af-9279aaf08eae)
乱码是什么问题了？

**Comment by lyblsgo** [comment]
FunASR社区软件包windows版本: https://www.modelscope.cn/models/iic/funasr-runtime-win-cpu-x64/summary

**Comment by lyblsgo** [comment]
If the issue persists, please reopen the issue and provide detailed steps to reproduce, as well as server and client logs.
