### ISSUE TITLE
FunASR离线文件转写服务 支持多线程吗

### ISSUE THREAD

**Issue by hpqiu** [alibaba-damo-academy/FunASR#763]
文档 funasr/runtime/docs/SDK_tutorial_zh.md 好像是说支持多线程的，但我用例子代码funasr_wss_client.py，测试结果，只能单线程。服务器配置:
PARAMS_DECODER_THREAD_NUM=32
PARAMS_IO_THREAD_NUM=8

请教是我配置有问题吗？

**Comment by hpqiu** [comment]
Ubuntu  22.04 64位
gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04.1)
Python 3.10.6
./funasr-runtime-deploy-offline-cpu-zh.sh start

  The path in the docker of the FunASR service executor          : /workspace/FunASR/funasr/runtime/websocket/build/bin/funasr-wss-server
  Set the host port used for use by the FunASR service           : 10095
  Set the docker port used by the FunASR service                 : 10095
  Set the number of threads used for decoding the FunASR service : 32
  Set the number of threads used for IO the FunASR service       : 8

  Sample code will be store in local                             : /root/funasr-runtime-resources/samples
  The flag for the use of SSL                                    : 1
  The docker ID that already exists is                           : 73a445d801d1

客户端 线程=1正常
python3 funasr_wss_client.py --host "127.0.0.1" --port 10095 --mode offline --audio_in /root/kkk2.wav --thread_num=1
Namespace(host='127.0.0.1', port=10095, chunk_size=[5, 10, 5], chunk_interval=10, audio_in='/root/kkk2.wav', send_without_sleep=True, thread_num=1, words_max_print=10000, output_dir=None, ssl=1, mode='offline')
/root/funasr-runtime-resources/samples/python/funasr_wss_client.py:277: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(ws_client(id, chunk_begin, chunk_size))
/root/funasr-runtime-resources/samples/python/funasr_wss_client.py:258: DeprecationWarning: ssl.SSLContext() without protocol argument is deprecated.
  ssl_context = ssl.SSLContext()
/root/funasr-runtime-resources/samples/python/funasr_wss_client.py:258: DeprecationWarning: ssl.PROTOCOL_TLS is deprecated
  ssl_context = ssl.SSLContext()
connect to wss://127.0.0.1:10095
pid0_0: demo: 不开不开我不开。
Exception: sent 1000 (OK); then received 1000 (OK)
end
线程=2，只有一线正常
python3 funasr_wss_client.py --host "127.0.0.1" --port 10095 --mode offline --audio_in /root/kkk2.wav --thread_num=1
Namespace(host='127.0.0.1', port=10095, chunk_size=[5, 10, 5], chunk_interval=10, audio_in='/root/kkk2.wav', send_without_sleep=True, thread_num=1, words_max_print=10000, output_dir=None, ssl=1, mode='offline')
/root/funasr-runtime-resources/samples/python/funasr_wss_client.py:277: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(ws_client(id, chunk_begin, chunk_size))
/root/funasr-runtime-resources/samples/python/funasr_wss_client.py:258: DeprecationWarning: ssl.SSLContext() without protocol argument is deprecated.
  ssl_context = ssl.SSLContext()
/root/funasr-runtime-resources/samples/python/funasr_wss_client.py:258: DeprecationWarning: ssl.PROTOCOL_TLS is deprecated
  ssl_context = ssl.SSLContext()
connect to wss://127.0.0.1:10095
pid0_0: demo: 不开不开我不开。
Exception: sent 1000 (OK); then received 1000 (OK)
end

**Comment by lukeewin** [comment]
C++版本是支持多线程并发转录的，但是python版本的目前不支持并发转录，这是我所知道的，同时我也想知道如何修改python代码，使得我可以在python中并发转录，因为C++版本虽然是并发转录，但是不是实时转录的。
