### ISSUE TITLE
Paraformer-large-热词版模型不支持长音频

### ISSUE THREAD

**Issue by 1547481339** [alibaba-damo-academy/FunASR#766]
Paraformer-large-热词版模型不支持长音频
speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404 识别长音频（7分钟wav文件，大小14M），报错
RuntimeError: [enforce fail at CPUAllocator.cpp:68] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 871194256 bytes. Error code 12 (Cannot allocate memory)

**Comment by lingfengchencn** [comment]
是不支持的，用之前，先用vad /sd 等模型对音频进行切割后，在丢给 热词版模型就好啦。

**Comment by R1ckShi** [comment]
这里是一个示例，可以使用带有vad的pipeline，模型本身不能解码过长的音频

from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

param_dict = dict()
param_dict['hotword'] = "三茅老师"
param_dict['clas_scale'] = 1.00  # 1.50 # set it larger if you want high recall (sacrifice general accuracy)
# 13% relative recall raise over internal hotword test set (45%->51%)
# CER might raise when utterance contains no hotword

inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model="damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404",
    vad_model="damo/speech_fsmn_vad_zh-cn-16k-common-pytorch",
    param_dict=param_dict)

rec_result = inference_pipeline(audio_in='https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/vad_example.wav')
print(rec_result)
