### ISSUE TITLE
音频静音时间过长，识别结果时间戳跨越太大

### ISSUE THREAD

**Issue by lawindman666** [alibaba-damo-academy/FunASR#771]
开发者，你好！
我现在遇到一个问题，在音频的中间部分，如果静音时间比较长，出来的时间戳跨度比较大。
比如音频从30s-50s都是静音，出来的时间戳是这样
5
00:00:27,300 --> 00:00:48,920
也会留情不认一朵电话

6
00:00:49,100 --> 00:00:50,700
真是让人伤神

第六条字幕的时间跨度太大，有参考可以设置吗？
我上次了一个测试音频
[MyAudio_4.zip](https://github.com/alibaba-damo-academy/FunASR/files/12123086/MyAudio_4.zip)
？

**Comment by langgz** [comment]
Please list you envs

OS: [e.g. linux]
Python/C++ Version：
Package Version：pytorch、torchaudio、modelscope、funasr version（pip list）
Model：
Command：
Details：
Error log：
