### ISSUE TITLE
流语音识别，运行服务程序报错

### ISSUE THREAD

**Issue by hpc203** [alibaba-damo-academy/FunASR#774]
按照这里的例子，运行流语音识别程序
python funasr_wss_server.py --port 10095
报错了，错误日志是这样的
![image](https://github.com/alibaba-damo-academy/FunASR/assets/28389623/aa758a43-154b-469e-a155-d119f7cd636d)
我的机器里，已经安装过modelscope funasr，为什么会出现这个错误呢

**Comment by langgz** [comment]
Please list your envs:

OS: [e.g. linux]
Python/C++ Version：
Package Version：pytorch、torchaudio、modelscope、funasr version（pip list）
Model：
Command：
Details：
Error log：

**Comment by hpc203** [comment]
OS: linux
Python3.11
Package Version：pytorch2.0.1、torchaudio2.0.2、modelscope1.3.2、funasr0.7.0
Model：damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online
Command：python funasr_wss_server.py --port 10095
Details：
Error log：ImportError:
Audio model import failed: modelscope.preprocessors.asr, if you want to use audio related function, please execute
`pip install modelscope[audio] -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html`

**Comment by hpc203** [comment]
> Please list your envs:
> 
> OS: [e.g. linux] Python/C++ Version： Package Version：pytorch、torchaudio、modelscope、funasr version（pip list） Model： Command： Details： Error log：

已经列出了环境情况，请问是什么原因呢？

**Comment by hnluo** [comment]
Please update modelsocpe，pip install modelscope[audio] -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html

**Comment by hpc203** [comment]
> Please update modelscope，pip install modelscope[audio] -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html

这个指令，试过好多次了，还是报错的

**Comment by langgz** [comment]
Please update modelscope by cmd:

```shell
pip install -U modelscope -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html -i https://mirror.sjtu.edu.cn/pypi/web/simple
```

Update funasr by:

```shell
git clone https://github.com/alibaba/FunASR.git && cd FunASR
pip install -e ./
```

**Comment by lukeewin** [comment]
> 

你是否已经安装了modelscope，如果没有安装，可以执行pip install modelscope命令安装一下这个依赖包。
