### ISSUE TITLE
怎样可以提高热词的召回率

### ISSUE THREAD

**Issue by uloveqian2021** [alibaba-damo-academy/FunASR#782]
目前用热词模型时发现，有一些词加到热词表里后也无法识别，请问怎样可以提高热词的召回率

**Comment by hnluo** [comment]
Fine-tuning may be fine

**Comment by R1ckShi** [comment]
热词模型的inference支持通过clas_scale调整激励大小，默认1.0，越大热词激励越明显，参考https://github.com/alibaba-damo-academy/FunASR/blob/main/egs_modelscope/asr/paraformer/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404/demo.py
contextual_paraformer的热词激励是隐式的，不能显式的优化目标热词，上述方法依然不能召回可以尝试使用自己的数据finetune热词模型
