### ISSUE TITLE
微调paraformer-large模型速度慢，更改batchsize后也无效

### ISSUE THREAD

**Issue by sunnymoon155** [alibaba-damo-academy/FunASR#783]
4卡训练显存占用只有5G，请问这个怎么能调一下batch size呢？batch_bins这个参数指的是batch size吗，调整后无效呀。
另外数据读取支持wenet类似的tar格式吗

**Comment by hnluo** [comment]
Please refer to https://alibaba-damo-academy.github.io/FunASR/en/modelscope_pipeline/asr_pipeline.html#finetune-with-pipeline

**Comment by yangppde** [comment]
请问问题后面有解决吗
