### ISSUE TITLE
离线长音频版本，pb转onnx后精度下降

### ISSUE THREAD

**Issue by Dalaoyel** [alibaba-damo-academy/FunASR#785]

**Comment by Dalaoyel** [comment]
model_dir = "damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch"
中文还好，英文很多词会错乱。这是否正常

**Comment by langgz** [comment]
OS: [e.g. linux]
Python/C++ Version：
Package Version：pytorch、torchaudio、modelscope、funasr version（pip list）
Model：
Command：
Details：
Error log：

**Comment by Dalaoyel** [comment]
OS: linux
Python/C++ Version：3.7.0
Package Version：
	pytorch==1.12.0+cu113、
	torchaudio==0.12.0+cu113、
	modelscope==1.6.1、
	funasr version==0.7.1、
	onnx==1.14.0、
	onnxruntime、1.14.1

Model：
	speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch

Command:
	
	model.onnx：
	from funasr.runtime.python.onnxruntime.funasr_onnx import Paraformer,Fsmn_vad,CT_Transformer
	model_dir = "./speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch"
	quantize = False
	intra_op_num_threads = 1
	asr_model = Paraformer(model_dir, batch_size=1, quantize=quantize, intra_op_num_threads=intra_op_num_threads)
	punc_model = CT_Transformer("./punc_ct-transformer_zh-cn-common-vocab272727-pytorch", batch_size=1, quantize=quantize, intra_op_num_threads=intra_op_num_threads)
	result_1 = asr_model("test_en_cn_mix.wav")
	result_2 = punc_model(result_1[0]["preds"])
	print(result_1,result_2)

	model.pb：
	inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model="./speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch",)
	rec_result = inference_pipeline(audio_in="test_en_cn_mix.wav")
	print(rec_result)


Details：
pb推理如下：
'text': "这几天，拉老师准备教材新秀的面试，然后看自己录下来的视频，发现我的课堂语言真的非常的匮乏。有时候学生回答完了，想要评价一下，就只会good very good，自己都觉得很尴尬。所以呢这几天我就在网上看了大概三四十个美国老师上课的视频，我整理了一些classroom language or classroom phrases来供大家参考。第一块是classiroom management or classiroom ministrations，就是你为课堂设计的一些活动，你怎么样来引导指令你的学生去进行操作呢？比如你想让你的学生开始阅读吧，这怎么讲啊？let's start reading about you're going to read paragraph three。now we're going to read paragraph three， what i'd like it to do is to read paragraph three and figure out its topic sentence。i want you to read paragraph three and figure out it's main idea。 gonna have read ad paragraph， three and out out main grah three具体。一，please please turn to ge three locate paragraph two。now let's figure out what it is meaning about那开始吧。怎么说？let's get started。 let's begin ready here。 we go。okay， go ahelp限制时间for one minute。 i'll call it to stop跟我读free after me。第二部分呢是在课堂上向学生提问asking questions。你可以说it looks like you too are having a good discussion。 could you please share your opinions with us？could you tell me the meaning of the title？ i was wondering if you know the meaning of the title， do you know the meaning of the title？i'd like to know your understanding of the title。有时候没听清楚学生的回答，你可以追问。are you saying i didn't quite follow you could you say again，最后一个部分呢？就是在学生回答完以后，给他们一些反馈，giving feedbacks学生回答的不错，可以说good good， try did a good job， well done excellent。 that's wrthat i absolutely很熟。嗯，that's interesting你同意学生的观点。你可以说i'm with you on答案。i agree with you。i have the same opinion，学生回答的不好，你也要鼓励他。don't worry about that。i appreciate your trying，你i can it it dyour next time。那老师整理的呢暂时就是这些了，我觉得要真正把他们内化为自己上课时能够脱口而出的教师用语，大家是需要在真正的课堂上不断的去提醒自己，要用上这些你新学习的语言，不然在开公开课或者是面试的时候，你还要去思考一下教师用语是什么？那真的挺分散你的注意力的，就是你本来对自己的这节课的设计可能还没有记得很熟。一我还要再去思考教师用语。呃，真的是挺拖后腿的一件事情。当然了，准备好教师用语，这是一堂课当中一个你可以准备的很小的细节。更重要的是，你对整堂课的设计，你想让学生学会省用最好的教师用语，就是你和学生之间自然发生的交流光准备这些教师用语是完全不够的。课堂学学生的回答你是永远意料不到的。而且每节课都有自己特定的话题。所以你要不断充实自己的常识，多增长一些见识。同时就很多的话题，自己平常就多多训练口语的表达，这样才能在课堂当中做到自然从容、淡定有趣，吸引学生。十月底还有一堂公开课，等着拉老师，我们一起加油吧。如果喜欢拉老师这方面的内容，记得点赞、收藏评论告诉我，我们下期见了，拜拜。"
onnx推理如下：
这几天，拉老师准备教材新秀的面试，然后看自己录下来的视频，发现我的教堂语言真的非常的匮乏。有时候学生回答完了，想要评价一下，就只会good very good，自己都觉得很尴尬。所以呢这几天我就在网上看了大概三四十个。now let's t's上课的视频，我整理了一些classroom language or clclh your agraphh three make参加ggleleyou to clash m aggrah three。 now clclh room paragraphs。就let's t's read设计的一些活动，你怎么样来引导指令你的学生去进行操作呢？比如let's让你的学生开始阅读吧，这怎么讲？let's t's rireadme， again， ready going。 go， read paragraph three。 now。 let's going to read paragraph three。 now， let's get start do to to read paragraph three。i ggout out ad paraggraph three leyou to to read paragrapthree three figure out three。 my idea。i i'd have to read paragraph three now lead the pargragrah three， let's you to read ad figout three， read， paragraph three lelet's figure out what diaggraph three那开始吧。so so let's t's to art to read gragrah today。lewe go go you。 you go the制时间for one minute。 i'll tell it to stop three。let's ggthis第二部分呢是reggout three reggout or clclh me of the e。 you it leks like you too。i having a good discussion， could you please share your opinions with us？could you tell me the meaning of the title？i was wondering if you know the meaning of the title， do you know the meaning of the title？i didn't know your understanding of the title。有时候没听清楚学生的回答，你可以追问。i you say， i didn't quite follow you good disiniagain。最后一个部分呢就是在学生回答完以后给他们一些反馈，giving有语的当当学学学学的的西，你可以说要要你rea good job， b done excelelent about that you are absoluly rright。嗯，that's interesting你同意学生的观点。i可以说i with you on that。 i agree with you。i have the same opinion，学生回答的不好，你也要鼓励他。i like to about that。i appreciate your try again， you can do a bad， the the next time。你你要学学的呢？暂时就是的的了，你觉得要真正把他己内容学自己上课时能够脱口而出的教师用语。大家是需要在真正的学堂上，你断学学学习的东题，你要这这你的学习的设题，你你要要学学学学己己学习的时候，你还要要学学学些，你你学语语是什么？那这个请分散你的注意力的就是你真正对自己的这节课的设计，你能要学学学的的时，你你还要再去思考教师用语，真的是请folfolry的一件事情。当然了，准备好教师用语，这是一堂课当中一个你可以准备的很小的细节。更重要的是你对整堂课的设计，你想让学生学习的时候，最好的教师用语就是你和学生之间自然发生的时候，光准备这些教师用语是完全不够的。课堂上学生的回答你是永远学学的的的。而且每节课对我己己学定的设题，所以要要断断自己己己的话，识你学学学学的语，你时就很多的回答你，你要要对对己训练口语的表当，这样才能好教堂课中做到自然的容，做到有趣吸引学情。当然你还有一堂公开课等等，拉老师我们一起加油吧。如果喜欢拉老师这方面的内容，记得点赞、学藏学会告时，你你你下you you out you。"

Error log：
pb转onnx，英文单词连贯性精度损失。
.onnx is not exist, begin to export onnx
/data/yaoqiling/FunASR-main/funasr/modules/embedding.py:397: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  log_timescale_increment = torch.log(torch.tensor([10000], dtype=dtype, device=device)) / (depth / 2 - 1)
Warning: ONNX Preprocess - Removing mutation from node aten::add_ on block input: 'frame.17'. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation from node aten::add_ on block input: 'integrate.23'. This changes graph semantics.
Warning: ONNX Preprocess - Removing mutation from node aten::add_ on block input: 'integrate.21'. This changes graph semantics.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
/data/yaoqiling/anaconda3/envs/speech_test/lib/python3.7/site-packages/torch/onnx/symbolic_opset9.py:3227: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with LSTM can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  + "or define the initial states (h0/c0) as inputs of the model. "
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
output dir: ./speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch

test_video:
	https://www.bilibili.com/video/BV16R4y1p7J7/?spm_id_from=333.337.search-card.all.click&vd_source=313e806f3b4adad1c179f32c9476722b

**Comment by langgz** [comment]
> OS: linux Python/C++ Version：3.7.0 Package Version： pytorch==1.12.0+cu113、 torchaudio==0.12.0+cu113、 modelscope==1.6.1、 funasr version==0.7.1、 onnx==1.14.0、 onnxruntime、1.14.1
> 
> Model： speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch
> 
> Command:
> 
> ```
> model.onnx：
> from funasr.runtime.python.onnxruntime.funasr_onnx import Paraformer,Fsmn_vad,CT_Transformer
> model_dir = "./speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch"
> quantize = False
> intra_op_num_threads = 1
> asr_model = Paraformer(model_dir, batch_size=1, quantize=quantize, intra_op_num_threads=intra_op_num_threads)
> punc_model = CT_Transformer("./punc_ct-transformer_zh-cn-common-vocab272727-pytorch", batch_size=1, quantize=quantize, intra_op_num_threads=intra_op_num_threads)
> result_1 = asr_model("test_en_cn_mix.wav")
> result_2 = punc_model(result_1[0]["preds"])
> print(result_1,result_2)
> 
> model.pb：
> inference_pipeline = pipeline(
> task=Tasks.auto_speech_recognition,
> model="./speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch",)
> rec_result = inference_pipeline(audio_in="test_en_cn_mix.wav")
> print(rec_result)
> ```
> 
> Details： pb推理如下： 'text': "这几天，拉老师准备教材新秀的面试，然后看自己录下来的视频，发现我的课堂语言真的非常的匮乏。有时候学生回答完了，想要评价一下，就只会good very good，自己都觉得很尴尬。所以呢这几天我就在网上看了大概三四十个美国老师上课的视频，我整理了一些classroom language or classroom phrases来供大家参考。第一块是classiroom management or classiroom ministrations，就是你为课堂设计的一些活动，你怎么样来引导指令你的学生去进行操作呢？比如你想让你的学生开始阅读吧，这怎么讲啊？let's start reading about you're going to read paragraph three。now we're going to read paragraph three， what i'd like it to do is to read paragraph three and figure out its topic sentence。i want you to read paragraph three and figure out it's main idea。 gonna have read ad paragraph， three and out out main grah three具体。一，please please turn to ge three locate paragraph two。now let's figure out what it is meaning about那开始吧。怎么说？let's get started。 let's begin ready here。 we go。okay， go ahelp限制时间for one minute。 i'll call it to stop跟我读free after me。第二部分呢是在课堂上向学生提问asking questions。你可以说it looks like you too are having a good discussion。 could you please share your opinions with us？could you tell me the meaning of the title？ i was wondering if you know the meaning of the title， do you know the meaning of the title？i'd like to know your understanding of the title。有时候没听清楚学生的回答，你可以追问。are you saying i didn't quite follow you could you say again，最后一个部分呢？就是在学生回答完以后，给他们一些反馈，giving feedbacks学生回答的不错，可以说good good， try did a good job， well done excellent。 that's wrthat i absolutely很熟。嗯，that's interesting你同意学生的观点。你可以说i'm with you on答案。i agree with you。i have the same opinion，学生回答的不好，你也要鼓励他。don't worry about that。i appreciate your trying，你i can it it dyour next time。那老师整理的呢暂时就是这些了，我觉得要真正把他们内化为自己上课时能够脱口而出的教师用语，大家是需要在真正的课堂上不断的去提醒自己，要用上这些你新学习的语言，不然在开公开课或者是面试的时候，你还要去思考一下教师用语是什么？那真的挺分散你的注意力的，就是你本来对自己的这节课的设计可能还没有记得很熟。一我还要再去思考教师用语。呃，真的是挺拖后腿的一件事情。当然了，准备好教师用语，这是一堂课当中一个你可以准备的很小的细节。更重要的是，你对整堂课的设计，你想让学生学会省用最好的教师用语，就是你和学生之间自然发生的交流光准备这些教师用语是完全不够的。课堂学学生的回答你是永远意料不到的。而且每节课都有自己特定的话题。所以你要不断充实自己的常识，多增长一些见识。同时就很多的话题，自己平常就多多训练口语的表达，这样才能在课堂当中做到自然从容、淡定有趣，吸引学生。十月底还有一堂公开课，等着拉老师，我们一起加油吧。如果喜欢拉老师这方面的内容，记得点赞、收藏评论告诉我，我们下期见了，拜拜。" onnx推理如下： 这几天，拉老师准备教材新秀的面试，然后看自己录下来的视频，发现我的教堂语言真的非常的匮乏。有时候学生回答完了，想要评价一下，就只会good very good，自己都觉得很尴尬。所以呢这几天我就在网上看了大概三四十个。now let's t's上课的视频，我整理了一些classroom language or clclh your agraphh three make参加ggleleyou to clash m aggrah three。 now clclh room paragraphs。就let's t's read设计的一些活动，你怎么样来引导指令你的学生去进行操作呢？比如let's让你的学生开始阅读吧，这怎么讲？let's t's rireadme， again， ready going。 go， read paragraph three。 now。 let's going to read paragraph three。 now， let's get start do to to read paragraph three。i ggout out ad paraggraph three leyou to to read paragrapthree three figure out three。 my idea。i i'd have to read paragraph three now lead the pargragrah three， let's you to read ad figout three， read， paragraph three lelet's figure out what diaggraph three那开始吧。so so let's t's to art to read gragrah today。lewe go go you。 you go the制时间for one minute。 i'll tell it to stop three。let's ggthis第二部分呢是reggout three reggout or clclh me of the e。 you it leks like you too。i having a good discussion， could you please share your opinions with us？could you tell me the meaning of the title？i was wondering if you know the meaning of the title， do you know the meaning of the title？i didn't know your understanding of the title。有时候没听清楚学生的回答，你可以追问。i you say， i didn't quite follow you good disiniagain。最后一个部分呢就是在学生回答完以后给他们一些反馈，giving有语的当当学学学学的的西，你可以说要要你rea good job， b done excelelent about that you are absoluly rright。嗯，that's interesting你同意学生的观点。i可以说i with you on that。 i agree with you。i have the same opinion，学生回答的不好，你也要鼓励他。i like to about that。i appreciate your try again， you can do a bad， the the next time。你你要学学的呢？暂时就是的的了，你觉得要真正把他己内容学自己上课时能够脱口而出的教师用语。大家是需要在真正的学堂上，你断学学学习的东题，你要这这你的学习的设题，你你要要学学学学己己学习的时候，你还要要学学学些，你你学语语是什么？那这个请分散你的注意力的就是你真正对自己的这节课的设计，你能要学学学的的时，你你还要再去思考教师用语，真的是请folfolry的一件事情。当然了，准备好教师用语，这是一堂课当中一个你可以准备的很小的细节。更重要的是你对整堂课的设计，你想让学生学习的时候，最好的教师用语就是你和学生之间自然发生的时候，光准备这些教师用语是完全不够的。课堂上学生的回答你是永远学学的的的。而且每节课对我己己学定的设题，所以要要断断自己己己的话，识你学学学学的语，你时就很多的回答你，你要要对对己训练口语的表当，这样才能好教堂课中做到自然的容，做到有趣吸引学情。当然你还有一堂公开课等等，拉老师我们一起加油吧。如果喜欢拉老师这方面的内容，记得点赞、学藏学会告时，你你你下you you out you。"
> 
> Error log： pb转onnx，英文单词连贯性精度损失。 .onnx is not exist, begin to export onnx /data/xxxxxxx/FunASR-main/funasr/modules/embedding.py:397: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect. log_timescale_increment = torch.log(torch.tensor([10000], dtype=dtype, device=device)) / (depth / 2 - 1) Warning: ONNX Preprocess - Removing mutation from node aten::add_ on block input: 'frame.17'. This changes graph semantics. Warning: ONNX Preprocess - Removing mutation from node aten::add_ on block input: 'integrate.23'. This changes graph semantics. Warning: ONNX Preprocess - Removing mutation from node aten::add_ on block input: 'integrate.21'. This changes graph semantics. Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. /data/xxxxxxx/anaconda3/envs/speech_test/lib/python3.7/site-packages/torch/onnx/symbolic_opset9.py:3227: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with LSTM can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model.
> 
> * "or define the initial states (h0/c0) as inputs of the model. "
> 
> WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. output dir: ./speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch
> 
> test_video: https://www.bilibili.com/video/BV16R4y1p7J7/?spm_id_from=333.337.search-card.all.click&vd_source=313e806f3b4adad1c179f32c9476722b

The pipeline includes the VAD model, which can perform inference on long audio input. The ONNX model, by default, can only perform inference on short audio inputs of up to 15 seconds. If you need to process long audio, you have to combine the VAD model ONNX by yourself. We suggest using the C++ version of ONNX, which supports high-concurrency and multiple requests. Ref to [docs](https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/runtime/docs/SDK_tutorial_zh.md)
