### ISSUE TITLE
C++ Onnx Runtime 如何使用 UniASR 模型

### ISSUE THREAD

**Issue by endink** [alibaba-damo-academy/FunASR#788]
如何分别获得实时上屏的结果和校正后的结果，难道是要自己用代码推理两次吗？
用同一个模型分别初始化 FunOfflineInit 和 FunASRInit ？   
  
然后：   

   
FunASRInfer 和 FunOfflineInfer 分别推理？

因为 C++ 没有太多文档说明，也没有详细例子，目前用 Offline 效果良好，但是上屏不及时，希望指点，谢谢！

**Comment by hnluo** [comment]
UniASR model does not support exporting onnx models，we will release the c++ onnx runtime for two pass model soon，you can join the DingTalk group((27215013275)) for updates。

**Comment by endink** [comment]
2pass use python cmd, no plan for onnx?

**Comment by rookie0607** [comment]
> UniASR模型不支持导出onnx模型，我们将很快发布两个通道模型的c++ onnx运行时，您可以加入钉钉群((27215013275))获取更新。

uniasr模型以后会支持导出onnx吗
