### ISSUE TITLE
有没有一键部署阿里云函数计算的模版

### ISSUE THREAD

**Issue by xiangzidetiandi** [alibaba-damo-academy/FunASR#791]
我看魔塔上很多模型能够一键部署阿里云函数计算，能够快速在生产环境进行使用。调研了funasr的部署方式，没有发现能够快速在函数计算平台的部署方式，希望能够提供，降低在生产环境的使用门槛

**Comment by langgz** [comment]
Please ref to [deploy docs](https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/runtime/docs/SDK_tutorial_zh.md)
