### ISSUE TITLE
FunASR离线文件转写 内容丢失

### ISSUE THREAD

**Issue by chchenxingyu-cxy** [alibaba-damo-academy/FunASR#793]
**OS**: Linux 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Python/C++ Version：Python 3.7.16
**Package Version**：pytorch、torchaudio、modelscope、funasr version（pip list）
pytorch-wpe             0.0.1
torchaudio              0.11.0
modelscope              1.7.1
funasr                  0.7.1
**Model**：offline
**Command**：
服务端启动:python funasr_wss_server.py --port 10095 --certfile ""
客户端启动:python funasr_wss_client.py --host "127.0.0.1" --port 10095 --mode offline --audio_in "/opt/cctv_1.wav" --output_dir "./results" --ssl 0
**Details**：
离线转写功能，输入的音频没有完全转写，结果缺一部分.
客户端启动后的结果:
pid0_0: demo: 二零一四年，习近平总书记两次来到河南兰考，总书记叮嘱兰考的党员干部，要切实关心农村，每个家庭特别是贫困家庭通过因地制宜发展产业，促进农民增收致富落实。总书记重要要求兰考作出了三年脱贫七年小康的承诺。近年来，当地因地制宜，发展壮大，产业顺利脱贫摘帽眼下，鸡蛋销售迎来好行情。这两天，张庄村村民闫春光一直在鸡场里忙活，将一筐筐鸡蛋装箱出售

音频地址: https://wwvu.lanzouq.com/iCXBf13z6awd

**Comment by zhaomingwork** [comment]
see #794

**Comment by chchenxingyu-cxy** [comment]
FunASR/funasr/runtime/java/FunasrWsClient.java 这个文件还会出现上面的问题

**Comment by langgz** [comment]
> FunASR/funasr/runtime/java/FunasrWsClient.java 这个文件还会出现上面的问题

ref to https://github.com/alibaba-damo-academy/FunASR/pull/795
