### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by wl-junlin** [alibaba-damo-academy/FunASR#797]
I am using ubuntu20.04, g++ 9.4.0, cmake 3.26.3, to compile runtime/websocket

> **_i added include_directories(${ONNXRUNTIME_DIR}/include) to cmakefile.txt to solve the missing .h file error_**

### commands
`cmake  -DCMAKE_BUILD_TYPE=debug .. -DONNXRUNTIME_DIR=third_party/onnxruntime-linux-x64-1.14.0 -DFFMPEG_DIR=third_party/ffmpeg-N-111383-g20b8688092-linux64-gpl-shared `

`make`

### error
[ 63%] Building CXX object src/CMakeFiles/funasr.dir/audio.cpp.o
/home/FunASR/funasr/runtime/onnxruntime/src/audio.cpp: In member function ‘bool funasr::Audio::FfmpegLoad(const char*)’:
/home/FunASR/funasr/runtime/onnxruntime/src/audio.cpp:251:91: error: invalid conversion from ‘const AVCodec**’ to ‘AVCodec**’ [-fpermissive]
  251 |     int audioStreamIndex = av_find_best_stream(formatContext, AVMEDIA_TYPE_AUDIO, -1, -1, &codec, 0);
      |                                                                                           ^~~~~~
      |                                                                                           |
      |                                                                                           const AVCodec**

**Comment by StargazerWayne** [comment]
> You can use docker for compiling the project([docker sdk](https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/runtime/docs/SDK_tutorial_zh.md))

what if I want compile from source, is there any tutorial?@hnluo

**Comment by StargazerWayne** [comment]
> > You can use docker for compiling the project([docker sdk](https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/runtime/docs/SDK_tutorial_zh.md))
> 
> what if I want compile from source, is there any tutorial?[@hnluo](https://github.com/hnluo)

I just sorted it out on my own. For those may need ([the tutorial](https://github.com/modelscope/FunASR/blob/main/runtime/websocket/readme.md)).
