### ISSUE TITLE
可以在android平台推理吗？

### ISSUE THREAD

**Issue by wchuan163** [alibaba-damo-academy/FunASR#8]
可以在android平台推理吗？

**Comment by langgz** [comment]
目前还不行，需要自己移植一下环境

**Comment by csukuangfj** [comment]
可以看下 https://github.com/k2-fsa/sherpa-onnx/releases/tag/v1.8.10

支持在 android 和 ios 上跑 Paraformer. 流式和非流式的 Paraformer, 都支持.

<img width="971" alt="Screenshot 2023-11-23 at 13 25 49" src="https://github.com/alibaba-damo-academy/FunASR/assets/5284924/10dae484-1e7e-423a-bc83-62925a121ae4">
