### ISSUE TITLE
客户端使用2psss时，怎么区分那些返回是First-pass，那些返回是Second-pass

### ISSUE THREAD

**Issue by chenxingyu-cxy** [alibaba-damo-academy/FunASR#803]
客户端启动
python funasr_wss_client.py --host "127.0.0.1" --port 10095 --mode 2pass --chunk_size "5,10,5" --audio_in "/opt/cctv_1.wav" --ssl 0

以下是返回结果
{'mode': '2pass-online', 'text': '二零一', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '四年习', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '近平总书', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '记两', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '次来到', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '河南兰', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '考', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '总书记宾', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '嘱兰考', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '的党员干', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '部要', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '切实关', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '心农', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '村每个家', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '庭特别', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '是贫', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '困家庭', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '通过', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '因地制', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '宜发展', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '产业', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '促进农', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '民增收', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '致富', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '落', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '实总书', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '记重要', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '要求', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '兰考作', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '出了', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '三年脱', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '贫七', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '年小', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '康的承诺', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '近年来', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '当地', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '因地制', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '宜发展', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '壮大产', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '业顺', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '利脱', 'wav_name': 'demo', 'is_final': True}
{'mode': '2pass-online', 'text': '贫摘帽', 'wav_name': 'demo', 'is_final': True}{'mode': '2pass-offline', 'text': '二零一四年，习近平总书记两次来到河南兰考，总书记叮嘱兰考的党员干部，要切实关心农村，每个家庭特别是贫困家庭通过因地制宜发展产业，促进农民增收致富落实。总书记重要要求兰考作出了三年脱贫七年小康的承诺。近年来，当地因地制宜，发展壮大，产业顺利脱贫摘帽', 'wav_name': 'demo', 'is_final': True}

**Comment by MyWestCity** [comment]
你可以改下代码的，前面那每个小句都是async_asr_online这个方法里面推理返回的，最后一句是async_asr推理返回的，你分别加一个不同的标志位就行了

**Comment by langgz** [comment]
> 2pass-offline

The `mode` of 1st pass is `2pass-online`, and the 2nd is `2pass-offline`.
