### ISSUE TITLE
关于python示例代码中的几个模型使用的问题

### ISSUE THREAD

**Issue by quzhixue-Kimi** [alibaba-damo-academy/FunASR#814]
hi there,

关于python示例（FunASR/funasr/runtime/python/websocket/funasr_wss_server.py）代码中所使用的几个模型的问题：

### _问题1:_
parser.add_argument("--asr_model",
                    type=str,
                    default="damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch",
                    help="model from modelscope")
// https://www.modelscope.cn/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch/summary

parser.add_argument("--asr_model_online",
                    type=str,
                    default="damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online",
                    help="model from modelscope")
// https://www.modelscope.cn/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/summary

parser.add_argument("--vad_model",
                    type=str,
                    default="damo/speech_fsmn_vad_zh-cn-16k-common-pytorch",
                    help="model from modelscope")
// https://modelscope.cn/models/damo/speech_fsmn_vad_zh-cn-16k-common-pytorch/summary

parser.add_argument("--punc_model",
                    type=str,
                    default="damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727",
                    help="model from modelscope")
// https://modelscope.cn/models/damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727/summary

并且使用html client代码（FunASR/funasr/runtime/html5/static）进行测试：

**_### model： 2pass或者online
选择录音模式：麦克风_**

用2台电脑分别作为html客户端连接到python运行的服务端，发现第一个问题：

后一个电脑连接成功后，并开启麦克风进行录音，可以在html实时输出！但是此前连接成功后的电脑客户端，在开启录音后无法实时输出内容。
试着注释掉 第135行  await clear_websocket() 代码，然后重新进行测试，问题解决了！

### **_问题2:_**
试着在服务器端输出中文内容，进行代码修改
message = json.dumps({"mode": mode, "text": rec_result["text"], "wav_name": websocket.wav_name,"is_final":websocket.is_speaking}, ### **_ensure_asiic=False_**)
print(message)

同时，### **_为了区别两台电脑，是不同的坐席人员，将html中wav_name字段临时改为uuid_**

输出内容如下：
![image](https://github.com/alibaba-damo-academy/FunASR/assets/8235746/3ccc56c3-3a7c-4630-870d-48c26ca587c4)

### **_问题3:_**
目前是实时对麦克风进行测试！是不是意味着电话通话过程中，只能识别当前电脑设备的麦克风内容，而无法识别到通话另一头的内容？
（坐席人员所说的内容可以识别，而另一边的用户所说的内容无法识别）
是否，如果是wav或者mp3离线文件中的2人或者多人的完整录音对话，则可以分别识别出对应的内容呢？

**Comment by langgz** [comment]
The python service only supports one client. If you have more than one client, you could deploy the c++ service. [c++ deploy docs](https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/runtime/docs/SDK_tutorial_online_zh.md)

**Comment by quzhixue-Kimi** [comment]
hi there,

Is there any information in the document about 'The python service only supports one client'? If possible, please add it.

And, are there any ideas about the rest issues?

BR
Kimi

**Comment by quzhixue-Kimi** [comment]
hi there,

Followed by the document via https://alibaba-damo-academy.github.io/FunASR/en/funasr/runtime/websocket/readme.html
In the section 'Service with websocket-cpp', we tried to run the command as below:

### 
**_./funasr-wss-server-2pass --download-model-dir /workspace/models --offline-model-dir /workspace/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx --vad-dir /workspace/models/damo/speech_fsmn_vad_zh-cn-16k-common-onnx --punc-dir /workspace/models/damo/punc_ct-transformer_zh-cn-common-vocab272727-onnx --online-model-dir /workspace/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online --quantize False_**

One error occurred:
No argument of --offline-model-dir
![image](https://github.com/alibaba-damo-academy/FunASR/assets/8235746/fb4c8d23-1bcb-4966-bd6a-90bcd7450190)



And, we tried to modify and run the command again:

### **_./funasr-wss-server-2pass --offline-model-revision /workspace/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx --vad-dir /workspace/models/damo/speech_fsmn_vad_zh-cn-16k-common-onnx --punc-dir /workspace/models/damo/punc_ct-transformer_zh-cn-common-vocab272727-onnx --online-model-dir /workspace/models/damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online --quantize false_**

One new error occurred:
![image](https://github.com/alibaba-damo-academy/FunASR/assets/8235746/f0db8437-7df5-4b21-81a6-41ffd2be45ae)


It is appreciated that you may help update your document and investigate about the 'decoder.onnx' issue.


BR
Kimi

**Comment by langgz** [comment]
> 

For the `chunk_size`:`[5, 10, 5]`, it means duration of current chunk is 600ms, with 300ms lookback and 300ms lookahead. The lookback and lookahead is doing on the side of server, which means you only send 600ms audio bytes to server for one time.
![paraformer-online](https://github.com/alibaba-damo-academy/FunASR/assets/18321252/612dc1f8-0701-44e0-896f-6c405c5c3d1d)

**Comment by langgz** [comment]
> 

The docs has been fix. Please ref to the new docs. https://github.com/alibaba-damo-academy/FunASR/commit/e08be2e41ca35031e1ea7649c475f767f50e402b#diff-2536f316f752f01f03689886c89e4ef1fd76f8cb50fdded4e8483efeacc0f4faL123

But we suggest that you could wait for moment, since we are fix a bug of crashing.
