### ISSUE TITLE
2pass模式多并发请求服务端崩溃

### ISSUE THREAD

**Issue by 1547481339** [alibaba-damo-academy/FunASR#817]
使用funasr_samples 中提供的java的demo  模拟多并发请求 服务端，跑一分钟左右后崩溃，崩溃时日志打印 Segmentation fault 
online模式跑时间长了以后崩溃，使用的docker镜像为 funasr-runtime-sdk-online-cpu-0.1.0
![image](https://github.com/alibaba-damo-academy/FunASR/assets/25165462/53b1d0b0-b8d8-49b3-a2fa-3b8f355f20a5)

**Comment by zhaomingwork** [comment]
@1547481339 请提供下测试文件和java命令，好复现

**Comment by 1547481339** [comment]
我用java客户端代码测试的，程序脚本比较长，钉钉私发给您吧，另外我分析了吐核文件，也一并发给您

**Comment by lyblsgo** [comment]
FunASR real-time speech recognition software package has been updated with bug fixes (including server crashes), which can be updated using the following methods:

If you are using the one-click deployment method: running the command will automatically update the image, sudo bash funasr-runtime-deploy-online-cpu-zh.sh install --workspace ./funasr-runtime-resources
Reference: https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/runtime/docs/SDK_tutorial_online_zh.md

If you are using manual deployment: pull the new image, sudo docker pull registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-online-cpu-0.1.1
Reference: https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/runtime/docs/SDK_advanced_guide_online_zh.md
