### ISSUE TITLE
服务端关闭ssl报错

### ISSUE THREAD

**Issue by liuchenustb** [alibaba-damo-academy/FunASR#818]
服务端启动命令：

./run_server_2pass.sh   --download-model-dir /workspace/models   --vad-dir damo/speech_fsmn_vad_zh-cn-16k-common-onnx   --model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-onnx    --online-model-dir damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx    --punc-dir damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727-onnx    --certfile ""    --keyfile ""

客户端测试命令：

python3 funasr_wss_client.py --host "127.0.0.1" --port 10095 --mode 2pass --audio_in "/root/audio_data/wav.scp" --ssl 0

服务端报错日志：

asr model init finished. listen on port:10095
I20230808 15:57:31.002465   507 websocket-server-2pass.cpp:25] on_tls_init called with hdl: 0x7ff8880110c0
I20230808 15:57:31.002636   507 websocket-server-2pass.cpp:26] using TLS mode: Mozilla Intermediate
[2023-08-08 15:57:30] [error] handle_transport_init received error: TLS handshake failed
[2023-08-08 15:57:30] [info] asio async_shutdown error: asio.ssl:336462231 (shutdown while in init (SSL routines, SSL_shutdown))

**Comment by lmxin123** [comment]
请问解决了吗，我也遇到这个问题
