### ISSUE TITLE
实时识别偶现崩溃问题

### ISSUE THREAD

**Issue by 1547481339** [alibaba-damo-academy/FunASR#819]
实时识别多并发服务端偶现崩溃情况，日志如下
![71e18b8d809e2176f14b0759db070dc](https://github.com/alibaba-damo-academy/FunASR/assets/25165462/bb6b4896-7666-4357-8242-06a95d5f00a9)

实时识别多并发跑一段时间（1个半小时左右）后挂了
![image](https://github.com/alibaba-damo-academy/FunASR/assets/25165462/3d779a56-8832-48a1-981d-9f7e8971093b)

测试方法：使用funasr_samples里java的demo，控制20并发同时请求服务端，偶现崩溃现象
docker镜像：funasr-runtime-sdk-online-cpu-0.1.0

**Comment by lyblsgo** [comment]
FunASR real-time speech recognition software package has been updated with bug fixes (including server crashes), which can be updated using the following methods:

If you are using the one-click deployment method: running the command will automatically update the image, sudo bash funasr-runtime-deploy-online-cpu-zh.sh install --workspace ./funasr-runtime-resources
Reference: https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/runtime/docs/SDK_tutorial_online_zh.md

If you are using manual deployment: pull the new image, sudo docker pull registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-online-cpu-0.1.1
Reference: https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/runtime/docs/SDK_advanced_guide_online_zh.md

**Comment by 1547481339** [comment]
decoder-thread-num=8，客户端15并发，稳定跑了超过24小时，未崩溃
