### ISSUE TITLE
paraformer加载finetune的模型，pipeline仍然跑的是原始官方模型

### ISSUE THREAD

**Issue by juzstu** [alibaba-damo-academy/FunASR#820]
OS: Ubuntu 20.04.4 LTS
Python Version：py 3.8.10
Package Version：pytorch==2.0.1, modelscope==1.6.1, funasr==0.4.8
Model：speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
Command：py脚本
问题描述：
加载finetune的模型，并替换model.bin，但pipeline却仍然在下载官方的模型，预测结果和官方模型一致
<img width="1350" alt="image" src="https://github.com/alibaba-damo-academy/FunASR/assets/19447572/007de115-55eb-4501-978a-9793176c4bb4">

**Comment by langgz** [comment]
Please update modelscope-1.8 and funasr-0.7.1.

```
pip install -U modelscope -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html -i https://mirror.sjtu.edu.cn/pypi/web/simple
git clone https://github.com/alibaba/FunASR.git && cd FunASR
pip install -e ./
```

**Comment by juzstu** [comment]
> Please update modelscope-1.8 and funasr-0.7.1.
> 
> ```
> pip install -U modelscope -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html -i https://mirror.sjtu.edu.cn/pypi/web/simple
> git clone https://github.com/alibaba/FunASR.git && cd FunASR
> pip install -e ./
> ```

升级了还是和之前一样，仍然在下载模型。
我的inference代码如下：
`base_path = '/data'
finetune_model = f'{base_path}/save_model/valid.acc.ave_10best.pb'
model = 'damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch'
ori_model = f'{base_path}/finetune_model'
pretrained_model_path = snapshot_download(model, cache_dir=ori_model, local_files_only=True)

shutil.copy(finetune_model, os.path.join(pretrained_model_path, 'model.pb'))
model = f'{ori_model}/{model}'

result_list = []
inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    model=model
)`

**Comment by langgz** [comment]
> > Please update modelscope-1.8 and funasr-0.7.1.
> > ```
> > pip install -U modelscope -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html -i https://mirror.sjtu.edu.cn/pypi/web/simple
> > git clone https://github.com/alibaba/FunASR.git && cd FunASR
> > pip install -e ./
> > ```
> 
> 升级了还是和之前一样，仍然在下载模型。 我的inference代码如下：
> 
> ```
> base_path = '/data'
> finetune_model = f'{base_path}/save_model/valid.acc.ave_10best.pb'
> model = 'damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch'
> ori_model = f'{base_path}/finetune_model'
> pretrained_model_path = snapshot_download(model, cache_dir=ori_model, local_files_only=True)
> 
> shutil.copy(finetune_model, os.path.join(pretrained_model_path, 'model.pb'))
> model = f'{ori_model}/{model}'
> 
> result_list = []
> inference_pipeline = pipeline(
>     task=Tasks.auto_speech_recognition,
>     model=model
> )
> ```

I have add the parameter `update_model=False`. Please update funasr to 0.7.2. https://github.com/alibaba-damo-academy/FunASR/commit/9ad47905531e1b212d278b99e5069e8448a12cdf

**Comment by juzstu** [comment]
> > > Please update modelscope-1.8 and funasr-0.7.1.
> > > ```
> > > pip install -U modelscope -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html -i https://mirror.sjtu.edu.cn/pypi/web/simple
> > > git clone https://github.com/alibaba/FunASR.git && cd FunASR
> > > pip install -e ./
> > > ```
> > 
> > 
> > 升级了还是和之前一样，仍然在下载模型。 我的inference代码如下：
> > ```
> > base_path = '/data'
> > finetune_model = f'{base_path}/save_model/valid.acc.ave_10best.pb'
> > model = 'damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch'
> > ori_model = f'{base_path}/finetune_model'
> > pretrained_model_path = snapshot_download(model, cache_dir=ori_model, local_files_only=True)
> > 
> > shutil.copy(finetune_model, os.path.join(pretrained_model_path, 'model.pb'))
> > model = f'{ori_model}/{model}'
> > 
> > result_list = []
> > inference_pipeline = pipeline(
> >     task=Tasks.auto_speech_recognition,
> >     model=model
> > )
> > ```
> 
> I have add the parameter `update_model=False`. Please update funasr to 0.7.2. [9ad4790](https://github.com/alibaba-damo-academy/FunASR/commit/9ad47905531e1b212d278b99e5069e8448a12cdf)

这个pipeline 是modelscope.pipelines里的，你说的`update_model=False是更新funasr到0.7.2，请问怎么在modelscope.pipelines里使用？

**Comment by langgz** [comment]
> inference_pipeline = pipeline(
>     task=Tasks.auto_speech_recognition,
>     model=model
> )

```
inference_pipeline = pipeline(
    task=Tasks.auto_speech_recognition,
    update_model=False,
    model=model
)
```
