### ISSUE TITLE
ffmpeg的下载地址有问题，目前代码中的版本可能已经被移除，需要换个版本

### ISSUE THREAD

**Issue by y00281951** [alibaba-damo-academy/FunASR#837]
https://github.com/alibaba-damo-academy/FunASR/blob/f5da7be222bac52b206e7fdd821075c713994e5d/funasr/runtime/onnxruntime/third_party/download_ffmpeg.sh#L1
7月9号的版本不存在了，需要换一个

**Comment by lyblsgo** [comment]
thanks, the problem is fixed

**Comment by Jack-Lin-gif** [comment]
> https://github.com/alibaba-damo-academy/FunASR/blob/f5da7be222bac52b206e7fdd821075c713994e5d/funasr/runtime/onnxruntime/third_party/download_ffmpeg.sh#L1 7月9号的版本不存在了，需要换一个

请问在哪里更改啊
