### ISSUE TITLE
识别的数字转换成阿拉伯数字

### ISSUE THREAD

**Issue by Huanyongji** [alibaba-damo-academy/FunASR#843]
请问识别的数字如何能转换成阿拉伯数字，比如一百九十二点一一五，输出192.115

谢谢

**Comment by langgz** [comment]
The feature of ITN is now in progress of testing, maybe you could test it on:
https://101.37.77.25:1333/static/index.html

**Comment by tianzuishiwo** [comment]
cn2an包可以解决问题

**Comment by wuhongsheng** [comment]
+1

**Comment by rookiesswang** [comment]
cn2an目前没法处理包含数字名词的情况，比如：会把张三转化为张3，零售价转化为0售价。还有别的更好的方案吗
