### ISSUE TITLE
请问热词版本模型支持lora方式微调吗

### ISSUE THREAD

**Issue by uloveqian2021** [alibaba-damo-academy/FunASR#844]
您好，我想利用lora方式微调 “speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404”，发现报错，“lora_list参数不支持

`if __name__ == '__main__':
    params = modelscope_args(model="/root/training/FunASR/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404", data_path="./data")
    params.output_dir = "./checkpoint_lora"              # 模型保存路径
    params.data_path = "/root/training/FunASR/data"            # 数据路径
    params.dataset_type = "small"                   # finetune contextual_paraformer模型只能使用large dataset
    params.batch_bins = 2000                      # batch size，如果dataset_type="small"，batch_bins单位为fbank特征帧数，如果dataset_type="large"，batch_bins单位为毫秒，
    params.max_epoch = 20                           # 最大训练轮数
    params.lr = 0.00005                              # 设置学习率

    init_param = []                                 # 初始模型路径，默认加载modelscope模型初始化，例如: ["checkpoint/20epoch.pb"]
    freeze_param = []                               # 模型参数freeze, 例如: ["encoder"]
    ignore_init_mismatch = True                     # 是否忽略模型参数初始化不匹配
    use_lora = False                                # 是否使用lora进行模型微调
    params.param_dict = {"init_param":init_param, "freeze_param": freeze_param, "ignore_init_mismatch": ignore_init_mismatch}
    if use_lora:
        enable_lora = True
        lora_bias = "all"
        lora_params = {"lora_list":['q','v'], "lora_rank":8, "lora_alpha":16, "lora_dropout":0.1}
        lora_config = {"enable_lora": enable_lora, "lora_bias": lora_bias, "lora_params": lora_params}
        params.param_dict.update(lora_config)

    modelscope_finetune(params)`

**Comment by hnluo** [comment]
Please provide complete error message and funasr version

**Comment by uloveqian2021** [comment]
> Please provide complete error message and funasr version

问题已经解决，在ContextualParaformerDecoder方法中添加“lora_list”参数即可:

`
class ContextualParaformerDecoder(ParaformerSANMDecoder):
    """
    Author: Speech Lab of DAMO Academy, Alibaba Group
    Paraformer: Fast and Accurate Parallel Transformer for Non-autoregressive End-to-End Speech Recognition
    https://arxiv.org/abs/2006.01713
    """
    def __init__(
        self,
        vocab_size: int,
        encoder_output_size: int,
        attention_heads: int = 4,
        linear_units: int = 2048,
        num_blocks: int = 6,
        dropout_rate: float = 0.1,
        positional_dropout_rate: float = 0.1,
        self_attention_dropout_rate: float = 0.0,
        src_attention_dropout_rate: float = 0.0,
        input_layer: str = "embed",
        use_output_layer: bool = True,
        pos_enc_class=PositionalEncoding,
        normalize_before: bool = True,
        concat_after: bool = False,
        att_layer_num: int = 6,
        kernel_size: int = 21,
        sanm_shfit: int = 0,
        **lora_list: List[str] = None,
        lora_rank: int = 8,
        lora_alpha: int = 16,
        lora_dropout: float = 0.1,**
    ):
`
且需更改所有“MultiHeadedAttentionCrossAtt”中的参数：
`
        MultiHeadedAttentionCrossAtt(
              # attention_heads, attention_dim, src_attention_dropout_rate
              attention_heads, attention_dim, src_attention_dropout_rate, lora_list, lora_rank, lora_alpha, lora_dropout
  ),
`

**Comment by hnluo** [comment]
Yes, MultiHeadedAttentionSANM and MultiHeadedAttentionCrossAtt class currently support lora fine-tuning, for other class you can refer to for adaptation.

**Comment by uloveqian2021** [comment]
> Yes, MultiHeadedAttentionSANM and MultiHeadedAttentionCrossAtt class currently support lora fine-tuning, for other class you can refer to for adaptation.

现在推理遇到问题，加载lora方式微调的模型后，会报错：
```
RuntimeError: AutomaticSpeechRecognitionPipeline: Error(s) in loading state_dict for ContextualParaformer:        Unexpected key(s) in state_dict: "encoder.encoders0.0.self_attn.linear_q_k_v.lora_A", "encoder.encoders0.0.self_attn.linear_q_k_v.lora_B", "encoder.encoders.0.self_attn.linear_q_k_v.lora_A", "encoder.encoders.0.self_attn.linear_q_k_v.lora_B", "encoder.encoders.1.self_attn.linear_q_k_v.lora_A", "encoder.encoders.1.self_attn.linear_q_k_v.lora_B", "encoder.encoders.2.self_attn.linear_q_k_v.lora_A", "encoder.encoders.2.self_attn.linear_q_k_v.lora_B", "encoder.encoders.3.self_attn.linear_q_k_v.lora_A", "encoder.encoders.3.self_attn.linear_q_k_v.lora_B", "encoder.encoders.4.self_attn.linear_q_k_v.lora_A", "encoder.encoders.4.self_attn.linear_q_k_v.lora_B", "encoder.encoders.5.self_attn.linear_q_k_v.lora_A", "encoder.encoders.5.self_attn.linear_q_k_v.lora_B", "encoder.encoders.6.self_attn.linear_q_k_v.lora_A", "encoder.encoders.6.self_attn.linear_q_k_v.lora_B", "encoder.encoders.7.self_attn.linear_q_k_v.lora_A", "encoder.encoders.7.self_attn.linear_q_k_v.lora_B", "encoder.encoders.8.self_attn.linear_q_k_v.lora_A", "encoder.encoders.8.self_attn.linear_q_k_v.lora_B", "encoder.encoders.9.self_attn.linear_q_k_v.lora_A", "encoder.encoders.9.self_attn.linear_q_k_v.lora_B", "encoder.encoders.10.self_attn.linear_q_k_v.lora_A", "encoder.encoders.10.self_attn.linear_q_k_v.lora_B", "encoder.encoders.11.self_attn.linear_q_k_v.lora_A", "encoder.encoders.11.self_attn.linear_q_k_v.lora_B", "encoder.encoders.12.self_attn.linear_q_k_v.lora_A", 
```
这个怎么处理呢，

**Comment by hnluo** [comment]
You can check config.yaml file, whether the lora parameter is in it.

**Comment by uloveqian2021** [comment]
> You can check config.yaml file, whether the lora parameter is in it.

大佬不太明白，是需要在config.yaml中指定相关参数吗
