### ISSUE TITLE
Java客户端连接失败  - Connection closed by remote peer Code: -1 Reason: 

### ISSUE THREAD

**Issue by HbeH** [alibaba-damo-academy/FunASR#845]
- Connection closed by remote peer Code: -1 Reason:  - Connection closed by remote peer Code: -1 Reason:

**Comment by aguozhihua** [comment]
这个java客户端问题连不上的解决了吗？

**Comment by HbeH** [comment]
> 这个java客户端问题连不上的解决了吗？

太久了，我都忘记怎么解决的了

**Comment by aguozhihua** [comment]
大佬回想一下看看？# 如果您想关闭ssl，增加参数：--certfile 0是加这个参数？

**Comment by aguozhihua** [comment]
我加了--certfile 0这个参数是可以提交请求了，但是没有响应识别的内容，看log里面是识别出来了，不知道怎么没有响应内容怎么就断开了。

root@854d7ed18a90:/workspace/FunASR/runtime/java# java   -cp build:lib/Java-WebSocket-1.5.3.jar:lib/slf4j-simple-1.7.25.jar:lib/slf4j-api-1.7.25.jar:lib/json-simple-1.1.1.jar:lib/argparse4j-0.9.0.jar   -Dfile.encoding=utf-8    websocket.FunasrWsClient --host localhost --port 10095 --audio_in ./test.mp3 --num_threads 1 --mode 2pass
10095
serIp=localhost,srvPort=10095,wavPath=./test.mp3,strChunkSize5, 10, 5
Thread1 is running...
chunk_size:60
CHUNK:960
stride:0
wsAddress:ws://localhost:10095
[Thread-3] INFO websocket.FunasrWsClient - sendJson: {"mode":"2pass","is_speaking":true,"chunk_size":[5,10,5],"wav_format":"mp3","chunk_interval":10,"wav_name":"javatest"}
[Thread-3] INFO websocket.FunasrWsClient - sendEof: {"is_speaking":false}
[WebSocketConnectReadThread-14] INFO websocket.FunasrWsClient - Connection closed by us Code: 1000 Reason:

**Comment by aguozhihua** [comment]
谢谢了 钉钉群号有吗麻烦发一下

**Comment by juzstu** [comment]
> 我加了--certfile 0这个参数是可以提交请求了，但是没有响应识别的内容，看log里面是识别出来了，不知道怎么没有响应内容怎么就断开了。
> 
> root@854d7ed18a90:/workspace/FunASR/runtime/java# java -cp build:lib/Java-WebSocket-1.5.3.jar:lib/slf4j-simple-1.7.25.jar:lib/slf4j-api-1.7.25.jar:lib/json-simple-1.1.1.jar:lib/argparse4j-0.9.0.jar -Dfile.encoding=utf-8 websocket.FunasrWsClient --host localhost --port 10095 --audio_in ./test.mp3 --num_threads 1 --mode 2pass 10095 serIp=localhost,srvPort=10095,wavPath=./test.mp3,strChunkSize5, 10, 5 Thread1 is running... chunk_size:60 CHUNK:960 stride:0 wsAddress:ws://localhost:10095 [Thread-3] INFO websocket.FunasrWsClient - sendJson: {"mode":"2pass","is_speaking":true,"chunk_size":[5,10,5],"wav_format":"mp3","chunk_interval":10,"wav_name":"javatest"} [Thread-3] INFO websocket.FunasrWsClient - sendEof: {"is_speaking":false} [WebSocketConnectReadThread-14] INFO websocket.FunasrWsClient - Connection closed by us Code: 1000 Reason:

我也遇到了这个问题，请问你解决了吗？
