### ISSUE TITLE
实时识别server端启动指定decoder-thread-num=8，实际占用cpu核数大于8

### ISSUE THREAD

**Issue by 1547481339** [alibaba-damo-academy/FunASR#848]
我在decoder-thread-num=8的情况下，逐步增加并发，刚开始增加并发时占用核数会逐步增加，当加到24并发时，占用核数增加到14核时，再增加并发，占用核数不会增加，超过30并发后，偶现崩溃
cpu占用情况：
![76dd98618735881ea622542ebc69efe8](https://github.com/alibaba-damo-academy/FunASR/assets/25165462/f415f629-e342-4eb7-9347-018ea7f18d49)
崩溃日志：
![4f06cd82d5b43b7898b5c30a55a58c14](https://github.com/alibaba-damo-academy/FunASR/assets/25165462/11158bbf-d7b8-41ca-9777-b0c824c05668)

我后来给了15并发，大概占9到11个核，decoder-thread-num指定的还是8，跑了超过24小时，稳定未崩溃
cpu占用情况：
![image](https://github.com/alibaba-damo-academy/FunASR/assets/25165462/3a907c1d-7060-47a4-8539-e82ef2cbc793)

**Comment by lyblsgo** [comment]
1、please update the docker image to the newest version funasr-runtime-sdk-online-cpu-0.1.1
2、onnxruntime runs in parallel (sessionOptions.SetIntraOpNumThreads(numThread), numThread is the number of threads used to parallelize the execution within nodes, default is 4 in FunASR SDK);
