### ISSUE TITLE
FunASR离线文件转写服务

### ISSUE THREAD

**Issue by Stonexiao** [alibaba-damo-academy/FunASR#852]
FunASR 离线文件转写服务部署，docker镜像启动部署（https://alibaba-damo-academy.github.io/FunASR/en/funasr/runtime/docs/SDK_advanced_guide_offline_zh.html）服务启动成长之后，使用demo调用，websocket无法连接成功，服务端报错，错误信息如下：

asr model init finished. listen on port:6650
I20230814 18:25:26.155937   239 websocket-server.cpp:25] on_tls_init called with hdl: 0x7fcaac010c30
I20230814 18:25:26.156011   239 websocket-server.cpp:26] using TLS mode: Mozilla Intermediate
[2023-08-14 18:25:26] [error] handle_transport_init received error: TLS handshake failed
[2023-08-14 18:25:26] [info] asio async_shutdown error: asio.ssl:336462231 (shutdown while in init (SSL routines, SSL_shutdown))

**Comment by Stonexiao** [comment]
docker 镜像启动的怎么关闭ssl证书验证？

**Comment by langgz** [comment]
@lyblsgo Please detail the docs about how to close ssl. Add the following config to `run_server.sh`
`--keyfile 0 --certfile 0`
