### ISSUE TITLE
转成onnx模型精度下降

### ISSUE THREAD

**Issue by Adagio112** [alibaba-damo-academy/FunASR#853]
下面是用自己的数据集对paraformer-large pytorch模型、onnx fp32模型、onnx int8量化模型的wer测试效果。
![图片](https://github.com/alibaba-damo-academy/FunASR/assets/66060016/df4e7ebc-78d4-477e-8c65-08be4a116970)

从图中可以看到，onnx模型的精度都有下降，尤其是data2数据集，量不量化的影响不大，但是由pb转成onnx之后，识别的效果变很差，请问是什么原因？该怎么解决呢？

**Comment by Adagio112** [comment]
是因为onnx推理的时候没有加vad检测，加了之后整体的识别效果与pb模型的效果差别很小。

**Comment by lhanzl** [comment]
@Adagio112 您好，最近我也关注到这个问题。你提到的vad是一个影响因素，你有对比过python pipeline（加vad）和websocket cpp（加vad，实际使用的）服务的WER吗？
