### ISSUE TITLE
paraformer微调有问题，valid的评估效果每个epoch都一样

### ISSUE THREAD

**Issue by juzstu** [alibaba-damo-academy/FunASR#862]
OS: Ubuntu 20.04.4 LTS
Python Version：py 3.8.10
Package Version：pytorch==2.0.1, modelscope==1.6.1, funasr==0.4.8
Model：speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
Command：py脚本
问题描述：
微调有问题，无论是自己的数据集还是aishell的，valid的评估一直是[valid] loss_att=0.008, pre_loss_att=nan, acc=1.000, cer=0.000e+00, wer=0.000e+00, loss_pre=1.907e-07, loss=0.008

部分日志如下
```
[ CUDAFloatType{1} ], loss: 0.4273
[ CUDAFloatType{1} ]}) of traced region cannot be understood by the tracer, only outputs matchingdict[Union[str, Tensor], Union[Tensor, Tuple[Tensor, ...]]] can be a dictionary output of a traced function
Error occurs, No graph saved
/usr/local/lib/python3.8/dist-packages/funasr/train/reporter.py:79: UserWarning: No valid stats found
warnings.warn("No valid stats found")
[speech-a5-master-0] 2023-08-16 17:38:19,309 (trainer:334) INFO: 1epoch results: [train] iter_time=6.271, forward_time=0.388, loss_att=0.572, acc=0.875, loss_pre=1.001e-05, loss=0.572, backward_time=0.194, optim_step_time=0.097, optim0_lr0=3.333e-09, train_time=10.827, time=10.9 seconds, total_count=1, gpu_max_cached_mem_GB=5.223, [valid] loss_att=0.008, pre_loss_att=nan, acc=1.000, cer=0.000e+00, wer=0.000e+00, loss_pre=1.907e-07, loss=0.008, time=1.81 seconds, total_count=1, gpu_max_cached_mem_GB=5.223
```

**Comment by hnluo** [comment]
Please update funasr, and try again.

**Comment by juzstu** [comment]
> Please update funasr, and try again.

I also try the modelscope==1.8.1, funasr==0.7.2, the result is same, the train loss is ok.

**Comment by hnluo** [comment]
![image](https://github.com/alibaba-damo-academy/FunASR/assets/42902471/3bc651e6-ddd2-4151-a6bb-a96f455915d4)
This is the training log of aishell-1 dataset, it is ok.

**Comment by juzstu** [comment]
> ![image](https://user-images.githubusercontent.com/42902471/260981938-3bc651e6-ddd2-4151-a6bb-a96f455915d4.png) This is the training log of aishell-1 dataset, it is ok.

I sample 1000 records from the aishell-1 dataset, 200 for valid, but acc=1，cer=0, wer=0. Is the format of train and validation is right?
<img width="832" alt="image" src="https://github.com/alibaba-damo-academy/FunASR/assets/19447572/e5239daa-fda8-48ef-b376-accfe56ba549">

**Comment by hnluo** [comment]
Paraformer-large model is well performerce on aishell-1 test, so 1000 samples are to small for evaluating model performance.

**Comment by juzstu** [comment]
> Paraformer-large model is well performerce on aishell-1 test, so 1000 samples are to small for evaluating model performance.

but in my custom dataset, the valid is same as the aishell-1, acc=1，cer=0, wer=0.

**Comment by juzstu** [comment]
> Paraformer-large model is well performerce on aishell-1 test, so 1000 samples are to small for evaluating model performance.

but in my custom dataset, the valid is same as the aishell-1, acc=1，cer=0, wer=0.

**Comment by hnluo** [comment]
You can try to update the funasr version, the current version is 0.7.4.

**Comment by juzstu** [comment]
> You can try to update the funasr version, the current version is 0.7.4.

use funasr==0.7.4, modelscope==1.8.3, I got this error below:
```
RuntimeError: ASRTrainer: 0 lines found: /aishell/train/speech_shape
```
<img width="421" alt="image" src="https://github.com/alibaba-damo-academy/FunASR/assets/19447572/f37115ab-29c2-474c-adc9-ee1581e1f4b7">

**Comment by hnluo** [comment]
![image](https://github.com/alibaba-damo-academy/FunASR/assets/42902471/0df10a84-d59f-4fd8-8d75-2645ab14826d)

Please check you data format. [finetune-with-your-data](https://alibaba-damo-academy.github.io/FunASR/en/egs_modelscope/asr/TEMPLATE/README.html#finetune-with-your-data)
