### ISSUE TITLE
没有找到CT-Transformer标点-中文-通用-pytorch的训练脚本

### ISSUE THREAD

**Issue by SmileGoat** [alibaba-damo-academy/FunASR#864]
在代码中找到了 TargetDelayTransformer 和 VadRealtimeTransformer
from funasr.models.target_delay_transformer import TargetDelayTransformer
from funasr.models.vad_realtime_transformer import VadRealtimeTransformer
麻烦请问一下，魔塔demo中的标点模型训练脚本有开源计划吗？
与已开源的TargetDelayTransformer 和 VadRealtimeTransformer，性能差别是怎样的？

**Comment by langgz** [comment]
Please ref to [issue](https://github.com/alibaba-damo-academy/FunASR/issues/893)
