### ISSUE TITLE
关于FunASR实时语音听写服务开发指南的问题

### ISSUE THREAD

**Issue by wwfcnu** [alibaba-damo-academy/FunASR#883]
FunASR实时语音听写服务开发指南中
启动 funasr-wss-server-2pass服务程序：
```
--download-model-dir 模型下载地址，通过设置model ID从Modelscope下载模型
--model-dir  modelscope model ID
--online-model-dir  modelscope model ID
--quantize  True为量化ASR模型，False为非量化ASR模型，默认是True
--vad-dir  modelscope model ID
--vad-quant   True为量化VAD模型，False为非量化VAD模型，默认是True
--punc-dir  modelscope model ID
--punc-quant   True为量化PUNC模型，False为非量化PUNC模型，默认是True
--port  服务端监听的端口号，默认为 10095
--decoder-thread-num  服务端启动的推理线程数，默认为 8
--io-thread-num  服务端启动的IO线程数，默认为 1
--certfile  ssl的证书文件，默认为：../../../ssl_key/server.crt，如需关闭，设置为""
--keyfile   ssl的密钥文件，默认为：../../../ssl_key/server.key，如需关闭，设置为""
```
这些参数中，--model-dir  modelscope model ID --online-model-dir  modelscope model ID这两个参数有什么区别，另外如果我不需要vad和punc，不指定相关参数就可以吗

**Comment by MyWestCity** [comment]
因为这个是2pass模式，所以针对每一句话，接收到每一小段推理就是用的online-model-dir实时模型，这句话结束时针对这一整句话又会用model-dir离线模型推理一遍，相当于一次更正校准。
punc不要还行，vad不要的话，用这个估计跑不出结果，如果你是有另外的VAD模型，那你就得改他的代码

**Comment by lyblsgo** [comment]
> FunASR实时语音听写服务开发指南中 启动 funasr-wss-server-2pass服务程序：
> 
> ```
> --download-model-dir 模型下载地址，通过设置model ID从Modelscope下载模型
> --model-dir  modelscope model ID
> --online-model-dir  modelscope model ID
> --quantize  True为量化ASR模型，False为非量化ASR模型，默认是True
> --vad-dir  modelscope model ID
> --vad-quant   True为量化VAD模型，False为非量化VAD模型，默认是True
> --punc-dir  modelscope model ID
> --punc-quant   True为量化PUNC模型，False为非量化PUNC模型，默认是True
> --port  服务端监听的端口号，默认为 10095
> --decoder-thread-num  服务端启动的推理线程数，默认为 8
> --io-thread-num  服务端启动的IO线程数，默认为 1
> --certfile  ssl的证书文件，默认为：../../../ssl_key/server.crt，如需关闭，设置为""
> --keyfile   ssl的密钥文件，默认为：../../../ssl_key/server.key，如需关闭，设置为""
> ```
> 
> 这些参数中，--model-dir modelscope model ID --online-model-dir modelscope model ID这两个参数有什么区别，另外如果我不需要vad和punc，不指定相关参数就可以吗
--online-model-dir is the real-time model used for real-time transcription, while --model-dir is the offline model used for result correction.
Currently, disabling the vad and punc models is not supported, and the default values will be used if the related parameters are not specified.
If you have customized requirements, you can modify the code as the source code is open sourced.

**Comment by lyblsgo** [comment]
> FunASR实时语音听写服务开发指南中 启动 funasr-wss-server-2pass服务程序：
> 
> ```
> --download-model-dir 模型下载地址，通过设置model ID从Modelscope下载模型
> --model-dir  modelscope model ID
> --online-model-dir  modelscope model ID
> --quantize  True为量化ASR模型，False为非量化ASR模型，默认是True
> --vad-dir  modelscope model ID
> --vad-quant   True为量化VAD模型，False为非量化VAD模型，默认是True
> --punc-dir  modelscope model ID
> --punc-quant   True为量化PUNC模型，False为非量化PUNC模型，默认是True
> --port  服务端监听的端口号，默认为 10095
> --decoder-thread-num  服务端启动的推理线程数，默认为 8
> --io-thread-num  服务端启动的IO线程数，默认为 1
> --certfile  ssl的证书文件，默认为：../../../ssl_key/server.crt，如需关闭，设置为""
> --keyfile   ssl的密钥文件，默认为：../../../ssl_key/server.key，如需关闭，设置为""
> ```
> 
> 这些参数中，--model-dir modelscope model ID --online-model-dir modelscope model ID这两个参数有什么区别，另外如果我不需要vad和punc，不指定相关参数就可以吗

--online-model-dir is the real-time model used for real-time transcription, while --model-dir is the offline model used for result correction.
Currently, disabling the vad and punc models is not supported, and the default values will be used if the related parameters are not specified.
If you have customized requirements, you can modify the code as the source code is open sourced.

**Comment by yaleimeng** [comment]
@MyWestCity   既然一句话结束时整句使用离线模型推理了一遍，相当于更正校准。那么最终输出直接是离线模型推理的结果吗？流式推理的中间结果是否丢弃了？

**Comment by MyWestCity** [comment]
> @MyWestCity 既然一句话结束时整句使用离线模型推理了一遍，相当于更正校准。那么最终输出直接是离线模型推理的结果吗？流式推理的中间结果是否丢弃了？

不能说丢弃，实时语音那肯定是需要实时率的，不能每次都等一句话说完才返回结果，那用户体验就很差了，所以中间是需要有输出，哪怕准确率相比离线转写低一点

**Comment by lmxin123** [comment]
这里说的实时，我理解的是边说话边返回识别结果，这才叫实时吧。
但是提个html界面上的功能，都是录完整段话之后再返回识别结果，这样跟离线就遇什么区别了。
![image](https://github.com/alibaba-damo-academy/FunASR/assets/12029452/40627d3c-9bdb-49ea-af50-20a098f8025b)
另外不太理解这里的2pass跟online的区别是什么
