### ISSUE TITLE
CT_transformer 是否支持文本顺滑?

### ISSUE THREAD

**Issue by Cescfangs** [alibaba-damo-academy/FunASR#885]
https://github.com/alibaba-damo-academy/FunASR/blob/f70f70711045fc191a4ce9498c155d61e969b57f/funasr/runtime/python/onnxruntime/funasr_onnx/punc_bin.py#L17-L22

看到CT_Transformer 注释写的是支持标点预测和文本顺滑功能的，但是代码只实现了标点预测的功能

**Comment by langgz** [comment]
Sorry, it does not support yet.
