### ISSUE TITLE
部署funasr实时听写服务

### ISSUE THREAD

**Issue by wwfcnu** [alibaba-damo-academy/FunASR#889]
尊敬的作者，你好：
我想问的是，在部署这个服务之后，做推理的时候，可以输出rtf吗？
另外我注意到，实时听写docker部署的时候
`python funasr_wss_client.py  -mode [offline,online,2pass]`
-mode这里的offline和离线文件撰写的offline有什么不同

**Comment by lyblsgo** [comment]
1、RTF output is currently not supported, but you can modify the source code if you have customization requirements. The code is open source.

2、The ASR model remains the same with File transcription, while the VAD (Voice Activity Detection) and Punctuation models are stream-based models.  The red part in the image represents the offline mode.
![image](https://github.com/alibaba-damo-academy/FunASR/assets/9068933/6e9524f4-ba22-4e3d-98ab-b80b50b738c7)
