### ISSUE TITLE
More effcient gpu solution?

### ISSUE THREAD

**Issue by locasxe** [alibaba-damo-academy/FunASR#899]
I have tested the paraformer-cpp-onnx with gpu 3090, however, inference speed is nothing better than cpu, and even much slower when infered with model_quant.onnx. I dont know the reason( quant model can be worse on gpu? gpu has no advantage over cpu?). 
So, I wonder is there any idea to improve the speed? 
Or other better solution to use paraformer on gpu？
Thx very much

**Comment by langgz** [comment]
Onnruntime is not suitable for gpu inference. We are working on developing the gpu runtime. If you are interest in it, maybe we could develop together.
