### ISSUE TITLE
微调英文数据，loss不降低，训练集的acc一直维持在很低的状态

### ISSUE THREAD

**Issue by I-am-little-curly-hair** [alibaba-damo-academy/FunASR#903]
我试验了以下两个模型：

speech_paraformer_asr-en-16k-vocab4199-pytorch
speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch

分别用他们微调了speech_asr_commonvoice_en_trainsets，loss不降低，训练集的acc一直维持在很低的状态

为了排除超参数设置的问题，我从speech_asr_commonvoice_en_trainsets中随便抽出了一条音频，再用这俩模型分别跑了50个epoch，loss还是不降低，训练集的acc还是维持在不到0.1的状态

为了排除代码或者自建数据集格式的问题，我照葫芦画瓢找了一条中文音频，又分别用这俩模型跑了下，基本上第3个epoch训练集的acc就达到1.0了

现在可以确定的是，它们对英文数据微调的支持是存在问题的，请问我该怎么修改？

**Comment by hnluo** [comment]
Please check your english training data, whether english word is splited by space。

**Comment by hnluo** [comment]
You can use speech_paraformer_asr-en-16k-vocab4199-pytorch model to infer training subsets, check whether training data is correct.

**Comment by I-am-little-curly-hair** [comment]
> You can use speech_paraformer_asr-en-16k-vocab4199-pytorch model to infer training subsets, check whether training data is correct.

![image](https://github.com/alibaba-damo-academy/FunASR/assets/34257532/7a40fc1d-8df2-4dfb-ba1f-ae70c422f6e4)
![image](https://github.com/alibaba-damo-academy/FunASR/assets/34257532/ee254e3f-9906-4e17-96d6-6bceb60c02ae)
![image](https://github.com/alibaba-damo-academy/FunASR/assets/34257532/8100918a-4127-4270-ba3b-e825e87519fe)

上面是我的wav.scp、text、以及音频文件，可以看到，我的训练集就有一条数据，而且我听了下这个wav，它的音频内容和文本是能对上的

![image](https://github.com/alibaba-damo-academy/FunASR/assets/34257532/64a6f05b-74a5-41ff-bfdd-5f9a59a72d92)
<img width="490" alt="微信截图_20230901094249" src="https://github.com/alibaba-damo-academy/FunASR/assets/34257532/1676125e-a5bf-4cff-b7d4-9f8281c1d4ed">

上面是我的测试代码、以及测试结果，我用"speech_paraformer_asr-en-16k-vocab4199-pytorch"这个模型试了下，发现效果还不错，只错了一个单词

![image](https://github.com/alibaba-damo-academy/FunASR/assets/34257532/7afd311e-1edf-4c7c-aa31-a76f39e66390)

上面是我的微调代码，完全照抄的，我用这套代码调中文数据集就没有任何问题

![image](https://github.com/alibaba-damo-academy/FunASR/assets/34257532/3a29dcd4-0e33-4433-b086-4b7e698c613d)

上面是我的微调中间过程，可以看到，acc、wer指标低的吓人
同时我想问下，那个acc指标是啥意思？还有，英文不是应该计算wer吗？为啥还会计算cer指标？
