### ISSUE TITLE
粤语ASR

### ISSUE THREAD

**Issue by wy192** [alibaba-damo-academy/FunASR#905]
目前看粤语的pipline里面不支持VAD+ASR+标点的pipline，不知道能否支持，或者短音频支持返回字级别时间戳

**Comment by hnluo** [comment]
You can combine VAD+ASR+PUNC model by pipeline，refer to https://github.com/alibaba-damo-academy/FunASR/discussions/278

**Comment by wy192** [comment]
粤语短音频不支持返回每个字的时间戳，断句之后我们无法还原断句之后每个句子的开始时间
