### ISSUE TITLE
不在token.txt里的热词字符报错

### ISSUE THREAD

**Issue by hzfei** [alibaba-damo-academy/FunASR#906]
funasr_onnx==0.2.1
https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/runtime/python/onnxruntime/funasr_onnx/paraformer_bin.py
请求的时候，设置热词:["N","仏"]会报错。

![企业微信截图_16934469628449](https://github.com/alibaba-damo-academy/FunASR/assets/42926130/f214684e-7dde-4a42-a34c-5bec1d671da6)

**Comment by R1ckShi** [comment]
fixed, please pull the latest FunASR https://github.com/alibaba-damo-academy/FunASR/pull/939
