### ISSUE TITLE
funasr-0.7.5 export online model error

### ISSUE THREAD

**Issue by duj12** [alibaba-damo-academy/FunASR#912]
after update funasr from 0.7.4 to 0.7.5, I find the online model `damo/speech_paraformer_asr_nat-zh-cn-16k-common-vocab8404-online` export with error.

this is the command I used:

`python -m funasr.export.export_model --model-name damo/speech_paraformer_asr_nat-zh-cn-16k-common-vocab8404-online --export-dir ./export --type onnx --quantize false`

the log is like:
![7f2937411d3112e7ff081eb58a007a85](https://github.com/alibaba-damo-academy/FunASR/assets/37294470/9c2e488a-db1c-4f51-944a-12993ea3f7c4)

When I reinstall funasr==0.7.4, the online model can be export successfully.

**Comment by hnluo** [comment]
Please update your funasr, this bug has been fixed three day ago [fix onnx export bug #901](https://github.com/alibaba-damo-academy/FunASR/pull/901)
`git clone https://github.com/alibaba/FunASR.git && cd FunASR pip install -e ./`

**Comment by duj12** [comment]
> Please update your funasr, this bug has been fixed three day ago [fix onnx export bug #901](https://github.com/alibaba-damo-academy/FunASR/pull/901) `git clone https://github.com/alibaba/FunASR.git && cd FunASR pip install -e ./`

OK, so the reason of error in my case is because the #901 update is not released in pip yet.
I will install funasr with the latest source code. Thanks.
