### ISSUE TITLE
OOM using the training flow of aishell/paraformer

### ISSUE THREAD

**Issue by JayC319** [alibaba-damo-academy/FunASR#913]
I am new to ASR and whole machine learning training flow, I am currently training AISHELL on paraformer architecture, I am at stage 4, but I found it hard to trace down the code, where can I modify my batch size to solve this problem or is there anything I can do?  I can't even see 1 epoch pass by, is there a minimum requirement of hardware to train?

**Comment by JayC319** [comment]
Just few minutes before your reply, I changed it from the yaml file, and also switch GPU num to 1, and it seems to be training.
Is there any suggestion of how to referencing the model on the paper to code. Since the structure is stacked with layers. Thanks a lot.

**Comment by langgz** [comment]
ref to [docs](https://alibaba-damo-academy.github.io/FunASR/en/reference/papers.html)

**Comment by JayC319** [comment]
thanks a lot, appreciate all your works
