### ISSUE TITLE
large-contextual(hotword model) export onnx quantized model meets segmentation fault after the server is connected for a while.

### ISSUE THREAD

**Issue by duj12** [alibaba-damo-academy/FunASR#915]
I use the latest code #901 to export the contextual model, when using non-quantized onnx model, the server run normally.

But when I use quantized onnx model, the server happen to meet segmentation fault（often happen after connected for a while）, which is weird. 

I know that the quantized onnx hotword model export is still in progress, you can check this issue at the same time when you improve the accuracy of the quantized model.

**Comment by R1ckShi** [comment]
code updated in contextual paraformer model's export, we exclude quantize for ops in bias encoder and bias decoder for better performance, you can try it be pulling the latest code 
https://github.com/alibaba-damo-academy/FunASR/pull/939
but i think the segmentation fault in server maybe not related with the model itself
