### ISSUE TITLE
html5 server can not be connected after a long-time connection.

### ISSUE THREAD

**Issue by duj12** [alibaba-damo-academy/FunASR#916]
Firstly, I start the 2pass onnx cpp server, then start a html server.
In the web explorer, after a long-time connection(Press Connect -> Press Start, the server run normally, about server minutes), I press "Stop" button, then the ASR server can't be reached any more. 

I checked the html5 server, it's still running, and the ASR-2pass-wss-server is also running, So I don't know what happened.

All I can do is to kill the html5 service, and then restart. To my supprise, the server take a while to be restart（much longer than I first start it）. 
After restart，the ASR server can be reached again. 

I suppose the official h5 service
```
离线文件转写(热词模型)：https://101.37.77.25:1335/static/index.html

离线文件转写(时间戳模型)：https://101.37.77.25:1334/static/index.html

实时听写：https://101.37.77.25:1336/static/index.html
```
 may also meet the same issue? 
I don't know this is a bug of html5 server or not. May someone check it?

**Comment by langgz** [comment]
Maybe you cloud update funasr and try it again. @zhaomingwork has fix a version https://github.com/alibaba-damo-academy/FunASR/pull/898
