### ISSUE TITLE
数字识别，日期和时间中间有粘连

### ISSUE THREAD

**Issue by wu-xiaohua** [alibaba-damo-academy/FunASR#918]
(https://101.37.77.25:1333/static/index.html)测试数字识别，输入：将于九月四号两点三十举行会议，识别结果为：将于09/042:30举行会议

**Comment by duj12** [comment]
现在的想法是，按照规则匹配到不同的单位，将一个数字和单位作为一段，不同的段之间，考虑加个空格或者逗号，但是这会导致有些段内部不应该被隔开的位置也可能被隔开。
这个例子09/042:30，还有一个四千四千五->40004500，目前还在想办法解决。

**Comment by langgz** [comment]
The demo service has been updated. Please try it again.
https://101.37.77.25:1333/static/index.html

![image](https://github.com/alibaba-damo-academy/FunASR/assets/18321252/f9929d14-314a-4f35-9104-03ac4216b308)

**Comment by wu-xiaohua** [comment]
完美👍
