### ISSUE TITLE
paraformer-large模型token

### ISSUE THREAD

**Issue by kli017** [alibaba-damo-academy/FunASR#929]
请教一下关于paraformer-large-8404模型tokens中的英文是按照什么规则生成的？看着不太像char, 是bpe吗？egs脚本text2token中只有char跟phn呢。如果处理自己语料微调的话是直接按char进行token区分吗，有没有中英混合语料的例子呢？感谢

**Comment by hnluo** [comment]
Refer to [finetune-with-your-data](https://alibaba-damo-academy.github.io/FunASR/en/egs_modelscope/asr/TEMPLATE/README.html#finetune-with-your-data)
