### ISSUE TITLE
funasr-speech-separation is not in the pipelines registry group speech-separation

### ISSUE THREAD

**Issue by juzstu** [alibaba-damo-academy/FunASR#938]
OS: Ubuntu 20.04.4 LTS
Python Version：py 3.8.10
Package Version：pytorch==2.0.1, modelscope==1.8.4, funasr==0.7.6
Model：speech_separation_mossformer_8k_pytorch
Command：py脚本
问题描述：
code:
```
separation = pipeline(
   Tasks.speech_separation,
   model='damo/speech_separation_mossformer_8k_pytorch',
   output_dir='./',
   model_revision='v1.0.2')
```
KeyError: 'funasr-speech-separation is not in the pipelines registry group speech-separation. Please make sure the correct version of ModelScope library is used.

**Comment by hnluo** [comment]
Please update modelscope package
