### ISSUE TITLE
Memory leak in funasr-runtime-sdk-cpu-0.2.1 ?

### ISSUE THREAD

**Issue by lhanzl** [alibaba-damo-academy/FunASR#943]
Thank you for contributing excellent code.
I encountered a problem when using both online and offline SDKs

Docker Version: registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-cpu-0.2.1
SDK: ./funasr-wss-server & ./funasr-wss-server-2pass
Command：python3 funasr_wss_client.py --host "127.0.0.1" --port 10095 --mode offline --audio_in $audio,
                     python3 funasr_wss_client.py --host "127.0.0.1" --port 10096 --mode 2pass --audio_in $audio

Problem: Every time an audio is recognized, the memory will increase a bit

Looking forward to your reply.

**Comment by lyblsgo** [comment]
Try the newest version. If the issue persists, please reopen the issue and provide detailed steps to reproduce, as well as server and client logs.
