### ISSUE TITLE
onnxruntim编译错误

### ISSUE THREAD

**Issue by kli017** [alibaba-damo-academy/FunASR#944]
env：
ubuntu18.04
g++ 7.5.0
gcc 7.5.0
get error while using cmd: cmake --build .
onnxruntime/src/precomp.h:25:10: fatal error: onnxruntime_run_options_config_keys.h: No such file or directory

**Comment by JVfisher** [comment]
我也遇到这个问题了，请问是如何解决的？
![Uploading 9212AFAE-D3E9-4360-BDD9-DF62E2867479.png…]()

**Comment by nolanwang-uk** [comment]
(Wrote by 16/04/2024)
Try swap to funasr: release v0.3.0, onnxruntime: release v1.14.0, ffmpeg-shared: release 28/02/2023
Solved for me at least so far

**Comment by BruceLee569** [comment]
找到原因了，cmake的参数没指定路径，直接复制文档里的了 🤣
cmake  -DCMAKE_BUILD_TYPE=release .. -DONNXRUNTIME_DIR=/path/to/onnxruntime-linux-x64-1.14.0 -DFFMPEG_DIR=/path/to/ffmpeg-master-latest-linux64-gpl-shared
