### ISSUE TITLE
TN 错误

### ISSUE THREAD

**Issue by lifeiteng** [alibaba-damo-academy/FunASR#962]
中文

输入 `拨打 0551-4376729 购买彩票.`
当前输出 `拨打 零五五一年四十三月七六七二九 购买彩票.`
目标输出 `拨打 零五五幺 四三七六七二九 购买彩票.`

**Comment by lyblsgo** [comment]
@duj12 Please take a look when you have a moment.

**Comment by duj12** [comment]
> 中文
> 
> 输入 `拨打 0551-4376729 购买彩票.` 当前输出 `拨打 零五五一年四十三月七六七二九 购买彩票.` 目标输出 `拨打 零五五幺 四三七六七二九 购买彩票.`

你用的是fun_text_processing里面的TN功能吗？

**Comment by lyblsgo** [comment]
If the issue persists, please reopen the issue and provide detailed steps to reproduce, as well as server and client logs.
