### ISSUE TITLE
Logging message wouldn't change

### ISSUE THREAD

**Issue by JayC319** [alibaba-damo-academy/FunASR#965]
I was trying to see the model strcuture through logging, but no matter how I add logging in build_asr_model.py, the message won't show, even if I modify the line 277 `logging.info(f"Vocabulary size: {vocab_size}")` in to  `logging.info(f"VVVVocabulary size: {vocab_size}")`, the message is still Vocabulary size: {vocab_size}, But I am pretty sure that this code is invoked. How can I use the advantage of logging to trace the code?

**Comment by LauraGPT** [comment]
I think you have intsalled funasr by `pip install`. If you want to run funasr by source code, you should install funasr again by `pip install -e ./`. [doc](https://alibaba-damo-academy.github.io/FunASR/en/installation/installation.html#or-install-from-source-code)

**Comment by JayC319** [comment]
Sorry for the dumb questions, I can change some partial logging message such as directly from train.py in funasr/bin.
However not build_asr_model.py in funasr/build_utils, is it still the sameproblem?
