### ISSUE TITLE
使用paraformer在iOS上的runtime例子报错?

### ISSUE THREAD

**Issue by iclovemiku** [alibaba-damo-academy/FunASR#968]
OS: Mac

Python/C++ Version：python 3.9.17

Xcode version:14.3.1
pod version:1.12.1

Details：
/Users/haoxu/Downloads/FunASR/funasr/runtime/onnxruntime/include/funasrruntime.h:104:50 'CompileHotwordEmbedding' has C-linkage specified, but returns incomplete type 'const std::vector<std::vector<float>>' which could be incompatible with C

/Users/haoxu/Downloads/FunASR/funasr/runtime/onnxruntime/include/model.h:20:92 Non-void function does not return a value

**Comment by lyblsgo** [comment]
pull the latest code

**Comment by iclovemiku** [comment]
OK, I'll try.

**Comment by iclovemiku** [comment]
成功了,谢谢啊,非常感谢🙏
