### ISSUE TITLE
在启动C++版本的funasr-wss-server-2pass是，如何去掉加载vad和punc模型？

### ISSUE THREAD

**Issue by lukeewin** [alibaba-damo-academy/FunASR#972]
环境：funasr-sdk-online-cpu-0.1.2
你好，我想去掉服务端的vad和punc功能，这边通过去掉参数的方式，但是看日志还是加载了这两个模型，请问应该如何去掉vad和punc功能，是必须要修改源代码然后编译吗？有更简单的方式吗？
下面是我的修改方式：我把vad和punc参数去掉了。

download_model_dir="/workspace/models"
model_dir="damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404-onnx"
online_model_dir="damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx"
itn_dir="thuduj12/fst_itn_zh"
decoder_thread_num=32
io_thread_num=8
port=10095
certfile="../../../ssl_key/server.crt"
keyfile="../../../ssl_key/server.key"

. ../../egs/aishell/transformer/utils/parse_options.sh || exit 1;

cd /workspace/FunASR/funasr/runtime/websocket/build/bin
if [ -z "$certfile" ] || [ "$certfile" -eq 0 ]; then
./funasr-wss-server-2pass  \
  --download-model-dir ${download_model_dir} \
  --model-dir ${model_dir} \
  --online-model-dir ${online_model_dir} \
  --itn-dir ${itn_dir} \
  --decoder-thread-num ${decoder_thread_num} \
  --io-thread-num  ${io_thread_num} \
  --port ${port} \
  --certfile  "" \
  --keyfile ""
else
./funasr-wss-server-2pass  \
  --download-model-dir ${download_model_dir} \
  --model-dir ${model_dir} \
  --online-model-dir ${online_model_dir} \
  --itn-dir ${itn_dir} \
  --decoder-thread-num ${decoder_thread_num} \
  --io-thread-num  ${io_thread_num} \
  --port ${port} \
  --certfile  ${certfile} \
  --keyfile ${keyfile}
fi

**Comment by lyblsgo** [comment]
The code is open source. Please modify the source code for customization requirements
