### ISSUE TITLE
C++版实时转写异常退出

### ISSUE THREAD

**Issue by MyWestCity** [alibaba-damo-academy/FunASR#980]
OS: Linux
最新的镜像 registry.cn-hangzhou.aliyuncs.com/funasr_repo/funasr:funasr-runtime-sdk-online-cpu-0.1.2

模型：
download_model_dir="/workspace/models"
model_dir="damo/speech_paraformer-large-contextual_asr_nat-zh-cn-16k-common-vocab8404-onnx"
online_model_dir="damo/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online-onnx"
vad_dir="damo/speech_fsmn_vad_zh-cn-16k-common-onnx"
itn_dir="thuduj12/fst_itn_zh"
decoder_thread_num=32
io_thread_num=8
port=10031
certfile=0 # "../../../ssl_key/server.crt"
keyfile=0 # "../../../ssl_key/server.key"
punc_dir="damo/punc_ct-transformer_zh-cn-common-vad_realtime-vocab272727-onnx"

前端连接服务导致报错：
terminate called after throwing an instance of 'nlohmann::json_abi_v3_11_2::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: 'P'
./run_server_2pass.sh: line 47:     9 Aborted                 (core dumped) ./funasr-wss-server-2pass --download-model-dir ${download_model_dir} --model-dir ${model_dir} --online-model-dir ${online_model_dir} --vad-dir ${vad_dir} --punc-dir ${punc_dir} --itn-dir ${itn_dir} --decoder-thread-num ${decoder_thread_num} --io-thread-num ${io_thread_num} --port ${port} --certfile "" --keyfile ""

**Comment by LauraGPT** [comment]
Please provide detailed steps to reproduce the problem, which will help us troubleshoot the issue.

**Comment by lyblsgo** [comment]
Try the newest version. If the issue persists, please reopen the issue and provide detailed steps to reproduce, as well as server and client logs.
