### ISSUE TITLE
Paraformer语音识别 如何加入说话人识别模型

### ISSUE THREAD

**Issue by chiliuliu** [alibaba-damo-academy/FunASR#988]

**Comment by tramphero** [comment]
Please refer to this egs: https://github.com/alibaba-damo-academy/FunASR/tree/main/egs/alimeeting/modular_sa_asr

**Comment by LauraGPT** [comment]
Please ref to the [model](https://github.com/alibaba-damo-academy/FunASR/tree/main/egs_modelscope/asr_vad_spk/speech_paraformer-large-vad-punc-spk_asr_nat-zh-cn)

**Comment by chiliuliu** [comment]
> Please refer to this egs: https://github.com/alibaba-damo-academy/FunASR/tree/main/egs/alimeeting/modular_sa_asr

hello, I have tried this model. However, there is no any attribute of the result showing the information of speakers. And the structure of the output from the pipeline _output_dir=output_dir_ is not the same as the one shown on your website.

你好，我尝试了这个模型，但是发现返回的结果没有显示任何说话人信息。并且输出的信息和模型官网上提供的不一致。

**Comment by chiliuliu** [comment]
> Please ref to the [model](https://github.com/alibaba-damo-academy/FunASR/tree/main/egs_modelscope/asr_vad_spk/speech_paraformer-large-vad-punc-spk_asr_nat-zh-cn)

hello, I have tried this model. However, there is no any attribute of the result showing the information of speakers. And the structure of the output from the pipeline output_dir=output_dir is not the same as the one shown on your website.

你好，我尝试了这个模型，但是发现返回的结果没有显示任何说话人信息。并且输出的信息和模型官网上提供的不一致。
