### ISSUE TITLE
paraformer finetune error

### ISSUE THREAD

**Issue by wusong1128** [alibaba-damo-academy/FunASR#989]
OS:  
linux

Python Version：
python 3.8.10

Package Version：pytorch、torchaudio、modelscope、funasr version（pip list）
torch2.0.1 torchaudio2.0.2 modelscope1.9.1 funasr0.7.8

Model：
speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online

Command：
python finetune.py

Details：
dataset_type = "large"

Error log：
Train正常，validate出现UnicodeDecodeError。
 
![finetune_bug](https://github.com/alibaba-damo-academy/FunASR/assets/63332221/f0001f6e-e8cb-4f61-8449-493b38a40747)

**Comment by hnluo** [comment]
Please update funasr, bug has been fixed [#1001](https://github.com/alibaba-damo-academy/FunASR/pull/1001/)
