### ISSUE TITLE
不同词典大小的微调

### ISSUE THREAD

**Issue by ruby11dog** [alibaba-damo-academy/FunASR#991]
请问下现在支持把pretrained模型在不同词典大小下进行微调吗？比如把原本词典大小8404的pretrained模型在词典大小200左右的数据集下进行微调

**Comment by LauraGPT** [comment]
You can check if 200 word lists are included in the 8404 word list. If all of them are included, you can directly proceed with finetuning. If there are words that are not included, you need to manually add them to the 8404 word list.
