### ISSUE TITLE
目前一个服务端同时只支持一个客户端访问吗？

### ISSUE THREAD

**Issue by uncleunclelu** [alibaba-damo-academy/FunASR#992]
OS: windows/linux
Python Version：3.8
Package Version：pytorch、torchaudio、modelscope、funasr version（pip list）
Model：speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch
Command：
Details：
model loading
model loaded! only support one client at the same time now!!!!

**Comment by LauraGPT** [comment]
Maybe you could ref to [docs](https://alibaba-damo-academy.github.io/FunASR/en/funasr/quick_start_zh.html)
