### ISSUE TITLE
如何测试funasr并发性？

### ISSUE THREAD

**Issue by lukeewin** [alibaba-damo-academy/FunASR#994]
这里我用jmeter测试，每次测试都报错，然后退出funasr服务端。
我是参考https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/runtime/docs/websocket_protocol_zh.md传入的参数。
也即是{"mode": "offline", "wav_name": "wav_name","wav_format":"pcm","is_speaking": True,"hotwords":"阿里巴巴 达摩院 阿里云","itn":True}
请问你们是如何压测的？

**Comment by manbuheiniu** [comment]
不是自带python的websocket客户端吗？多启几个客户端模拟用户呢

**Comment by lukeewin** [comment]
https://github.com/alibaba-damo-academy/FunASR/issues/994#issuecomment-1752285174

这个方式不能得出测试指标，怎么指定可以支持多少个并发呢

**Comment by LauraGPT** [comment]
To test throughput, change the input to "wav.scp" and set the "--thread_num" parameter for the number of test routes. Also, ensure that the number of audio files in "wav.scp" is greater than the value of "thread_num".
