### ISSUE TITLE
html客户端，wss链接失败

### ISSUE THREAD

**Issue by 2954456878** [alibaba-damo-academy/FunASR#995]
docker部署服务端后，html网页连接wss失败，服务端报错
![52f58db4abc5f17f63fc442ef241c272](https://github.com/alibaba-damo-academy/FunASR/assets/88914706/30a2a224-ef52-4bc5-bca1-fb1949620631)

**Comment by 2954456878** [comment]
funasr_wss_client.py 能正常wss连接，并识别成功。
和openssl证书有什么关系吗

**Comment by 2954456878** [comment]
OpenSSL 1.0.2k-fips  26 Jan 2017

**Comment by yellowfish621** [comment]
你好，请问手动访问后也不能连接是为什么
