### ISSUE TITLE
C++和Python代码 ApplyLfr函数是不是不一致？导致输出结果有差距

### ISSUE THREAD

**Issue by Alone749-i** [alibaba-damo-academy/FunASR#997]
#################################【C++】###########################################
vector<float> Paraformer::ApplyLfr(const std::vector<float> &in) 
{
    int32_t in_feat_dim = fbank_opts_.mel_opts.num_bins; //80
    int32_t in_num_frames = in.size() / in_feat_dim;  // 251

    std::cout << "lfr_m" << lfr_m << "lfr_n" << lfr_n << std::endl;
    int32_t out_num_frames =
        (in_num_frames - lfr_m) / lfr_n + 1; // (251 - 7) / 7
    int32_t out_feat_dim = in_feat_dim * lfr_m; // 560

    std::vector<float> out(out_num_frames * out_feat_dim); // 

    const float *p_in = in.data();
    float *p_out = out.data();

    for (int32_t i = 0; i != out_num_frames; ++i) {
      std::copy(p_in, p_in + out_feat_dim, p_out);

      p_out += out_feat_dim;
      p_in += lfr_n * in_feat_dim;
    }

    return out;
  }
#################################【Python】###########################################
    def apply_lfr(inputs: np.ndarray, lfr_m: int, lfr_n: int) -> np.ndarray:
        LFR_inputs = []

        T = inputs.shape[0]
        T_lfr = int(np.ceil(T / lfr_n))
        left_padding = np.tile(inputs[0], ((lfr_m - 1) // 2, 1))
        inputs = np.vstack((left_padding, inputs))
        T = T + (lfr_m - 1) // 2
        for i in range(T_lfr):
            if lfr_m <= T - i * lfr_n:
                LFR_inputs.append(
                    (inputs[i * lfr_n:i * lfr_n + lfr_m]).reshape(1, -1))
            else:
                # process last LFR frame
                num_padding = lfr_m - (T - i * lfr_n)
                frame = inputs[i * lfr_n:].reshape(-1)
                for _ in range(num_padding):
                    frame = np.hstack((frame, inputs[-1]))

                LFR_inputs.append(frame)
        LFR_outputs = np.vstack(LFR_inputs).astype(np.float32)
        return LFR_outputs

Python这边对语音数据做了padding操作，C++这边好像并没有什么操作.就只是做了一个reshape的操作。

目前影响是导致有些语音数据翻译之后前一两个字缺失和翻译错误。

**Comment by LauraGPT** [comment]
Great! If it is convenient to you, please make a pr to funasr.

**Comment by lyblsgo** [comment]
Thank you for the feedback. The issue has been fixed and will be included in the next release.
