### ISSUE TITLE
V100长音频版本识别8分钟音频爆显存

### ISSUE THREAD

**Issue by troycjj** [alibaba-damo-academy/FunASR#999]
V100 32G Ubuntu
识别8分钟的音频的时候爆显存
长音频版本能否单独设置model使用的GPU或者CPU，例如vad使用CPU，ASR使用GPU

**Comment by LauraGPT** [comment]
The following is the demo, which could be found in [demo](https://github.com/alibaba-damo-academy/FunASR/tree/main/egs_modelscope/asr_vad_punc/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch):
```
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

if __name__ == '__main__':
    audio_in = 'https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/vad_example.wav'
    output_dir = "./results"
    inference_pipeline = pipeline(
        task=Tasks.auto_speech_recognition,
        model='damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch',
        vad_model='damo/speech_fsmn_vad_zh-cn-16k-common-pytorch',
        #punc_model='damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch',
        punc_model='damo/punc_ct-transformer_cn-en-common-vocab471067-large',
        output_dir=output_dir,
    )
    rec_result = inference_pipeline(audio_in=audio_in, batch_size_token=5000, batch_size_token_threshold_s=40, max_single_segment_time=6000)
    print(rec_result)
```
You could set the `batch_size_token=3000`,  `batch_size_token_threshold_s=30`, `max_single_segment_time=3000`

**Comment by troycjj** [comment]
> The following is the demo, which could be found in [demo](https://github.com/alibaba-damo-academy/FunASR/tree/main/egs_modelscope/asr_vad_punc/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch):
> 
> ```
> from modelscope.pipelines import pipeline
> from modelscope.utils.constant import Tasks
> 
> if __name__ == '__main__':
>     audio_in = 'https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/vad_example.wav'
>     output_dir = "./results"
>     inference_pipeline = pipeline(
>         task=Tasks.auto_speech_recognition,
>         model='damo/speech_paraformer-large-vad-punc_asr_nat-zh-cn-16k-common-vocab8404-pytorch',
>         vad_model='damo/speech_fsmn_vad_zh-cn-16k-common-pytorch',
>         #punc_model='damo/punc_ct-transformer_zh-cn-common-vocab272727-pytorch',
>         punc_model='damo/punc_ct-transformer_cn-en-common-vocab471067-large',
>         output_dir=output_dir,
>     )
>     rec_result = inference_pipeline(audio_in=audio_in, batch_size_token=5000, batch_size_token_threshold_s=40, max_single_segment_time=6000)
>     print(rec_result)
> ```
> 
> You could set the `batch_size_token=3000`, `batch_size_token_threshold_s=30`, `max_single_segment_time=3000`

thanks，but I found vad is very slow,nearly 10 times slower by asr, any solutions can accelarate it?
